/* Reisregels, regio Afrika. Rijformaat: zie ./europa.js. */
module.exports = ['Afrika', 'Een fooi van ~10% is gebruikelijk; bij gidsen en safari-personeel per dag', [
  ['ZA', 'vrij', 90, 'links', '10111', 1],
  ['EG', 'aankomst', 30, 'rechts', '122', 0],
  ['MA', 'vrij', 90, 'rechts', '190', 0],
  ['DZ', 'visum', 0, 'rechts', '17', 0],
  ['TN', 'vrij', 90, 'rechts', '197', 0],
  ['LY', 'visum', 0, 'rechts', '1515', 0, 'Negatief reisadvies; reizen wordt afgeraden'],
  ['NG', 'visum', 0, 'rechts', '112', 0, 'Controleer het actuele reisadvies voor vertrek'],
  ['GH', 'aankomst', 30, 'rechts', '191', 0],
  ['KE', 'toestemming', 90, 'links', '999', 0, 'Elektronische reistoestemming (eTA) vooraf aanvragen'],
  ['ET', 'evisum', 30, 'rechts', '911', 0],
  ['TZ', 'aankomst', 90, 'links', '112', 0],
  ['UG', 'evisum', 90, 'links', '999', 0],
  ['RW', 'aankomst', 30, 'rechts', '112', 0, 'Plastic tassen zijn verboden en worden bij aankomst ingenomen'],
  ['BI', 'visum', 0, 'rechts', '117', 0],
  ['SN', 'vrij', 90, 'rechts', '17', 0],
  ['CI', 'evisum', 90, 'rechts', '110', 0],
  ['CM', 'visum', 0, 'rechts', '117', 0],
  ['AO', 'vrij', 30, 'rechts', '113', 0],
  ['MZ', 'aankomst', 30, 'links', '119', 0],
  ['ZM', 'aankomst', 90, 'links', '999', 0],
  ['ZW', 'aankomst', 90, 'links', '999', 0],
  ['BW', 'vrij', 90, 'links', '999', 1],
  ['NA', 'vrij', 90, 'links', '10111', 1],
  ['MU', 'vrij', 90, 'links', '999', 1],
  ['SC', 'vrij', 90, 'links', '999', 1],
  ['MG', 'aankomst', 30, 'rechts', '117', 0],
  ['ML', 'visum', 0, 'rechts', '17', 0, 'Negatief reisadvies; reizen wordt afgeraden'],
  ['BF', 'visum', 0, 'rechts', '17', 0, 'Negatief reisadvies; reizen wordt afgeraden'],
  ['NE', 'visum', 0, 'rechts', '17', 0, 'Negatief reisadvies; reizen wordt afgeraden'],
  ['TD', 'visum', 0, 'rechts', '17', 0, 'Controleer het actuele reisadvies voor vertrek'],
  ['SD', 'visum', 0, 'rechts', '999', 0, 'Negatief reisadvies; reizen wordt afgeraden'],
  ['SS', 'visum', 0, 'rechts', '999', 0, 'Negatief reisadvies; reizen wordt afgeraden'],
  ['ER', 'visum', 0, 'rechts', '113', 0],
  ['DJ', 'evisum', 30, 'rechts', '17', 0],
  ['SO', 'visum', 0, 'rechts', '888', 0, 'Negatief reisadvies; reizen wordt afgeraden'],
  ['GM', 'vrij', 90, 'rechts', '117', 0],
  ['GN', 'evisum', 90, 'rechts', '117', 0],
  ['GW', 'aankomst', 90, 'rechts', '117', 0],
  ['SL', 'aankomst', 30, 'rechts', '999', 0],
  ['LR', 'visum', 0, 'rechts', '911', 0],
  ['TG', 'aankomst', 15, 'rechts', '117', 0],
  ['BJ', 'evisum', 30, 'rechts', '117', 0],
  ['GA', 'evisum', 90, 'rechts', '1730', 0],
  ['GQ', 'visum', 0, 'rechts', '114', 0],
  ['CG', 'visum', 0, 'rechts', '117', 0],
  ['CD', 'visum', 0, 'rechts', '112', 0, 'Controleer het actuele reisadvies voor vertrek'],
  ['CF', 'visum', 0, 'rechts', '117', 0, 'Negatief reisadvies; reizen wordt afgeraden'],
  ['MW', 'aankomst', 30, 'links', '997', 0],
  ['LS', 'aankomst', 14, 'links', '112', 0],
  ['SZ', 'vrij', 30, 'links', '999', 0],
  ['KM', 'aankomst', 45, 'rechts', '17', 0],
  ['CV', 'toestemming', 30, 'rechts', '132', 0, 'Vooraf online registreren (EASE)'],
  ['ST', 'vrij', 15, 'rechts', '112', 0],
  ['MR', 'aankomst', 30, 'rechts', '117', 0, 'Alcohol is verboden']
]];
