/* Reisregels, regio Azie (incl. Midden-Oosten). Rijformaat: zie ./europa.js. */
module.exports = ['Azie', 'Fooi is meestal 5-10%; in Japan en Zuid-Korea is fooi niet gebruikelijk', [
  ['JP', 'vrij', 90, 'links', '110', 1, 'Geen fooi geven -- dat kan als onbeleefd worden ervaren'],
  ['CN', 'vrij', 30, 'rechts', '110', 0, 'Visumvrij tot 30 dagen (regeling loopt; controleer voor vertrek)'],
  ['KR', 'vrij', 90, 'rechts', '112', 1],
  ['TW', 'vrij', 90, 'rechts', '110', 0],
  ['HK', 'vrij', 90, 'links', '999', 1],
  ['MO', 'vrij', 90, 'links', '999', 1],
  ['MN', 'vrij', 30, 'rechts', '105', 0],
  ['SG', 'vrij', 90, 'links', '999', 1, 'Strenge regels: hoge boetes op afval en kauwgom; drugsdelicten worden zeer zwaar bestraft'],
  ['MY', 'vrij', 90, 'links', '999', 0, 'Drugsdelicten worden zeer zwaar bestraft'],
  ['TH', 'vrij', 60, 'links', '191', 0],
  ['VN', 'vrij', 45, 'rechts', '113', 0],
  ['PH', 'vrij', 30, 'rechts', '911', 0],
  ['ID', 'aankomst', 30, 'links', '112', 0, 'Visum bij aankomst; drugsdelicten worden zeer zwaar bestraft'],
  ['KH', 'aankomst', 30, 'rechts', '117', 0],
  ['LA', 'aankomst', 30, 'rechts', '191', 0],
  ['MM', 'evisum', 28, 'rechts', '199', 0, 'Controleer het actuele reisadvies voor vertrek'],
  ['BN', 'vrij', 90, 'links', '993', 1, 'Alcohol wordt niet verkocht; strenge gedragsregels'],
  ['TL', 'aankomst', 30, 'links', '112', 0],
  ['IN', 'evisum', 30, 'links', '112', 0, 'E-visum vooraf aanvragen'],
  ['BD', 'aankomst', 30, 'links', '999', 0],
  ['PK', 'evisum', 30, 'links', '15', 0, 'Controleer het actuele reisadvies voor vertrek'],
  ['LK', 'evisum', 30, 'links', '119', 0],
  ['NP', 'aankomst', 90, 'links', '100', 0],
  ['BT', 'visum', 0, 'links', '113', 0, 'Visum via een erkende reisorganisatie; dagtarief voor toeristen'],
  ['MV', 'aankomst', 30, 'links', '119', 0],
  ['AF', 'visum', 0, 'rechts', '119', 0, 'Negatief reisadvies; reizen wordt afgeraden'],
  ['KZ', 'vrij', 30, 'rechts', '112', 0],
  ['UZ', 'vrij', 30, 'rechts', '112', 0],
  ['KG', 'vrij', 60, 'rechts', '112', 0],
  ['TJ', 'evisum', 45, 'rechts', '112', 0],
  ['TM', 'visum', 0, 'rechts', '112', 0],
  ['GE', 'vrij', 365, 'rechts', '112', 1],
  ['AM', 'vrij', 180, 'rechts', '112', 1],
  ['AZ', 'evisum', 30, 'rechts', '112', 0],
  ['SA', 'evisum', 90, 'rechts', '911', 0, 'Alcohol is verboden; strenge kleding- en gedragsregels'],
  ['AE', 'vrij', 90, 'rechts', '999', 1, 'Strenge regels rond alcohol, foto\'s van personen en gedrag in het openbaar'],
  ['QA', 'vrij', 30, 'rechts', '999', 1, 'Strenge gedragsregels; alcohol alleen in vergunde hotels'],
  ['KW', 'evisum', 90, 'rechts', '112', 1, 'Alcohol is verboden'],
  ['BH', 'evisum', 30, 'rechts', '999', 1],
  ['OM', 'vrij', 14, 'rechts', '9999', 1],
  ['YE', 'visum', 0, 'rechts', '191', 0, 'Negatief reisadvies; reizen wordt afgeraden'],
  ['IL', 'vrij', 90, 'rechts', '100', 1, 'Controleer het actuele reisadvies voor vertrek'],
  ['JO', 'aankomst', 30, 'rechts', '911', 0],
  ['LB', 'aankomst', 30, 'rechts', '112', 0, 'Controleer het actuele reisadvies voor vertrek'],
  ['SY', 'visum', 0, 'rechts', '112', 0, 'Negatief reisadvies; reizen wordt afgeraden'],
  ['IQ', 'aankomst', 60, 'rechts', '104', 0, 'Controleer het actuele reisadvies voor vertrek'],
  ['IR', 'visum', 0, 'rechts', '110', 0, 'Negatief reisadvies; alcohol is verboden; strenge kledingregels']
]];
