/* Spellen (data): de vragenbank van het Quizduel -- algemene kennis op
   jongvolwassen niveau, per vraag drie opties en de index van het juiste
   antwoord. De server deelt de opties uit en houdt de oplossing voor
   zichzelf tot er geantwoord is. */
module.exports = [
  ['Wat is de hoofdstad van Australie?', ['Sydney', 'Canberra', 'Melbourne'], 1],
  ['Welke rivier stroomt door Parijs?', ['De Seine', 'De Rhone', 'De Loire'], 0],
  ['Hoeveel provincies telt Nederland?', ['Tien', 'Elf', 'Twaalf'], 2],
  ['Welk element heeft het symbool Fe?', ['Fluor', 'IJzer', 'Fosfor'], 1],
  ['Wie schilderde De Nachtwacht?', ['Vermeer', 'Rembrandt', 'Frans Hals'], 1],
  ['Wat is de grootste planeet van ons zonnestelsel?', ['Saturnus', 'Neptunus', 'Jupiter'], 2],
  ['In welk land ligt Machu Picchu?', ['Peru', 'Chili', 'Mexico'], 0],
  ['Hoeveel snaren heeft een klassieke gitaar?', ['Vijf', 'Zes', 'Zeven'], 1],
  ['Welke taal heeft de meeste moedertaalsprekers?', ['Engels', 'Mandarijn', 'Spaans'], 1],
  ['Wat is de langste rivier van Europa?', ['De Donau', 'De Wolga', 'De Rijn'], 1],
  ['Welk orgaan filtert afvalstoffen uit het bloed?', ['De lever', 'De nier', 'De milt'], 1],
  ['Hoeveel spelers telt een voetbalelftal op het veld?', ['Tien', 'Elf', 'Twaalf'], 1],
  ['Welke planeet staat het dichtst bij de zon?', ['Venus', 'Mercurius', 'Mars'], 1],
  ['Wat is de hoofdstad van Canada?', ['Toronto', 'Vancouver', 'Ottawa'], 2],
  ['Wie schreef Het Achterhuis?', ['Anne Frank', 'Harry Mulisch', 'Hella Haasse'], 0],
  ['Hoeveel botten telt een volwassen mens ongeveer?', ['106', '206', '306'], 1],
  ['Welk land heeft de vorm van een laars?', ['Spanje', 'Italie', 'Portugal'], 1],
  ['Wat meet een barometer?', ['Luchtdruk', 'Vochtigheid', 'Temperatuur'], 0],
  ['In welk jaar viel de Berlijnse Muur?', ['1987', '1989', '1991'], 1],
  ['Welke oceaan is de grootste?', ['De Atlantische', 'De Indische', 'De Stille'], 2],
  ['Hoeveel harten heeft een octopus?', ['Een', 'Twee', 'Drie'], 2],
  ['Welk metaal is vloeibaar bij kamertemperatuur?', ['Kwik', 'Lood', 'Tin'], 0],
  ['Wie componeerde de Ode aan de vreugde?', ['Mozart', 'Beethoven', 'Bach'], 1],
  ['Welk gas nemen planten overdag vooral op?', ['Zuurstof', 'Koolstofdioxide', 'Stikstof'], 1],
  ['Wat is de hoofdstad van Turkije?', ['Istanboel', 'Ankara', 'Izmir'], 1],
  ['Hoeveel ringen telt het olympische symbool?', ['Vier', 'Vijf', 'Zes'], 1],
  ['Welke Nederlandse stad heet de Domstad?', ['Utrecht', 'Nijmegen', 'Den Bosch'], 0],
  ['Wat is het grootste land ter wereld?', ['China', 'Canada', 'Rusland'], 2],
  ['Welke bloedgroep is de universele donor?', ['O-negatief', 'AB-positief', 'A-negatief'], 0],
  ['Wie schilderde de Zonnebloemen?', ['Van Gogh', 'Mondriaan', 'Monet'], 0],
  ['In welk land staat de Taj Mahal?', ['Pakistan', 'India', 'Iran'], 1],
  ['Wat is het snelste landdier?', ['De jachtluipaard', 'De antilope', 'Het paard'], 0],
  ['Hoeveel dagen telt februari in een schrikkeljaar?', ['28', '29', '30'], 1],
  ['Welk instrument heeft 88 toetsen?', ['Het orgel', 'De piano', 'De accordeon'], 1],
  ['Welke berg is de hoogste ter wereld?', ['De K2', 'De Mount Everest', 'De Kilimanjaro'], 1],
  ['Wat is de munteenheid van Japan?', ['De yen', 'De won', 'De yuan'], 0],
  ['Uit welk land komt de tango?', ['Brazilie', 'Argentinie', 'Cuba'], 1],
  ['Hoeveel kleuren telt de regenboog volgens de traditie?', ['Zes', 'Zeven', 'Acht'], 1],
  ['Welke zee ligt tussen Europa en Afrika?', ['De Middellandse Zee', 'De Zwarte Zee', 'De Rode Zee'], 0],
  ['Wie zette als eerste mens voet op de maan?', ['Buzz Aldrin', 'Neil Armstrong', 'Joeri Gagarin'], 1],
  ['Wat is het chemische symbool voor goud?', ['Go', 'Au', 'Ag'], 1],
  ['Welk land won het eerste WK voetbal in 1930?', ['Brazilie', 'Uruguay', 'Argentinie'], 1],
  ['Hoeveel poten heeft een spin?', ['Zes', 'Acht', 'Tien'], 1],
  ['Wie schilderde Victory Boogie Woogie?', ['Mondriaan', 'Karel Appel', 'Van Doesburg'], 0],
  ['In welke stad staat het Colosseum?', ['Athene', 'Rome', 'Napels'], 1],
  ['Wat is de hoofdstad van Brazilie?', ['Rio de Janeiro', 'Sao Paulo', 'Brasilia'], 2],
  ['Welke vitamine maakt je huid aan in de zon?', ['Vitamine C', 'Vitamine D', 'Vitamine B12'], 1],
  ['Welk sterrenbeeld hoort bij eind juli?', ['De Leeuw', 'De Vissen', 'De Stier'], 0]
];
