/* Magnaat Hospitality Universe: speelbaarheid, foutpaden, replay en de harde
   grens tussen simulatieresultaat en een levende onderneming. */
'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const H=require('../server/kern/spellen/magnaat/hospitality');
test('goud, rood, zwart en platina zijn vier speelbare routes',()=>{for(const route of Object.keys(H.ROUTES)){const w=H.nieuw();assert.equal(H.start(w,route).status,200);while(w.status==='live'){for(const i of w.incidenten.filter(x=>x.status==='open'))assert.equal(H.besluit(w,i.id,i.keuzes[0]).status,200);H.stap(w)}assert.equal(w.status,'afgerond');assert.ok(w.voorstellen.length)}});
test('een zwarte route stapelt verstoringen maar passeert geen menselijk besluit',()=>{const w=H.nieuw();H.start(w,'zwart');assert.equal(w.incidenten.length,3);const x=w.incidenten[0],voor=w.scores[x.as];assert.equal(H.besluit(w,x.id,'bestaat niet').status,400);assert.equal(x.status,'open');assert.equal(H.besluit(w,x.id,x.keuzes[0]).status,200);assert.equal(x.status,'hersteld');assert.ok(w.scores[x.as]>voor);assert.equal(w.replay.length,1)});
test('dezelfde open verstoring wordt niet dubbel geïnjecteerd',()=>{const w=H.nieuw();H.start(w,'goud');assert.equal(H.injecteer(w,H.INCIDENTEN[0]).status,200);assert.equal(H.injecteer(w,H.INCIDENTEN[0]).status,409);assert.equal(w.incidenten.length,1)});
test('een anonieme bron bevat alleen het meegegeven bedrijfsbeeld',()=>{const bron={soort:'live-geanonimiseerd',tafels:20,menu:40,gasten:63};const w=H.nieuw(bron);assert.deepEqual(w.bron,bron);assert.equal(JSON.stringify(w).includes('naam'),false);assert.equal(JSON.stringify(w).includes('email'),false)});
test('dezelfde mensen reizen van discovery tot nazorg door de keten',()=>{const w=H.nieuw({soort:'synthetisch',gasten:6,medewerkers:3});H.start(w,'goud');const gast=w.wereld.gasten[0],id=gast.id;for(let i=0;i<8;i++)H.stap(w);assert.equal(w.wereld.gasten.find(g=>g.id===id),gast);assert.equal(gast.status,'nazorg');assert.equal(w.wereld.reserveringen.length,6);assert.equal(w.wereld.bestellingen.length,6);assert.equal(w.wereld.betalingen.length,6);assert.equal(w.wereld.audit.length,8)});
test('geen arrival-toestemming betekent ontvangen zonder tracking',()=>{const w=H.nieuw();H.start(w,'goud');for(let i=0;i<4;i++)H.stap(w);const zonder=w.wereld.gasten.find(g=>!g.toestemming);assert.ok(zonder);assert.equal(zonder.status,'ontvangen-zonder-tracking')});
test('een allergiebestelling blijft geblokkeerd tot een geldige menselijke keuze',()=>{const w=H.nieuw();H.start(w,'goud');for(let i=0;i<5;i++)H.stap(w);const order=w.wereld.bestellingen.find(o=>o.allergie);assert.equal(order.status,'wacht-op-mens');H.injecteer(w,H.INCIDENTEN.find(i=>i.id==='allergie'));assert.equal(H.besluit(w,'allergie','menselijke dubbelcheck').status,200);assert.equal(order.status,'veilig-bevestigd');assert.ok(w.wereld.audit.some(a=>a.wat==='menselijk-herstel'))});
test('betaling en looncontrole ontstaan pas in hun eigen fase',()=>{const w=H.nieuw();H.start(w,'goud');for(let i=0;i<6;i++)H.stap(w);assert.equal(w.wereld.betalingen.length,0);H.stap(w);assert.ok(w.wereld.betalingen.every(p=>p.status==='betaald'));H.stap(w);assert.ok(w.wereld.medewerkers.filter(m=>m.id!=='M-NIEUW').every(m=>/controle|onboarding/.test(m.status)))});
test('de discoverywereld biedt meerdere typen zaak zonder persoonsgegevens',()=>{const w=H.nieuw();assert.equal(w.wereld.markt.length,3);assert.ok(w.wereld.markt.some(v=>v.type==='hotelrestaurant'));assert.ok(w.wereld.markt.some(v=>v.toegankelijk));assert.ok(w.wereld.gasten.some(g=>g.toegankelijk))});
test('document, leverancier, no-show en privacy hebben herstelroutes',()=>{for(const id of ['document','levering','noshow','privacy']){const w=H.nieuw();H.start(w,'goud');for(let i=0;i<2;i++)H.stap(w);const inc=H.INCIDENTEN.find(x=>x.id===id);assert.equal(H.injecteer(w,inc).status,200);assert.equal(H.besluit(w,id,inc.keuzes[0]).status,200);assert.equal(w.incidenten.find(x=>x.id===id).status,'hersteld')}});
