/* App-gids data, deel2b: het vervolg van ./deel2.js, dat over de 10 kB ging.
   Geknipt op een entry-grens, dus de samengevoegde gids is er niet door
   veranderd. Zie ../appgids.js voor de uitleg. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/hangar.html': G('Hangar: uw privevliegtuigen en charters, met vlieguren en de laatst bekende positie.',
    ['Zet een toestel erbij met type, registratie, thuishaven en stoelen', 'Boek de vluchten met vlieguren en bemanning', 'Zie per toestel de eerstvolgende vlucht en de totale vlieguren'],
    'De positie is de aankomst van de recentste vlucht, anders de thuishaven. Geen live tracking, en dat zegt de app er ook bij.'),
  '/apps/lifestyle.html': G('Het Privékantoor: de ene app van uw Lifestyle Pass. Alles wat u heeft op één levensbeeld, met de Rechterhand als uitvoerende hand.',
    ['Begin bij Nu: één kop die zegt of u iets moet doen, plus uw ochtend- of avondbriefing',
      'Zeg onder Nu wanneer u weg bent; wij zoeken op wat daar in uw andere apps mee samenhangt: paspoorten, een verzekering, de vaccinatie van de hond, een toezegging die u al deed',
      'Vooruit bundelt alle termijnen uit die apps, inclusief wat al te laat is',
      'Onder Mandaat bepaalt u per onderwerp hoever wij zonder u gaan, en tot welk bedrag',
      'Een zaak valt uiteen in deelopdrachten die elk uw eigen grens volgen',
      'Woning, Kring, Bezit, Reis en Veilig zijn de kamers waar u het invult',
      'Kantoor is de plattegrond van twintig werelden'],
    'Over gezondheid en nalatenschap beslist u zelf: die blijven besloten, komen niet op ons bureau, en daar kunt u ons geen mandaat voor geven.'),
  '/apps/logboek.html': G('Logboek: het onderhoudsboek van uw jacht, jet, oldtimer of ander kostbaar bezit.',
    ['Zet een object erbij met soort, merk, bouwjaar en registratie', 'Boek keuringen, servicebeurten, reparaties en verzekeringen met datum en kosten', 'Zie bovenaan wat er binnenkort weer aan de beurt is'],
    'De datum waarop iets weer aan de beurt is, is het hele punt: een keuring die verloopt kost meer dan het onderhoud zelf.'),
  '/apps/maison.html': G('Maison: uw huishouden en staf -- wie er werkt, welke taken lopen, en wat er speelt in en om huis.',
    ['Zet uw huishoudelijk personeel erbij met rol en contact', 'Geef een taak aan iemand met een datum, en vink hem af', 'Houd een logboek bij van wat er in en om huis speelt'],
    'Afspraken die opgeschreven staan hoeven door niemand van de twee onthouden te worden.'),
  '/apps/mecenaat.html': G('Mecenaat: uw filantropie op orde -- toezeggingen, betalingen en wat er via de RTFoundation loopt.',
    ['Zet een gift erbij met doel, thema en bedrag', 'Geef aan of het een toezegging is of al betaald', 'Zie het overzicht: toegezegd, betaald, en het deel via de RTFoundation'],
    'Dit is een administratie en geen betaalkanaal: het vinkje "betaald" legt vast wat u elders deed.'),
  '/apps/nalatenschap.html': G('Nalatenschap: een discreet, versleuteld dossier voor later.',
    ['Leg vast welke documenten er zijn en waar ze liggen', 'Zet uw vertrouwenspersonen erbij: notaris, executeur, advocaat', 'Schrijf uw persoonlijke wensen op'],
    'Waar iets ligt, de contactgegevens en de wensen staan versleuteld op schijf. De app bewaart geen documenten zelf, alleen waar ze te vinden zijn.'),
  '/apps/reisboek.html': G('Reisboek: uw prive-reisdossier -- per reis een draaiboek in plaats van losse bevestigingen.',
    ['Zet per reis de heen- en terugreis en de tussenstops', 'Leg de verblijven en het dag-tot-dag-programma vast', 'Bewaar de reisdocumenten met hun geldigheid'],
    'Het overzicht seint welke documenten binnenkort verlopen. Dat is het enige waar u vlak voor vertrek niets meer aan kunt doen.'),
  '/apps/rendezvous.html': G('Rendez-vous: besloten introducties, waar de ontmoeting het product is.',
    ['Zet uw profiel op, geef aan waar u wanneer bent en wanneer u meestal kunt',
      'Bij een wederzijdse interesse ziet u waar u tegelijk bent en welk dagdeel u beiden uitkomt',
      'Met Arrange it stelt Rahul een ontmoeting samen; keurt u beiden goed, dan regelt De Rechterhand het'],
    'Uw verblijfplaats geeft u zelf op en niemand ziet uw dagdelen; bij een match hoort u alleen waar en wanneer u elkaar treft.'),
  '/apps/table.html': G('Table: de prive-diners en events die u ZELF geeft.',
    ['Maak een gelegenheid met datum en locatie', 'Zet de gastenlijst erbij met dieet en voorkeuren, en maak de tafelindeling', 'Stel het menu per gang samen'],
    'Alles blijft bewaard en is herbruikbaar, dus de volgende keer begint u niet opnieuw. Reserveren bij een zaak doet u in Het Huis.'),
  '/apps/concierge.html': G('Het concierge-bureau: hier werkt uw Rechterhand voor u.',
    ['Zie de aanvragen van uw leden', 'Pak op, regel en koppel terug', 'Houd het logboek bij'],
    'Terugkoppelen vóór het lid het vraagt: dat is het verschil tussen goed en uitstekend.'),
  '/apps/redactiekantoor.html': G('Het redactiekantoor: waar RTG Nieuws gemaakt wordt.',
    ['Schrijf, redigeer en plan artikelen', 'Beheer rubrieken en beeld', 'Publiceer na eindredactie'],
    'Check je feiten twee keer; snelheid wint nooit van kloppen.'),
  '/apps/leverancier-rtmail.html': G('RTMAIL voor uw zaak: het postvak op uw zaakcode, waar de draaiboeken (sollicitatie, inkoop, factuur, overheid) hun seintjes bezorgen.',
    ['Lees ontvangen en verzonden post op codenaam', 'Stuur zelf een bericht naar een andere zaak of groothandel', 'Alles op codenamen; echte namen blijven in de kluis'],
    'Kijk hier na een drukke dag even langs; de seintjes staan gebundeld klaar zonder dat u een externe mailbox hoeft te openen.'),
  /* Uit de tak die de Mall-aanvragen bracht; ze horen bij deel2 en die zit aan
     zijn omvanggrens, dus staan ze hier bij de rest van het vervolg. */
  '/apps/mijnmall.html': G('Mijn Mall: wat u bewaarde, de reizen die u bouwt en de vragen die u uitzette.',
    ['Bewaar iets uit de Mall in een lijst', 'Bouw een reis uit verblijf, vervoer, tafel en iets te doen',
     'Plaats een vraag als u iets niet vindt, en kies zelf uit de reacties'],
    'Er wordt hier niets afgerekend: elke regel gaat naar de partij die hem levert, met zijn eigen bevestiging.'),
  '/apps/leverancier-aanvragen.html': G('Aanvragen uit de Mall: leden die zoeken wat u kunt leveren.',
    ['Zie alleen vragen die bij uw vak en werkgebied passen', 'Reageer met wat u kunt bieden en wat het kost',
     'Bedenkt u zich, dan werkt u uw eigen reactie bij'],
    'Staat er niets, stel dan uw werkgebied in; dat bepaalt welke vragen u ziet.')
};
