/* App-gids data, deel10b: het vervolg van deel10, opgeknipt op de 10 kB-grens
   nadat de check die map echt ging zien (de mapfilter matchte 'data' als
   deelstring van 'appgids-data' en sloeg alles over). De knip zit op een
   entry-grens en niet op een onderwerp -- een gidslijst is een lijst.
   Hier: de Foundation OS-schermen en RTG Handel. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/foundation/os.html': G('Foundation OS: het bestuurssysteem van de RTFoundation -- landelijk toezicht, zelfstandige stadsafdelingen, partnerstichtingen, projecten, vrijwilligers, geld en hulpvragen.',
    ['Kies een stadsafdeling; u ziet alleen de steden waar u een zetel heeft, het landelijke bestuur ziet ze alle',
      'Werk per tabblad: impact, projecten, partners, vrijwilligers, geld, hulpvragen, integriteit, gemeente en ondernemers',
      'Werk per tabblad verder: subsidies met hun rapportagemomenten, voorraad per batch, activiteiten met wachtlijst en incheck, en communicatie',
      'Onder Netwerk deelt u een blauwdruk met andere steden, koopt u samen in, leent u vrijwilligers uit en ziet u het koppelbord met RTG',
      'Onder Bestuur staan de knoppen van het toezicht: modules per stad, de status van de afdeling, de goedkeuringslimieten en de zetels'],
    'Geoormerkt geld gaat hier nooit naar een ander project, wie een uitgave aanvraagt keurt hem niet zelf goed, en een melding kan niemand verwijderen -- ook het landelijke bestuur niet.'),
  '/apps/foundation/os-vrijwilliger.html': G('Mijn vrijwilligerswerk: uw eigen planning, uren en VOG-datum, op uw eigen code.',
    ['Vul de code in die u van uw coordinator kreeg (RTFV-...)',
      'Zet aan wanneer u kunt, en welke talen en vaardigheden u meebrengt; dat ziet uw coordinator meteen',
      'Geef uw uren door; ze tellen mee zodra uw coordinator ze bevestigt'],
    'Uw VOG, de gedragscode en uw status zet de afdeling en niet u zelf -- een VOG die je zelf invult is geen VOG-controle meer. Er staan geen contactgegevens achter deze code, want een code wordt meegelezen.'),
  '/apps/foundation/os-deelnemer.html': G('Mijn hulpvraag: hoe het ervoor staat, en de knop om uw toestemming in te trekken.',
    ['Vul de code in die u van de RTF-afdeling kreeg (RTFD-...)',
      'Lees in gewone taal waar uw vraag staat en wat er is gedaan',
      'Trek uw toestemming in als u niet meer wilt dat uw gegevens worden gedeeld; dat kan hier, zonder te bellen'],
    'Wat er al is gedaan blijft in het dossier staan -- dat wissen zou het onbetrouwbaar maken, ook voor u -- maar er gaat daarna niets meer naar een partner.'),
  '/apps/foundation/os-publiek.html': G('RTFoundation in uw buurt: wat er loopt, waar u binnen kunt lopen en hoe u meedoet.',
    ['Kies uw stad en zie welke projecten er draaien',
      'Bekijk de activiteiten die openstaan, met datum, plek en of er nog plek is',
      'Lees hoe u meedoet als vrijwilliger of als ondernemer'],
    'Er staat met opzet geen enkel getal over hulpvragen op deze pagina: in een kleine buurt is zo\'n getal geen statistiek maar een aanwijzing. De maat is: wat zou je op een poster in het buurthuis hangen?'),
  '/apps/foundation/os-veld.html': G('Uw eigen lijst als medewerker: wat aan u is toegewezen, het bezoekrapport en de vervolgafspraak.',
    ['Open de app; u ziet uitsluitend de hulpvragen die uw coordinator aan u heeft toegewezen',
      'Vraag het adres op als u op bezoek gaat -- dat openen wordt genoteerd, precies zoals op kantoor',
      'Noteer wat u heeft gezien en gedaan, met een vervolgafspraak of de reden dat er geen vervolg nodig is'],
    'Afronden doet uw coordinator: dat zet de bewaartermijn in gang en sluit de zaak, en zo\'n besluit hoort niet op de stoep te vallen. Een rapport zonder vervolg is hoe een hulpvraag blijft liggen -- iedereen denkt dan dat de ander aan zet is.'),
  '/apps/foundation/os-donateur.html': G('Uw eigen giften: wat u gaf, waar het heen ging en uw giftbewijs.',
    ['Vul de code in die u van de stichting kreeg (RTFS-...)',
      'Zie per gift waar hij heen ging: een project of een stadsafdeling, met wat daar het doel is',
      'Vraag uw giftbewijs op; bij een periodieke gift staat de overeenkomst erbij'],
    'U ziet uitsluitend uw eigen giften, nooit die van iemand anders. En nooit mensen: waar uw geld heen ging is een project; wie er geholpen is, is niet aan ons om te vertellen.'),
  '/apps/foundation/os-bestuur.html': G('De governance-laag: bestuursvergaderingen, landelijk beleid, het jaarverslag, risico\'s, grote giften en de meldcode.',
    ['Leg een vergadering vast met het aantal bestuurders erbij -- dat getal is de noemer van het quorum',
      'Neem besluiten; wie een belang heeft bij het punt kan niet als stemmer worden geteld',
      'Stel de notulen vast in een VOLGENDE vergadering; daarna ligt alles vast',
      'Stel het jaarverslag op (de cijfers bevriezen), laat het bestuur het vaststellen en publiceer het'],
    'Dit scherm gaat niet over wat de stichting deed maar over of ze het bevoegd deed en het kan laten zien. Een grote of contante gift staat stil tot de herkomst is beoordeeld, en een meldcode-dossier kan niemand verwijderen.'),
  '/apps/handel.html': G('RTG Handel: inkoop tussen zaken -- een aanvraag uitzetten bij een heel soort bedrijf, offertes vergelijken, gunnen, laten leveren en betalen.',
    ['Zet een aanvraag uit bij een SOORT bedrijf en niet bij een adres; elke zaak van dat soort ziet hem, ook een die zich gisteren aanmeldde',
      'Vergelijk de offertes die binnenkomen en gun er een; daarmee ligt de prijs vast',
      'Volg dezelfde weg tot het eind: inplannen, leveren met bewijs, factureren, voldaan melden'],
    'Een leverancier ziet de prijs van zijn concurrent niet, en een factuur die afwijkt van het gegunde bedrag weigert: dat is dan een nieuwe afspraak en geen correctie.'),
  '/apps/foundation/os-portaal.html': G('Het portaal voor partnerstichtingen, gemeenten en lokale ondernemers: uw eigen dossier, op uw eigen code.',
    ['Vul de code in die u van het RTF-kantoor kreeg (RTFP voor een stichting, RTFG voor een gemeente, RTFO voor een bedrijf)',
      'Een stichting ziet de samenwerkingsafspraken en de eigen projecten; een gemeente uitsluitend getelde cijfers; een ondernemer waar zijn bijdrage terechtkwam',
      'De code blijft in dit tabblad en wordt nergens bewaard -- op een gedeelde computer sluit u hem weg door het tabblad te sluiten'],
    'Een gemeente krijgt hier nooit een dossier of een naam te zien, en buurten met minder dan vijf hulpvragen worden samengevoegd: een klein getal in een kleine buurt is geen statistiek meer.')
};
