/* App-gids data, deel7 (20 pagina's). Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/personeel.html': G('De personeels-app (PDA): uw dienst, taken en team op zak.',
    ['Klok in en zie uw dienst', 'Pak taken op en meld ze af', 'Praat met collega\'s via chat of walkie-talkie'],
    'Meld afwijkingen meteen; een klein bericht nu voorkomt groot gedoe later.'),
  '/apps/backoffice.html': G('De RTG Backoffice: het kantoor dat leden en partners helpt.',
    ['Behandel verificaties en aanvragen', 'Zoek dwars door het systeem', 'Bekijk prestaties en weekcijfers'],
    'Het actiecentrum sorteert op urgentie: van boven naar beneden werken is genoeg.'),
  '/apps/klankwerk-kantoor.html': G('De RTG-naam onder een uitgave: de enige plek waar een mens dat kan toekennen.',
    ['Lees de aanvraag en luister naar het werk',
     'Zet de RTG-naam eronder, of niet',
     'Schrijf uw reden: de maker leest hem'],
    'Nee zeggen haalt niets weg. De uitgave blijft gewoon staan onder de codenaam van de maker.'),
  '/apps/rtgkantoor.html': G('Het RTG Kantoor: het huis van de eigen RTG AI, die meeleest, zichzelf traint en pas na uw knop het roer krijgt.',
    ['Volg de gereedheid: dekking en ervaring groeien door mee te lezen', 'De AI meldt zelf wanneer hij er klaar voor is', 'Geef het roer met de knop; daarna draait het routinewerk automatisch door, en de terug-knop is altijd van u'],
    'De AI adviseert, de mens beslist: overnemen kan alleen via uw knop, en aan het roer doet hij uitsluitend het veilige routinewerk.'),
  '/apps/kantoren.html': G('RTG Kantoren: alle afdelingen en de boardroom, met de zelfzorg van het systeem.',
    ['Loop de afdelingen langs met hun KPI\'s', 'Schakel in de boardroom wat aan of uit moet', 'Bekijk opruimen, beschermen, repareren en upgraden'],
    'De boardroom kan alles zien en alles schakelen; grote knoppen vragen om een tweede blik.'),
  '/apps/boardroom.html': G('De boardroom: het hoogste overzicht, alles zien en alles kunnen schakelen.',
    ['Bekijk het hele systeem in één oogopslag', 'Zet regie-schakelaars om', 'Laat Rahul voorstellen doen en beslis zelf'],
    'De AI adviseert, de boardroom beslist; die volgorde is een principe, geen toeval.'),
  '/apps/architect-pda.html': G('De architect-PDA: het architectenbureau op zak.',
    ['Bekijk projecten en hun fase', 'Leg bevindingen op locatie vast', 'Deel met het bureau'],
    'Foto\'s op locatie zeggen meer dan een pagina notities.'),
  '/apps/websitestudio.html': G('De Website-studio van het Atelier: bouw met de muis een eigen RTG-sjabloon uit blokken, alsof het een sjabloon is.',
    ['Sleep blokken op hun plek: hero, koppen, tekst, beeld, kolommen, galerij', 'Klik in de tekst om te typen; kies een accentkleur en licht of donker', 'Bewaar het sjabloon, bekijk het als voorbeeld of exporteer het als losse pagina'],
    'Het is een eigen ontwerp in het Atelier, los van de echte site: hier kun je vrij spelen zonder iets aan de website te veranderen.'),
  '/apps/sitemaker.html': G('De Website-maker: begin een eigen bedrijf en bouw met de muis je eigen website, klaar om online te gaan.',
    ['Bouw je site uit blokken: klik en typ, kies beeld, accentkleur en licht of donker', 'Stel de telefoon-, tablet- en desktopversie apart in', 'Klik op Ga online: je site krijgt een RTG-adres (naam.rtg) en staat in de RTG-browser'],
    'Voor beginnende ondernemers: van leeg doek tot online bedrijf, alles binnen het huis en op codenaam.'),
  '/apps/browser.html': G('De RTG-browser: blader door het besloten web van het huis en bezoek de sites die leden hebben gebouwd.',
    ['Typ een adres in de balk (bijv. jouwzaak.rtg) of kies een site op RTG Start', 'Ga terug en vooruit zoals in een echte browser', 'Elke site buigt mee met je vensterbreedte: telefoon, tablet of desktop'],
    'Een eigen web binnen RTG: geen extern internet, alles op codenaam en tussen leden.'),
  '/apps/redactie.html': G('De RTG Redactie: de luxe, efficiente nieuwsredactie voor nieuwsbedrijven (het Journalistiek-genre).',
    ['Plaats met een knop snel nieuws, of schrijf artikelen als concept en publiceer later', 'Beheer rubrieken en volg wat het best gelezen wordt', 'Bouw de eigen krantsite volledig in je eigen huisstijl met blokken'],
    'Een compleet redactiekantoor achter de zaak-inlog; de gepubliceerde krant leest iedereen in RTG Krant.'),
  '/apps/redactie-pda.html': G('De verslaggevers-PDA: snel nieuws plaatsen vanaf locatie, zo van de straat de krant in.',
    ['Typ een kop, kies een rubriek en publiceer meteen', 'Of bewaar als concept voor de eindredactie', 'Zie je recente stukken en zet ze live of terug naar concept'],
    'De redactie op zak: kort schrijven, direct publiceren, later bijschaven op kantoor.'),
  '/apps/krant.html': G('RTG Krant: lees de kranten die nieuwsbedrijven binnen RTG uitgeven, elk in de eigen huisstijl.',
    ['Kies een krant in de gids of open er een op adres', 'Blader per rubriek en lees het volledige artikel', 'De voorpagina staat in de eigen huisstijl van de krant'],
    'Onafhankelijk nieuws binnen het huis: elke titel met een eigen gezicht, gemaakt in de RTG Redactie.'),
  '/apps/passkeys.html': G('Passkeys: inloggen met je vingerafdruk, gezicht of sleutel; geen wachtwoord meer.',
    ['Maak een passkey aan op dit toestel', 'Log voortaan in zonder wachtwoord', 'Beheer of verwijder je sleutels'],
    'Een passkey is niet te phishen: er valt niets over te typen of af te kijken.'),
  '/apps/vluchten.html': G('RTG Vluchten: je vluchten en de private aviation van partners.',
    ['Bekijk vluchten en beschikbaarheid', 'Vraag een boeking aan; de partner bevestigt', 'Volg je reis in de app'],
    'Boekingen zijn pas definitief na bevestiging; de app zegt dat ook eerlijk.'),
  '/apps/thuiswacht.html': G('De Thuiswacht: je zegt hoe lang je onderweg bent, en meld je je niet, dan krijgt je kring bericht met je laatst bekende plek.',
    ['Kies hoe lang je onderweg bent en start de wacht', 'Druk op "Ik ben thuis" zodra je binnen bent', 'Stuur je kring een keer een proefalarm, zodat je weet dat het werkt'],
    'De klok loopt op de server, niet in de app: valt je telefoon uit, dan gaat het alarm juist wel af. Stilte is hier het signaal.'),
  '/apps/codewoord.html': G('Het Codewoord: een gewone zin die je kring stil waarschuwt met je plek, zonder dat er op je scherm iets gebeurt.',
    ['Kies een zin van minstens drie woorden die niet opvalt', 'Laat hem vallen in een gewoon gesprek met Rahul', 'Oefen hem af en toe als je alleen bent'],
    'Je zin wordt alleen als onleesbare afdruk bewaard; ook wij kunnen hem niet teruglezen, en het scherm toont hem nooit meer.'),
  '/apps/life.html': G('RTG Life: alles wat vandaag over jouw leven bij RTG te zeggen valt, op een scherm.',
    ['Lees bovenaan waar vandaag het meeste te winnen valt', 'Bekijk je signalen; wat niet gemeten wordt zegt dat er ook bij',
      'Spring door naar Doelen, Balans of je afspraken'],
    'Dit scherm meet zelf niets en legt niets vast: het leest de lagen die je al had. Staat er "niet gemeten", dan is er geen bron, en niet een slechte uitslag.'),
  '/apps/doelen.html': G('Doelen: waar je begon, waar je heen wilt, wanneer en waarom.',
    ['Zet een doel neer met je beginpunt, je streefpunt en een datum', 'Zet af en toe een meting erin',
      'Loopt het anders? Verzet de datum; het pad wordt opnieuw uitgerekend vanaf waar je staat'],
    'De mijlpalen liggen niet vast maar worden elke keer opnieuw berekend. Een gemiste week is daarom geen mislukking, alleen een ander pad; er zijn geen reeksen om bij te houden.'),
  '/apps/vitaal.html': G('Vitaal: een dagelijkse check-in voor medicijnen, of gewoon om te laten weten dat het goed gaat.',
    ['Stel in hoe vaak je je meldt', 'Druk op "Het gaat goed"', 'Kies wie er gaat kijken als je je niet meldt'],
    'Je hoeft de app niet open te hebben: de server telt af, dus een vergeten check-in valt vanzelf op.'),
  '/apps/thuisrust.html': G('Thuisrust: niet storen tot je thuis bent, zonder dat je onbereikbaar wordt.',
    ['Kies een stand en hoe lang hij hooguit duurt', 'De wereld gaat stil; je kring komt er altijd doorheen', 'De stand eindigt vanzelf, of zodra je incheckt in de Thuiswacht'],
    'De veiligheidsbaan is de hele truc: je hoeft niet te kiezen tussen rust en bereikbaar zijn voor wie ertoe doet.'),
  '/apps/schoolpartner.html': G('De School Partner-app: de werkbank voor directie en lerarenteam, rechtstreeks op de leerlijn.',
    ['Directie: laat personeel toe en zie alle klassen met hun cijfers', 'Leraar: start een online les, zet collega\'s vast op je klas (max drie) of neem er een waar', 'Zet met een paar vinkjes een SO, proefwerk, examen of MO klaar uit de leerlijn; het cijfervoorstel blijft een advies'],
    'De motor kijkt na, maar de leraar beslist: elk cijfer is pas een cijfer als een mens erop drukt.'),
  '/apps/ik.html': G('Wie ben ik: wat Rahul over jou mag weten, en hoe hij tegen je doet.',
    ['Kies of Rahul een maatje, plagerig, zakelijk of rustig is', 'Zet je voornaamwoorden en hoe je genoemd wilt worden', 'Geef zelf aan of je iets gelooft; dan feliciteert hij je en houdt hij er rekening mee'],
    'Alles is optioneel en alles is weer weg te halen. Rahul raadt nooit: niet je geloof uit je naam, niet je aanspreekvorm uit je paspoort.'),
  '/apps/residentie.html': G('De Residence: het virtuele grandhotel van RTG om elkaar te leren kennen -- voor je echt op date gaat.',
    ['Speel samen: midgetgolf, darts, kegelen of baantjes zwemmen; in het restaurant stelt het huis vragen', 'Praat met de zaal via de balk onderin, of stuur een schittering of hartje', 'Je suite is een compleet penthouse (bed, douche, keuken, telefoon); nodig iemand uit via de huistelefoon'],
    'Alles is inbegrepen bij de pas en iedereen heet er bij zijn codenaam: gezellig zonder scores, streaks of winkeltjes.')
};
