/* App-gids data, deel1 (de leden-apps, eerste helft; het vervolg staat in
   deel6). Zie ../appgids.js voor de uitleg; nieuwe pagina's krijgen hier (of in
   het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  /* ---- het leden-OS en de leden-apps (RTG-toon: ingetogen, je/jij) ---- */
  '/apps/index.html': G('Het RTG OS-bureaublad: alle apps van het platform als iconen, met de klok en je accounts.',
    ['Meld je eerst aan; zonder aanmelding zie je alleen de welkomstkaart, het gratis RTG-abonnement is de minimale ingang', 'Tik een tegel; de app opent schermvullend en de terug-knop brengt je hier terug', 'Je ziet alleen de tegels van jouw wereld; met Toon alles zie je alles'],
    'Dit is ook de voordeur van de website; op telefoon en groot scherm hetzelfde, passend geschaald.'),
  '/apps/app.html': G('Jouw leden-app: reserveren, boeken, bestellen, chatten en betalen, alles op codenaam.',
    ['Open een genre en reserveer of boek direct', 'Vraag Rahul wat je maar wilt; hij regelt het met jouw inlog', 'Bekijk je codes, tickets en bestellingen onder je profiel'],
    'Je echte naam blijft in de kluis; partners zien alleen je codenaam. Dat is bewust ons ontwerp.'),
  '/apps/bureau.html': G('Het RTG OS-bureaublad (zelfde als de voordeur): alle apps als iconen op elk scherm.',
    ['Tik een tegel; de app opent schermvullend', 'Wissel rechtsboven tussen je accounts', 'Deze oude ingang toont hetzelfde bureaublad als de voordeur'],
    'Handig op een tablet of tweede scherm: alles van RTG op één werkblad.'),
  '/apps/berichten.html': G('Je berichten met vrienden en partners, automatisch vertaald als dat nodig is.',
    ['Stuur een bericht op codenaam', 'Bel of videobel vanuit het gesprek', 'Deel een snap of verhaal met wie jij kiest'],
    'Berichten in een andere taal worden voor je vertaald; jij leest en schrijft gewoon in je eigen taal.'),
  '/apps/pulse.html': G('Pulse: wat er nu speelt in jouw RTG-wereld, rustig gebundeld.',
    ['Lees de hoogtepunten van vandaag', 'Tik door naar de app waar iets gebeurt', 'Stel in waarover je seintjes wilt'],
    'Geen eindeloze feed: Pulse toont wat er is en houdt dan op. Dat is bewust.'),
  '/apps/nieuws.html': G('RTG Nieuws: de redactie bundelt wat voor leden telt.',
    ['Lees artikelen per rubriek', 'Bewaar wat je later wilt lezen', 'Reageer waar dat kan'],
    'Kwaliteit boven snelheid: liever één goed stuk dan tien snelle.'),
  '/apps/hotels.html': G('Verblijven: hotels, appartementen en villa\'s van onze partners, met ledenprijzen.',
    ['Bekijk kamers, foto\'s en vrije data', 'Boek direct; de partner bevestigt', 'Open je kamer met keyless waar dat kan'],
    'De ledenprijsgarantie geldt overal: nooit meer dan de publieke prijs van de partner zelf.'),
  '/apps/reisbureau.html': G('Het RTG-reisbureau: samengestelde reizen tegen de nettoprijs.',
    ['Blader door de reizen of vraag AI-reisadvies', 'Vraag een reis aan; een reisadviseur bevestigt', 'Volg en annuleer je aanvragen onder Mijn'],
    'Vertel je wens in gewone woorden; het advies wijst de best passende reis aan en legt uit waarom.'),
  '/apps/foodcourt.html': G('De Food Court: alle restaurants op een rij, reserveren in een paar tikken.',
    ['Kies een restaurant en bekijk de tijdsloten', 'Reserveer; de zaak beslist en je krijgt bericht', 'Bekijk keuken, prijs en ledenvoordeel per zaak'],
    'Reserveer ruim vooruit voor de populaire avonden; annuleren kan altijd netjes in de app.'),
  '/apps/uitgaan.html': G('Uitgaan: bars, clubs en beachclubs met hun avonden en gastenlijsten.',
    ['Bekijk de avonden per adres', 'Zet jezelf op de gastenlijst', 'Laat je entreecode zien aan de deur'],
    'Je leeftijdslaag bepaalt wat je ziet; dat is voor je eigen veiligheid en die van de zaak.'),
  '/apps/mall.html': G('De RTG Mall: de enige plek waar je bij RTG koopt, van eigen-merk tot boutieks, plus de bibliotheken.',
    ['Bestel eigen-merk en boerderijproducten direct', 'Blader door de App- en Reis-Bibliotheek; installeren is inbegrepen', 'Leg mode apart of laat een maat naar de paskamer brengen'],
    'De bibliotheken zijn een pas-voordeel: tienduizenden apps en een miljoen reisgidsen, zonder bijbetalen.'),
  '/apps/pay.html': G('RTG Pay: betalen en tikken tussen vrienden, veilig en direct.',
    ['Stuur of vraag een tik', 'Bekijk je saldo en geschiedenis', 'Splits een rekening met je gezelschap'],
    'Voor elke betaling zie je eerst een bevestiging; niets gaat er zonder jouw akkoord uit.'),
  '/apps/wbw.html': G('Wie betaalt wat: groepsuitgaven bijhouden met een live balans.',
    ['Maak een groep en zet uitgaven erin', 'Zie live wie wat voorschoot', 'Verreken in één keer via RTG Pay'],
    'Direct na de vakantie verrekenen voorkomt het eeuwige "dat komt nog wel".'),
  '/apps/bank.html': G('RTG Bank: je rekening, sparen en krediet in de vertrouwde RTG-stijl.',
    ['Bekijk je saldo en afschriften', 'Zet spaardoelen en volg ze', 'Vraag krediet aan; een mens beoordeelt'],
    'De AI adviseert, een mens beslist; zeker bij geld houden we die volgorde altijd aan.'),
  '/apps/balans.html': G('RTG Balans: je financiële overzicht en de boekhoudhulp.',
    ['Bekijk inkomsten en uitgaven per maand', 'Laat de AI-boekhouder meedenken', 'Exporteer voor je administratie'],
    'Tien minuten per week naar je balans kijken voorkomt de meeste geldverrassingen.'),
  '/apps/sport.html': G('RTG Sport: kampen, lessen en sportieve activiteiten van partners.',
    ['Bekijk het aanbod en de data', 'Meld je aan voor een kamp of les', 'Stel een vraag aan de organisatie'],
    'Begin klein: één vast uur per week houd je langer vol dan een groots plan.'),
  '/apps/spelen.html': G('Spelen: bordspellen en partyspellen met vrienden, live tegen elkaar.',
    ['Start een lobby en nodig vrienden uit', 'Kies een spel: van dammen tot Magnaat', 'Praat mee in de spelchat'],
    'Sommige spellen hebben een leeftijdspoort; dat regelt de app automatisch netjes voor je.'),
};
