/* App-gids data, deel10: de zeven werkschermen van het Horeca OS naast
   /apps/horeca.html (dat in deel8 staat). Zie ../appgids.js voor de uitleg. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = Object.assign({
  '/apps/horeca-expeditie.html': G('Expeditie en keukenregie: de pas, waar een tafel compleet de deur uit gaat.',
    ['Zie per tafel en gang hoeveel borden klaar zijn en hoe lang het eerste al koud staat',
      'Geef zelf uit; er wordt niets automatisch afgevinkt',
      'Lees de drukterem: openstaande bereidingsminuten gedeeld door het aantal koks'],
    'Staat-koud is het getal dat telt: vier borden die na elkaar de deur uit gaan, zijn vier keer half warm.'),
  '/apps/horeca-bezorg.html': G('Bezorgdispatch en de rit: zones, tijdsloten, volgorde en het afleverbewijs.',
    ['Check een adres: het antwoord noemt de zone, de kosten en anders de reden waarom het niet kan',
      'Vul de tijdsloten in keukenminuten; tien pizza\'s zijn geen tien diners',
      'Loop de rit af van inpakken tot aftekenen; vertrekken kan pas als beide vinkjes staan'],
    'Er wordt geen foto van een mens of een deur bewaard: het bewijs legt vast wat een geschil later beslecht.'),
  '/apps/horeca-hotel.html': G('Gastrekening en roomservice: alles van het verblijf op een rekening.',
    ['Open een gastrekening op een kamer en boek ontbijt, minibar, spa of restaurant erop',
      'Draai de nachtrun; twee keer drukken boekt geen twee nachten',
      'Neem roomservice op, geef hem vrij naar de keuken en boek hem op de kamer'],
    'De toeristenbelasting staat als eigen regel en niet in de kamerprijs: een gast hoort te zien wat hij aan wie betaalt.'),
  '/apps/horeca-events.html': G('Events: offerte, akkoord, verbruik en nacalculatie.',
    ['Zet de posten op een offerte en leg het akkoord vast met een naam erbij',
      'Boek de aanbetaling en later de werkelijke kosten en uren',
      'Draai de nacalculatie: opbrengst, kosten, marge en de opbrengst per gast'],
    'Posten wijzigen na een akkoord maakt een nieuwe versie die opnieuw bevestigd moet worden; de vorige blijft bewaard.'),
  '/apps/horeca-club.html': G('Club: polsbandtegoed, minimum spend en de deurteller.',
    ['Waardeer een polsband op, boek erop af en betaal het restsaldo terug',
      'Zie per VIP-tafel wat er van de minimum spend nog te gaan is',
      'Tel aan de deur in, uit en herbetreding, met de gastenlijst per promoter erbij'],
    'Op een band staat een nummer en een saldo, geen naam: wie hem verliest, verliest zijn tegoed en niet zijn identiteit.'),
  '/apps/horeca-haccp.html': G('HACCP-registratie: temperatuurlogboek, batches en controlelijsten.',
    ['Leg meetpunten met hun grenzen vast en noteer de metingen',
      'Zie welke batches over de datum zijn en boek ze af met een reden',
      'Vink een controlelijst af, punt voor punt'],
    'Wat vandaag nog niet gemeten is, staat er als gemist bij; een leeg logboek ziet er anders precies zo uit als een goed logboek.'),
  '/apps/werk.html': G('RTG Werk OS: de werkplek van een hele organisatie -- projecten, kennis, klanten, service, bouw, IT, contracten en besluiten.',
    ['Ga naar binnen met de werkruimtecode en uw eigen lid-token; dat is bewust iets anders dan uw RTG-pas',
      'Lees uw startscherm: het volgt uw rollen, en wat geen bron heeft staat er als NIET GEMETEN in plaats van als nul',
      'Kies een module en zie de lijst plus wat aandacht vraagt; koppel eenmalig uw RTG-account voor agenda, postvak en kluis'],
    'Wat u niet mag zien, staat er niet als lege doos; en wat nergens wordt gemeten, staat er met de reden erbij.'),
  '/apps/horeca-beheer.html': G('Beheer: de dag over alle kanalen, de fooienpot, de loonkosten en de signalen.',
    ['Lees de omzet per kanaal en per betaalwijze, met fooi en oninbaar apart',
      'Verdeel de fooienpot over gewerkte uren; de som van de delen is exact de pot',
      'Zet het loon tegenover de omzet zonder fooi en bekijk de signalen'],
    'Er staat geen omzetprognose op dit scherm: wat er staat is wat er nu open staat en wat er vandaag is binnengekomen.'),
  '/apps/zakelijk.html': G('Zakelijk vervoer: het reisbeleid van uw bedrijf, de ritten die op uw akkoord wachten en het maandoverzicht.',
    ['Zet de grenzen: maximum per rit, budget per medewerker, tijden, steden en kostenplaatsen',
      'Geef akkoord op de ritten boven uw drempel; tot dat moment staan ze op geen enkel planbord',
      'Lees per maand wat er is gereden, per kostenplaats en per medewerker'],
    'Een leeg veld is geen grens. En elke afwijzing die uw medewerker leest, noemt de regel en het getal -- daarom staat naast de knoppen wat hij ziet.'),
  /* RTG Command staat hier en niet bij de andere kantoorschermen in deel7:
     dat bestand zit tegen de omvangsgrens aan, en een gids-entry is geen reden
     om er overheen te gaan. */
  '/apps/command.html': G('RTG Command: het RTG- en RTF-kantoor in één app. Zien, zoeken, vragen, herstellen en besturen op hetzelfde objectmodel.',
    ['Vraag het in gewone taal aan de operator; u krijgt een gemeten antwoord met oorzaken, en daarna één knop: doe de veilige gevallen en geef mij de uitzonderingen',
      'Zoek in de balk bovenaan op naam, code, kenteken, plaats of status en open elk object als dossier, met de tijdlijn en alles wat eraan hangt',
      'Wijzig een beleidsregel pas nadat u hem als proef hebt doorgerekend; zware regels vragen een tweede paar ogen en zijn met één knop terug te zetten'],
    'Elke functie heeft drie niveaus: handmatig, assisted en autonoom. Welk niveau geldt, hangt niet aan de knop maar aan het beleid van dat moment -- dezelfde handeling is autonoom bij een enkel geval en mensenwerk bij honderd.'),
}, require('./deel10b'));
