/* App-gids data, deel3 (32 pagina's). Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/studio-pda.html': G('De studio-PDA: automotive, marine en aviation op locatie.',
    ['Bekijk programma\'s en hun status', 'Leg schouwingen en metingen vast', 'Deel het lookbook met de klant'],
    'Meet twee keer, noteer één keer; de studio bouwt op jouw cijfers.'),
  '/apps/belastingkantoor.html': G('Het belastingkantoor: de inspecteurskant van de belastingtool.',
    ['Bekijk aangiften en aanslagen', 'Controleer en keur goed of af', 'Beantwoord vragen van ondernemers'],
    'Duidelijk uitleggen waarom iets niet klopt, scheelt drie brieven heen en weer.'),
  '/apps/rechtbank.html': G('De Rechtspraak (griffie): zaken, zittingen en uitspraken.',
    ['Beheer de rol en de zittingen', 'Verwerk stukken van partijen', 'Publiceer uitspraken'],
    'Een nette griffie is het halve vonnis: orde in de stukken, rust in de zaal.'),
  '/apps/gemeente.html': G('RTG Gemeente: het loket van de gemeente voor inwoners.',
    ['Regel documenten en aanvragen', 'Meld iets in de openbare ruimte', 'Volg de status van je zaak'],
    'Alles wat hier kan, hoeft niet meer aan een balie; en de status is altijd eerlijk.'),
  '/apps/gemeenteloket.html': G('Het gemeente-loket: de medewerkerskant van de gemeente.',
    ['Behandel aanvragen van inwoners', 'Zet zaken door naar de buitendienst', 'Koppel de status terug'],
    'De inwoner ziet letterlijk de status die jij zet; houd hem actueel.'),
  '/apps/gemeentepda.html': G('De gemeente-PDA: de buitendienst op straat.',
    ['Pak meldingen op in de wijk', 'Leg vast met foto en plek', 'Meld af als het klaar is'],
    'Een foto bij de afmelding maakt het loket en de melder allebei blij.'),
  '/apps/overheid.html': G('De Overheid: het landelijke loket (MijnOverheid) binnen de demo.',
    ['Bekijk je gegevens en berichten', 'Regel landelijke zaken digitaal', 'Machtig wie namens je mag handelen'],
    'Eén keer inloggen, alles op één plek; en jij bepaalt wie er namens jou iets mag.'),
  '/apps/overheidspda.html': G('De overheids-PDA: de ambtenaar in het veld.',
    ['Bekijk je werkvoorraad', 'Handel zaken op locatie af', 'Leg vast voor het dossier'],
    'Het dossier is het geheugen van de overheid; schrijf voor je opvolger.'),
  '/apps/rijksloket.html': G('Het Rijks-loket: de ambtenarenkant van de landelijke overheid.',
    ['Behandel aanvragen en berichten', 'Werk dossiers bij', 'Koppel besluiten netjes terug'],
    'Een besluit in gewone taal is ook een besluit; liever begrijpelijk dan deftig.'),
  '/apps/luchthaven.html': G('RTG Airport operations: de luchthaven draaiend houden.',
    ['Volg vluchten, gates en bagage', 'Stuur teams aan op piekmomenten', 'Schakel bij verstoring via het draaiboek'],
    'Bij verstoring eerst het draaiboek, dan improviseren; die volgorde redt de dag.'),
  '/apps/marechaussee.html': G('De Brigade RTG Airport: toezicht en grenscontrole in de demo.',
    ['Bekijk de posten en de planning', 'Registreer controles', 'Schakel met de meldkamer'],
    'Rustig en voorspelbaar werken houdt de rij kort en de sfeer goed.'),
  '/apps/meldkamer.html': G('De RTG Meldkamer: alle hulpdiensten op één scherm.',
    ['Neem meldingen aan en zet eenheden in', 'Volg het gezamenlijke rampbeeld', 'Schaal op en af volgens de keten'],
    'De AI-coördinator stelt voor, de centralist beslist; zo blijft de mens aan het stuur.'),
  '/apps/defensie.html': G('RTG Defensie: logistiek, paraatheid, onderhoud en oefeningen.',
    ['Bekijk paraatheid en materieel', 'Plan verplaatsingen en oefeningen', 'Volg de veldhospitaal-keten'],
    'Paraatheid is onderhoud plus oefening; beide staan hier eerlijk in beeld.'),
  '/apps/sportclub.html': G('FC RTG, het clubkantoor: teams, wedstrijden en vrijwilligers.',
    ['Beheer teams en opstellingen', 'Plan wedstrijden en trainingen', 'Regel de kantine en de vrijwilligers'],
    'Een club draait op vrijwilligers: een bedankje in de app doet wonderen.'),
  '/apps/kantoorpda.html': G('De Kantoor-PDA is verhuisd naar de personeels-app.',
    ['Open de personeels-app', 'Kies daar je kantoorfunctie'],
    'Eén app voor al het personeelswerk: dat is makkelijker dan vijf losse.'),
  '/apps/zorgbalie.html': G('De Zorgbalie is verhuisd naar de personeels-app.',
    ['Open de personeels-app', 'Kies daar de medische receptie'],
    'Eén app voor al het personeelswerk: dat is makkelijker dan vijf losse.'),
  '/apps/lesmaker.html': G('De Lesmaker: maak met AI in een paar tikken complete lesstof, uit elk onderwerp of een app uit de bibliotheken.',
    ['Kies een onderwerp en het niveau; de AI schrijft de les met quiz', 'Deel de klascode; de kinderen doen live mee op hun eigen scherm', 'Start elke vraag zelf en volg de klas op het bord'],
    'De AI maakt de stof, u houdt de regie: u bepaalt wat er start en wanneer. Fouten van kinderen zijn leerpunten, geen afrekenmoment.'),
  '/apps/stadsdoos.html': G('De Stadsdoos veld-app: de gemeente-doos op locatie beheren.',
    ['Bekijk de status van de stadsdoos', 'Voer ter plekke controles uit', 'Meld bevindingen aan het loket'],
    'Een doos die je regelmatig naloopt, valt zelden onverwacht uit.'),
  '/apps/juridisch/voorwaarden.html': G('De ledenvoorwaarden van RTG, in gewone taal per hoofdstuk.',
    ['Lees per onderwerp wat er geldt', 'Zoek het hoofdstuk dat je nodig hebt', 'Vragen? Stel ze via de app'],
    'Wij schrijven voorwaarden om gelezen te worden; staat er iets onduidelijks, dan horen we het graag.'),
  '/apps/juridisch/privacy.html': G('De privacyverklaring: wat we bewaren, waarom, en wat jouw rechten zijn.',
    ['Lees wat er met je gegevens gebeurt', 'Bekijk je AVG-rechten (inzage, wissen)', 'Zie hoe de codenaam-kluis werkt'],
    'Partners zien alleen je codenaam; je echte naam blijft in de gescheiden kluis. Dat is de kern van ons ontwerp.'),
  '/apps/juridisch/partnervoorwaarden.html': G('De partnervoorwaarden: de afspraken tussen RTG en de aangesloten zaken.',
    ['Lees de afspraken per hoofdstuk', 'Bekijk het platformmodel en de betaling', 'Vragen? Het kantoor helpt'],
    'De ledenprijsgarantie staat hier zwart op wit: een lid betaalt nooit meer dan de publieke prijs.'),

  /* ---- de RTFoundation-apps (kindvriendelijk: warm, je/jij) ---- */
  '/apps/foundation/index.html': G('Dit is jullie RTFoundation-app: alle hulp en leuke dingen voor het gezin op één plek.',
    ['Kies een tegel die bij je past', 'Vraag een grote mee als iets moeilijk is', 'Alles hier is gratis en veilig'],
    'Alles in deze app is er om je te helpen; er zit nooit een rekening of reclame achter.'),
  '/apps/foundation/agenda.html': G('De gezinsagenda: wat er deze week gebeurt, voor iedereen te zien.',
    ['Zet er iets in dat je niet wilt vergeten', 'Kijk wat er vandaag en morgen is', 'Zet een herinnering voor jezelf'],
    'Elke avond even kijken wat er morgen is; dan begint je dag rustig.'),
  '/apps/foundation/babyboek.html': G('Het fotoboekje: de mooiste momenten van de kleintjes, veilig bij het gezin.',
    ['Zet er een foto en een verhaaltje in', 'Blader terug door de momenten', 'Alleen jullie gezin kan erbij'],
    'Schrijf er een zinnetje bij; over tien jaar is dat zinnetje goud waard.'),
  '/apps/foundation/beheer.html': G('Gezin beheren: hier regelen de groten de profielen en de veiligheid.',
    ['Maak profielen voor het gezin', 'Zet de juiste leeftijdsgroep per kind', 'Beheer de gezinscode'],
    'De leeftijdsgroep bepaalt wat een kind ziet; goed instellen is het halve werk.'),
  '/apps/foundation/bieb.html': G('De App-Bibliotheek: twintigduizend goede apps, allemaal gratis voor jullie.',
    ['Zoek een app of blader per soort', 'Installeer met één tik', 'Bekijk je eigen apps bij Mijn'],
    'Alles is hier echt gratis: geen aankopen, geen reclame, geen trucjes.'),
  '/apps/foundation/schoolbieb.html': G('De School-Bibliotheek: tienduizend school-apps voor jouw leeftijd.',
    ['Kies je niveau en je vak', 'Installeer wat je helpt bij school', 'Leer op jouw tempo'],
    'Elke dag een kwartiertje oefenen werkt beter dan één keer heel lang.'),
  '/apps/foundation/beroepen.html': G('De Beroepen-Bibliotheek: twee miljoen gratis leer-apps over echte beroepen, van lasser tot ondernemer.',
    ['Kies een wereld: technisch & agrarisch, of het bedrijfsleven', 'Zoek een beroep en begin bij het leerpad op jouw niveau', 'Installeer wat je helpt; alles is gratis'],
    'Een vak leren is goud waard: met je handen of met je hoofd, allebei is even knap.'),
  '/apps/foundation/bord.html': G('Het bord: jullie gezinsbord met briefjes en plannen.',
    ['Hang er een briefje op', 'Schuif kaartjes naar klaar', 'Kijk wat de anderen erop zetten'],
    'Een briefje op het bord is nooit zeuren; zo weet iedereen het gewoon.'),
  '/apps/foundation/contact.html': G('Contact: praten met je gezin en je vrienden, veilig en vertaald als het moet.',
    ['Stuur een berichtje', 'Bel of videobel', 'Nieuwe vrienden keurt een grote eerst goed'],
    'Twijfel je over een bericht van iemand? Laat het een grote zien; dat is nooit klikken.'),
  '/apps/foundation/cv.html': G('De CV-maker: maak stap voor stap een net cv voor je bijbaan of stage.',
    ['Vul de stappen in; je ziet je cv meteen', 'Alles wordt op je toestel bewaard', 'Klaar? Download of deel hem'],
    'Schrijf op wat je écht gedaan hebt, ook klusjes en hobby\'s; dat is meer waard dan dure woorden.'),
  '/apps/foundation/dromen.html': G('Onze dromen: wat jullie gezin later wil; samen sparen en plannen.',
    ['Zet een droom erbij', 'Kijk hoe ver jullie zijn', 'Vier de kleine stappen'],
    'Een grote droom wordt haalbaar als je hem in stapjes knipt.'),
};
