/* App-gids data, deel4 (19 pagina's). Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/foundation/meedoen-ontdekken.html': G('Meedoen & Ontdekken: openbaar buurtaanbod en kansen uit FoundationOS in één warme ingang.',
    ['Kies zelf uw stad en bekijk alleen activiteiten die echt openstaan', 'Bewaar belangstelling op uw toestel en neem de gegevens mee naar de organisator', 'Start vanuit Maken een club, project, buurtruil of onderzoek in het Living Lab'],
    'FoundationOS vraagt uw precieze locatie niet. Belangstelling is nog geen reservering; de organisator bevestigt uw plek.'),
  '/apps/foundation/veilig-vertrouwd.html': G('Veilig & Vertrouwd: uw gezinsstatus, vertrouwde kring en passende hulp op één rustige plek.',
    ['Laat zonder precieze locatie weten dat u veilig thuis of onderweg bent', 'Bekijk echte banden en wat u per persoon deelt of mag zien', 'Bel bij direct gevaar 112 of open Veilig Thuis en andere bestaande hulproutes'],
    'Door een scherm te openen wordt niets verstuurd. Een band geeft nooit vanzelf toegang en een korte status deelt geen GPS-positie.'),
  '/apps/foundation/gezondheid-welzijn.html': G('Gezondheid & Welzijn: wat vandaag helpt, uw eigen ritme en echte zorgcontacten op één rustige plek.',
    ['Bekijk vastgelegde medicatie en komende gezondheidsafspraken', 'Onthoud slaap, beweging, eten, rust en gevoel alleen op uw eigen toestel', 'Open echte RTG Care-contacten, uw vertrouwde kring of de hulpwijzer'],
    'Deze app geeft geen diagnose of gezondheidsscore en verzint geen huisarts of begeleider. Wat niet aan een echte bron is gekoppeld, blijft leeg.'),
  '/apps/foundation/geld-later.html': G('Geld & Later: begrijp uw ruimte van vandaag en vind de volgende haalbare stap naar leren, studie of werk.',
    ['Bekijk het echte zakgeldpotje, spaardoel en de beweging van deze maand', 'Open leren, studie, vacatures en de lokale cv vanuit één route', 'Bereken een budget, start een echt spaardoel of bekijk uw rechten'],
    'De toekomstlijn is een routekaart, geen voorspelling. Het budget en cv blijven op dit toestel.'),
  '/apps/foundation/samen-thuis.html': G('Samen Thuis: de gezamenlijke dag, ieder gezinslid en kleine afspraken op één rustige plek.',
    ['Bekijk echte afspraken, taken en het geplande eten van vandaag', 'Zie per gezinslid alleen vastgelegde afspraken en ochtendstatus', 'Verdeel een taak, vraag hulp of zet een herinnering op de dag'],
    'Samen Thuis raadt geen locatie of aanwezigheid. Wat niet door het gezin is vastgelegd, wordt ook niet als feit getoond.'),
  '/apps/foundation/registreren.html': G('De veilige FOUNDATION-balie voor een gezin, school, vrijwilliger of partnerstichting.',
    ['Kies hoe je wilt meedoen', 'Vul alleen de gevraagde registratiegegevens in', 'Volg daarna de officiële controles'],
    'Mail nooit een kopie van je identiteitsbewijs of VOG; een medewerker legt alleen de controle-uitkomst vast.'),
  '/apps/foundation/geld.html': G('Het geldmaatje: leren omgaan met geld, op jouw niveau.',
    ['Doe de leerstukjes over geld', 'Oefen met sparen en kiezen', 'Vraag als iets niet klopt'],
    'Eerst sparen, dan kopen: wie dat jong leert, heeft er zijn leven lang plezier van.'),
  '/apps/foundation/gezondheid.html': G('Het gezondheidsmaatje: goed voor jezelf zorgen, zonder gedoe.',
    ['Bekijk tips over slapen, eten en bewegen', 'Houd bij hoe je je voelt', 'Vraag hulp als het nodig is'],
    'Goed slapen is de beste superkracht die er is; echt waar.'),
  '/apps/foundation/hulpwijzer.html': G('De hulpwijzer: waar je terecht kunt als je ergens mee zit.',
    ['Zoek op waar je hulp bij wilt', 'Zie wie je kunt bellen of schrijven', 'Alles is vertrouwelijk'],
    'Hulp vragen is dapper, niet zwak; de eerste stap is de moeilijkste en die kun jij.'),
  '/apps/foundation/arena.html': G('De Arena: snelle duels tegen je vrienden of klasgenoten, of solo trainen.',
    ['Kies het Flitsduel (tien sommen), het Reactieduel (het stoplicht) of het Geheugenduel (reeksen natikken)', 'Daag vrienden of klasgenoten uit; klasgenoten zien alleen je codenaam', 'Solo oefenen kan altijd, zonder tegenstander'],
    'Alles telt alleen binnen het potje: geen ranglijst, geen bewaarde scores.'),
  '/apps/foundation/keuken.html': G('De gezinskeuken: samen koken, boodschappen en weekmenu\'s.',
    ['Kies recepten voor de week', 'Maak samen het boodschappenlijstje', 'Kook met de stap-voor-stap-hulp'],
    'Wie helpt koken, eet lekkerder; proef onderweg en je leert vanzelf.'),
  '/apps/foundation/klusjes.html': G('Klusjes en sterren: helpen in huis en er iets voor terugzien.',
    ['Kies een klusje van de lijst', 'Klaar? Zet hem af en verdien sterren', 'Spaar je sterren voor iets leuks'],
    'Elke dag een klein klusje voelt licht; alles op zaterdag voelt zwaar.'),
  '/apps/foundation/kompas.html': G('Het kompas: nadenken over wie je bent en wat je wilt, met een maatje dat meedenkt.',
    ['Doe de denkstukjes op jouw tempo', 'Schrijf op wat je ontdekt', 'Deel alleen wat jij wilt delen'],
    'Er is geen goed of fout antwoord over wie jij bent; nadenken zelf is het punt.'),
  '/apps/foundation/leren.html': G('Leren & Groei: zie wat vandaag telt, wat al groeit en wie rustig met je mee kan kijken.',
    ['Kies een voorgestelde stap uit je echte leerroute', 'Bekijk leerdoelen met bewijs zonder ranglijst', 'Vraag om een andere uitleg of open een live les met een begeleider'],
    'Het dagplan is een voorstel, geen opdracht. Er is geen reeks, achterstand of vergelijking met een ander.'),
  '/apps/foundation/markt.html': G('Koopje: de gezinsmarkt voor tweedehands en delen.',
    ['Zet iets erop dat weg mag', 'Zoek iets dat jullie nodig hebben', 'Ruil of geef door in de buurt'],
    'Wat jij niet meer gebruikt, maakt een ander blij; doorgeven is twee keer winst.'),
  '/apps/foundation/partner.html': G('De Stadsraad: het portaal van de stadspartner (foundation, club of instelling).',
    ['Log in met de raadcode van uw stad', 'Bekijk de lab-uitslagen die op de raadstafel liggen', 'Stem namens uw stad; een besluit valt pas als beide kanten gestemd hebben'],
    'Per stad een invloedrijke partner; samen met RTG-personeel beslist u over de uitslagen van het onderzoek.'),
  '/apps/foundation/ochtend.html': G('Het ochtendritme: rustig opstaan met een vast lijstje.',
    ['Zet jullie ochtendstappen op volgorde', 'Vink af wat klaar is', 'Zie in één blik of iedereen op schema ligt'],
    'Een vast ritme maakt de ochtend rustig; je hoofd hoeft niet meer na te denken.'),
  '/apps/foundation/oppasinfo.html': G('Belangrijke info: alles wat een oppas of invaller moet weten.',
    ['Zet de belangrijke dingen erin (allergieën, bedtijd, nummers)', 'Deel met de oppas van vanavond', 'Haal de toegang daarna weer weg'],
    'Wat op papier bij de koelkast hing, staat nu veilig hier; en je kunt het weer intrekken.'),
  '/apps/foundation/opvoeden.html': G('Opvoedhulp: steun voor ouders, zonder oordeel.',
    ['Lees per leeftijd wat helpt', 'Bekijk hoe andere ouders het doen', 'Vraag hulp als het zwaar wordt'],
    'Niemand voedt perfect op; goed genoeg is echt goed genoeg.'),
  '/apps/foundation/overhoren.html': G('Overhoren: woordjes en begrippen erin krijgen, op de slimme manier.',
    ['Maak of kies een lijst', 'Laat je overhoren; fouten komen vaker terug', 'Speel een duel met een vriend'],
    'Tien minuten per dag verslaat twee uur op de avond ervoor; je hoofd houdt van herhalen.'),
  '/apps/foundation/pesten.html': G('Sterker dan pesten: wat je kunt doen als jij of een ander gepest wordt.',
    ['Lees wat je kunt zeggen en doen', 'Bewaar bewijs van online pesten', 'Praat met een grote die je vertrouwt'],
    'Pesten is nooit jouw schuld; erover praten is de sterkste zet die er is.'),
  '/apps/foundation/onveilig.html': G('Als je niet veilig bent: waar je gratis terechtkunt, per situatie.',
    ['Zoek de situatie die op jou lijkt', 'Bel of chat -- anoniem mag', 'Lees wat wij niet voor je kunnen verbergen'],
    'Bij direct gevaar 112; onveilig thuis is Veilig Thuis, 0800-2000, dag en nacht en gratis.'),
  '/apps/foundation/wegwijzer.html': G('Zelf iets in gang zetten, zonder account en zonder uw naam.',
    ['Zeg of u nu veilig bent', 'Kies wat wij mogen bewaren', 'Bewaar uw code om het in te trekken'],
    'Hier zit niemand klaar: moet er nu iemand komen, bel dan 112 of Veilig Thuis 0800-2000.'),
  '/apps/foundation/privacy.html': G('Privacy en veiligheid: wat van jou is, blijft van jou.',
    ['Leer wat je beter niet deelt', 'Check je instellingen samen met een grote', 'Meld het als iets niet klopt'],
    'Een foto die weg is, is nooit echt weg; denk drie tellen na voor je deelt.'),
  '/apps/foundation/projecten.html': G('Samen aan een project: met je gezin of vrienden iets moois maken.',
    ['Start een project en nodig uit', 'Verdeel de taken', 'Vier het als het af is'],
    'Een project af maken leert je meer dan tien beginnen; klein beginnen mag.'),
  '/apps/foundation/reis.html': G('Op reis: alles voor een gezinsreis, van paklijst tot spelletjes onderweg.',
    ['Maak samen de paklijst', 'Bekijk tips voor onderweg', 'Speel de reisspelletjes in de auto'],
    'Wie zijn eigen tas inpakt, vergeet minder én sjouwt bewuster.'),
};
