/* App-gids data, deel 12: de samengestelde commandoschermen en Living OS.
   Zie ../appgids.js voor de gedeelde uitleglaag. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/festival.html': G('Het festival draaien: de poort, het beeld en het terrein.',
    ['Poort: kies waar u staat; het veld houdt zelf de focus, zodat een handscanner gewoon werkt',
      'Beeld: alleen wat aandacht vraagt, met de tijd die er nog is -- en welke plekken NIET gemeten worden',
      'Zonder verbinding heet een scan ONBEVESTIGD en gaat hij in de wachtrij, nooit groen'],
    'Oranje is zelden fraude: iemand liep terug naar zijn auto, of een hek stond even offline. Er staat bij waar en hoe laat de eerste scan was, zodat u het kunt vragen in plaats van te weigeren.'),
  '/apps/festival-gast.html': G('Uw kant van het festival: uw pas, het programma en uw groep.',
    ['Uw pascode staat groot in beeld -- dat is wat u aan de poort laat zien',
      'Het programma toont alleen sets die getekend zijn, met erbij hoeveel er nog niet rond zijn',
      'Een groep maakt u zelf; u geeft de code aan wie u erbij wilt, RTG stuurt niemand iets'],
    'Een festival verschijnt hier zodra u er een pas heeft of in een groep zit. Er is geen lijst met festivals om uit te kiezen.'),
  '/apps/arrival.html': G('Invisible Arrival: een tijdelijke gastpas waarmee een zaak uw komst kan voorbereiden zonder uw route of GPS te volgen.',
    ['Vertel Rahul het moment, gezelschap en alleen de wensen die voor dit bezoek nodig zijn',
      'Controleer het voorstel voordat u de aanvraag verstuurt',
      'Deel vrijwillig onderweg, in de buurt of gearriveerd; stop delen wanneer u wilt'],
    'De tijdelijke pas is het toegangsbewijs en verloopt na het bezoek. Deel hem dus niet met anderen.'),
  '/apps/geld-command.html': G('RTG Geld Command: uw rekeningen, plannen, veiligheidsgrenzen en beslissingen in een financieel werkblad.',
    ['Lees eerst wat vandaag echt aandacht vraagt', 'Simuleer een keuze voordat er geld beweegt',
      'Bevestig een betaling altijd zelf bij de financiële leverancier'],
    'Rahul mag rekenen, vergelijken en voorbereiden; geld verplaatsen blijft een persoonlijke handeling.'),
  '/apps/living-os.html': G('Het Vooruitzicht, de cockpit van LivingOS: geld, tijd, energie, mensen en beleving als een samenhangende wereld vooruit bekijken.',
    ['Beschrijf het gewenste resultaat en de harde grenzen; vergelijk de waarschijnlijke, ideale en verstoorde wereld',
      'Bekijk wat lokaal klaarstaat en waarop providers nog moeten antwoorden',
      'Geef alleen de voorbereiding vrij; boeken en betalen blijven apart geblokkeerd'],
    'Gereed betekent pas gereed als de echte provider dat heeft bevestigd; een mooie voorspelling is geen bewijs. Een simulatie helpt kiezen maar beslist niet.'),
  '/apps/partner-network.html': G('Symbiotic Partner Network: bedrijven werken rond één gastbelofte samen zonder hun hele dossiers te delen.',
    ['Open het gezamenlijke servicecontract', 'Vergelijk capaciteit, kwaliteit, marge en privacy per partner',
      'Kies een herstelroute wanneer een deelnemer de belofte niet kan dragen'],
    'Iedere partner ontvangt alleen wat nodig is voor zijn eigen deel; de gezamenlijke uitkomst blijft controleerbaar.'),
  '/apps/reizen-veilig.html': G('Reizen en Veilig: plannen, vervoer, aankomst en vrijwillige veiligheidsdeling in één reiswerkruimte.',
    ['Plan vervoer op tijd, prijs en uitstoot', 'Open uw samengestelde reizen naast de live reisdag',
      'Kies per moment wie uw plan, voortgang of tijdelijke locatie mag zien'],
    'Locatie delen staat standaard uit, stopt automatisch en kan ieder moment handmatig worden beëindigd.'),
  '/apps/vandaag.html': G('Vandaag: uw korte dagbriefing en de snelste ingang naar de software die nu nodig is.',
    ['Lees de briefing van Rahul', 'Open een voorstel of vraag in gewone taal om een andere app',
      'Zet een tweede werkblad ernaast wanneer twee onderwerpen bij dezelfde beslissing horen'],
    'Vandaag is een regiescherm: de bronapp blijft de plek waar gegevens worden gewijzigd of een handeling definitief wordt uitgevoerd.')
};
