/* App-gids data, deel5. Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/foundation/kantoor.html': G('Het RTF-kantoor: het eigen kantoor van de RTFoundation, gebouwd op dezelfde plattegrond als het RTG-kantoor.',
    ['Loop de kamers langs met hun cijfers en werklijsten', 'Zet taken per kamer en vink ze af', 'Zie de 30%-stroom, de clubs en het lab in een oogopslag'],
    'Dezelfde structuur als het RTG-kantoor: wie het ene huis kent, kan meteen in het andere werken.'),
  '/apps/foundation/clubswerk.html': G('Clubs & steden: de RTF-afdeling die met grote (sport)clubs in elke stad samenwerkt.',
    ['Meld een club aan en geef de clubcode door', 'Hang programma\'s en afspraken aan de samenwerking', 'Koppel RTF-teamleden en schrijf in het gedeelde log'],
    'Een club met een vast RTF-gezicht en een gedeeld logboek werkt sneller dan tien losse mailtjes.'),
  '/apps/foundation/club.html': G('Het clubportaal: uw club en de RTFoundation, samen op een scherm.',
    ['Meld aan met uw clubcode', 'Bekijk de programma\'s, afspraken en uw vaste RTF-team', 'Schrijf in het gedeelde samenwerkingslog'],
    'U ziet hier alleen het dossier van uw eigen club; zo hoort het.'),
  '/apps/lab.html': G('Het RTG Onderzoekslab: onderzoek en ontwikkeling voor RTG en de RTFoundation samen.',
    ['Start een project in een veld (hardware, software, dorpshulp, landbouw, meta-onderzoek)', 'Doorloop de vaste keten: idee, onderzoek, prototype, proef, uitrol', 'Laat een mens de veiligheids- en ethiektoets tekenen en bouw de kennisbank'],
    'Een kleine eerlijke proef verslaat een groot vaag plan; en de kennisbank vergeet nooit iets.'),
  '/apps/foundation/magazine.html': G('Het RTFoundation-magazine: wat de foundation doet, waarom en hoe.',
    ['Lees hoe 30% van elke bijdrage naar goede doelen gaat', 'Zie de verdeling: 20% lokaal, 10% de foundation zelf', 'Volg de ingangen naar het Lab-fonds, de clubs en de gezinsapp'],
    'Empowering journeys, building futures: reizen die vooruit brengen, dichtbij en verder weg.'),
  '/apps/labfonds.html': G('Het Lab-fonds: leden zamelen samen in voor het RTF Onderzoekslab, per locatie verdeeld.',
    ['Zamel in voor de omgeving die jij kent; het geld gaat naar de pot van die plek', 'Doe een voorstel wat de pot in de omgeving kan betekenen', 'Beslis samen: de leden stemmen, de AI-scheidsrechter bewaakt de eerlijkheid'],
    'Het fonds is er voor de omgeving, nooit voor prive gewin; daarom kijkt een scheidsrechter mee en beslis je samen.'),
  '/apps/rtgcode.html': G('De RTG-code: een gesloten, levende code die alleen onze app maakt en leest, in RTG-stijl.',
    ['Toon je levende code; hij ververst zichzelf en vervalt binnen tientallen seconden', 'Kies het merkteken in het hart: de lippen of het horloge', 'Scan of plak een code; de app verifieert hem en weigert verlopen of vreemde codes'],
    'Geen gewone QR: alleen de RTG-app kan de code duiden, en een foto veroudert vanzelf.'),
  '/apps/pakketten.html': G('RTG Bedrijfspakketten: kies je bedrijfstype en krijg de juiste indeling voor je eigen zaak.',
    ['Kies je type (tech, horeca, retail, hotel, zorg, creatief)', 'Zie de werkplekken, werk-apps en technieken die je nodig hebt, met een 3D-plattegrond en QR-codes', 'Vertel je situatie en laat Rahul het pakket op maat bijkleuren'],
    'Dit gaat over jouw zaak; hoe de RTG-kantoren zelf werken blijft bedrijfsgeheim.'),

  '/apps/werkplek.html': G('De werkplek: RTG en de RTFoundation zijn twee huizen; u kiest er een en werkt daarbinnen.',
    ['Kies het huis waar u vandaag werkt; u ziet alleen dat huis', 'Bekijk de cijfers en wat er op dit moment loopt', 'Houd de bezetting en de takenlijst van dat huis bij'],
    'De bezetting draait op codenamen: de echte naam blijft in de kluis, ook op uw eigen werkplek.'),

  /* ---- de kleinsten (0 t/m 5), samen met papa of mama ---- */
  '/apps/foundation/tellen.html': G('Tellen tot tien: dingen aantikken en samen hardop meetellen.',
    ['Tik de plaatjes een voor een aan; bij elke tik komt er een cijfer bij', 'Kies daarna hoeveel het er waren', 'Ga door zolang uw kind wil, of stop gewoon'],
    'Geen klok en geen puntentelling: het hardop meetellen van een volwassene doet het werk.'),
  '/apps/foundation/kleuren.html': G('Kleuren en vormen: zoeken op kleur, op vorm, of op allebei tegelijk.',
    ['Kies de moeilijkheid: alleen kleur, alleen vorm, of beide', 'Lees de opdracht voor en laat uw kind aanwijzen', 'Bij een misser blijft het spel gewoon staan, zonder straf'],
    'Begin bij alleen kleur; beide tegelijk is voor veel kleuters nog een stap te ver.'),
  '/apps/foundation/memorie.html': G('Memorie: kaartjes omdraaien en paren zoeken.',
    ['Kies drie, zes of acht paren', 'Draai twee kaartjes om; passen ze niet, dan gaan ze weer dicht', 'Speel mee en benoem hardop wat u ziet'],
    'Drie paren is voor een peuter al een hele klus; groter maken kan altijd nog.'),
  '/apps/foundation/verhaaltje.html': G('Voorleesverhaaltjes: zes korte verhalen om samen te lezen, bladzijde voor bladzijde.',
    ['Kies een verhaaltje uit de lijst', 'Blader met Vorige en Volgende; niets gaat vanzelf verder', 'Lees hardop voor en kijk samen naar de plaat'],
    'De verhalen zijn voor deze app geschreven, lopen goed af en bevatten niets engs.'),
  '/apps/foundation/liedjes.html': G('Liedjes en versjes: oude Nederlandse liedjes met de tekst groot in beeld.',
    ['Filter op zingen, handjes of slapen', 'Kies een liedje; de hele tekst komt in beeld', 'Zing zelf: er wordt met opzet geen geluid afgespeeld'],
    'De mooiste versie is die van uw eigen stem; herhaling werkt bij kleintjes beter dan afwisseling.'),
  '/apps/foundation/gevoel.html': G('Hoe voel je je: het gezichtje aantikken dat past, en samen kijken wat helpt.',
    ['Tik het gevoel aan dat het beste past', 'Lees samen het zinnetje en de drie dingen die kunnen helpen', 'Adem mee met de bol als het te druk wordt van binnen'],
    'Er wordt niets opgeslagen of verstuurd: gevoelens van een kind horen niet in een dossier.'),

  /* ---- tieners ---- */
  '/apps/foundation/presenteren.html': G('Spreekbeurt en presentatie: je verhaal opbouwen in vaste stukken, met tijdverdeling en een oefenklok.',
    ['Vul de acht onderdelen in, van opening tot vragen', 'Zet je spreektijd en zie hoeveel tijd elk stuk krijgt', 'Oefen hardop met de klok en print je briefje met steekwoorden'],
    'Twee keer hardop en staand oefenen scheelt meer dan tien keer in je hoofd doorlezen.'),
  '/apps/foundation/budget.html': G('Maandbegroting: wat komt binnen, wat gaat eruit, wat houd je over.',
    ['Zet je inkomsten erin, met de suggesties als startpunt', 'Vul je uitgaven aan en zie de balk meteen meebewegen', 'Zet een spaardoel en lees hoeveel maanden dat kost'],
    'Alles blijft in je eigen scherm; dit is algemene uitleg, geen financieel advies.'),
  '/apps/foundation/rechten.html': G('Wat mag ik op welke leeftijd: werken, geld, school en zorg per leeftijd.',
    ['Kies je leeftijd en zie wat nu al geldt en wat nog komt', 'Filter op werk, school, zelf beslissen, zorg of online', 'Bekijk de werktijdentabel die bij jouw leeftijd hoort'],
    'Algemene informatie over de Nederlandse regels, geen juridisch advies; je cao of school kan strenger zijn.'),
  '/apps/foundation/mediawijs.html': G('Online wijs: echte situaties van je telefoon, met eerlijke uitleg over wat je keuze oplevert.',
    ['Lees de situatie en kies wat je zou doen', 'Zie meteen waarom die keuze verstandig, matig of riskant is', 'Onthoud de regel die eronder staat en ga door naar de volgende'],
    'Er is geen goed cijfer te halen; de bedoeling is dat je de valkuil herkent voordat hij echt langskomt.'),
  '/apps/vertaler.html': G('RTG Vertaler: typen of spreken, live vertalen op de eigen motor.',
    ['Kies de talen (of wissel ze om) en typ; na een halve seconde rust staat de vertaling er',
     'Druk op Spreek om te dicteren en op Lees voor om de vertaling te horen',
     'Onderweg? De reiszinnen per situatie vertalen met een tik; bewaar je vaste zinnen op het toestel'],
    'Geschiedenis en bewaarde zinnen blijven op je toestel; zonder AI-sleutel vertaalt het huiswoordenboek en zegt de app eerlijk wat niet lukt.'),
  '/apps/memo.html': G('RTG Memo: spraakmemo\'s die gewoon in je Bestanden-kluis leven.',
    ['Druk op Neem op en spreek in; stoppen is bewaren (map Memo\'s in je kluis)',
     'Zet het meeluisteren aan voor een transcript; dat blijft op je toestel',
     'Druk op Samenvatting en Rahul vat het transcript samen -- de audio gaat nooit naar de AI'],
    'Weggooien is naar de prullenbak van je kluis (30 dagen te herstellen) en je kluiskwota is dezelfde; geen tweede opslaglaag.')
};
