/* App-gids data, deel7b (het vervolg van deel7; dat bestand liep over de
   10 KB-keuringsgrens). Zie ../appgids.js voor de uitleg. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/thuiswacht.html': G('De Thuiswacht: je zegt hoe lang je onderweg bent, en meld je je niet, dan krijgt je kring bericht met je laatst bekende plek.',
    ['Kies hoe lang je onderweg bent en start de wacht', 'Druk op "Ik ben thuis" zodra je binnen bent', 'Stuur je kring een keer een proefalarm, zodat je weet dat het werkt'],
    'De klok loopt op de server, niet in de app: valt je telefoon uit, dan gaat het alarm juist wel af. Stilte is hier het signaal.'),
  '/apps/codewoord.html': G('Het Codewoord: een gewone zin die je kring stil waarschuwt met je plek, zonder dat er op je scherm iets gebeurt.',
    ['Kies een zin van minstens drie woorden die niet opvalt', 'Laat hem vallen in een gewoon gesprek met Rahul', 'Oefen hem af en toe als je alleen bent'],
    'Je zin wordt alleen als onleesbare afdruk bewaard; ook wij kunnen hem niet teruglezen, en het scherm toont hem nooit meer.'),
  '/apps/toestemming.html': G('Toestemming: wie raakt jouw gegevens aan, en waar zet je dat stop.',
    ['Zie per partij wat die mag zien en tot wanneer', 'Trek in wat je niet meer wilt',
      'Lees onderaan waar deze lijst ophoudt'],
    'Intrekken gaat naar de laag waar de toestemming leeft, niet naar een vinkje hier: er blijft dus nergens een kopie staan die nog wel mag.'),
  '/apps/life.html': G('RTG Life: alles wat vandaag over jouw leven bij RTG te zeggen valt, op een scherm.',
    ['Begin bij "Uw dag": alles wat vandaag ergens staat, op volgorde van de klok',
      'Lees bovenaan waar vandaag het meeste te winnen valt', 'Bekijk je signalen; wat niet gemeten wordt zegt dat er ook bij',
      'Zet onderaan je noodkaart klaar: wie er gebeld moet worden als jij het even niet kunt vertellen',
      'Spring door naar Doelen, Balans of je afspraken'],
    'Dit scherm meet zelf niets en legt niets vast: het leest de lagen die je al had. Staat er "niet gemeten", dan is er geen bron, en niet een slechte uitslag. RTG deelt je dag ook niet in -- het weet niet hoeveel energie je hebt of wat er buiten RTG in je dag staat, en een indeling verzinnen uit de rest levert een zelfverzekerd verkeerd plan. Ook je noodkaart is een lezer: de allergenen erop komen uit je zorgprofiel, dus er staat nooit iets op wat je daar hebt weggehaald, en niemand kan hem op afstand opvragen.'),
  '/apps/doelen.html': G('Doelen: waar je begon, waar je heen wilt, wanneer en waarom.',
    ['Zet een doel neer met je beginpunt, je streefpunt en een datum', 'Zet af en toe een meting erin',
      'Loopt het anders? Verzet de datum; het pad wordt opnieuw uitgerekend vanaf waar je staat'],
    'De mijlpalen liggen niet vast maar worden elke keer opnieuw berekend. Een gemiste week is daarom geen mislukking, alleen een ander pad; er zijn geen reeksen om bij te houden.'),
  '/apps/gedachten.html': G('Gedachtenboek: iets opschrijven, voor jezelf.',
    ['Schrijf op wat je kwijt wilt', 'Lees terug wat je eerder schreef', 'Gooi weg wat weg mag; er blijft geen kopie staan'],
    'Er leest geen model mee, er wordt niets samengevat en er komt geen stemmingsgrafiek uit. Een dagboek dat geanalyseerd wordt is geen dagboek, dus er bestaat geen route die deze tekst ergens anders heen stuurt. Staan er woorden in die te zwaar zijn voor een app, dan blijft je notitie gewoon staan en komt de weg naar echte hulp ernaast.'),
  '/apps/medicijnen.html': G('Medicijnen: je eigen schema, met wat er vandaag staat en hoeveel er nog in huis is.',
    ['Zet een middel erbij: naam en sterkte precies zoals op het doosje', 'Geef de tijden op waarop je het gebruikt',
      'Teken af wat je hebt genomen; de voorraad telt daarop mee'],
    'RTG bepaalt nooit een dosering. Er is geen middelenlijst om uit te kiezen, geen voorgestelde sterkte en geen controle op combinaties of bijwerkingen -- daar is je arts of apotheek voor. Vul je geen voorraad in, dan staat er niets; RTG verzint geen getal.'),
  '/apps/vitaal.html': G('Vitaal: een dagelijkse check-in voor medicijnen, of gewoon om te laten weten dat het goed gaat.',
    ['Stel in hoe vaak je je meldt', 'Druk op "Het gaat goed"', 'Kies wie er gaat kijken als je je niet meldt'],
    'Je hoeft de app niet open te hebben: de server telt af, dus een vergeten check-in valt vanzelf op.'),
  '/apps/thuisrust.html': G('Thuisrust: niet storen tot je thuis bent, zonder dat je onbereikbaar wordt.',
    ['Kies een stand en hoe lang hij hooguit duurt', 'De wereld gaat stil; je kring komt er altijd doorheen', 'De stand eindigt vanzelf, of zodra je incheckt in de Thuiswacht'],
    'De veiligheidsbaan is de hele truc: je hoeft niet te kiezen tussen rust en bereikbaar zijn voor wie ertoe doet.'),
  '/apps/schoolpartner.html': G('De School Partner-app: de werkbank voor directie en lerarenteam, rechtstreeks op de leerlijn.',
    ['Directie: laat personeel toe en zie alle klassen met hun cijfers', 'Leraar: start een online les, zet collega\'s vast op je klas (max drie) of neem er een waar', 'Zet met een paar vinkjes een SO, proefwerk, examen of MO klaar uit de leerlijn; het cijfervoorstel blijft een advies'],
    'De motor kijkt na, maar de leraar beslist: elk cijfer is pas een cijfer als een mens erop drukt.'),
  '/apps/ik.html': G('Wie ben ik: wat Rahul over jou mag weten, en hoe hij tegen je doet.',
    ['Kies of Rahul een maatje, plagerig, zakelijk of rustig is', 'Zet je voornaamwoorden en hoe je genoemd wilt worden', 'Geef zelf aan of je iets gelooft; dan feliciteert hij je en houdt hij er rekening mee'],
    'Alles is optioneel en alles is weer weg te halen. Rahul raadt nooit: niet je geloof uit je naam, niet je aanspreekvorm uit je paspoort.'),
  '/apps/residentie.html': G('De Residence: het virtuele grandhotel van RTG om elkaar te leren kennen -- voor je echt op date gaat.',
    ['Speel samen: midgetgolf, darts, kegelen of baantjes zwemmen; in het restaurant stelt het huis vragen', 'Praat met de zaal via de balk onderin, of stuur een schittering of hartje', 'Je suite is een compleet penthouse (bed, douche, keuken, telefoon); nodig iemand uit via de huistelefoon'],
    'Alles is inbegrepen bij de pas en iedereen heet er bij zijn codenaam: gezellig zonder scores, streaks of winkeltjes.')
};
