/* App-gids data, deel4 (29 pagina's). Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/foundation/geld.html': G('Het geldmaatje: leren omgaan met geld, op jouw niveau.',
    ['Doe de leerstukjes over geld', 'Oefen met sparen en kiezen', 'Vraag als iets niet klopt'],
    'Eerst sparen, dan kopen: wie dat jong leert, heeft er zijn leven lang plezier van.'),
  '/apps/foundation/gezondheid.html': G('Het gezondheidsmaatje: goed voor jezelf zorgen, zonder gedoe.',
    ['Bekijk tips over slapen, eten en bewegen', 'Houd bij hoe je je voelt', 'Vraag hulp als het nodig is'],
    'Goed slapen is de beste superkracht die er is; echt waar.'),
  '/apps/foundation/hulpwijzer.html': G('De hulpwijzer: waar je terecht kunt als je ergens mee zit.',
    ['Zoek op waar je hulp bij wilt', 'Zie wie je kunt bellen of schrijven', 'Alles is vertrouwelijk'],
    'Hulp vragen is dapper, niet zwak; de eerste stap is de moeilijkste en die kun jij.'),
  '/apps/foundation/keuken.html': G('De gezinskeuken: samen koken, boodschappen en weekmenu\'s.',
    ['Kies recepten voor de week', 'Maak samen het boodschappenlijstje', 'Kook met de stap-voor-stap-hulp'],
    'Wie helpt koken, eet lekkerder; proef onderweg en je leert vanzelf.'),
  '/apps/foundation/klusjes.html': G('Klusjes en sterren: helpen in huis en er iets voor terugzien.',
    ['Kies een klusje van de lijst', 'Klaar? Zet hem af en verdien sterren', 'Spaar je sterren voor iets leuks'],
    'Elke dag een klein klusje voelt licht; alles op zaterdag voelt zwaar.'),
  '/apps/foundation/kompas.html': G('Het kompas: nadenken over wie je bent en wat je wilt, met een maatje dat meedenkt.',
    ['Doe de denkstukjes op jouw tempo', 'Schrijf op wat je ontdekt', 'Deel alleen wat jij wilt delen'],
    'Er is geen goed of fout antwoord over wie jij bent; nadenken zelf is het punt.'),
  '/apps/foundation/leren.html': G('Leren: overhoren, duellen, samen aan projecten en beter schrijven.',
    ['Kies wat je wilt oefenen', 'Daag een vriend uit voor een duel', 'Laat de schrijfcoach meelezen'],
    'Fouten maken is gewoon oefenen; wie nooit een fout maakt, oefent te makkelijk.'),
  '/apps/foundation/markt.html': G('Koopje: de gezinsmarkt voor tweedehands en delen.',
    ['Zet iets erop dat weg mag', 'Zoek iets dat jullie nodig hebben', 'Ruil of geef door in de buurt'],
    'Wat jij niet meer gebruikt, maakt een ander blij; doorgeven is twee keer winst.'),
  '/apps/foundation/ochtend.html': G('Het ochtendritme: rustig opstaan met een vast lijstje.',
    ['Zet jullie ochtendstappen op volgorde', 'Vink af wat klaar is', 'Zie in één blik of iedereen op schema ligt'],
    'Een vast ritme maakt de ochtend rustig; je hoofd hoeft niet meer na te denken.'),
  '/apps/foundation/oppasinfo.html': G('Belangrijke info: alles wat een oppas of invaller moet weten.',
    ['Zet de belangrijke dingen erin (allergieën, bedtijd, nummers)', 'Deel met de oppas van vanavond', 'Haal de toegang daarna weer weg'],
    'Wat op papier bij de koelkast hing, staat nu veilig hier; en je kunt het weer intrekken.'),
  '/apps/foundation/opvoeden.html': G('Opvoedhulp: steun voor ouders, zonder oordeel.',
    ['Lees per leeftijd wat helpt', 'Bekijk hoe andere ouders het doen', 'Vraag hulp als het zwaar wordt'],
    'Niemand voedt perfect op; goed genoeg is echt goed genoeg.'),
  '/apps/foundation/overhoren.html': G('Overhoren: woordjes en begrippen erin krijgen, op de slimme manier.',
    ['Maak of kies een lijst', 'Laat je overhoren; fouten komen vaker terug', 'Speel een duel met een vriend'],
    'Tien minuten per dag verslaat twee uur op de avond ervoor; je hoofd houdt van herhalen.'),
  '/apps/foundation/pesten.html': G('Sterker dan pesten: wat je kunt doen als jij of een ander gepest wordt.',
    ['Lees wat je kunt zeggen en doen', 'Bewaar bewijs van online pesten', 'Praat met een grote die je vertrouwt'],
    'Pesten is nooit jouw schuld; erover praten is de sterkste zet die er is.'),
  '/apps/foundation/privacy.html': G('Privacy en veiligheid: wat van jou is, blijft van jou.',
    ['Leer wat je beter niet deelt', 'Check je instellingen samen met een grote', 'Meld het als iets niet klopt'],
    'Een foto die weg is, is nooit echt weg; denk drie tellen na voor je deelt.'),
  '/apps/foundation/projecten.html': G('Samen aan een project: met je gezin of vrienden iets moois maken.',
    ['Start een project en nodig uit', 'Verdeel de taken', 'Vier het als het af is'],
    'Een project af maken leert je meer dan tien beginnen; klein beginnen mag.'),
  '/apps/foundation/reis.html': G('Op reis: alles voor een gezinsreis, van paklijst tot spelletjes onderweg.',
    ['Maak samen de paklijst', 'Bekijk tips voor onderweg', 'Speel de reisspelletjes in de auto'],
    'Wie zijn eigen tas inpakt, vergeet minder én sjouwt bewuster.'),
  '/apps/foundation/rust.html': G('Even rust: ademhalen en tot rust komen als het te veel wordt.',
    ['Adem mee met de cirkel', 'Kies een rustmoment dat bij je past', 'Kom terug wanneer je wilt'],
    'Drie keer diep ademen werkt echt; je lijf kalmeert je hoofd.'),
  '/apps/foundation/school.html': G('School: je rooster, huiswerk, cijfers en berichten van school.',
    ['Bekijk je rooster en huiswerk', 'Zie je cijfers zodra ze er zijn', 'Ziekmelden gaat via je ouders hier'],
    'Huiswerk meteen in de app zetten scheelt gedoe; je hoofd mag het dan vergeten.'),
  '/apps/foundation/schrift.html': G('Het schrift: live meeschrijven met de les.',
    ['Doe mee met wat de juf of meester deelt', 'Schrijf je eigen aantekeningen', 'Alles wordt vanzelf bewaard'],
    'In je eigen woorden opschrijven werkt beter dan overtypen; dan snapt je hoofd het echt.'),
  '/apps/foundation/schrijven.html': G('Schrijven: elke dag een leuke schrijfopdracht met een vriendelijke coach.',
    ['Pak de opdracht van vandaag', 'Schrijf; de coach leest mee als je wilt', 'Bewaar je mooiste stukken'],
    'De coach herschrijft nooit jouw tekst; jij blijft de schrijver, altijd.'),
  '/apps/foundation/steun.html': G('Steun voor jou: als het thuis of vanbinnen even zwaar is.',
    ['Lees dat je niet de enige bent', 'Zie wie je kunt bellen, ook anoniem', 'Praat met iemand die je vertrouwt'],
    'Je hoeft het niet alleen te dragen; er zijn mensen die niets liever doen dan luisteren.'),
  '/apps/foundation/studie.html': G('Verder leren: kiezen wat je na school wilt en hoe je daar komt.',
    ['Verken studies en beroepen', 'Kijk wat erbij past en wat het kost', 'Praat erover met je mentor of ouders'],
    'Kies met je nieuwsgierigheid, niet met je angst; je mag altijd nog bijsturen.'),
  '/apps/foundation/toetsen.html': G('De toetsplanner: rustig naar je toetsen toe werken.',
    ['Zet je toetsen erin', 'De planner verdeelt het leren voor je', 'Vink af wat je gedaan hebt'],
    'Beginnen is het moeilijkst; plan het eerste blokje extra klein, dan kom je vanzelf op gang.'),
  '/apps/foundation/veilig.html': G('Veilig thuis: wat te doen als thuis niet veilig voelt.',
    ['Lees wat je kunt doen, stap voor stap', 'Zie de nummers die je altijd mag bellen', 'Dit blijft tussen jou en de hulp'],
    'Bellen mag altijd, ook als je twijfelt of het "erg genoeg" is; dat mag de hulp beoordelen.'),
  '/apps/foundation/verjaardagen.html': G('Verjaardagen en wensen: nooit meer een verjaardag missen.',
    ['Zie wie er binnenkort jarig is', 'Bewaar cadeau-ideeën per persoon', 'Zet een herinnering voor het kaartje'],
    'Een kaartje op tijd is meer waard dan een cadeau te laat.'),
  '/apps/foundation/vrienden.html': G('Contacten: je vrienden, snaps en verhalen, veilig geregeld.',
    ['Stuur snaps en bekijk verhalen', 'Nieuwe vrienden keurt een grote goed', 'Blokkeer of meld wat niet oké is'],
    'Echte vrienden vragen nooit om geheimen voor je ouders; dat is een rood vlaggetje.'),
  '/apps/foundation/werk.html': G('Werk en vacatures: bijbanen en stages die bij jouw leeftijd passen.',
    ['Bekijk vacatures voor jouw leeftijd', 'Solliciteer met je cv uit de CV-maker', 'Volg je sollicitaties live'],
    'Een korte, eerlijke sollicitatie verslaat een lange opgepompte; wees gewoon jezelf.'),
  '/apps/foundation/klas.html': G('De klas-PDA: doe live mee met de les van je juf of meester, op je eigen scherm of de iPad.',
    ['Typ de klascode van het bord en je voornaam', 'Lees de uitleg en beantwoord de vragen zodra ze starten', 'Zie je score en aan het einde het podium'],
    'Snel antwoorden geeft een klein beetje extra punten, maar goed nadenken levert het meest op.'),
  '/apps/foundation/zakgeld.html': G('Zakgeld: jouw eigen potje, sparen en uitgeven leren.',
    ['Houd bij wat erin komt en eruit gaat', 'Zet een spaardoel', 'Kijk hoe ver je bent'],
    'Verdeel je zakgeld in potjes (sparen, uitgeven, geven); dan is kiezen ineens makkelijk.')
};
