/* App-gids data, deel 12: de samengestelde commandoschermen en Living OS.
   Zie ../appgids.js voor de gedeelde uitleglaag. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/festival.html': G('Het festival draaien: de poort, het beeld en het terrein.',
    ['Poort: kies waar u staat; het veld houdt zelf de focus, zodat een handscanner gewoon werkt',
      'Beeld: alleen wat aandacht vraagt, met de tijd die er nog is -- en welke plekken NIET gemeten worden',
      'Zonder verbinding heet een scan ONBEVESTIGD en gaat hij in de wachtrij, nooit groen'],
    'Oranje is zelden fraude: iemand liep terug naar zijn auto, of een hek stond even offline. Er staat bij waar en hoe laat de eerste scan was, zodat u het kunt vragen in plaats van te weigeren.'),
  '/apps/festival-gast.html': G('Uw kant van het festival: uw pas, het programma en uw groep.',
    ['Uw pascode staat groot in beeld -- dat is wat u aan de poort laat zien',
      'Het programma toont alleen sets die getekend zijn, met erbij hoeveel er nog niet rond zijn',
      'Een groep maakt u zelf; u geeft de code aan wie u erbij wilt, RTG stuurt niemand iets'],
    'Een festival verschijnt hier zodra u er een pas heeft of in een groep zit. Er is geen lijst met festivals om uit te kiezen.'),
  '/apps/chauffeur.html': G('RTG Chauffeur: de persoonlijke PDA voor veilige ritmeldingen, navigatie en iedere uitvoeringsfase van een vervoersopdracht.',
    ['Bekijk de route, duur, afstand en vaste ritprijs voordat u een aanvraag aanneemt',
      'Gebruik de grote faseknop voor vertrek, aankomst, instappen, rijden en voltooien',
      'Deel positie alleen tijdens een levende rit; na afronding stopt de app automatisch'],
    'De officiële RTG-klok en de rustige bediening helpen onderweg, maar de server bewaakt de waarheid: een ongeldige statusstap of rit van een andere vervoerder wordt geweigerd.'),
  '/apps/foundation/mail.html': G('RTF Mail: het persoonlijke Foundation-postvak dat naar buiten alleen uw codenaam toont.',
    ['Lees post die voor uw Foundation-profiel is bestemd', 'Schrijf intern naar een ander RTG- of Foundation-postvak',
      'Gebruik het publieke codenaam-adres pas nadat het Foundation-domein veilig live staat'],
    'Uw profiel bepaalt het afzenderadres; een adres kan nooit via het formulier worden overgenomen.'),
  '/apps/arrival.html': G('Invisible Arrival: een tijdelijke gastpas waarmee een zaak uw komst kan voorbereiden zonder uw route of GPS te volgen.',
    ['Vertel Rahul het moment, gezelschap en alleen de wensen die voor dit bezoek nodig zijn',
      'Controleer het voorstel voordat u de aanvraag verstuurt',
      'Deel vrijwillig onderweg, in de buurt of gearriveerd; stop delen wanneer u wilt'],
    'De tijdelijke pas is het toegangsbewijs en verloopt na het bezoek. Deel hem dus niet met anderen.'),
  '/apps/geld-command.html': G('RTG Geld Command: uw rekeningen, plannen, veiligheidsgrenzen en beslissingen in een financieel werkblad.',
    ['Lees eerst wat vandaag echt aandacht vraagt', 'Simuleer een keuze voordat er geld beweegt',
      'Bevestig een betaling altijd zelf bij de financiële leverancier'],
    'Rahul mag rekenen, vergelijken en voorbereiden; geld verplaatsen blijft een persoonlijke handeling.'),
  '/apps/living-os.html': G('Het Vooruitzicht, de cockpit van LivingOS: geld, tijd, energie, mensen en beleving als een samenhangende wereld vooruit bekijken.',
    ['Beschrijf het gewenste resultaat en de harde grenzen; vergelijk de waarschijnlijke, ideale en verstoorde wereld',
      'Bekijk wat lokaal klaarstaat en waarop providers nog moeten antwoorden',
      'Geef alleen de voorbereiding vrij; boeken en betalen blijven apart geblokkeerd'],
    'Gereed betekent pas gereed als de echte provider dat heeft bevestigd; een mooie voorspelling is geen bewijs. Een simulatie helpt kiezen maar beslist niet.'),
  '/apps/partner-network.html': G('Symbiotic Partner Network: bedrijven werken rond één gastbelofte samen zonder hun hele dossiers te delen.',
    ['Open het gezamenlijke servicecontract', 'Vergelijk capaciteit, kwaliteit, marge en privacy per partner',
      'Kies een herstelroute wanneer een deelnemer de belofte niet kan dragen'],
    'Iedere partner ontvangt alleen wat nodig is voor zijn eigen deel; de gezamenlijke uitkomst blijft controleerbaar.'),
  '/apps/reizen-veilig.html': G('Reizen en Veilig: plannen, vervoer, aankomst en vrijwillige veiligheidsdeling in één reiswerkruimte.',
    ['Plan vervoer op tijd, prijs en uitstoot', 'Open uw samengestelde reizen naast de live reisdag',
      'Kies per moment wie uw plan, voortgang of tijdelijke locatie mag zien'],
    'Locatie delen staat standaard uit, stopt automatisch en kan ieder moment handmatig worden beëindigd.'),
  '/apps/sociaal-prive.html': G('Privé: de besloten ingang naar persoonlijke ontmoetingen, gezelschap, clubs en attenties binnen RTG Social.',
    ['Kies de ruimte die past bij wat u met iemand wilt doen', 'Lees bij iedere ruimte wie toegang heeft en welke identiteit zichtbaar is',
      'Bevestig zelf voordat een voorstel, uitnodiging of bericht iemand anders bereikt'],
    'De privéwereld bewaart niets dubbel. Meet, Vonk, Rendez-vous, Cercle, Entourage en Attenties blijven ieder eigenaar van hun eigen gegevens.'),
  '/apps/vandaag.html': G('Vandaag: uw korte dagbriefing en de snelste ingang naar de software die nu nodig is.',
    ['Lees de briefing van Rahul', 'Open een voorstel of vraag in gewone taal om een andere app',
      'Zet een tweede werkblad ernaast wanneer twee onderwerpen bij dezelfde beslissing horen'],
    'Vandaag is een regiescherm: de bronapp blijft de plek waar gegevens worden gewijzigd of een handeling definitief wordt uitgevoerd.'),
  '/apps/appcel.html': G('Een app van een andere partij, die draait in een afgeschermde cel binnen RTG.',
    ['Lees bovenaan van wie deze app is', 'Druk op "Wat mag deze app?" om te zien wat je hem hebt gegeven',
      'Neem een machtiging terug wanneer je wilt; de app blijft werken met wat er overblijft'],
    'Deze app heeft geen verbinding met de buitenwereld en ziet nooit je echte naam of je e-mailadres -- alleen je codenaam, en alleen als je dat hebt verleend.'),
  '/apps/appstore-uitgever.html': G('Het uitgeversbureau: hier zendt uw organisatie een eigen app in voor de RTG App Store.',
    ['Vraag eerst een uitgeversplek aan; een mens van RTG laat u toe',
      'Kies de map van uw app en druk op Proefkeuring -- u ziet per bestand en per regel wat er nog niet kan',
      'Zend in wanneer de proef doorkomt; daarna kijkt een mens van RTG naar wat uw app doet'],
    'De machinepoort keurt nooit goed: hij kan alleen afkeuren of doorlaten naar een mens. Vraag alleen de machtigingen die u echt gebruikt -- elke machtiging is een vinkje dat een lid kan weglaten.'),
  '/apps/appstore-kantoor.html': G('De keuringskant van de App Store: hier tekent een mens van RTG af wat een derde heeft ingezonden.',
    ['Zet eerst uw naam erbij; elk besluit hieronder draagt hem en gaat het journaal in',
      'Lees wat de app DOET, niet alleen wat de machinepoort erover zegt -- die keurt nooit goed',
      'Publiceren of weigeren met een reden; die reden leest de uitgever'],
    'Een geschorste uitgever verliest zijn apps op hetzelfde moment, ook bij de leden die ze al hadden. Wie voor zo\'n app betaalde, krijgt een teruggaverecht dat u hier afhandelt.'),
  '/apps/appstore-dossier.html': G('Het inkoopdossier: wat er over een app van derden bekend is, en wat wij er juist NIET over beweren.',
    ['Lees eerst wat de app nooit krijgt en waar uw gegevens blijven',
      'Kijk bij elke bewering naar de bron ernaast; die wijst een bestand aan dat na te lezen is',
      'Sluit af met "Wat dit dossier NIET zegt" -- daar begint uw eigen onderzoek'],
    'Zonder app in het adres toont deze pagina het kanaaldossier: wat voor ELKE app van derden hier geldt, en welke machtigingen er met opzet niet bestaan. Die vraag hoeft u maar een keer te stellen.'),
  '/apps/zaakkosten.html': G('RTG Kostprijs voor uw zaak: wat het gebruik van uw zaak ons kost, en wie dat betaalt.',
    ['Lees bovenaan de toestand en het verwachte bedrag; staat er geen bedrag, dan is er nog geen tarief -- geen nul',
      'Open "Waarom dit bedrag" om de keten terug te lezen tot de factuur van onze eigen leverancier',
      'Kijk bij "Wie betaalt dit" of dit op uw maandfactuur komt, en waarom wel of niet'],
    'Dit is hetzelfde beeld dat een lid van zijn eigen gebruik ziet, op de sessie van uw zaak. Een verbruiksgrens zet u hier niet: die hoort bij een persoon, en het kantoorslot van RTG staat er los van.'),
  '/apps/kosten.html': G('RTG Kostprijs: wat kost elke gebruiker ons, en wie betaalt dat.',
    ['Vul eerst de tarieven en de nota\'s in; zonder bron rekent deze laag niets uit en is elk bedrag te laag',
      'Lees het dekkingspercentage nooit los van het blok eronder -- van sommige gebruikers is geen bijdrage bekend',
      'Vrijgeven zet de doorbelasting op de maandfactuur die er al is; dat kan een keer per maand'],
    'Let op het label naast elk bedrag. "Gemeten" komt van een teller; "vermoed" is een verdeling van een nota, en dat is een schatting hoe precies het getal er ook uitziet. Een gezin van de RTFoundation krijgt hier nooit een rekening.')
};
