/* App-gids data, deel10: de zeven werkschermen van het Horeca OS naast
   /apps/horeca.html (dat in deel8 staat). Zie ../appgids.js voor de uitleg. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/horeca-expeditie.html': G('Expeditie en keukenregie: de pas, waar een tafel compleet de deur uit gaat.',
    ['Zie per tafel en gang hoeveel borden klaar zijn en hoe lang het eerste al koud staat',
      'Geef zelf uit; er wordt niets automatisch afgevinkt',
      'Lees de drukterem: openstaande bereidingsminuten gedeeld door het aantal koks'],
    'Staat-koud is het getal dat telt: vier borden die na elkaar de deur uit gaan, zijn vier keer half warm.'),
  '/apps/horeca-bezorg.html': G('Bezorgdispatch en de rit: zones, tijdsloten, volgorde en het afleverbewijs.',
    ['Check een adres: het antwoord noemt de zone, de kosten en anders de reden waarom het niet kan',
      'Vul de tijdsloten in keukenminuten; tien pizza\'s zijn geen tien diners',
      'Loop de rit af van inpakken tot aftekenen; vertrekken kan pas als beide vinkjes staan'],
    'Er wordt geen foto van een mens of een deur bewaard: het bewijs legt vast wat een geschil later beslecht.'),
  '/apps/horeca-hotel.html': G('Gastrekening en roomservice: alles van het verblijf op een rekening.',
    ['Open een gastrekening op een kamer en boek ontbijt, minibar, spa of restaurant erop',
      'Draai de nachtrun; twee keer drukken boekt geen twee nachten',
      'Neem roomservice op, geef hem vrij naar de keuken en boek hem op de kamer'],
    'De toeristenbelasting staat als eigen regel en niet in de kamerprijs: een gast hoort te zien wat hij aan wie betaalt.'),
  '/apps/horeca-events.html': G('Events: offerte, akkoord, verbruik en nacalculatie.',
    ['Zet de posten op een offerte en leg het akkoord vast met een naam erbij',
      'Boek de aanbetaling en later de werkelijke kosten en uren',
      'Draai de nacalculatie: opbrengst, kosten, marge en de opbrengst per gast'],
    'Posten wijzigen na een akkoord maakt een nieuwe versie die opnieuw bevestigd moet worden; de vorige blijft bewaard.'),
  '/apps/horeca-club.html': G('Club: polsbandtegoed, minimum spend en de deurteller.',
    ['Waardeer een polsband op, boek erop af en betaal het restsaldo terug',
      'Zie per VIP-tafel wat er van de minimum spend nog te gaan is',
      'Tel aan de deur in, uit en herbetreding, met de gastenlijst per promoter erbij'],
    'Op een band staat een nummer en een saldo, geen naam: wie hem verliest, verliest zijn tegoed en niet zijn identiteit.'),
  '/apps/horeca-haccp.html': G('HACCP-registratie: temperatuurlogboek, batches en controlelijsten.',
    ['Leg meetpunten met hun grenzen vast en noteer de metingen',
      'Zie welke batches over de datum zijn en boek ze af met een reden',
      'Vink een controlelijst af, punt voor punt'],
    'Wat vandaag nog niet gemeten is, staat er als gemist bij; een leeg logboek ziet er anders precies zo uit als een goed logboek.'),
  '/apps/werk.html': G('RTG Werk OS: de werkplek van een hele organisatie -- projecten, kennis, klanten, service, bouw, IT, contracten en besluiten.',
    ['Ga naar binnen met de werkruimtecode en uw eigen lid-token; dat is bewust iets anders dan uw RTG-pas',
      'Lees uw startscherm: het volgt uw rollen, en wat geen bron heeft staat er als NIET GEMETEN in plaats van als nul',
      'Kies een module en zie de lijst plus wat aandacht vraagt; koppel eenmalig uw RTG-account voor agenda, postvak en kluis'],
    'Wat u niet mag zien, staat er niet als lege doos; en wat nergens wordt gemeten, staat er met de reden erbij.'),
  '/apps/horeca-beheer.html': G('Beheer: de dag over alle kanalen, de fooienpot, de loonkosten en de signalen.',
    ['Lees de omzet per kanaal en per betaalwijze, met fooi en oninbaar apart',
      'Verdeel de fooienpot over gewerkte uren; de som van de delen is exact de pot',
      'Zet het loon tegenover de omzet zonder fooi en bekijk de signalen'],
    'Er staat geen omzetprognose op dit scherm: wat er staat is wat er nu open staat en wat er vandaag is binnengekomen.'),
  '/apps/zakelijk.html': G('Zakelijk vervoer: het reisbeleid van uw bedrijf, de ritten die op uw akkoord wachten en het maandoverzicht.',
    ['Zet de grenzen: maximum per rit, budget per medewerker, tijden, steden en kostenplaatsen',
      'Geef akkoord op de ritten boven uw drempel; tot dat moment staan ze op geen enkel planbord',
      'Lees per maand wat er is gereden, per kostenplaats en per medewerker'],
    'Een leeg veld is geen grens. En elke afwijzing die uw medewerker leest, noemt de regel en het getal -- daarom staat naast de knoppen wat hij ziet.'),
  '/apps/foundation/os.html': G('Foundation OS: het bestuurssysteem van de RTFoundation -- landelijk toezicht, zelfstandige stadsafdelingen, partnerstichtingen, projecten, vrijwilligers, geld en hulpvragen.',
    ['Kies een stadsafdeling; u ziet alleen de steden waar u een zetel heeft, het landelijke bestuur ziet ze alle',
      'Werk per tabblad: impact, projecten, partners, vrijwilligers, geld, hulpvragen, integriteit, gemeente en ondernemers',
      'Werk per tabblad verder: subsidies met hun rapportagemomenten, voorraad per batch, activiteiten met wachtlijst en incheck, en communicatie',
      'Onder Netwerk deelt u een blauwdruk met andere steden, koopt u samen in, leent u vrijwilligers uit en ziet u het koppelbord met RTG',
      'Onder Bestuur staan de knoppen van het toezicht: modules per stad, de status van de afdeling, de goedkeuringslimieten en de zetels'],
    'Geoormerkt geld gaat hier nooit naar een ander project, wie een uitgave aanvraagt keurt hem niet zelf goed, en een melding kan niemand verwijderen -- ook het landelijke bestuur niet.'),
  '/apps/foundation/os-vrijwilliger.html': G('Mijn vrijwilligerswerk: uw eigen planning, uren en VOG-datum, op uw eigen code.',
    ['Vul de code in die u van uw coordinator kreeg (RTFV-...)',
      'Zet aan wanneer u kunt, en welke talen en vaardigheden u meebrengt; dat ziet uw coordinator meteen',
      'Geef uw uren door; ze tellen mee zodra uw coordinator ze bevestigt'],
    'Uw VOG, de gedragscode en uw status zet de afdeling en niet u zelf -- een VOG die je zelf invult is geen VOG-controle meer. Er staan geen contactgegevens achter deze code, want een code wordt meegelezen.'),
  '/apps/foundation/os-deelnemer.html': G('Mijn hulpvraag: hoe het ervoor staat, en de knop om uw toestemming in te trekken.',
    ['Vul de code in die u van de RTF-afdeling kreeg (RTFD-...)',
      'Lees in gewone taal waar uw vraag staat en wat er is gedaan',
      'Trek uw toestemming in als u niet meer wilt dat uw gegevens worden gedeeld; dat kan hier, zonder te bellen'],
    'Wat er al is gedaan blijft in het dossier staan -- dat wissen zou het onbetrouwbaar maken, ook voor u -- maar er gaat daarna niets meer naar een partner.'),
  '/apps/foundation/os-publiek.html': G('RTFoundation in uw buurt: wat er loopt, waar u binnen kunt lopen en hoe u meedoet.',
    ['Kies uw stad en zie welke projecten er draaien',
      'Bekijk de activiteiten die openstaan, met datum, plek en of er nog plek is',
      'Lees hoe u meedoet als vrijwilliger of als ondernemer'],
    'Er staat met opzet geen enkel getal over hulpvragen op deze pagina: in een kleine buurt is zo\'n getal geen statistiek maar een aanwijzing. De maat is: wat zou je op een poster in het buurthuis hangen?'),
  '/apps/foundation/os-veld.html': G('Uw eigen lijst als medewerker: wat aan u is toegewezen, het bezoekrapport en de vervolgafspraak.',
    ['Open de app; u ziet uitsluitend de hulpvragen die uw coordinator aan u heeft toegewezen',
      'Vraag het adres op als u op bezoek gaat -- dat openen wordt genoteerd, precies zoals op kantoor',
      'Noteer wat u heeft gezien en gedaan, met een vervolgafspraak of de reden dat er geen vervolg nodig is'],
    'Afronden doet uw coordinator: dat zet de bewaartermijn in gang en sluit de zaak, en zo\'n besluit hoort niet op de stoep te vallen. Een rapport zonder vervolg is hoe een hulpvraag blijft liggen -- iedereen denkt dan dat de ander aan zet is.'),
  '/apps/foundation/os-donateur.html': G('Uw eigen giften: wat u gaf, waar het heen ging en uw giftbewijs.',
    ['Vul de code in die u van de stichting kreeg (RTFS-...)',
      'Zie per gift waar hij heen ging: een project of een stadsafdeling, met wat daar het doel is',
      'Vraag uw giftbewijs op; bij een periodieke gift staat de overeenkomst erbij'],
    'U ziet uitsluitend uw eigen giften, nooit die van iemand anders. En nooit mensen: waar uw geld heen ging is een project; wie er geholpen is, is niet aan ons om te vertellen.'),
  '/apps/foundation/os-bestuur.html': G('De governance-laag: bestuursvergaderingen, landelijk beleid, het jaarverslag, risico\'s, grote giften en de meldcode.',
    ['Leg een vergadering vast met het aantal bestuurders erbij -- dat getal is de noemer van het quorum',
      'Neem besluiten; wie een belang heeft bij het punt kan niet als stemmer worden geteld',
      'Stel de notulen vast in een VOLGENDE vergadering; daarna ligt alles vast',
      'Stel het jaarverslag op (de cijfers bevriezen), laat het bestuur het vaststellen en publiceer het'],
    'Dit scherm gaat niet over wat de stichting deed maar over of ze het bevoegd deed en het kan laten zien. Een grote of contante gift staat stil tot de herkomst is beoordeeld, en een meldcode-dossier kan niemand verwijderen.'),
  '/apps/foundation/os-portaal.html': G('Het portaal voor partnerstichtingen, gemeenten en lokale ondernemers: uw eigen dossier, op uw eigen code.',
    ['Vul de code in die u van het RTF-kantoor kreeg (RTFP voor een stichting, RTFG voor een gemeente, RTFO voor een bedrijf)',
      'Een stichting ziet de samenwerkingsafspraken en de eigen projecten; een gemeente uitsluitend getelde cijfers; een ondernemer waar zijn bijdrage terechtkwam',
      'De code blijft in dit tabblad en wordt nergens bewaard -- op een gedeelde computer sluit u hem weg door het tabblad te sluiten'],
    'Een gemeente krijgt hier nooit een dossier of een naam te zien, en buurten met minder dan vijf hulpvragen worden samengevoegd: een klein getal in een kleine buurt is geen statistiek meer.')
};
