/* App-gids data, deel2 (26 pagina's). Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/home.html': G('De RTG Home Kit: alle elektronica van je huis op één plek, per kamer, met scènes die je met één tik start.',
    ['Bedien lampen, klimaat, gordijnen en audio per kamer', 'Laat Rahul een scène voorstellen (bijv. filmavond) en bewaar hem', 'Verbind merken via de open koppelstandaard; hun apparaten doen meteen mee', 'Alles uit met één tik; sloten bedien je altijd zelf'],
    'De AI stelt scènes voor, jij beslist; en een deur van het slot halen blijft altijd jouw eigen losse tik. Dat is een vaste veiligheidsregel.'),
  '/apps/juridisch.html': G('Juridisch: de voorwaarden, privacyregels en jouw AVG-rechten, in gewone taal.',
    ['Lees de voorwaarden per onderwerp', 'Vraag je gegevens op of laat ze wissen', 'Bekijk wat partners wel en niet zien'],
    'Jouw echte naam staat in een aparte kluis; partners werken met je codenaam. Zo is het ontworpen.'),
  '/apps/scherm.html': G('Tweede scherm: spiegel je werkplek of maak er een extra werkplek van.',
    ['Koppel met de code op je hoofdscherm', 'Kies spiegelen of een eigen werkplek', 'Ontkoppel met één tik'],
    'Een tweede scherm naast de kassa scheelt loopwerk: orders links, afrekenen rechts.'),
  '/apps/wallet.html': G('RTG Wallet: je ledenpas, tickets, sleutels, munten en klantenkaarten op een plek.',
    ['Bovenaan ligt je ledenpas: codenaam, lidnummer en een QR', 'Tik op een kaart voor het grote codescherm', 'Koop feestmunten, wissel ze in en voeg zelf kaarten toe'],
    'De zorgpas van de verzekeraar verschijnt hier vanzelf; wat je niet meer nodig hebt haal je er zo weer uit.'),
  '/apps/rtgid.html': G('RTG iD: jouw digitale identiteit; inloggen met een tik, delen wat jij kiest.',
    ['Voer de koppelcode van een dienst in en zie wie er aanklopt', 'Bevestig of weiger; er wordt nooit meer gedeeld dan gevraagd', 'Bekijk je inzagelog en trek toegang of machtigingen in'],
    'Een dienst die alleen "18 of ouder" hoeft te weten, krijgt precies dat bewijs; je geboortedatum blijft in de kluis.'),
  '/apps/office.html': G('RTG Office: tekstdocumenten en rekenbladen, automatisch bewaard.',
    ['Maak een document of rekenblad', 'Deel op codenaam met wie jij kiest', 'Exporteer wanneer je wilt'],
    'Alles wordt vanzelf bewaard terwijl je typt; je kunt niets kwijtraken.'),
  '/apps/doos.html': G('De Zaakdoos: het kastje dat je zaak lokaal draaiend houdt, ook zonder internet.',
    ['Bekijk de status van je doos', 'Beheer wifi, updates en stroomwacht op afstand', 'Speel het journaal na bij twijfel'],
    'Valt het internet uit, dan draait je zaak gewoon door; de doos synct later alles netjes bij.'),
  '/apps/techniek.html': G('De technische status: gezondheid, zekeringen en de AI-monteur.',
    ['Bekijk de gezondheid van alle onderdelen', 'Zet een zekering om bij problemen', 'Laat de AI een diagnose voorstellen'],
    'Groen wil je zien; wordt iets geel, kijk dan eerst naar de laatste wijziging.'),
  '/apps/attenties.html': G('Attenties: kleine gebaren op het juiste moment, verzorgd door uw Rechterhand.',
    ['Kies een gelegenheid en een attentie', 'Wij verzorgen inpakken en bezorgen', 'Volg de status discreet in de app'],
    'Een attentie op tijd is meer waard dan een groot gebaar te laat; de agenda helpt u herinneren.'),
  '/apps/cellier.html': G('Cellier: uw wijnkelder, bijgehouden en aangevuld met verstand.',
    ['Bekijk uw kelder en drinkvensters', 'Laat aanvullen op advies', 'Reserveer flessen voor een diner'],
    'Het drinkvenster zegt wanneer een fles op zijn mooist is; de kelder let er voor u op.'),
  '/apps/cercle.html': G('Cercle: uw besloten clubs en lidmaatschappen, met reciprociteit en gastpassen.',
    ['Zet een club erbij met stad, lidnummer, dresscode en gastpassen',
     'Vraag waar u in een stad terecht kunt -- op eigen lidmaatschap of via reciprociteit',
     'Boek een gastpas af als u iemand meeneemt; het aantal loopt vanzelf terug'],
    'Alles hierin komt uit wat u zelf invult. RTG houdt geen clubgids bij en belooft niets namens een club: bel vooruit.'),
  '/apps/entourage.html': G('Entourage: uw vaste reisgezelschap, met hun voorkeuren, dieet en documenten.',
    ['Zet de mensen erbij die u meeneemt, met hun band en hun dieet',
     'Leg per persoon documenten vast met vervaldatum -- paspoort, visum, rijbewijs, verzekering, vaccinatie',
     'Stel een gezelschap samen en zie wat er ontbreekt of bijna verloopt'],
    'De app waarschuwt over data die U heeft ingevuld. Inreisvereisten per land staan er met opzet niet in: die veranderen per week en per nationaliteit, en iets beweren wat wij niet kunnen naslaan is erger dan niets zeggen.'),
  '/apps/garderobe.html': G('Garde-robe: uw garderobe in beeld, met de styling van de boutieks.',
    ['Bekijk wat er hangt en wat er mist', 'Ontvang stylingvoorstellen van uw huizen', 'Laat een maat naar de paskamer brengen'],
    'Een garderobe die klopt is stiller dan een kast die vol is; wij letten op de gaten.'),
  '/apps/hangar.html': G('Hangar: uw voertuigen en vaartuigen, onderhoud en gereedheid.',
    ['Zie de staat van elk object', 'Plan onderhoud bij de juiste partner', 'Houd papieren en keuringen bij'],
    'Onderhoud op tijd is goedkoper dan reparatie te laat; de app herinnert u discreet.'),
  '/apps/lifestyle.html': G('Het Privékantoor: de ene app van uw Lifestyle Pass. Alles wat u heeft op één levensbeeld, met de Rechterhand als uitvoerende hand.',
    ['Begin bij Nu: één kop die zegt of u iets moet doen, plus uw ochtend- of avondbriefing',
      'Zeg onder Nu wanneer u weg bent; wij zoeken op wat daar in uw andere apps mee samenhangt: paspoorten, een verzekering, de vaccinatie van de hond, een toezegging die u al deed',
      'Vooruit bundelt alle termijnen uit die apps, inclusief wat al te laat is',
      'Onder Mandaat bepaalt u per onderwerp hoever wij zonder u gaan, en tot welk bedrag',
      'Een zaak valt uiteen in deelopdrachten die elk uw eigen grens volgen',
      'Woning, Kring, Bezit, Reis en Veilig zijn de kamers waar u het invult',
      'Kantoor is de plattegrond van twintig werelden'],
    'Over gezondheid en nalatenschap beslist u zelf: die blijven besloten, komen niet op ons bureau, en daar kunt u ons geen mandaat voor geven.'),
  '/apps/logboek.html': G('Logboek: het stille verslag van wat er voor u geregeld is.',
    ['Blader door wat er gedaan is', 'Zoek op onderwerp of datum', 'Exporteer voor uw administratie'],
    'Eén plek waar alles staat; u hoeft niets te onthouden.'),
  '/apps/maison.html': G('Maison: uw huizen en hun huishouding, verzorgd op afstand.',
    ['Zie per huis wat er speelt', 'Plan staf, onderhoud en seizoensklaar maken', 'Open deuren op afstand waar dat kan'],
    'Een huis dat klaarstaat voelt u bij binnenkomst; dat is precies het werk dat u niet ziet.'),
  '/apps/mecenaat.html': G('Mecenaat: uw geven aan cultuur en goede doelen, goed geregeld.',
    ['Kies wat u wilt steunen', 'Wij regelen de afspraken en de verantwoording', 'Volg wat uw bijdrage doet'],
    'Gericht geven doet meer dan breed strooien; wij helpen u kiezen.'),
  '/apps/nalatenschap.html': G('Nalatenschap: uw wensen en documenten, ordelijk en vertrouwelijk.',
    ['Leg uw wensen vast', 'Bewaar documenten op één veilige plek', 'Deel alleen met wie u aanwijst'],
    'Nu een uur ordenen bespaart uw naasten later maanden zoeken.'),
  '/apps/reisboek.html': G('Reisboek: uw reizen, verleden en toekomst, in één verzorgd boek.',
    ['Bekijk komende reizen met alle details', 'Blader terug door waar u was', 'Deel een reis met uw gezelschap'],
    'Vóór vertrek één blik in het reisboek en u weet alles: tijden, adressen, codes.'),
  '/apps/rendezvous.html': G('Rendez-vous: afspraken op niveau, door ons voorbereid.',
    ['Vraag een afspraak of diner aan', 'Wij regelen plek, tijd en details', 'U verschijnt; de rest staat'],
    'Zeg wat het moment nodig heeft; wij kennen de adressen die erbij passen.'),
  '/apps/table.html': G('Table: uw vaste tafels en de avonden die ertoe doen.',
    ['Reserveer bij de huizen die u kent', 'Uw voorkeuren reizen mee', 'Laat de sommelier alvast kiezen'],
    'Een vaste tafel is een relatie: hoe vaker u komt, hoe beter men u kent.'),
  '/apps/concierge.html': G('Het concierge-bureau: hier werkt uw Rechterhand voor u.',
    ['Zie de aanvragen van uw leden', 'Pak op, regel en koppel terug', 'Houd het logboek bij'],
    'Terugkoppelen vóór het lid het vraagt: dat is het verschil tussen goed en uitstekend.'),
  '/apps/redactiekantoor.html': G('Het redactiekantoor: waar RTG Nieuws gemaakt wordt.',
    ['Schrijf, redigeer en plan artikelen', 'Beheer rubrieken en beeld', 'Publiceer na eindredactie'],
    'Check je feiten twee keer; snelheid wint nooit van kloppen.'),
  '/apps/leverancier.html': G('De leverancier-app: uw hele zaak in één scherm, van orders tot personeel.',
    ['Beheer orders, reserveringen en voorraad', 'Stuur uw team aan met rooster en taken', 'Vraag de zaak-AI om cijfers en advies'],
    'Kijk elke ochtend één minuut naar het actiecentrum; dan begint de dag zonder verrassingen.'),
  '/apps/leverancier-rtmail.html': G('RTMAIL voor uw zaak: het postvak op uw zaakcode, waar de draaiboeken (sollicitatie, inkoop, factuur, overheid) hun seintjes bezorgen.',
    ['Lees ontvangen en verzonden post op codenaam', 'Stuur zelf een bericht naar een andere zaak of groothandel', 'Alles op codenamen; echte namen blijven in de kluis'],
    'Kijk hier na een drukke dag even langs; de seintjes staan gebundeld klaar zonder dat u een externe mailbox hoeft te openen.')
};
