/* App-gids data, deel1 (32 pagina's). Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  /* ---- het leden-OS en de leden-apps (RTG-toon: ingetogen, je/jij) ---- */
  '/apps/index.html': G('Het RTG OS-bureaublad: alle apps van het platform als iconen, met de klok en je accounts.',
    ['Meld je eerst aan; zonder aanmelding zie je alleen de welkomstkaart, het gratis RTG-abonnement is de minimale ingang', 'Tik een tegel; de app opent schermvullend en de terug-knop brengt je hier terug', 'Je ziet alleen de tegels van jouw wereld; met Toon alles zie je alles'],
    'Dit is ook de voordeur van de website; op telefoon en groot scherm hetzelfde, passend geschaald.'),
  '/apps/app.html': G('Jouw leden-app: reserveren, boeken, bestellen, chatten en betalen, alles op codenaam.',
    ['Open een genre en reserveer of boek direct', 'Vraag Rahul wat je maar wilt; hij regelt het met jouw inlog', 'Bekijk je codes, tickets en bestellingen onder je profiel'],
    'Je echte naam blijft in de kluis; partners zien alleen je codenaam. Dat is bewust ons ontwerp.'),
  '/apps/bureau.html': G('Het RTG OS-bureaublad (zelfde als de voordeur): alle apps als iconen op elk scherm.',
    ['Tik een tegel; de app opent schermvullend', 'Wissel rechtsboven tussen je accounts', 'Deze oude ingang toont hetzelfde bureaublad als de voordeur'],
    'Handig op een tablet of tweede scherm: alles van RTG op één werkblad.'),
  '/apps/berichten.html': G('Je berichten met vrienden en partners, automatisch vertaald als dat nodig is.',
    ['Stuur een bericht op codenaam', 'Bel of videobel vanuit het gesprek', 'Deel een snap of verhaal met wie jij kiest'],
    'Berichten in een andere taal worden voor je vertaald; jij leest en schrijft gewoon in je eigen taal.'),
  '/apps/pulse.html': G('Pulse: wat er nu speelt in jouw RTG-wereld, rustig gebundeld.',
    ['Lees de hoogtepunten van vandaag', 'Tik door naar de app waar iets gebeurt', 'Stel in waarover je seintjes wilt'],
    'Geen eindeloze feed: Pulse toont wat er is en houdt dan op. Dat is bewust.'),
  '/apps/nieuws.html': G('RTG Nieuws: de redactie bundelt wat voor leden telt.',
    ['Lees artikelen per rubriek', 'Bewaar wat je later wilt lezen', 'Reageer waar dat kan'],
    'Kwaliteit boven snelheid: liever één goed stuk dan tien snelle.'),
  '/apps/hotels.html': G('Verblijven: hotels, appartementen en villa\'s van onze partners, met ledenprijzen.',
    ['Bekijk kamers, foto\'s en vrije data', 'Boek direct; de partner bevestigt', 'Open je kamer met keyless waar dat kan'],
    'De ledenprijsgarantie geldt overal: nooit meer dan de publieke prijs van de partner zelf.'),
  '/apps/reisbureau.html': G('Het RTG-reisbureau: samengestelde reizen tegen de nettoprijs.',
    ['Blader door de reizen of vraag AI-reisadvies', 'Vraag een reis aan; een reisadviseur bevestigt', 'Volg en annuleer je aanvragen onder Mijn'],
    'Vertel je wens in gewone woorden; het advies wijst de best passende reis aan en legt uit waarom.'),
  '/apps/foodcourt.html': G('De Food Court: alle restaurants op een rij, reserveren in een paar tikken.',
    ['Kies een restaurant en bekijk de tijdsloten', 'Reserveer; de zaak beslist en je krijgt bericht', 'Bekijk keuken, prijs en ledenvoordeel per zaak'],
    'Reserveer ruim vooruit voor de populaire avonden; annuleren kan altijd netjes in de app.'),
  '/apps/uitgaan.html': G('Uitgaan: bars, clubs en beachclubs met hun avonden en gastenlijsten.',
    ['Bekijk de avonden per adres', 'Zet jezelf op de gastenlijst', 'Laat je entreecode zien aan de deur'],
    'Je leeftijdslaag bepaalt wat je ziet; dat is voor je eigen veiligheid en die van de zaak.'),
  '/apps/mall.html': G('De RTG Mall: de enige plek waar je bij RTG koopt, van eigen-merk tot boutieks, plus de bibliotheken.',
    ['Bestel eigen-merk en boerderijproducten direct', 'Blader door de App- en Reis-Bibliotheek; installeren is inbegrepen', 'Leg mode apart of laat een maat naar de paskamer brengen'],
    'De bibliotheken zijn een pas-voordeel: tienduizenden apps en een miljoen reisgidsen, zonder bijbetalen.'),
  '/apps/pay.html': G('RTG Pay: betalen en tikken tussen vrienden, veilig en direct.',
    ['Stuur of vraag een tik', 'Bekijk je saldo en geschiedenis', 'Splits een rekening met je gezelschap'],
    'Voor elke betaling zie je eerst een bevestiging; niets gaat er zonder jouw akkoord uit.'),
  '/apps/wbw.html': G('Wie betaalt wat: groepsuitgaven bijhouden met een live balans.',
    ['Maak een groep en zet uitgaven erin', 'Zie live wie wat voorschoot', 'Verreken in één keer via RTG Pay'],
    'Direct na de vakantie verrekenen voorkomt het eeuwige "dat komt nog wel".'),
  '/apps/bank.html': G('RTG Bank: je rekening, sparen en krediet in de vertrouwde RTG-stijl.',
    ['Bekijk je saldo en afschriften', 'Zet spaardoelen en volg ze', 'Vraag krediet aan; een mens beoordeelt'],
    'De AI adviseert, een mens beslist; zeker bij geld houden we die volgorde altijd aan.'),
  '/apps/balans.html': G('RTG Balans: je financiële overzicht en de boekhoudhulp.',
    ['Bekijk inkomsten en uitgaven per maand', 'Laat de AI-boekhouder meedenken', 'Exporteer voor je administratie'],
    'Tien minuten per week naar je balans kijken voorkomt de meeste geldverrassingen.'),
  '/apps/sport.html': G('RTG Sport: kampen, lessen en sportieve activiteiten van partners.',
    ['Bekijk het aanbod en de data', 'Meld je aan voor een kamp of les', 'Stel een vraag aan de organisatie'],
    'Begin klein: één vast uur per week houd je langer vol dan een groots plan.'),
  '/apps/spelen.html': G('Spelen: bordspellen en partyspellen met vrienden, live tegen elkaar.',
    ['Start een lobby en nodig vrienden uit', 'Kies een spel: van dammen tot Magnaat', 'Praat mee in de spelchat'],
    'Sommige spellen hebben een leeftijdspoort; dat regelt de app automatisch netjes voor je.'),
  '/apps/muziek.html': G('RTG Sound: muziek voor je dag, samengesteld zonder gejaag.',
    ['Kies een sfeer of kanaal', 'Speel af en bedien vanaf elk scherm', 'Bewaar wat je mooi vindt'],
    'Muziek zonder eindeloos scrollen: kies één sfeer en laat hem gewoon spelen.'),
  '/apps/theater.html': G('RTG Theater: de videobibliotheek op bioscoopniveau, tot 4K zonder hercompressie.',
    ['Kies een kanaal of titel', 'Kijk in de kwaliteit die je verbinding aankan', 'Reageer op titels waar dat open staat'],
    'Alles is vooraf goedgekeurd door het kantoor; daarom vind je hier geen ruis.'),
  '/apps/clips.html': G('RTG Clips: korte video\'s van leden; jouw clips blijven op jouw toestel.',
    ['Bekijk de eindige dagselectie', 'Maak zelf een clip; hij blijft lokaal bij jou', 'Deel bewust, niet automatisch'],
    'De selectie is bewust eindig: als hij op is, is hij op. Geen oneindige scroll.'),
  '/apps/podium.html': G('RTG Podium: het eigen live-streamingkanaal (18+, met verificatie).',
    ['Kijk live streams van makers', 'Steun een maker met een cadeau via RTG Pay', 'Abonneer op wie je vaker wilt zien'],
    'Cadeaus zijn echt geld: de app vraagt altijd eerst een bevestiging.'),
  '/apps/camera.html': G('RTG Camera: foto\'s maken en nabewerken in de eigen studio.',
    ['Maak een foto met de zoeker', 'Bewerk in de studio: licht, kleur, kader', 'Bewaar of deel bewust'],
    'De beste bewerking is licht: probeer eerst de belichting voor je naar filters grijpt.'),
  '/apps/oog.html': G('RTG Eye: camera-visie op je toestel, voor voertuigschouw en werkvloerlog.',
    ['Scan een voertuig voor of na gebruik', 'Log hands-free wat je ziet', 'Deel het rapport met de zaak'],
    'Een schouw van één minuut vooraf voorkomt discussies achteraf; de foto\'s zijn je bewijs.'),
  '/apps/ov.html': G('RTG OV: bus, trein, metro, veerboot en taxi in één reisapp met live GPS.',
    ['Plan een route van deur tot deur', 'Check in met je code of je pas', 'Volg je voertuig live op de kaart'],
    'Bij vertraging rekent de app automatisch een nieuwe route; even verversen is genoeg.'),
  '/apps/ovdienst.html': G('De OV-dienst: het werkscherm van de chauffeur en de verkeersleiding.',
    ['Zie je dienst en je voertuig', 'Meld vertrek, halte en bijzonderheden', 'Houd contact met de meldkamer'],
    'Rustig rijden en eerlijk melden: de reiziger ziet live wat jij doorgeeft.'),
  '/apps/ovroutes.html': G('De OV-routetekenaar: lijnen en haltes op de kaart zetten.',
    ['Teken een lijn met haltes', 'Zet tijden en frequenties', 'Publiceer naar de reisapp'],
    'Teken eerst de haltes, dan de lijn; dat werkt sneller en preciezer.'),
  '/apps/flits.html': G('RTG Flits: het rustige rijscherm met meldingen van de community.',
    ['Zie flitsers, files en ongevallen op je route', 'Meld zelf met één tik of met je stem', 'De landregels bepalen wat getoond mag worden'],
    'Handen aan het stuur: alles kan met spraak, en de app houdt zelf zijn mond op het juiste moment.'),
  '/apps/navigatie.html': G('RTG Navigatie: het huiseigen navigatiesysteem in 3D, met alles wat wij kunnen.',
    ['Zoek een zaak, halte, loket of laadpaal en rijd erheen', 'Kies auto, EV, fiets, lopen of OV; de ETA past mee', 'Zet lagen aan (tank, laad, Flits) en meld zelf een wegprobleem'],
    'De kaart is helemaal van ons: geen Google, geen externe tegels. Sleep om rond te kijken, knijp om te zoomen.'),
  '/apps/horloge.html': G('Het RTG-horloge: het signatuurhorloge van het huis, een opengewerkt skelethorloge dat naast de lippen het symbool van RTG wordt.',
    ['Bekijk het levende 3D-uurwerk dat op de klok van je toestel loopt', 'Zie de drie scholen: de vorm (AP), de leesbaarheid (Rolex) en de techniek (Porsche)', 'Beweeg de muis om het relief te laten spelen (op een computer)'],
    'Alles klopt tot op de milliseconde: de balans op precies 4 Hz, 28.800 halveslagen per uur, foutmarge 0,0.'),
  '/apps/rtg.html': G('RTG - Het Huis: de website van het huis als een high-end magazine op een pagina; swipe zijwaarts om te bladeren.',
    ['Swipe (of gebruik de pijlen) om door de bladen te bladeren', 'Lees per blad een tak: de passen, reizen, care, leren, cultuur, De Salon, de foundation en partners', 'Op het slotblad spring je naar het 3D-uitzicht of terug naar het bureaublad'],
    'Een magazine als app: geen losse internetpagina\'s, alles in een pagina die je doorbladert, in de rustige huisstijl.'),
  '/apps/uitzicht.html': G('Het uitzicht van RTG: een stille 3D-skyline van het hele ecosysteem, in eigen huis getekend.',
    ['Kijk naar de langzaam draaiende stad; elk blok is een tak van het huis', 'Zie het gouden rasterlicht op de grond, hetzelfde als onder de navigatie', 'Rechtsboven loopt de analoge RTG-klok mee op de tijd van je toestel'],
    'Alles is eigen werk op een huiseigen WebGL-motor: geen three.js, geen stockbeeld, geen extern merk.'),
  '/apps/ghost.html': G('Ghost Driver: de voorspellende verkeers- en logistieksimulatie.',
    ['Bekijk de verwachte drukte per uur', 'Speel een scenario door voor je vloot', 'Deel het beeld met de verkeersleider'],
    'Plan je ritten om de voorspelde pieken heen; tien minuten schuiven scheelt vaak een half uur file.'),
  '/apps/vonk.html': G('RTG Vonk: kennismaken op wensen, met een reservering in het midden.',
    ['Vertel wat jij zoekt', 'Bij een wederzijdse like regelt de app een plek in het midden', 'De eerste ronde is geregeld; de rest is aan jullie'],
    'Wees eerlijk in je wensen; de match wordt er alleen maar beter van.'),
  '/apps/passkeys.html': G('Passkeys: inloggen met je vingerafdruk, gezicht of sleutel; geen wachtwoord meer.',
    ['Maak een passkey aan op dit toestel', 'Log voortaan in zonder wachtwoord', 'Beheer of verwijder je sleutels'],
    'Een passkey is niet te phishen: er valt niets over te typen of af te kijken.'),
  '/apps/vluchten.html': G('RTG Vluchten: je vluchten en de private aviation van partners.',
    ['Bekijk vluchten en beschikbaarheid', 'Vraag een boeking aan; de partner bevestigt', 'Volg je reis in de app'],
    'Boekingen zijn pas definitief na bevestiging; de app zegt dat ook eerlijk.'),
};
