/* App-gids data, deel9 (13 pagina's). Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/foundation/kleuren.html': G('Kleuren en vormen: zoeken op kleur, op vorm, of op allebei tegelijk.',
    ['Kies de moeilijkheid: alleen kleur, alleen vorm, of beide', 'Lees de opdracht voor en laat uw kind aanwijzen', 'Bij een misser blijft het spel gewoon staan, zonder straf'],
    'Begin bij alleen kleur; beide tegelijk is voor veel kleuters nog een stap te ver.'),
  '/apps/foundation/memorie.html': G('Memorie: kaartjes omdraaien en paren zoeken.',
    ['Kies drie, zes of acht paren', 'Draai twee kaartjes om; passen ze niet, dan gaan ze weer dicht', 'Speel mee en benoem hardop wat u ziet'],
    'Drie paren is voor een peuter al een hele klus; groter maken kan altijd nog.'),
  '/apps/foundation/verhaaltje.html': G('Voorleesverhaaltjes: zes korte verhalen om samen te lezen, bladzijde voor bladzijde.',
    ['Kies een verhaaltje uit de lijst', 'Blader met Vorige en Volgende; niets gaat vanzelf verder', 'Lees hardop voor en kijk samen naar de plaat'],
    'De verhalen zijn voor deze app geschreven, lopen goed af en bevatten niets engs.'),
  '/apps/foundation/liedjes.html': G('Liedjes en versjes: oude Nederlandse liedjes met de tekst groot in beeld.',
    ['Filter op zingen, handjes of slapen', 'Kies een liedje; de hele tekst komt in beeld', 'Zing zelf: er wordt met opzet geen geluid afgespeeld'],
    'De mooiste versie is die van uw eigen stem; herhaling werkt bij kleintjes beter dan afwisseling.'),
  '/apps/foundation/gevoel.html': G('Hoe voel je je: het gezichtje aantikken dat past, en samen kijken wat helpt.',
    ['Tik het gevoel aan dat het beste past', 'Lees samen het zinnetje en de drie dingen die kunnen helpen', 'Adem mee met de bol als het te druk wordt van binnen'],
    'Er wordt niets opgeslagen of verstuurd: gevoelens van een kind horen niet in een dossier.'),

  /* ---- tieners ---- */
  '/apps/foundation/presenteren.html': G('Spreekbeurt en presentatie: je verhaal opbouwen in vaste stukken, met tijdverdeling en een oefenklok.',
    ['Vul de acht onderdelen in, van opening tot vragen', 'Zet je spreektijd en zie hoeveel tijd elk stuk krijgt', 'Oefen hardop met de klok en print je briefje met steekwoorden'],
    'Twee keer hardop en staand oefenen scheelt meer dan tien keer in je hoofd doorlezen.'),
  '/apps/foundation/budget.html': G('Maandbegroting: wat komt binnen, wat gaat eruit, wat houd je over.',
    ['Zet je inkomsten erin, met de suggesties als startpunt', 'Vul je uitgaven aan en zie de balk meteen meebewegen', 'Zet een spaardoel en lees hoeveel maanden dat kost'],
    'Alles blijft in je eigen scherm; dit is algemene uitleg, geen financieel advies.'),
  '/apps/foundation/rechten.html': G('Wat mag ik op welke leeftijd: werken, geld, school en zorg per leeftijd.',
    ['Kies je leeftijd en zie wat nu al geldt en wat nog komt', 'Filter op werk, school, zelf beslissen, zorg of online', 'Bekijk de werktijdentabel die bij jouw leeftijd hoort'],
    'Algemene informatie over de Nederlandse regels, geen juridisch advies; je cao of school kan strenger zijn.'),
  '/apps/foundation/mijnbanden.html': G('Wie mag iets van mij zien: per onderdeel, aan wie, en tot wanneer.',
    ['Vraag een band op codenaam; er is er pas een als de ander ja zegt',
      'Geef per onderdeel wat die ander mag zien, met een einddatum erbij',
      'Neem terug wat je gaf, of stop de band -- altijd, zonder uitleg'],
    'Standaard ziet niemand iets van jou, ook je ouders niet; je dagboekje, je stemming en je dromen zijn helemaal niet te delen.'),
  '/apps/foundation/mediawijs.html': G('Online wijs: echte situaties van je telefoon, met eerlijke uitleg over wat je keuze oplevert.',
    ['Lees de situatie en kies wat je zou doen', 'Zie meteen waarom die keuze verstandig, matig of riskant is', 'Onthoud de regel die eronder staat en ga door naar de volgende'],
    'Er is geen goed cijfer te halen; de bedoeling is dat je de valkuil herkent voordat hij echt langskomt.'),
  '/apps/vertaler.html': G('RTG Vertaler: typen of spreken, live vertalen op de eigen motor.',
    ['Kies de talen (of wissel ze om) en typ; na een halve seconde rust staat de vertaling er',
     'Druk op Spreek om te dicteren en op Lees voor om de vertaling te horen',
     'Onderweg? De reiszinnen per situatie vertalen met een tik; bewaar je vaste zinnen op het toestel'],
    'Geschiedenis en bewaarde zinnen blijven op je toestel; zonder AI-sleutel vertaalt het huiswoordenboek en zegt de app eerlijk wat niet lukt.'),
  '/apps/memo.html': G('RTG Memo: spraakmemo\'s die gewoon in je Bestanden-kluis leven.',
    ['Druk op Neem op en spreek in; stoppen is bewaren (map Memo\'s in je kluis)',
     'Zet het meeluisteren aan voor een transcript; dat blijft op je toestel',
     'Druk op Samenvatting en Rahul vat het transcript samen -- de audio gaat nooit naar de AI'],
    'Weggooien is naar de prullenbak van je kluis (30 dagen te herstellen) en je kluiskwota is dezelfde; geen tweede opslaglaag.'),
  '/apps/scanner.html': G('RTG Scanner: van papier naar je kluis, alles op het toestel.',
    ['Open de camera en leg pagina voor pagina vast, of kies bestaande foto\'s',
     'De documentmodus maakt papier vlak en leesbaar (zwart-wit, extra contrast)',
     'Bewaar als een PDF of als losse foto\'s in de map Scans van je Bestanden-kluis'],
    'De beeldbewerking en de PDF worden op je toestel gemaakt; er gaat geen beeld naar een andere server dan je eigen kluis.'),
  '/apps/boeken.html': G('RTG Boeken: een rustige lezer met een plank die met je meegroeit.',
    ['Kies uit de huisbibliotheek, of zet een tekstbestand (.txt) in je kluis en hij staat op de plank',
     'Lees in de eigen lezer; de lettergrootte stel je zelf in',
     'Je leesplek reist met je account mee: op elk toestel ga je verder waar je was'],
    'Bewust geen leesdoelen en geen reeksen -- lezen is geen wedstrijd. De server bewaart alleen je leesplek.')
};
