/* App-gids data, deel10: de zeven werkschermen van het Horeca OS naast
   /apps/horeca.html (dat in deel8 staat). Zie ../appgids.js voor de uitleg. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/horeca-expeditie.html': G('Expeditie en keukenregie: de pas, waar een tafel compleet de deur uit gaat.',
    ['Zie per tafel en gang hoeveel borden klaar zijn en hoe lang het eerste al koud staat',
      'Geef zelf uit; er wordt niets automatisch afgevinkt',
      'Lees de drukterem: openstaande bereidingsminuten gedeeld door het aantal koks'],
    'Staat-koud is het getal dat telt: vier borden die na elkaar de deur uit gaan, zijn vier keer half warm.'),
  '/apps/horeca-bezorg.html': G('Bezorgdispatch en de rit: zones, tijdsloten, volgorde en het afleverbewijs.',
    ['Check een adres: het antwoord noemt de zone, de kosten en anders de reden waarom het niet kan',
      'Vul de tijdsloten in keukenminuten; tien pizza\'s zijn geen tien diners',
      'Loop de rit af van inpakken tot aftekenen; vertrekken kan pas als beide vinkjes staan'],
    'Er wordt geen foto van een mens of een deur bewaard: het bewijs legt vast wat een geschil later beslecht.'),
  '/apps/horeca-hotel.html': G('Gastrekening en roomservice: alles van het verblijf op een rekening.',
    ['Open een gastrekening op een kamer en boek ontbijt, minibar, spa of restaurant erop',
      'Draai de nachtrun; twee keer drukken boekt geen twee nachten',
      'Neem roomservice op, geef hem vrij naar de keuken en boek hem op de kamer'],
    'De toeristenbelasting staat als eigen regel en niet in de kamerprijs: een gast hoort te zien wat hij aan wie betaalt.'),
  '/apps/horeca-events.html': G('Events: offerte, akkoord, verbruik en nacalculatie.',
    ['Zet de posten op een offerte en leg het akkoord vast met een naam erbij',
      'Boek de aanbetaling en later de werkelijke kosten en uren',
      'Draai de nacalculatie: opbrengst, kosten, marge en de opbrengst per gast'],
    'Posten wijzigen na een akkoord maakt een nieuwe versie die opnieuw bevestigd moet worden; de vorige blijft bewaard.'),
  '/apps/horeca-club.html': G('Club: polsbandtegoed, minimum spend en de deurteller.',
    ['Waardeer een polsband op, boek erop af en betaal het restsaldo terug',
      'Zie per VIP-tafel wat er van de minimum spend nog te gaan is',
      'Tel aan de deur in, uit en herbetreding, met de gastenlijst per promoter erbij'],
    'Op een band staat een nummer en een saldo, geen naam: wie hem verliest, verliest zijn tegoed en niet zijn identiteit.'),
  '/apps/horeca-haccp.html': G('HACCP-registratie: temperatuurlogboek, batches en controlelijsten.',
    ['Leg meetpunten met hun grenzen vast en noteer de metingen',
      'Zie welke batches over de datum zijn en boek ze af met een reden',
      'Vink een controlelijst af, punt voor punt'],
    'Wat vandaag nog niet gemeten is, staat er als gemist bij; een leeg logboek ziet er anders precies zo uit als een goed logboek.'),
  '/apps/werk.html': G('RTG Werk OS: de werkplek van een hele organisatie -- projecten, kennis, klanten, service, bouw, IT, contracten en besluiten.',
    ['Ga naar binnen met de werkruimtecode en uw eigen lid-token; dat is bewust iets anders dan uw RTG-pas',
      'Lees uw startscherm: het volgt uw rollen, en wat geen bron heeft staat er als NIET GEMETEN in plaats van als nul',
      'Kies een module en zie de lijst plus wat aandacht vraagt; koppel eenmalig uw RTG-account voor agenda, postvak en kluis'],
    'Wat u niet mag zien, staat er niet als lege doos; en wat nergens wordt gemeten, staat er met de reden erbij.'),
  '/apps/horeca-beheer.html': G('Beheer: de dag over alle kanalen, de fooienpot, de loonkosten en de signalen.',
    ['Lees de omzet per kanaal en per betaalwijze, met fooi en oninbaar apart',
      'Verdeel de fooienpot over gewerkte uren; de som van de delen is exact de pot',
      'Zet het loon tegenover de omzet zonder fooi en bekijk de signalen'],
    'Er staat geen omzetprognose op dit scherm: wat er staat is wat er nu open staat en wat er vandaag is binnengekomen.'),

  /* ---- het Foundation OS ---- */
  '/apps/foundation/os.html': G('Foundation OS: het bestuurssysteem van de RTFoundation -- landelijk toezicht, zelfstandige stadsafdelingen, partnerstichtingen, projecten, vrijwilligers, geld en hulpvragen.',
    ['Kies een stadsafdeling; u ziet alleen de steden waar u een zetel heeft, het landelijke bestuur ziet ze alle',
      'Werk per tabblad: impact, projecten, partners, vrijwilligers, geld, hulpvragen, integriteit, gemeente en ondernemers',
      'Werk per tabblad verder: subsidies met hun rapportagemomenten, voorraad per batch, activiteiten met wachtlijst en incheck, en communicatie',
      'Onder Netwerk deelt u een blauwdruk met andere steden, koopt u samen in, leent u vrijwilligers uit en ziet u het koppelbord met RTG',
      'Onder Bestuur staan de knoppen van het toezicht: modules per stad, de status van de afdeling, de goedkeuringslimieten en de zetels'],
    'Geoormerkt geld gaat hier nooit naar een ander project, wie een uitgave aanvraagt keurt hem niet zelf goed, en een melding kan niemand verwijderen -- ook het landelijke bestuur niet.'),
  '/apps/foundation/os-portaal.html': G('Het portaal voor partnerstichtingen, gemeenten en lokale ondernemers: uw eigen dossier, op uw eigen code.',
    ['Vul de code in die u van het RTF-kantoor kreeg (RTFP voor een stichting, RTFG voor een gemeente, RTFO voor een bedrijf)',
      'Een stichting ziet de samenwerkingsafspraken en de eigen projecten; een gemeente uitsluitend getelde cijfers; een ondernemer waar zijn bijdrage terechtkwam',
      'De code blijft in dit tabblad en wordt nergens bewaard -- op een gedeelde computer sluit u hem weg door het tabblad te sluiten'],
    'Een gemeente krijgt hier nooit een dossier of een naam te zien, en buurten met minder dan vijf hulpvragen worden samengevoegd: een klein getal in een kleine buurt is geen statistiek meer.')
};
