/* App-gids data, deel6 (vervolg van deel1: de leden-apps, tweede helft).
   Zie ../appgids.js voor de uitleg; nieuwe pagina's krijgen hier (of in het
   passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/muziek.html': G('RTG Sound: muziek voor je dag, samengesteld zonder gejaag.',
    ['Kies een sfeer of kanaal', 'Speel af en bedien vanaf elk scherm', 'Bewaar wat je mooi vindt'],
    'Muziek zonder eindeloos scrollen: kies één sfeer en laat hem gewoon spelen.'),
  '/apps/theater.html': G('RTG Theater: de videobibliotheek op bioscoopniveau, tot 4K zonder hercompressie.',
    ['Kies een kanaal of titel', 'Kijk in de kwaliteit die je verbinding aankan', 'Reageer op titels waar dat open staat'],
    'Alles is vooraf goedgekeurd door het kantoor; daarom vind je hier geen ruis.'),
  '/apps/clips.html': G('RTG Clips: korte video\'s van leden; jouw clips blijven op jouw toestel.',
    ['Bekijk de eindige dagselectie', 'Maak zelf een clip; hij blijft lokaal bij jou', 'Deel bewust, niet automatisch'],
    'De selectie is bewust eindig: als hij op is, is hij op. Geen oneindige scroll.'),
  '/apps/podium.html': G('RTG Podium: het eigen live-streamingkanaal (18+, met verificatie).',
    ['Kijk live streams van makers', 'Steun een maker met een cadeau via RTG Pay', 'Abonneer op wie je vaker wilt zien'],
    'Cadeaus zijn echt geld: de app vraagt altijd eerst een bevestiging.'),
  '/apps/camera.html': G('RTG Camera: foto\'s maken en nabewerken in de eigen studio.',
    ['Maak een foto met de zoeker', 'Bewerk in de studio: licht, kleur, kader', 'Bewaar of deel bewust'],
    'De beste bewerking is licht: probeer eerst de belichting voor je naar filters grijpt.'),
  '/apps/oog.html': G('RTG Eye: camera-visie op je toestel, voor voertuigschouw en werkvloerlog.',
    ['Scan een voertuig voor of na gebruik', 'Log hands-free wat je ziet', 'Deel het rapport met de zaak'],
    'Een schouw van één minuut vooraf voorkomt discussies achteraf; de foto\'s zijn je bewijs.'),
  '/apps/ov.html': G('RTG OV: bus, trein, metro, veerboot en taxi in één reisapp met live GPS.',
    ['Plan een route van deur tot deur', 'Check in met je code of je pas', 'Volg je voertuig live op de kaart'],
    'Bij vertraging rekent de app automatisch een nieuwe route; even verversen is genoeg.'),
  '/apps/ovdienst.html': G('De OV-dienst: het werkscherm van de chauffeur en de verkeersleiding.',
    ['Zie je dienst en je voertuig', 'Meld vertrek, halte en bijzonderheden', 'Houd contact met de meldkamer'],
    'Rustig rijden en eerlijk melden: de reiziger ziet live wat jij doorgeeft.'),
  '/apps/ovroutes.html': G('De OV-routetekenaar: lijnen en haltes op de kaart zetten.',
    ['Teken een lijn met haltes', 'Zet tijden en frequenties', 'Publiceer naar de reisapp'],
    'Teken eerst de haltes, dan de lijn; dat werkt sneller en preciezer.'),
  '/apps/flits.html': G('RTG Flits: het rustige rijscherm met meldingen van de community.',
    ['Zie flitsers, files en ongevallen op je route', 'Meld zelf met één tik of met je stem', 'De landregels bepalen wat getoond mag worden'],
    'Handen aan het stuur: alles kan met spraak, en de app houdt zelf zijn mond op het juiste moment.'),
  '/apps/navigatie.html': G('RTG Navigatie: het huiseigen navigatiesysteem in 3D, met alles wat wij kunnen.',
    ['Zoek een zaak, halte, loket of laadpaal en rijd erheen', 'Kies auto, EV, fiets, lopen of OV; de ETA past mee', 'Zet lagen aan (tank, laad, Flits) en meld zelf een wegprobleem'],
    'De kaart is helemaal van ons: geen Google, geen externe tegels. Sleep om rond te kijken, knijp om te zoomen.'),
  '/apps/horloge.html': G('Het RTG-horloge: het signatuurhorloge van het huis, een opengewerkt skelethorloge dat naast de lippen het symbool van RTG wordt.',
    ['Bekijk het levende 3D-uurwerk dat op de klok van je toestel loopt', 'Zie de drie scholen: de vorm (AP), de leesbaarheid (Rolex) en de techniek (Porsche)', 'Beweeg de muis om het relief te laten spelen (op een computer)'],
    'Alles klopt tot op de milliseconde: de balans op precies 4 Hz, 28.800 halveslagen per uur, foutmarge 0,0.'),
  '/apps/rtg.html': G('RTG - Het Huis: de website van het huis als een high-end magazine op een pagina; swipe zijwaarts om te bladeren.',
    ['Swipe (of gebruik de pijlen) om door de bladen te bladeren', 'Lees per blad een tak: de passen, reizen, care, leren, cultuur, De Salon, de foundation en partners', 'Op het slotblad spring je naar het 3D-uitzicht of terug naar het bureaublad'],
    'Een magazine als app: geen losse internetpagina\'s, alles in een pagina die je doorbladert, in de rustige huisstijl.'),
  '/apps/uitzicht.html': G('Het uitzicht van RTG: een stille 3D-skyline van het hele ecosysteem, in eigen huis getekend.',
    ['Kijk naar de langzaam draaiende stad; elk blok is een tak van het huis', 'Zie het gouden rasterlicht op de grond, hetzelfde als onder de navigatie', 'Rechtsboven loopt de analoge RTG-klok mee op de tijd van je toestel'],
    'Alles is eigen werk op een huiseigen WebGL-motor: geen three.js, geen stockbeeld, geen extern merk.'),
  '/apps/ghost.html': G('Ghost Driver: de voorspellende verkeers- en logistieksimulatie.',
    ['Bekijk de verwachte drukte per uur', 'Speel een scenario door voor je vloot', 'Deel het beeld met de verkeersleider'],
    'Plan je ritten om de voorspelde pieken heen; tien minuten schuiven scheelt vaak een half uur file.'),
  '/apps/vonk.html': G('RTG Vonk: kennismaken op wensen, met een reservering in het midden.',
    ['Vertel wat jij zoekt', 'Bij een wederzijdse like regelt de app een plek in het midden', 'De eerste ronde is geregeld; de rest is aan jullie'],
    'Wees eerlijk in je wensen; de match wordt er alleen maar beter van.'),
  '/apps/passkeys.html': G('Passkeys: inloggen met je vingerafdruk, gezicht of sleutel; geen wachtwoord meer.',
    ['Maak een passkey aan op dit toestel', 'Log voortaan in zonder wachtwoord', 'Beheer of verwijder je sleutels'],
    'Een passkey is niet te phishen: er valt niets over te typen of af te kijken.'),
  '/apps/vluchten.html': G('RTG Vluchten: je vluchten en de private aviation van partners.',
    ['Bekijk vluchten en beschikbaarheid', 'Vraag een boeking aan; de partner bevestigt', 'Volg je reis in de app'],
    'Boekingen zijn pas definitief na bevestiging; de app zegt dat ook eerlijk.'),
};
