/* App-gids data, deel1c: de staart van deel1 (nieuws, verblijven, reisbureau,
   food court, uitgaan, mall en verder). Zie ../appgids.js voor de uitleg.

   Opgeknipt op de 10 kB-grens van keuringsregel 13, net als ./deel1b.js. De
   knip zit op een entry-grens; ./deel1.js hangt dit deel er zelf achter, VOOR
   deel1b -- dezelfde vololgorde als toen het een bestand was, zodat een entry
   die in beide staat nog steeds dezelfde wint. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/nieuws.html': G('RTG Nieuws: de redactie bundelt wat voor leden telt.',
    ['Lees artikelen per rubriek', 'Bewaar wat je later wilt lezen', 'Reageer waar dat kan'],
    'Kwaliteit boven snelheid: liever één goed stuk dan tien snelle.'),
  '/apps/hotels.html': G('Verblijven: hotels, appartementen en villa\'s van onze partners, met ledenprijzen.',
    ['Bekijk kamers, foto\'s en vrije data', 'Boek direct; de partner bevestigt', 'Open je kamer met keyless waar dat kan'],
    'De ledenprijsgarantie geldt overal: nooit meer dan de publieke prijs van de partner zelf.'),
  '/apps/reisbureau.html': G('Het RTG-reisbureau: samengestelde reizen tegen de nettoprijs.',
    ['Blader door de reizen of vraag AI-reisadvies', 'Vraag een reis aan; een reisadviseur bevestigt', 'Volg en annuleer je aanvragen onder Mijn'],
    'Vertel je wens in gewone woorden; het advies wijst de best passende reis aan en legt uit waarom.'),
  '/apps/foodcourt.html': G('De Food Court: alle restaurants op een rij, reserveren in een paar tikken.',
    ['Kies een restaurant en bekijk de tijdsloten', 'Reserveer; de zaak beslist en je krijgt bericht', 'Bekijk keuken, prijs en ledenvoordeel per zaak'],
    'Reserveer ruim vooruit voor de populaire avonden; annuleren kan altijd netjes in de app.'),
  '/apps/uitgaan.html': G('Uitgaan: bars, clubs en beachclubs met hun avonden en gastenlijsten.',
    ['Bekijk de avonden per adres', 'Zet jezelf op de gastenlijst', 'Laat je entreecode zien aan de deur'],
    'Je leeftijdslaag bepaalt wat je ziet; dat is voor je eigen veiligheid en die van de zaak.'),
  '/apps/mall.html': G('De RTG Mall: de enige plek waar je bij RTG koopt, van eigen-merk tot boutieks, plus de bibliotheken.',
    ['Bestel eigen-merk en boerderijproducten direct', 'Blader door de App- en Reis-Bibliotheek; installeren is inbegrepen', 'Leg mode apart of laat een maat naar de paskamer brengen'],
    'De bibliotheken zijn een pas-voordeel: tienduizenden apps en een miljoen reisgidsen, zonder bijbetalen.'),
  '/apps/leverancier-commerce.html': G('De zaakkant van RTG Commerce: waarlangs u verkoopt, en wat er terugkomt.',
    ['Maak een verkoopweg en zet hem live; zie hoeveel er langs die weg te koop staat',
     'Neem een retour terug of wijs hem af met een reden, en noteer in welke staat het aankwam',
     'Handel af met een uitkomst; het bedrag staat daarna KLAAR in RTG Pay'],
    'Dit scherm verplaatst geen geld en boekt geen voorraad: het zet klaar en zegt waar u het uitvoert.'),
  '/apps/commerce.html': G('RTG Commerce: wat er te koop staat, wat er NIET te koop staat en waarom, en je mand over verkopers heen.',
    ['Zie per aanbod wat je ermee kunt: prijzen, reserveren, kopen, leveren, annuleren, terugsturen',
     'Kies een verkoper en zie welke regels buiten de etalage vallen, met de reden erbij',
     'Leg dingen van verschillende verkopers in een mand; je krijgt per verkoper een afrekening',
     'Ga naar de verkoper met je keuze mee: die staat bovenaan zijn scherm klaar'],
    'Er is bewust geen knop "betaal alles": achter die regels zitten verschillende partijen, en RTG bevestigt niets namens hen. Ook een doorgegeven keuze is geen bestelling -- dat blijft aan jou en aan de verkoper.'),
  '/apps/pay.html': G('RTG Pay: betalen en tikken tussen vrienden, veilig en direct.',
    ['Stuur of vraag een tik', 'Bekijk je saldo en geschiedenis', 'Splits een rekening met je gezelschap'],
    'Voor elke betaling zie je eerst een bevestiging; niets gaat er zonder jouw akkoord uit.'),
  '/apps/rtgone.html': G('RTG One: de gezamenlijke command room voor personeel van RTG en RTF, met werkstromen, besluiten en governance in een gecontroleerde omgeving.',
    ['Bekijk wat vandaag aandacht vraagt', 'Maak vanuit RTMAIL een werkstroom met eigenaar, bewijs en deadline', 'Leg besluiten via de juiste vier-ogenroute vast en volg iedere actie in het auditlog'],
    'Wissel bewust tussen het RTG-huis, het RTF-huis en de gedeelde ruimte; gegevens en rechten blijven per huis afgeschermd.'),
  '/apps/magnaat.html': G('Magnaat Wereld: oefen met echte RTG-werkprocessen in een volledig synthetische ondernemerswereld.',
    ['Kies een functie of servicedossier', 'Werk via de afgeschermde computer en PDA', 'Reken gevolgen veilig door in de economische cockpit'],
    'Geen spelhandeling raakt productiegegevens, echte betalingen of klantcommunicatie.'),
  '/apps/magnaat-kantoor.html': G('Het RTG Controleregister: functies, dekkingsgaten, veilige zelftests, automatische kantoortaken en menselijke fasebesluiten.',
    ['Bekijk de Capability Graph', 'Onderzoek open controlepunten', 'Laat alleen bevoegde mensen een voorstel naar test of pilot zetten'],
    'De Future Engine adviseert; mensen beslissen en iedere pilot blijft een sandbox.'),
  '/apps/ovcontrol.html': G('De OV Control Tower: live zicht op voertuigen, lijnen en geaggregeerde private operaties.',
    ['Bewaak voertuigen en bezetting', 'Vergelijk prestaties per lijn', 'Grijp als bevoegd personeelslid in bij uitzonderingen'],
    'Privéreizen blijven need-to-know: het bord toont capaciteit, nooit het profiel of de route van de hoofdgast.'),
  '/apps/partner-worden.html': G('Partner worden: een gecontroleerde aanvraag voor een Business Pass en zakelijke RTG-werkplek.',
    ['Meld aan met de Business Pass', 'Vul bedrijfs- en contactgegevens in', 'Volg de menselijke beoordeling en inrichting'],
    'Een aanvraag zet niets automatisch live; een bevoegde medewerker beoordeelt en activeert.'),
};
