/* App-gids data, deel2 (26 pagina's). Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = Object.assign({
  '/apps/home.html': G('De RTG Home Kit: alle elektronica van je huis op één plek, per kamer, met scènes die je met één tik start.',
    ['Bedien lampen, klimaat, gordijnen en audio per kamer', 'Laat Rahul een scène voorstellen (bijv. filmavond) en bewaar hem', 'Verbind merken via de open koppelstandaard; hun apparaten doen meteen mee', 'Alles uit met één tik; sloten bedien je altijd zelf'],
    'De AI stelt scènes voor, jij beslist; en een deur van het slot halen blijft altijd jouw eigen losse tik. Dat is een vaste veiligheidsregel.'),
  '/apps/juridisch.html': G('Juridisch: de voorwaarden, privacyregels en jouw AVG-rechten, in gewone taal.',
    ['Lees de voorwaarden per onderwerp', 'Vraag je gegevens op of laat ze wissen', 'Bekijk wat partners wel en niet zien'],
    'Jouw echte naam staat in een aparte kluis; partners werken met je codenaam. Zo is het ontworpen.'),
  '/apps/scherm.html': G('Tweede scherm: spiegel je werkplek of maak er een extra werkplek van.',
    ['Koppel met de code op je hoofdscherm', 'Kies spiegelen of een eigen werkplek', 'Ontkoppel met één tik'],
    'Een tweede scherm naast de kassa scheelt loopwerk: orders links, afrekenen rechts.'),
  '/apps/wallet.html': G('RTG Wallet: je ledenpas, tickets, sleutels, munten en klantenkaarten op een plek.',
    ['Bovenaan ligt je ledenpas: codenaam, lidnummer en een QR', 'Tik op een kaart voor het grote codescherm', 'Koop feestmunten, wissel ze in en voeg zelf kaarten toe'],
    'De zorgpas van de verzekeraar verschijnt hier vanzelf; wat je niet meer nodig hebt haal je er zo weer uit.'),
  '/apps/rtgid.html': G('RTG iD: jouw digitale identiteit; inloggen met een tik, delen wat jij kiest.',
    ['Voer de koppelcode van een dienst in en zie wie er aanklopt', 'Bevestig of weiger; er wordt nooit meer gedeeld dan gevraagd', 'Bekijk je inzagelog en trek toegang of machtigingen in'],
    'Een dienst die alleen "18 of ouder" hoeft te weten, krijgt precies dat bewijs; je geboortedatum blijft in de kluis.'),
  '/apps/office.html': G('RTG Office: tekstdocumenten en rekenbladen, automatisch bewaard.',
    ['Maak een document of rekenblad', 'Deel op codenaam met wie jij kiest', 'Exporteer wanneer je wilt'],
    'Alles wordt vanzelf bewaard terwijl je typt; je kunt niets kwijtraken.'),
  '/apps/doos.html': G('De Zaakdoos: het kastje dat je zaak lokaal draaiend houdt, ook zonder internet.',
    ['Bekijk de status van je doos', 'Beheer wifi, updates en stroomwacht op afstand', 'Speel het journaal na bij twijfel'],
    'Valt het internet uit, dan draait je zaak gewoon door; de doos synct later alles netjes bij.'),
  '/apps/techniek.html': G('De technische status: gezondheid, zekeringen en de AI-monteur.',
    ['Bekijk de gezondheid van alle onderdelen', 'Zet een zekering om bij problemen', 'Laat de AI een diagnose voorstellen'],
    'Groen wil je zien; wordt iets geel, kijk dan eerst naar de laatste wijziging.'),
  '/apps/attenties.html': G('Attenties: uw relatiebeheer -- wie, wanneer, en wat u al eens gaf.',
    ['Zet een relatie erbij met de band en de belangrijke data', 'Noteer hun voorkeuren', 'Houd de giftgeschiedenis bij, zodat u nooit twee keer hetzelfde geeft'],
    'Het overzicht toont wie er de komende dertig dagen een attentie verdient. Inpakken en bezorgen doet de app niet.'),
  '/apps/cellier.html': G('Cellier: uw wijnkelder, met drinkvensters en kelderwaarde.',
    ['Zet een fles erbij met domein, jaargang, aantal en waarde', 'Geef het drinkvenster op; het overzicht wijst aan wat nu op dronk is', 'Schenk een fles: het aantal telt vanzelf af'],
    'Het drinkvenster zegt wanneer een fles op zijn mooist is. Wij vullen niets aan en adviseren niets bij te kopen; wat er staat, vulde u zelf in.'),
  '/apps/cercle.html': G('Cercle: uw besloten clubs en lidmaatschappen, met reciprociteit en gastpassen.',
    ['Zet een club erbij met stad, lidnummer, dresscode en gastpassen',
     'Vraag waar u in een stad terecht kunt -- op eigen lidmaatschap of via reciprociteit',
     'Boek een gastpas af als u iemand meeneemt; het aantal loopt vanzelf terug'],
    'Alles hierin komt uit wat u zelf invult. RTG houdt geen clubgids bij en belooft niets namens een club: bel vooruit.'),
  '/apps/entourage.html': G('Entourage: uw vaste reisgezelschap, met hun voorkeuren, dieet en documenten.',
    ['Zet de mensen erbij die u meeneemt, met hun band en hun dieet',
     'Leg per persoon documenten vast met vervaldatum -- paspoort, visum, rijbewijs, verzekering, vaccinatie',
     'Stel een gezelschap samen en zie wat er ontbreekt of bijna verloopt'],
    'De app waarschuwt over data die U heeft ingevuld. Inreisvereisten per land staan er met opzet niet in: die veranderen per week en per nationaliteit, en iets beweren wat wij niet kunnen naslaan is erger dan niets zeggen.'),
  '/apps/garderobe.html': G('Garde-robe: uw garderobe op papier -- wat u heeft, en waar het hangt.',
    ['Zet een stuk erbij met type, merk, kleur en maat', 'Noteer in welke woning en welke kast het ligt', 'Houd uw vaklui bij: kleermaker, schoenmaker, stomerij'],
    'Het overzicht telt per categorie, zodat u ziet wat u heeft en waar. Wij stellen niets voor en adviseren niets te kopen.'),
}, require('./deel2b'));
