/* App-gids data, deel2 (26 pagina's). Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = Object.assign({
  '/apps/home.html': G('De RTG Home Kit: alle elektronica van je huis op één plek, per kamer, met scènes die je met één tik start.',
    ['Bedien lampen, klimaat, gordijnen en audio per kamer', 'Laat Rahul een scène voorstellen (bijv. filmavond) en bewaar hem', 'Verbind merken via de open koppelstandaard; hun apparaten doen meteen mee', 'Alles uit met één tik; sloten bedien je altijd zelf'],
    'De AI stelt scènes voor, jij beslist; en een deur van het slot halen blijft altijd jouw eigen losse tik. Dat is een vaste veiligheidsregel.'),
  '/apps/juridisch.html': G('Juridisch: de voorwaarden, privacyregels en jouw AVG-rechten, in gewone taal.',
    ['Lees de voorwaarden per onderwerp', 'Vraag je gegevens op of laat ze wissen', 'Bekijk wat partners wel en niet zien'],
    'Jouw echte naam staat in een aparte kluis; partners werken met je codenaam. Zo is het ontworpen.'),
  '/apps/scherm.html': G('Tweede scherm: spiegel je werkplek of maak er een extra werkplek van.',
    ['Koppel met de code op je hoofdscherm', 'Kies spiegelen of een eigen werkplek', 'Ontkoppel met één tik'],
    'Een tweede scherm naast de kassa scheelt loopwerk: orders links, afrekenen rechts.'),
  '/apps/wallet.html': G('RTG Wallet: je ledenpas, tickets, sleutels, munten en klantenkaarten op een plek.',
    ['Bovenaan ligt je ledenpas: codenaam, lidnummer en een QR', 'Tik op een kaart voor het grote codescherm', 'Koop feestmunten, wissel ze in en voeg zelf kaarten toe'],
    'De zorgpas van de verzekeraar verschijnt hier vanzelf; wat je niet meer nodig hebt haal je er zo weer uit.'),
  '/apps/rtgid.html': G('RTG iD: jouw digitale identiteit; inloggen met een tik, delen wat jij kiest.',
    ['Voer de koppelcode van een dienst in en zie wie er aanklopt', 'Bevestig of weiger; er wordt nooit meer gedeeld dan gevraagd', 'Bekijk je inzagelog en trek toegang of machtigingen in'],
    'Een dienst die alleen "18 of ouder" hoeft te weten, krijgt precies dat bewijs; je geboortedatum blijft in de kluis.'),
  '/apps/office.html': G('RTG Office: tekstdocumenten en rekenbladen, automatisch bewaard.',
    ['Maak een document of rekenblad', 'Deel op codenaam met wie jij kiest', 'Exporteer wanneer je wilt'],
    'Alles wordt vanzelf bewaard terwijl je typt; je kunt niets kwijtraken.'),
  '/apps/doos.html': G('De Zaakdoos: het kastje dat je zaak lokaal draaiend houdt, ook zonder internet.',
    ['Bekijk de status van je doos', 'Beheer wifi, updates en stroomwacht op afstand', 'Speel het journaal na bij twijfel'],
    'Valt het internet uit, dan draait je zaak gewoon door; de doos synct later alles netjes bij.'),
  '/apps/techniek.html': G('De technische status: gezondheid, zekeringen en de AI-monteur.',
    ['Bekijk de gezondheid van alle onderdelen', 'Zet een zekering om bij problemen', 'Laat de AI een diagnose voorstellen'],
    'Groen wil je zien; wordt iets geel, kijk dan eerst naar de laatste wijziging.'),
  '/apps/attenties.html': G('Attenties: kleine gebaren op het juiste moment, verzorgd door uw Rechterhand.',
    ['Kies een gelegenheid en een attentie', 'Wij verzorgen inpakken en bezorgen', 'Volg de status discreet in de app'],
    'Een attentie op tijd is meer waard dan een groot gebaar te laat; de agenda helpt u herinneren.'),
  '/apps/cellier.html': G('Cellier: uw wijnkelder, bijgehouden en aangevuld met verstand.',
    ['Bekijk uw kelder en drinkvensters', 'Laat aanvullen op advies', 'Reserveer flessen voor een diner'],
    'Het drinkvenster zegt wanneer een fles op zijn mooist is; de kelder let er voor u op.'),
  '/apps/cercle.html': G('Cercle: uw besloten kring binnen de Salon.',
    ['Zie wat uw kring deelt', 'Nodig uit wie erbij hoort', 'Organiseer een besloten moment'],
    'Klein houden is de kracht van een kring; kwaliteit van gezelschap boven aantal.'),
  '/apps/entourage.html': G('Entourage: de mensen om u heen (chauffeur, oppas, staf) op één plek geregeld.',
    ['Zet afspraken met uw vaste mensen', 'Deel alleen wat zij nodig hebben', 'Betaal en verantwoord netjes via de app'],
    'Duidelijke afspraken maken vaste mensen beter; de app houdt ze voor beide kanten bij.'),
  '/apps/garderobe.html': G('Garde-robe: uw garderobe in beeld, met de styling van de boutieks.',
    ['Bekijk wat er hangt en wat er mist', 'Ontvang stylingvoorstellen van uw huizen', 'Laat een maat naar de paskamer brengen'],
    'Een garderobe die klopt is stiller dan een kast die vol is; wij letten op de gaten.'),
  '/apps/leverancier.html': G('De leverancier-app: uw hele zaak in één scherm, van orders tot personeel.',
    ['Beheer orders, reserveringen en voorraad', 'Stuur uw team aan met rooster en taken', 'Vraag de zaak-AI om cijfers en advies'],
    'Kijk elke ochtend één minuut naar het actiecentrum; dan begint de dag zonder verrassingen.'),
}, require('./deel2b'));
