/* App-gids data, deel6 (24 pagina's). Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/media.html': G('RTG Media: één mediawereld -- muziek, video, korte video en live bij elkaar.',
    ['Kies een stand: Muziek, Kijk of Flow -- het is dezelfde wereld',
     'Open "alles hierover" en zie het hele stuk: de maker, zijn andere werk en de clips met dit geluid eronder',
     'Stuur uw wereld zelf bij met meer, minder, nooit en verras me'],
    'Bij elk stuk staat waarom het er staat. Wat u niet zelf hebt gezegd, weegt hier niet mee.'),
  '/apps/muziek.html': G('RTG Sound: muziek voor je dag, samengesteld zonder gejaag.',
    ['Kies een sfeer of kanaal', 'Speel af en bedien vanaf elk scherm', 'Bewaar wat je mooi vindt'],
    'Muziek zonder eindeloos scrollen: kies één sfeer en laat hem gewoon spelen.'),
  '/apps/theater.html': G('RTG Theater: de videobibliotheek op bioscoopniveau, tot 4K zonder hercompressie.',
    ['Kies een kanaal of titel', 'Kijk in de kwaliteit die je verbinding aankan', 'Reageer op titels waar dat open staat'],
    'Alles is vooraf goedgekeurd door het kantoor; daarom vind je hier geen ruis.'),
  '/apps/clips.html': G('RTG Clips: korte video\'s van leden; jouw clips blijven op jouw toestel.',
    ['Bekijk de eindige dagselectie', 'Maak zelf een clip; hij blijft lokaal bij jou', 'Deel bewust, niet automatisch'],
    'De selectie is bewust eindig: als hij op is, is hij op. Geen oneindige scroll.'),
  '/apps/klankwerk.html': G('RTG Klankwerk: zelf muziek maken, met een raster, een notenrol en Rahul erbij.',
    ['Zet een figuur in het raster of laat Rahul iets neerzetten',
     'Bewerk het: elke noot is van jou en alles is terug te draaien',
     'Noem het klaar en zet het onder je eigen clip, of neem het mee als bestand'],
    'Elke klank wordt door de app zelf opgewekt. Daarom zit er geen licentie van iemand anders in wat je maakt, en mag het onder je eigen clip.'),
  '/apps/zaal.html': G('De Zaal: waar de muziek te horen is die leden in RTG Klankwerk gemaakt hebben.',
    ['Luister; wat je hoort rekent je eigen toestel uit',
     'Zeg "mooi" of schrijf er iets bij',
     'Filter op wat onder de RTG-naam uitkwam, of op je eigen werk'],
    'Er is geen hitlijst en geen aanbevolen volgorde: wie bovenaan staat, staat daar omdat hij de laatste was.'),
  '/apps/agenda.html': G('RTG Agenda: een echte kalender; maand, week en lijst.',
    ['Plan zelf, of zeg het Rahul in gewone taal ("lunch vrijdag 12:30")',
     'Nodig uit op codenaam; de ander zegt ja of nee en jij ziet de stand',
     'Exporteer als .ics; dat opent in elke agenda ter wereld'],
    'Je RTG-boekingen staan er vanzelf in, goudgemarkeerd en alleen-lezen: de agenda leest RTG, hij herschrijft RTG niet.'),
  '/apps/notities.html': G('RTG Notities & Taken: het bord dat elke dag opengaat.',
    ['Zet een notitie of een lijst met vinkjes op het bord; vastpinnen zet bovenaan',
     'Deel op codenaam en werk samen: de ander vinkt af en vult aan',
     'Geef een notitie een datum en tijd; er komt vanzelf een gekoppelde afspraak in RTG Agenda'],
    'Het archief is de la, niet de prullenbak: niets verdwijnt stiekem.'),
  '/apps/bestanden.html': G('RTG Bestanden: de versleutelde kluis voor alles wat je bewaren wilt.',
    ['Sleep bestanden naar het scherm of druk op Upload; mappen houden het overzichtelijk',
     'Deel op codenaam: de ander kijkt en plaatst nieuwe versies, de kluis blijft van jou',
     'Elke nieuwe versie bewaart de oude; terugzetten kan altijd'],
    'De prullenbak bewaart 30 dagen en telt eerlijk mee voor je quotum: weg is pas weg als jij dat zegt.'),
  '/apps/meet.html': G('RTG Meet: vergaderen op codenaam, met scherm delen.',
    ['Maak een kamer of kom binnen met de zes-tekens code',
     'Deel je scherm met een knop; je camera komt vanzelf terug als je stopt',
     'Op een agenda-afspraak staat een Vergaderruimte-knop: de uitnodiging is de sleutel'],
    'Beeld en geluid lopen rechtstreeks tussen de toestellen; de server geeft alleen seinen door en ziet het gesprek zelf nooit.'),
  '/apps/galerij.html': G('RTG Galerij: al je beelden op een plek, de tijdlijn is de kalender.',
    ['Blader per maand; je Salon-posts en de beelden uit Bestanden staan er vanzelf in',
     'Zet een ster op wat je lief is en bouw albums; dat zijn verwijzingen, geen kopieen',
     'Open een beeld voor de kijker: bladeren, favoriet en de diavoorstelling'],
    'Geen gezichtsherkenning en geen slimme sortering: de galerij kijkt niet naar je foto\'s, hij toont ze alleen.'),
  '/apps/gereedschap.html': G('RTG Gereedschap: de dagelijkse basics, op huisniveau.',
    ['Reken met de eigen rekenmachine; btw en rekening delen zitten ernaast',
     'Zet wekkers en timers: de SERVER telt af, dus ook met de app dicht gaat het alarm af',
     'Stopwatch met rondes en een wereldklok waar de zomertijd vanzelf klopt'],
    'Zeg het ook gewoon tegen Rahul: "maak me morgen om 7 uur wakker" is een aanroep, geen kunstje.'),
  '/apps/podium.html': G('RTG Podium: het eigen live-streamingkanaal (18+, met verificatie).',
    ['Kijk live streams van makers', 'Steun een maker met een cadeau via RTG Pay', 'Abonneer op wie je vaker wilt zien'],
    'Cadeaus zijn echt geld: de app vraagt altijd eerst een bevestiging.'),
  '/apps/camera.html': G('RTG Camera: foto\'s maken en nabewerken in de eigen studio.',
    ['Maak een foto met de zoeker', 'Bewerk in de studio: licht, kleur, kader', 'Bewaar of deel bewust'],
    'De beste bewerking is licht: probeer eerst de belichting voor je naar filters grijpt.'),
  '/apps/oog.html': G('RTG Eye: camera-visie op je toestel, voor voertuigschouw en werkvloerlog.',
    ['Scan een voertuig voor of na gebruik', 'Log hands-free wat je ziet', 'Deel het rapport met de zaak'],
    'Een schouw van één minuut vooraf voorkomt discussies achteraf; de foto\'s zijn je bewijs.'),
  '/apps/ov.html': G('RTG Vervoer: een rit boeken, het OV en de bedrijfspendel in één app met live GPS.',
    ['Boek een rit naar een RTG-zaak, halte of favoriete plek', 'Check in op bus, trein, metro of veerboot',
      'Reserveer je plek in de pendel van je werkgever'],
    'De prijs staat vast zodra je aanvraagt; wat je daarna ziet is dezelfde prijs.'),
  '/apps/dispatch.html': G('RTG Dispatch: het planscherm van een vervoerder, met de vloot en de openstaande ritten.',
    ['Zie wat er open staat en wat er onderweg is', 'Wijs toe met de hand of laat de motor voorstellen',
      'Voer een boeking in voor iemand zonder app'],
    'Kijk bij een voorstel altijd even naar de rekensom eronder: die vertelt waarom die wagen bovenaan staat.'),
  '/apps/ovdienst.html': G('De OV-dienst: het werkscherm van de chauffeur en de verkeersleiding.',
    ['Zie je dienst en je voertuig', 'Meld vertrek, halte en bijzonderheden', 'Houd contact met de meldkamer'],
    'Rustig rijden en eerlijk melden: de reiziger ziet live wat jij doorgeeft.'),
  '/apps/ovroutes.html': G('De OV-routetekenaar: lijnen en haltes op de kaart zetten.',
    ['Teken een lijn met haltes', 'Zet tijden en frequenties', 'Publiceer naar de reisapp'],
    'Teken eerst de haltes, dan de lijn; dat werkt sneller en preciezer.'),
  '/apps/flits.html': G('RTG Flits: het rustige rijscherm met meldingen van de community.',
    ['Zie flitsers, files en ongevallen op je route', 'Meld zelf met één tik of met je stem', 'De landregels bepalen wat getoond mag worden'],
    'Handen aan het stuur: alles kan met spraak, en de app houdt zelf zijn mond op het juiste moment.'),
  '/apps/navigatie.html': G('RTG Navigatie: het huiseigen navigatiesysteem in 3D, met alles wat wij kunnen.',
    ['Zoek een zaak, halte, loket of laadpaal en rijd erheen', 'Kies auto, EV, fiets, lopen of OV; de ETA past mee', 'Zet lagen aan (tank, laad, Flits) en meld zelf een wegprobleem'],
    'De kaart is helemaal van ons: geen Google, geen externe tegels. Sleep om rond te kijken, knijp om te zoomen.'),
  '/apps/horloge.html': G('Het RTG-horloge: het signatuurhorloge van het huis, een opengewerkt skelethorloge dat naast de lippen het symbool van RTG wordt.',
    ['Bekijk het levende 3D-uurwerk dat op de klok van je toestel loopt', 'Zie de drie scholen: de vorm (AP), de leesbaarheid (Rolex) en de techniek (Porsche)', 'Beweeg de muis om het relief te laten spelen (op een computer)'],
    'Alles klopt tot op de milliseconde: de balans op precies 4 Hz, 28.800 halveslagen per uur, foutmarge 0,0.'),
  '/apps/rtg.html': G('RTG - Het Huis: de website van het huis als een high-end magazine op een pagina; swipe zijwaarts om te bladeren.',
    ['Swipe (of gebruik de pijlen) om door de bladen te bladeren', 'Lees per blad een tak: de passen, reizen, care, leren, cultuur, De Salon, de foundation en partners', 'Op het slotblad spring je naar het 3D-uitzicht of terug naar het bureaublad'],
    'Een magazine als app: geen losse internetpagina\'s, alles in een pagina die je doorbladert, in de rustige huisstijl.'),
  '/apps/uitzicht.html': G('Het uitzicht van RTG: een stille 3D-skyline van het hele ecosysteem, in eigen huis getekend.',
    ['Kijk naar de langzaam draaiende stad; elk blok is een tak van het huis', 'Zie het gouden rasterlicht op de grond, hetzelfde als onder de navigatie', 'Rechtsboven loopt de analoge RTG-klok mee op de tijd van je toestel'],
    'Alles is eigen werk op een huiseigen WebGL-motor: geen three.js, geen stockbeeld, geen extern merk.'),
  '/apps/ghost.html': G('Ghost Driver: de voorspellende verkeers- en logistieksimulatie.',
    ['Bekijk de verwachte drukte per uur', 'Speel een scenario door voor je vloot', 'Deel het beeld met de verkeersleider'],
    'Plan je ritten om de voorspelde pieken heen; tien minuten schuiven scheelt vaak een half uur file.'),
  '/apps/vonk.html': G('RTG Vonk: kennismaken op wensen, met een reservering in het midden.',
    ['Vertel wat jij zoekt', 'Bij een wederzijdse like regelt de app een plek in het midden', 'De eerste ronde is geregeld; de rest is aan jullie'],
    'Wees eerlijk in je wensen; de match wordt er alleen maar beter van.'),
  '/apps/rtgschool.html': G('RTG School: je leerpaspoort dat een leven lang meegaat, met lessen, oefenen, examentraining en je eigen Rahul Bijles.',
    ['Schrijf je in op je fase van de officiele ladder; je paspoort telt elk behaald leerdoel mee', 'Kies een groep of fase, lees de les en oefen vijf opgaven; bij vier goed wordt het doel bijgeschreven', 'Train voor een examen (terugblik pas aan het eind) of vraag het niveau-advies; Rahul Bijles legt alles geduldig uit op jouw niveau'],
    'Alles hier is oefening en advies: over overgaan, toelating en echte examens beslissen mensen en de officiele instellingen. Geen scores buiten de sessie, geen ranglijsten; leren is geen wedstrijd.')
};
