/* App-gids data, deel8 (22 pagina's). Zie ../appgids.js voor de uitleg;
   nieuwe pagina's krijgen hier (of in het passende deel) een eigen entry. */
const G = (wat, doe, tip) => ({ wat, doe, tip });

module.exports = {
  '/apps/foundation/campus.html': G('RTF Campus: jouw school, leerpaspoort, Game Hall, Magnaat en Foundation-gereedschap in één veilige werkplek.',
    ['Bekijk bovenaan welke passen actief zijn', 'Open je klas, leerroute of project vanuit dezelfde Campus', 'Gebruik Alles om alleen functies te zien die bij jouw leeftijd passen'],
    'Je geboortedatum bepaalt automatisch je leeftijdspas; zonder geldige pas blijft de Campus gesloten.'),
  '/apps/foundation/leerpaspoort.html': G('Mijn leerpaspoort: een persoonlijke leerlijn met lessen, oefeningen, examentraining, doelen en Rahul Bijles.',
    ['Kies een fase die je leeftijdspas toestaat', 'Volg een les en oefen vijf vragen in je eigen tempo', 'Vraag uitleg of niveau-advies en bespreek echte keuzes met school en thuis'],
    'Dit paspoort helpt je groeien maar geeft geen officieel diploma of bindend schooladvies.'),
  '/apps/foundation/rust.html': G('Even rust: ademhalen en tot rust komen als het te veel wordt.',
    ['Adem mee met de cirkel', 'Kies een rustmoment dat bij je past', 'Kom terug wanneer je wilt'],
    'Drie keer diep ademen werkt echt; je lijf kalmeert je hoofd.'),
  '/apps/foundation/school.html': G('School: je rooster, huiswerk, cijfers en berichten van school.',
    ['Bekijk je rooster en huiswerk', 'Zie je cijfers zodra ze er zijn', 'Ziekmelden gaat via je ouders hier'],
    'Huiswerk meteen in de app zetten scheelt gedoe; je hoofd mag het dan vergeten.'),
  '/apps/foundation/schrift.html': G('Het schrift: live meeschrijven met de les.',
    ['Doe mee met wat de juf of meester deelt', 'Schrijf je eigen aantekeningen', 'Alles wordt vanzelf bewaard'],
    'In je eigen woorden opschrijven werkt beter dan overtypen; dan snapt je hoofd het echt.'),
  '/apps/foundation/schrijven.html': G('Schrijven: elke dag een leuke schrijfopdracht met een vriendelijke coach.',
    ['Pak de opdracht van vandaag', 'Schrijf; de coach leest mee als je wilt', 'Bewaar je mooiste stukken'],
    'De coach herschrijft nooit jouw tekst; jij blijft de schrijver, altijd.'),
  '/apps/foundation/steun.html': G('Steun voor jou: als het thuis of vanbinnen even zwaar is.',
    ['Lees dat je niet de enige bent', 'Zie wie je kunt bellen, ook anoniem', 'Praat met iemand die je vertrouwt'],
    'Je hoeft het niet alleen te dragen; er zijn mensen die niets liever doen dan luisteren.'),
  '/apps/foundation/studie.html': G('Verder leren: kiezen wat je na school wilt en hoe je daar komt.',
    ['Verken studies en beroepen', 'Kijk wat erbij past en wat het kost', 'Praat erover met je mentor of ouders'],
    'Kies met je nieuwsgierigheid, niet met je angst; je mag altijd nog bijsturen.'),
  '/apps/foundation/toetsen.html': G('De toetsplanner: rustig naar je toetsen toe werken.',
    ['Zet je toetsen erin', 'De planner verdeelt het leren voor je', 'Vink af wat je gedaan hebt'],
    'Beginnen is het moeilijkst; plan het eerste blokje extra klein, dan kom je vanzelf op gang.'),
  '/apps/foundation/veilig.html': G('Veilig thuis: wat te doen als thuis niet veilig voelt.',
    ['Lees wat je kunt doen, stap voor stap', 'Zie de nummers die je altijd mag bellen', 'Dit blijft tussen jou en de hulp'],
    'Bellen mag altijd, ook als je twijfelt of het "erg genoeg" is; dat mag de hulp beoordelen.'),
  '/apps/foundation/verjaardagen.html': G('Verjaardagen en wensen: nooit meer een verjaardag missen.',
    ['Zie wie er binnenkort jarig is', 'Bewaar cadeau-ideeën per persoon', 'Zet een herinnering voor het kaartje'],
    'Een kaartje op tijd is meer waard dan een cadeau te laat.'),
  '/apps/foundation/vrienden.html': G('Contacten: je vrienden, snaps en verhalen, veilig geregeld.',
    ['Stuur snaps en bekijk verhalen', 'Nieuwe vrienden keurt een grote goed', 'Blokkeer of meld wat niet oké is'],
    'Echte vrienden vragen nooit om geheimen voor je ouders; dat is een rood vlaggetje.'),
  '/apps/foundation/werk.html': G('Werk en vacatures: bijbanen en stages die bij jouw leeftijd passen.',
    ['Bekijk vacatures voor jouw leeftijd', 'Solliciteer met je cv uit de CV-maker', 'Volg je sollicitaties live'],
    'Een korte, eerlijke sollicitatie verslaat een lange opgepompte; wees gewoon jezelf.'),
  '/apps/foundation/klas.html': G('De klas-PDA: doe live mee met de les van je juf of meester, op je eigen scherm of de iPad.',
    ['Typ de klascode van het bord en je voornaam', 'Lees de uitleg en beantwoord de vragen zodra ze starten', 'Bekijk alleen hoeveel vragen jij goed hebt beantwoord'],
    'Er is geen snelheidsbonus en geen podium; leren is geen wedstrijd.'),
  '/apps/foundation/zakgeld.html': G('Zakgeld: jouw eigen potje, sparen en uitgeven leren.',
    ['Houd bij wat erin komt en eruit gaat', 'Zet een spaardoel', 'Kijk hoe ver je bent'],
    'Verdeel je zakgeld in potjes (sparen, uitgeven, geven); dan is kiezen ineens makkelijk.'),
  '/apps/stad.html': G('Mijn Stad: het burgerloket van jouw stad binnen RTG.',
    ['Bekijk wat er in je stad speelt', 'Regel je stadszaken digitaal', 'Meld iets aan de gemeente'],
    'Een goede melding heeft een foto en een plek; dan kan de buitendienst er direct mee aan de slag.'),
  '/apps/hardware-pda.html': G('De hardware-PDA: het Hardwarelab op locatie.',
    ['Bekijk ontwerpen en prototypes', 'Leg testresultaten vast', 'Meld wat de werkplaats moet weten'],
    'Een goed testverslag noemt ook wat er wél werkte.'),
  '/apps/payroll.html': G('RTG Payroll: het loonkantoor van de RTG-kantoren, plus de matchtafel.',
    ['Zie wie waar werkt, met het past-signaal op de weekuren', 'Draai de loonrun per zaak en periode; elke medewerker krijgt zijn loonstrook', 'Bekijk de matchtafel: vacatures met kandidaten en mensen met passende bedrijven'],
    'Alleen wie zichzelf "open voor werk" zet, staat op de matchtafel; de rest is voor werkgevers onvindbaar.'),
  '/apps/thuis.html': G('RTG Thuis: logeren bij leden, wereldwijd -- met alle premium functies gratis.',
    ['Zoek een huis op plaats en datums; superhosts en toppers staan bovenaan', 'Boek met 0% servicekosten; bij keyless krijg je een deurcode voor self check-in', 'Zet je eigen huis live als host: kortingen, borg, co-hosts en gratis AI-prijsadvies'],
    'Bij elke boeking krijg je automatisch alle reisregels van het land mee -- visum, verkeer, alarmnummer en meer.'),
  '/apps/zaakpay.html': G('RTG Pay voor de zaak: het saldo van de kas, innen, uitbetalen en tegoed klaarzetten.',
    ['Inn een bedrag met de betaalcode die het lid in zijn app toont',
      'Zet tegoed klaar voor personeel of een klant; het geld gaat meteen uit de kas en staat vast tot iemand het ophaalt',
      'Betaal het saldo uit naar de rekening van de zaak -- dat is een handeling van de manager'],
    'Een zaak laadt niet bij zoals een lid: is de kas te laag, dan gaat het gewoon niet door. En verlopen tegoed haalt u zelf terug; het vervalt nooit stilzwijgend aan RTG.'),
  '/apps/kassa.html': G('De Kassa: een kassa-app voor elke zaak, met een modus per sector.',
    ['Kies de modus die bij de zaak past (bakker, restaurant, discotheek, sportkantine, personeelskantine, groenteboer)', 'Tik artikelen op de bon; weeg-artikelen rekenen per kilo', 'Reken af met contant, een RTG Pay-code of parkeer de bon op een tafel'],
    'Een kassamodus is een werkvorm, geen keurslijf: wissel gerust als de avond anders loopt dan de ochtend.'),
  '/apps/horeca.html': G('RTG Horeca: de zaal en de keuken op een scherm.',
    ['Open een rekening op een tafel en zet de bestelling erop, met de allergie in een eigen veld',
      'Geef een gang vrij; pas dan verschijnt hij op het keukenscherm, met de gewenste serveertijd',
      'Bovenaan staat wat gasten vragen, met de minuten erbij: eerst "Ik ga", daarna "Gedaan"'],
    'De keuken begint pas als de zaal een gang vrijgeeft: zo bepaalt de zaal het tempo van het diner en de keuken dat van de bereiding.')
};
