/* Hospitality Missions: de chef houdt de beslissing, Rahul verdeelt en de
   bestaande PDA is het persoonlijke verlengstuk. Alleen ingeklokte mensen
   krijgen nieuwe opdrachten; lopend werk verhuist nooit stil. */
'use strict';

module.exports=({accounts,app,crypto,db,managerOnly,notifySupplier,save,schoon,sseToSupplier,supplierAuth})=>{
  function missies(code){db.data.horecaMissies=db.data.horecaMissies||{};return db.data.horecaMissies[code]=db.data.horecaMissies[code]||[]}
  function liveTeam(code){const open=(((db.data.klok||{})[code])||[]).filter(k=>k&&k.in&&!k.out),ids=new Set();return open.filter(k=>!ids.has(String(k.staffId))&&ids.add(String(k.staffId))).map(k=>{const st=accounts.getStaffById(Number(k.staffId));return{id:k.staffId,name:k.name||(st&&st.name)||'Medewerker',func:(st&&st.func)||'Service',sinds:k.in}})}
  function missiePubliek(m){return{id:m.id,titel:m.titel,detail:m.detail,sectie:m.sectie,prioriteit:m.prioriteit,minuten:m.minuten,status:m.status,voorId:m.voorId,voorNaam:m.voorNaam,reden:m.reden,gemaaktDoor:m.gemaaktDoor,at:m.at,gestartAt:m.gestartAt||null,klaarAt:m.klaarAt||null,hulp:m.hulp||null}}
  function voorstelVan(tekst){const q=String(tekst||'').trim(),l=q.toLowerCase();let sectie=/mise|snij|voorbereid|keuken|gerecht/.test(l)?'Keuken':/drank|drink|bar|cocktail/.test(l)?'Bar':/afwas|spoel/.test(l)?'Afwas':'Zaal',prioriteit=/direct|spoed|nu|allerg/.test(l)?'hoog':'normaal',minuten=/drank|drink/.test(l)?5:/controle|check/.test(l)?10:15;return{titel:q.slice(0,90),detail:'Door Rahul voorbereid uit de instructie van de chef. Bevestig eerst; daarna verschijnt de missie op de juiste PDA.',sectie,prioriteit,minuten}}
  function beste(team,sectie,lijst){const actief=new Map();lijst.filter(m=>m.status==='nieuw'||m.status==='bezig').forEach(m=>actief.set(String(m.voorId),(actief.get(String(m.voorId))||0)+1));const woorden={Keuken:/keuken|kok|chef|pas/i,Bar:/bar|barman|sommelier/i,Afwas:/afwas|spoel/i,Zaal:/zaal|bedien|host|service/i};return team.slice().sort((a,b)=>{const am=woorden[sectie]&&woorden[sectie].test(a.func)?-2:0,bm=woorden[sectie]&&woorden[sectie].test(b.func)?-2:0;return(am+(actief.get(String(a.id))||0))-(bm+(actief.get(String(b.id))||0))})[0]||null}

  app.post('/api/supplier/horeca/missions',supplierAuth,(req,res)=>{const team=liveTeam(req.supplier.code),lijst=missies(req.supplier.code),spatial=(((db.data.horeca||{})[req.supplier.code]||{}).spatial)||{};res.json({team,missies:lijst.slice(0,100).map(missiePubliek),manager:!!req.actor.manager,mijn:req.actor.staffId?lijst.filter(m=>String(m.voorId)===String(req.actor.staffId)&&m.status!=='klaar'&&m.status!=='geannuleerd').map(missiePubliek):[],overdrachten:req.actor.staffId?(spatial.overdrachten||[]).filter(o=>o.status==='wacht'&&String(o.naarId)===String(req.actor.staffId)).slice(0,10):[]})});
  app.post('/api/supplier/horeca/missions/voorstel',supplierAuth,(req,res)=>{if(!managerOnly(req,res))return;const tekst=schoon(req.body.tekst,300);if(!tekst)return res.status(400).json({error:'Vertel Rahul wat er op de vloer nodig is.'});const team=liveTeam(req.supplier.code),v=voorstelVan(tekst),kandidaat=beste(team,v.sectie,missies(req.supplier.code));res.json({voorstel:v,kandidaat,kanActiveren:!!kandidaat,uitleg:kandidaat?kandidaat.name+' is ingeklokt, past bij '+v.sectie.toLowerCase()+' en heeft nu de minste actieve missies.':'Er is nu niemand ingeklokt. Rahul bewaart geen schijntoewijzing.'})});
  app.post('/api/supplier/horeca/missions/activeer',supplierAuth,(req,res)=>{if(!managerOnly(req,res))return;const v=req.body.voorstel||{},team=liveTeam(req.supplier.code),lijst=missies(req.supplier.code),gekozen=req.body.voorId?team.find(x=>String(x.id)===String(req.body.voorId)):beste(team,String(v.sectie||'Zaal'),lijst);if(!gekozen)return res.status(409).json({error:'Niemand is ingeklokt. Klok eerst een medewerker in of houd dit voorstel vast.'});const m={id:crypto.randomBytes(5).toString('hex'),titel:schoon(v.titel,90),detail:schoon(v.detail,300),sectie:schoon(v.sectie,30)||'Zaal',prioriteit:v.prioriteit==='hoog'?'hoog':'normaal',minuten:Math.max(1,Math.min(180,Number(v.minuten)||15)),status:'nieuw',voorId:gekozen.id,voorNaam:gekozen.name,reden:schoon(req.body.reden,180),gemaaktDoor:req.actor.name,at:new Date().toISOString()};if(!m.titel)return res.status(400).json({error:'Het voorstel mist een taak.'});lijst.unshift(m);db.data.horecaMissies[req.supplier.code]=lijst.slice(0,1000);save();notifySupplier(req.supplier.code,{icon:'werk',title:'Nieuwe missie voor '+gekozen.name,body:m.titel});sseToSupplier(req.supplier.code,'sync',{scope:'horeca-missies'});res.json({ok:true,missie:missiePubliek(m)})});
  app.post('/api/supplier/horeca/missions/status',supplierAuth,(req,res)=>{if(!req.actor.staffId)return res.status(403).json({error:'Open dit op uw persoonlijke PDA.'});const m=missies(req.supplier.code).find(x=>x.id===String(req.body.id||''));if(!m||String(m.voorId)!==String(req.actor.staffId))return res.status(404).json({error:'Deze missie hoort niet bij uw dienst.'});const status=String(req.body.status||'');if(!['bezig','klaar','hulp'].includes(status))return res.status(400).json({error:'Onbekende stap.'});if(status==='hulp')m.hulp={tekst:schoon(req.body.tekst,180)||'Ik heb hulp nodig.',at:new Date().toISOString()};else{m.status=status;m.hulp=null;m[status==='klaar'?'klaarAt':'gestartAt']=new Date().toISOString()}save();sseToSupplier(req.supplier.code,'sync',{scope:'horeca-missies'});res.json({ok:true,missie:missiePubliek(m)})});
};
