/* De app-gids: voor elke app-pagina een korte, eerlijke uitleg (wat is dit,
   wat kun je hier, een leerzame tip). De gedeelde basis-laag (shared/basis.js)
   haalt dit op via /api/gids/app en toont het achter het ?-knopje; zo heeft
   elke app dezelfde rustige leerlaag zonder eigen teksten te onderhouden.
   Pure data + een opzoekfunctie; geen state, geen db. */

const G = (wat, doe, tip) => ({ wat, doe, tip });

const GIDS = {
  /* ---- het leden-OS en de leden-apps (RTG-toon: ingetogen, je/jij) ---- */
  '/apps/index.html': G('De verzamelplek van alle RTG-apps: elke ingang die bij jouw pas hoort staat hier.',
    ['Kies een app; je inlog reist automatisch mee', 'Installeer een app als eigen icoon via je browsermenu', 'Kom hier terug met de terug-knop in elke app'],
    'Elke app werkt ook los als eigen schermpje op je telefoon; installeren kost niets.'),
  '/apps/app.html': G('Jouw leden-app: reserveren, boeken, bestellen, chatten en betalen, alles op codenaam.',
    ['Open een genre en reserveer of boek direct', 'Vraag Rahul wat je maar wilt; hij regelt het met jouw inlog', 'Bekijk je codes, tickets en bestellingen onder je profiel'],
    'Je echte naam blijft in de kluis; partners zien alleen je codenaam. Dat is bewust ons ontwerp.'),
  '/apps/bureau.html': G('Het RTG OS-bureaublad: al je apps als iconen op een groot scherm.',
    ['Open apps in vensters naast elkaar', 'Sleep en schik zoals je wilt', 'Gebruik de klok en de menubalk zoals op een echte computer'],
    'Handig op een tablet of tweede scherm: alles van RTG op één werkblad.'),
  '/apps/berichten.html': G('Je berichten met vrienden en partners, automatisch vertaald als dat nodig is.',
    ['Stuur een bericht op codenaam', 'Bel of videobel vanuit het gesprek', 'Deel een snap of verhaal met wie jij kiest'],
    'Berichten in een andere taal worden voor je vertaald; jij leest en schrijft gewoon in je eigen taal.'),
  '/apps/pulse.html': G('Pulse: wat er nu speelt in jouw RTG-wereld, rustig gebundeld.',
    ['Lees de hoogtepunten van vandaag', 'Tik door naar de app waar iets gebeurt', 'Stel in waarover je seintjes wilt'],
    'Geen eindeloze feed: Pulse toont wat er is en houdt dan op. Dat is bewust.'),
  '/apps/nieuws.html': G('RTG Nieuws: de redactie bundelt wat voor leden telt.',
    ['Lees artikelen per rubriek', 'Bewaar wat je later wilt lezen', 'Reageer waar dat kan'],
    'Kwaliteit boven snelheid: liever één goed stuk dan tien snelle.'),
  '/apps/hotels.html': G('Verblijven: hotels, appartementen en villa\'s van onze partners, met ledenprijzen.',
    ['Bekijk kamers, foto\'s en vrije data', 'Boek direct; de partner bevestigt', 'Open je kamer met keyless waar dat kan'],
    'De ledenprijsgarantie geldt overal: nooit meer dan de publieke prijs van de partner zelf.'),
  '/apps/reisbureau.html': G('Het RTG-reisbureau: samengestelde reizen tegen de nettoprijs.',
    ['Blader door de reizen of vraag AI-reisadvies', 'Vraag een reis aan; een reisadviseur bevestigt', 'Volg en annuleer je aanvragen onder Mijn'],
    'Vertel je wens in gewone woorden; het advies wijst de best passende reis aan en legt uit waarom.'),
  '/apps/foodcourt.html': G('De Food Court: alle restaurants op een rij, reserveren in een paar tikken.',
    ['Kies een restaurant en bekijk de tijdsloten', 'Reserveer; de zaak beslist en je krijgt bericht', 'Bekijk keuken, prijs en ledenvoordeel per zaak'],
    'Reserveer ruim vooruit voor de populaire avonden; annuleren kan altijd netjes in de app.'),
  '/apps/uitgaan.html': G('Uitgaan: bars, clubs en beachclubs met hun avonden en gastenlijsten.',
    ['Bekijk de avonden per adres', 'Zet jezelf op de gastenlijst', 'Laat je entreecode zien aan de deur'],
    'Je leeftijdslaag bepaalt wat je ziet; dat is voor je eigen veiligheid en die van de zaak.'),
  '/apps/mall.html': G('De RTG Mall: de enige plek waar je bij RTG koopt, van eigen-merk tot boutieks, plus de bibliotheken.',
    ['Bestel eigen-merk en boerderijproducten direct', 'Blader door de App- en Reis-Bibliotheek; installeren is inbegrepen', 'Leg mode apart of laat een maat naar de paskamer brengen'],
    'De bibliotheken zijn een pas-voordeel: tienduizenden apps en een miljoen reisgidsen, zonder bijbetalen.'),
  '/apps/pay.html': G('RTG Pay: betalen en tikken tussen vrienden, veilig en direct.',
    ['Stuur of vraag een tik', 'Bekijk je saldo en geschiedenis', 'Splits een rekening met je gezelschap'],
    'Voor elke betaling zie je eerst een bevestiging; niets gaat er zonder jouw akkoord uit.'),
  '/apps/wbw.html': G('Wie betaalt wat: groepsuitgaven bijhouden met een live balans.',
    ['Maak een groep en zet uitgaven erin', 'Zie live wie wat voorschoot', 'Verreken in één keer via RTG Pay'],
    'Direct na de vakantie verrekenen voorkomt het eeuwige "dat komt nog wel".'),
  '/apps/bank.html': G('RTG Bank: je rekening, sparen en krediet in de vertrouwde RTG-stijl.',
    ['Bekijk je saldo en afschriften', 'Zet spaardoelen en volg ze', 'Vraag krediet aan; een mens beoordeelt'],
    'De AI adviseert, een mens beslist; zeker bij geld houden we die volgorde altijd aan.'),
  '/apps/balans.html': G('RTG Balans: je financiële overzicht en de boekhoudhulp.',
    ['Bekijk inkomsten en uitgaven per maand', 'Laat de AI-boekhouder meedenken', 'Exporteer voor je administratie'],
    'Tien minuten per week naar je balans kijken voorkomt de meeste geldverrassingen.'),
  '/apps/sport.html': G('RTG Sport: kampen, lessen en sportieve activiteiten van partners.',
    ['Bekijk het aanbod en de data', 'Meld je aan voor een kamp of les', 'Stel een vraag aan de organisatie'],
    'Begin klein: één vast uur per week houd je langer vol dan een groots plan.'),
  '/apps/spelen.html': G('Spelen: bordspellen en partyspellen met vrienden, live tegen elkaar.',
    ['Start een lobby en nodig vrienden uit', 'Kies een spel: van dammen tot Magnaat', 'Praat mee in de spelchat'],
    'Sommige spellen hebben een leeftijdspoort; dat regelt de app automatisch netjes voor je.'),
  '/apps/muziek.html': G('RTG Sound: muziek voor je dag, samengesteld zonder gejaag.',
    ['Kies een sfeer of kanaal', 'Speel af en bedien vanaf elk scherm', 'Bewaar wat je mooi vindt'],
    'Muziek zonder eindeloos scrollen: kies één sfeer en laat hem gewoon spelen.'),
  '/apps/theater.html': G('RTG Theater: de videobibliotheek op bioscoopniveau, tot 4K zonder hercompressie.',
    ['Kies een kanaal of titel', 'Kijk in de kwaliteit die je verbinding aankan', 'Reageer op titels waar dat open staat'],
    'Alles is vooraf goedgekeurd door het kantoor; daarom vind je hier geen ruis.'),
  '/apps/clips.html': G('RTG Clips: korte video\'s van leden; jouw clips blijven op jouw toestel.',
    ['Bekijk de eindige dagselectie', 'Maak zelf een clip; hij blijft lokaal bij jou', 'Deel bewust, niet automatisch'],
    'De selectie is bewust eindig: als hij op is, is hij op. Geen oneindige scroll.'),
  '/apps/podium.html': G('RTG Podium: het eigen live-streamingkanaal (18+, met verificatie).',
    ['Kijk live streams van makers', 'Steun een maker met een cadeau via RTG Pay', 'Abonneer op wie je vaker wilt zien'],
    'Cadeaus zijn echt geld: de app vraagt altijd eerst een bevestiging.'),
  '/apps/camera.html': G('RTG Camera: foto\'s maken en nabewerken in de eigen studio.',
    ['Maak een foto met de zoeker', 'Bewerk in de studio: licht, kleur, kader', 'Bewaar of deel bewust'],
    'De beste bewerking is licht: probeer eerst de belichting voor je naar filters grijpt.'),
  '/apps/oog.html': G('RTG Eye: camera-visie op je toestel, voor voertuigschouw en werkvloerlog.',
    ['Scan een voertuig voor of na gebruik', 'Log hands-free wat je ziet', 'Deel het rapport met de zaak'],
    'Een schouw van één minuut vooraf voorkomt discussies achteraf; de foto\'s zijn je bewijs.'),
  '/apps/ov.html': G('RTG OV: bus, trein, metro, veerboot en taxi in één reisapp met live GPS.',
    ['Plan een route van deur tot deur', 'Check in met je code of je pas', 'Volg je voertuig live op de kaart'],
    'Bij vertraging rekent de app automatisch een nieuwe route; even verversen is genoeg.'),
  '/apps/ovdienst.html': G('De OV-dienst: het werkscherm van de chauffeur en de verkeersleiding.',
    ['Zie je dienst en je voertuig', 'Meld vertrek, halte en bijzonderheden', 'Houd contact met de meldkamer'],
    'Rustig rijden en eerlijk melden: de reiziger ziet live wat jij doorgeeft.'),
  '/apps/ovroutes.html': G('De OV-routetekenaar: lijnen en haltes op de kaart zetten.',
    ['Teken een lijn met haltes', 'Zet tijden en frequenties', 'Publiceer naar de reisapp'],
    'Teken eerst de haltes, dan de lijn; dat werkt sneller en preciezer.'),
  '/apps/flits.html': G('RTG Flits: het rustige rijscherm met meldingen van de community.',
    ['Zie flitsers, files en ongevallen op je route', 'Meld zelf met één tik of met je stem', 'De landregels bepalen wat getoond mag worden'],
    'Handen aan het stuur: alles kan met spraak, en de app houdt zelf zijn mond op het juiste moment.'),
  '/apps/ghost.html': G('Ghost Driver: de voorspellende verkeers- en logistieksimulatie.',
    ['Bekijk de verwachte drukte per uur', 'Speel een scenario door voor je vloot', 'Deel het beeld met de verkeersleider'],
    'Plan je ritten om de voorspelde pieken heen; tien minuten schuiven scheelt vaak een half uur file.'),
  '/apps/vonk.html': G('RTG Vonk: kennismaken op wensen, met een reservering in het midden.',
    ['Vertel wat jij zoekt', 'Bij een wederzijdse like regelt de app een plek in het midden', 'De eerste ronde is geregeld; de rest is aan jullie'],
    'Wees eerlijk in je wensen; de match wordt er alleen maar beter van.'),
  '/apps/passkeys.html': G('Passkeys: inloggen met je vingerafdruk, gezicht of sleutel; geen wachtwoord meer.',
    ['Maak een passkey aan op dit toestel', 'Log voortaan in zonder wachtwoord', 'Beheer of verwijder je sleutels'],
    'Een passkey is niet te phishen: er valt niets over te typen of af te kijken.'),
  '/apps/vluchten.html': G('RTG Vluchten: je vluchten en de private aviation van partners.',
    ['Bekijk vluchten en beschikbaarheid', 'Vraag een boeking aan; de partner bevestigt', 'Volg je reis in de app'],
    'Boekingen zijn pas definitief na bevestiging; de app zegt dat ook eerlijk.'),
  '/apps/stad.html': G('Mijn Stad: het burgerloket van jouw stad binnen RTG.',
    ['Bekijk wat er in je stad speelt', 'Regel je stadszaken digitaal', 'Meld iets aan de gemeente'],
    'Een goede melding heeft een foto en een plek; dan kan de buitendienst er direct mee aan de slag.'),
  '/apps/home.html': G('De RTG Home Kit: alle elektronica van je huis op één plek, per kamer, met scènes die je met één tik start.',
    ['Bedien lampen, klimaat, gordijnen en audio per kamer', 'Laat Rahul een scène voorstellen (bijv. filmavond) en bewaar hem', 'Alles uit met één tik; sloten bedien je altijd zelf'],
    'De AI stelt scènes voor, jij beslist; en een deur van het slot halen blijft altijd jouw eigen losse tik. Dat is een vaste veiligheidsregel.'),
  '/apps/juridisch.html': G('Juridisch: de voorwaarden, privacyregels en jouw AVG-rechten, in gewone taal.',
    ['Lees de voorwaarden per onderwerp', 'Vraag je gegevens op of laat ze wissen', 'Bekijk wat partners wel en niet zien'],
    'Jouw echte naam staat in een aparte kluis; partners werken met je codenaam. Zo is het ontworpen.'),
  '/apps/scherm.html': G('Tweede scherm: spiegel je werkplek of maak er een extra werkplek van.',
    ['Koppel met de code op je hoofdscherm', 'Kies spiegelen of een eigen werkplek', 'Ontkoppel met één tik'],
    'Een tweede scherm naast de kassa scheelt loopwerk: orders links, afrekenen rechts.'),
  '/apps/office.html': G('RTG Office: tekstdocumenten en rekenbladen, automatisch bewaard.',
    ['Maak een document of rekenblad', 'Deel op codenaam met wie jij kiest', 'Exporteer wanneer je wilt'],
    'Alles wordt vanzelf bewaard terwijl je typt; je kunt niets kwijtraken.'),
  '/apps/doos.html': G('De Zaakdoos: het kastje dat je zaak lokaal draaiend houdt, ook zonder internet.',
    ['Bekijk de status van je doos', 'Beheer wifi, updates en stroomwacht op afstand', 'Speel het journaal na bij twijfel'],
    'Valt het internet uit, dan draait je zaak gewoon door; de doos synct later alles netjes bij.'),
  '/apps/techniek.html': G('De technische status: gezondheid, zekeringen en de AI-monteur.',
    ['Bekijk de gezondheid van alle onderdelen', 'Zet een zekering om bij problemen', 'Laat de AI een diagnose voorstellen'],
    'Groen wil je zien; wordt iets geel, kijk dan eerst naar de laatste wijziging.'),
  '/apps/attenties.html': G('Attenties: kleine gebaren op het juiste moment, verzorgd door uw Rechterhand.',
    ['Kies een gelegenheid en een attentie', 'Wij verzorgen inpakken en bezorgen', 'Volg de status discreet in de app'],
    'Een attentie op tijd is meer waard dan een groot gebaar te laat; de agenda helpt u herinneren.'),
  '/apps/cellier.html': G('Cellier: uw wijnkelder, bijgehouden en aangevuld met verstand.',
    ['Bekijk uw kelder en drinkvensters', 'Laat aanvullen op advies', 'Reserveer flessen voor een diner'],
    'Het drinkvenster zegt wanneer een fles op zijn mooist is; de kelder let er voor u op.'),
  '/apps/cercle.html': G('Cercle: uw besloten kring binnen de Salon.',
    ['Zie wat uw kring deelt', 'Nodig uit wie erbij hoort', 'Organiseer een besloten moment'],
    'Klein houden is de kracht van een kring; kwaliteit van gezelschap boven aantal.'),
  '/apps/entourage.html': G('Entourage: de mensen om u heen (chauffeur, oppas, staf) op één plek geregeld.',
    ['Zet afspraken met uw vaste mensen', 'Deel alleen wat zij nodig hebben', 'Betaal en verantwoord netjes via de app'],
    'Duidelijke afspraken maken vaste mensen beter; de app houdt ze voor beide kanten bij.'),
  '/apps/garderobe.html': G('Garde-robe: uw garderobe in beeld, met de styling van de boutieks.',
    ['Bekijk wat er hangt en wat er mist', 'Ontvang stylingvoorstellen van uw huizen', 'Laat een maat naar de paskamer brengen'],
    'Een garderobe die klopt is stiller dan een kast die vol is; wij letten op de gaten.'),
  '/apps/hangar.html': G('Hangar: uw voertuigen en vaartuigen, onderhoud en gereedheid.',
    ['Zie de staat van elk object', 'Plan onderhoud bij de juiste partner', 'Houd papieren en keuringen bij'],
    'Onderhoud op tijd is goedkoper dan reparatie te laat; de app herinnert u discreet.'),
  '/apps/lifestyle.html': G('De Rechterhand: uw Lifestyle Pass-app; wij regelen, u beslist.',
    ['Vraag wat u geregeld wilt hebben', 'Uw vaste concierge pakt het op', 'Volg alles rustig in één overzicht'],
    'U hoeft niet te zoeken; zeg wat u wilt en de Rechterhand komt met een voorstel.'),
  '/apps/logboek.html': G('Logboek: het stille verslag van wat er voor u geregeld is.',
    ['Blader door wat er gedaan is', 'Zoek op onderwerp of datum', 'Exporteer voor uw administratie'],
    'Eén plek waar alles staat; u hoeft niets te onthouden.'),
  '/apps/maison.html': G('Maison: uw huizen en hun huishouding, verzorgd op afstand.',
    ['Zie per huis wat er speelt', 'Plan staf, onderhoud en seizoensklaar maken', 'Open deuren op afstand waar dat kan'],
    'Een huis dat klaarstaat voelt u bij binnenkomst; dat is precies het werk dat u niet ziet.'),
  '/apps/mecenaat.html': G('Mecenaat: uw geven aan cultuur en goede doelen, goed geregeld.',
    ['Kies wat u wilt steunen', 'Wij regelen de afspraken en de verantwoording', 'Volg wat uw bijdrage doet'],
    'Gericht geven doet meer dan breed strooien; wij helpen u kiezen.'),
  '/apps/nalatenschap.html': G('Nalatenschap: uw wensen en documenten, ordelijk en vertrouwelijk.',
    ['Leg uw wensen vast', 'Bewaar documenten op één veilige plek', 'Deel alleen met wie u aanwijst'],
    'Nu een uur ordenen bespaart uw naasten later maanden zoeken.'),
  '/apps/reisboek.html': G('Reisboek: uw reizen, verleden en toekomst, in één verzorgd boek.',
    ['Bekijk komende reizen met alle details', 'Blader terug door waar u was', 'Deel een reis met uw gezelschap'],
    'Vóór vertrek één blik in het reisboek en u weet alles: tijden, adressen, codes.'),
  '/apps/rendezvous.html': G('Rendez-vous: afspraken op niveau, door ons voorbereid.',
    ['Vraag een afspraak of diner aan', 'Wij regelen plek, tijd en details', 'U verschijnt; de rest staat'],
    'Zeg wat het moment nodig heeft; wij kennen de adressen die erbij passen.'),
  '/apps/table.html': G('Table: uw vaste tafels en de avonden die ertoe doen.',
    ['Reserveer bij de huizen die u kent', 'Uw voorkeuren reizen mee', 'Laat de sommelier alvast kiezen'],
    'Een vaste tafel is een relatie: hoe vaker u komt, hoe beter men u kent.'),
  '/apps/concierge.html': G('Het concierge-bureau: hier werkt uw Rechterhand voor u.',
    ['Zie de aanvragen van uw leden', 'Pak op, regel en koppel terug', 'Houd het logboek bij'],
    'Terugkoppelen vóór het lid het vraagt: dat is het verschil tussen goed en uitstekend.'),
  '/apps/redactiekantoor.html': G('Het redactiekantoor: waar RTG Nieuws gemaakt wordt.',
    ['Schrijf, redigeer en plan artikelen', 'Beheer rubrieken en beeld', 'Publiceer na eindredactie'],
    'Check je feiten twee keer; snelheid wint nooit van kloppen.'),
  '/apps/leverancier.html': G('De leverancier-app: uw hele zaak in één scherm, van orders tot personeel.',
    ['Beheer orders, reserveringen en voorraad', 'Stuur uw team aan met rooster en taken', 'Vraag de zaak-AI om cijfers en advies'],
    'Kijk elke ochtend één minuut naar het actiecentrum; dan begint de dag zonder verrassingen.'),
  '/apps/personeel.html': G('De personeels-app (PDA): uw dienst, taken en team op zak.',
    ['Klok in en zie uw dienst', 'Pak taken op en meld ze af', 'Praat met collega\'s via chat of walkie-talkie'],
    'Meld afwijkingen meteen; een klein bericht nu voorkomt groot gedoe later.'),
  '/apps/backoffice.html': G('De RTG Backoffice: het kantoor dat leden en partners helpt.',
    ['Behandel verificaties en aanvragen', 'Zoek dwars door het systeem', 'Bekijk prestaties en weekcijfers'],
    'Het actiecentrum sorteert op urgentie: van boven naar beneden werken is genoeg.'),
  '/apps/kantoren.html': G('RTG Kantoren: alle afdelingen en de boardroom, met de zelfzorg van het systeem.',
    ['Loop de afdelingen langs met hun KPI\'s', 'Schakel in de boardroom wat aan of uit moet', 'Bekijk opruimen, beschermen, repareren en upgraden'],
    'De boardroom kan alles zien en alles schakelen; grote knoppen vragen om een tweede blik.'),
  '/apps/boardroom.html': G('De boardroom: het hoogste overzicht, alles zien en alles kunnen schakelen.',
    ['Bekijk het hele systeem in één oogopslag', 'Zet regie-schakelaars om', 'Laat Rahul voorstellen doen en beslis zelf'],
    'De AI adviseert, de boardroom beslist; die volgorde is een principe, geen toeval.'),
  '/apps/architect-pda.html': G('De architect-PDA: het architectenbureau op zak.',
    ['Bekijk projecten en hun fase', 'Leg bevindingen op locatie vast', 'Deel met het bureau'],
    'Foto\'s op locatie zeggen meer dan een pagina notities.'),
  '/apps/hardware-pda.html': G('De hardware-PDA: het Hardwarelab op locatie.',
    ['Bekijk ontwerpen en prototypes', 'Leg testresultaten vast', 'Meld wat de werkplaats moet weten'],
    'Een goed testverslag noemt ook wat er wél werkte.'),
  '/apps/studio-pda.html': G('De studio-PDA: automotive, marine en aviation op locatie.',
    ['Bekijk programma\'s en hun status', 'Leg schouwingen en metingen vast', 'Deel het lookbook met de klant'],
    'Meet twee keer, noteer één keer; de studio bouwt op jouw cijfers.'),
  '/apps/belastingkantoor.html': G('Het belastingkantoor: de inspecteurskant van de belastingtool.',
    ['Bekijk aangiften en aanslagen', 'Controleer en keur goed of af', 'Beantwoord vragen van ondernemers'],
    'Duidelijk uitleggen waarom iets niet klopt, scheelt drie brieven heen en weer.'),
  '/apps/rechtbank.html': G('De Rechtspraak (griffie): zaken, zittingen en uitspraken.',
    ['Beheer de rol en de zittingen', 'Verwerk stukken van partijen', 'Publiceer uitspraken'],
    'Een nette griffie is het halve vonnis: orde in de stukken, rust in de zaal.'),
  '/apps/gemeente.html': G('RTG Gemeente: het loket van de gemeente voor inwoners.',
    ['Regel documenten en aanvragen', 'Meld iets in de openbare ruimte', 'Volg de status van je zaak'],
    'Alles wat hier kan, hoeft niet meer aan een balie; en de status is altijd eerlijk.'),
  '/apps/gemeenteloket.html': G('Het gemeente-loket: de medewerkerskant van de gemeente.',
    ['Behandel aanvragen van inwoners', 'Zet zaken door naar de buitendienst', 'Koppel de status terug'],
    'De inwoner ziet letterlijk de status die jij zet; houd hem actueel.'),
  '/apps/gemeentepda.html': G('De gemeente-PDA: de buitendienst op straat.',
    ['Pak meldingen op in de wijk', 'Leg vast met foto en plek', 'Meld af als het klaar is'],
    'Een foto bij de afmelding maakt het loket en de melder allebei blij.'),
  '/apps/overheid.html': G('De Overheid: het landelijke loket (MijnOverheid) binnen de demo.',
    ['Bekijk je gegevens en berichten', 'Regel landelijke zaken digitaal', 'Machtig wie namens je mag handelen'],
    'Eén keer inloggen, alles op één plek; en jij bepaalt wie er namens jou iets mag.'),
  '/apps/overheidspda.html': G('De overheids-PDA: de ambtenaar in het veld.',
    ['Bekijk je werkvoorraad', 'Handel zaken op locatie af', 'Leg vast voor het dossier'],
    'Het dossier is het geheugen van de overheid; schrijf voor je opvolger.'),
  '/apps/rijksloket.html': G('Het Rijks-loket: de ambtenarenkant van de landelijke overheid.',
    ['Behandel aanvragen en berichten', 'Werk dossiers bij', 'Koppel besluiten netjes terug'],
    'Een besluit in gewone taal is ook een besluit; liever begrijpelijk dan deftig.'),
  '/apps/luchthaven.html': G('RTG Airport operations: de luchthaven draaiend houden.',
    ['Volg vluchten, gates en bagage', 'Stuur teams aan op piekmomenten', 'Schakel bij verstoring via het draaiboek'],
    'Bij verstoring eerst het draaiboek, dan improviseren; die volgorde redt de dag.'),
  '/apps/marechaussee.html': G('De Brigade RTG Airport: toezicht en grenscontrole in de demo.',
    ['Bekijk de posten en de planning', 'Registreer controles', 'Schakel met de meldkamer'],
    'Rustig en voorspelbaar werken houdt de rij kort en de sfeer goed.'),
  '/apps/meldkamer.html': G('De RTG Meldkamer: alle hulpdiensten op één scherm.',
    ['Neem meldingen aan en zet eenheden in', 'Volg het gezamenlijke rampbeeld', 'Schaal op en af volgens de keten'],
    'De AI-coördinator stelt voor, de centralist beslist; zo blijft de mens aan het stuur.'),
  '/apps/defensie.html': G('RTG Defensie: logistiek, paraatheid, onderhoud en oefeningen.',
    ['Bekijk paraatheid en materieel', 'Plan verplaatsingen en oefeningen', 'Volg de veldhospitaal-keten'],
    'Paraatheid is onderhoud plus oefening; beide staan hier eerlijk in beeld.'),
  '/apps/sportclub.html': G('FC RTG, het clubkantoor: teams, wedstrijden en vrijwilligers.',
    ['Beheer teams en opstellingen', 'Plan wedstrijden en trainingen', 'Regel de kantine en de vrijwilligers'],
    'Een club draait op vrijwilligers: een bedankje in de app doet wonderen.'),
  '/apps/kantoorpda.html': G('De Kantoor-PDA is verhuisd naar de personeels-app.',
    ['Open de personeels-app', 'Kies daar je kantoorfunctie'],
    'Eén app voor al het personeelswerk: dat is makkelijker dan vijf losse.'),
  '/apps/zorgbalie.html': G('De Zorgbalie is verhuisd naar de personeels-app.',
    ['Open de personeels-app', 'Kies daar de medische receptie'],
    'Eén app voor al het personeelswerk: dat is makkelijker dan vijf losse.'),
  '/apps/lesmaker.html': G('De Lesmaker: maak met AI in een paar tikken complete lesstof, uit elk onderwerp of een app uit de bibliotheken.',
    ['Kies een onderwerp en het niveau; de AI schrijft de les met quiz', 'Deel de klascode; de kinderen doen live mee op hun eigen scherm', 'Start elke vraag zelf en volg de klas op het bord'],
    'De AI maakt de stof, u houdt de regie: u bepaalt wat er start en wanneer. Fouten van kinderen zijn leerpunten, geen afrekenmoment.'),
  '/apps/stadsdoos.html': G('De Stadsdoos veld-app: de gemeente-doos op locatie beheren.',
    ['Bekijk de status van de stadsdoos', 'Voer ter plekke controles uit', 'Meld bevindingen aan het loket'],
    'Een doos die je regelmatig naloopt, valt zelden onverwacht uit.'),
  '/apps/juridisch/voorwaarden.html': G('De ledenvoorwaarden van RTG, in gewone taal per hoofdstuk.',
    ['Lees per onderwerp wat er geldt', 'Zoek het hoofdstuk dat je nodig hebt', 'Vragen? Stel ze via de app'],
    'Wij schrijven voorwaarden om gelezen te worden; staat er iets onduidelijks, dan horen we het graag.'),
  '/apps/juridisch/privacy.html': G('De privacyverklaring: wat we bewaren, waarom, en wat jouw rechten zijn.',
    ['Lees wat er met je gegevens gebeurt', 'Bekijk je AVG-rechten (inzage, wissen)', 'Zie hoe de codenaam-kluis werkt'],
    'Partners zien alleen je codenaam; je echte naam blijft in de gescheiden kluis. Dat is de kern van ons ontwerp.'),
  '/apps/juridisch/partnervoorwaarden.html': G('De partnervoorwaarden: de afspraken tussen RTG en de aangesloten zaken.',
    ['Lees de afspraken per hoofdstuk', 'Bekijk het platformmodel en de betaling', 'Vragen? Het kantoor helpt'],
    'De ledenprijsgarantie staat hier zwart op wit: een lid betaalt nooit meer dan de publieke prijs.'),

  /* ---- de RTFoundation-apps (kindvriendelijk: warm, je/jij) ---- */
  '/apps/foundation/index.html': G('Dit is jullie RTFoundation-app: alle hulp en leuke dingen voor het gezin op één plek.',
    ['Kies een tegel die bij je past', 'Vraag een grote mee als iets moeilijk is', 'Alles hier is gratis en veilig'],
    'Alles in deze app is er om je te helpen; er zit nooit een rekening of reclame achter.'),
  '/apps/foundation/agenda.html': G('De gezinsagenda: wat er deze week gebeurt, voor iedereen te zien.',
    ['Zet er iets in dat je niet wilt vergeten', 'Kijk wat er vandaag en morgen is', 'Zet een herinnering voor jezelf'],
    'Elke avond even kijken wat er morgen is; dan begint je dag rustig.'),
  '/apps/foundation/babyboek.html': G('Het fotoboekje: de mooiste momenten van de kleintjes, veilig bij het gezin.',
    ['Zet er een foto en een verhaaltje in', 'Blader terug door de momenten', 'Alleen jullie gezin kan erbij'],
    'Schrijf er een zinnetje bij; over tien jaar is dat zinnetje goud waard.'),
  '/apps/foundation/beheer.html': G('Gezin beheren: hier regelen de groten de profielen en de veiligheid.',
    ['Maak profielen voor het gezin', 'Zet de juiste leeftijdsgroep per kind', 'Beheer de gezinscode'],
    'De leeftijdsgroep bepaalt wat een kind ziet; goed instellen is het halve werk.'),
  '/apps/foundation/bieb.html': G('De App-Bibliotheek: twintigduizend goede apps, allemaal gratis voor jullie.',
    ['Zoek een app of blader per soort', 'Installeer met één tik', 'Bekijk je eigen apps bij Mijn'],
    'Alles is hier echt gratis: geen aankopen, geen reclame, geen trucjes.'),
  '/apps/foundation/schoolbieb.html': G('De School-Bibliotheek: tienduizend school-apps voor jouw leeftijd.',
    ['Kies je niveau en je vak', 'Installeer wat je helpt bij school', 'Leer op jouw tempo'],
    'Elke dag een kwartiertje oefenen werkt beter dan één keer heel lang.'),
  '/apps/foundation/beroepen.html': G('De Beroepen-Bibliotheek: twee miljoen gratis leer-apps over echte beroepen, van lasser tot ondernemer.',
    ['Kies een wereld: technisch & agrarisch, of het bedrijfsleven', 'Zoek een beroep en begin bij het leerpad op jouw niveau', 'Installeer wat je helpt; alles is gratis'],
    'Een vak leren is goud waard: met je handen of met je hoofd, allebei is even knap.'),
  '/apps/foundation/bord.html': G('Het bord: jullie gezinsbord met briefjes en plannen.',
    ['Hang er een briefje op', 'Schuif kaartjes naar klaar', 'Kijk wat de anderen erop zetten'],
    'Een briefje op het bord is nooit zeuren; zo weet iedereen het gewoon.'),
  '/apps/foundation/contact.html': G('Contact: praten met je gezin en je vrienden, veilig en vertaald als het moet.',
    ['Stuur een berichtje', 'Bel of videobel', 'Nieuwe vrienden keurt een grote eerst goed'],
    'Twijfel je over een bericht van iemand? Laat het een grote zien; dat is nooit klikken.'),
  '/apps/foundation/cv.html': G('De CV-maker: maak stap voor stap een net cv voor je bijbaan of stage.',
    ['Vul de stappen in; je ziet je cv meteen', 'Alles wordt op je toestel bewaard', 'Klaar? Download of deel hem'],
    'Schrijf op wat je écht gedaan hebt, ook klusjes en hobby\'s; dat is meer waard dan dure woorden.'),
  '/apps/foundation/dromen.html': G('Onze dromen: wat jullie gezin later wil; samen sparen en plannen.',
    ['Zet een droom erbij', 'Kijk hoe ver jullie zijn', 'Vier de kleine stappen'],
    'Een grote droom wordt haalbaar als je hem in stapjes knipt.'),
  '/apps/foundation/geld.html': G('Het geldmaatje: leren omgaan met geld, op jouw niveau.',
    ['Doe de leerstukjes over geld', 'Oefen met sparen en kiezen', 'Vraag als iets niet klopt'],
    'Eerst sparen, dan kopen: wie dat jong leert, heeft er zijn leven lang plezier van.'),
  '/apps/foundation/gezondheid.html': G('Het gezondheidsmaatje: goed voor jezelf zorgen, zonder gedoe.',
    ['Bekijk tips over slapen, eten en bewegen', 'Houd bij hoe je je voelt', 'Vraag hulp als het nodig is'],
    'Goed slapen is de beste superkracht die er is; echt waar.'),
  '/apps/foundation/hulpwijzer.html': G('De hulpwijzer: waar je terecht kunt als je ergens mee zit.',
    ['Zoek op waar je hulp bij wilt', 'Zie wie je kunt bellen of schrijven', 'Alles is vertrouwelijk'],
    'Hulp vragen is dapper, niet zwak; de eerste stap is de moeilijkste en die kun jij.'),
  '/apps/foundation/keuken.html': G('De gezinskeuken: samen koken, boodschappen en weekmenu\'s.',
    ['Kies recepten voor de week', 'Maak samen het boodschappenlijstje', 'Kook met de stap-voor-stap-hulp'],
    'Wie helpt koken, eet lekkerder; proef onderweg en je leert vanzelf.'),
  '/apps/foundation/klusjes.html': G('Klusjes en sterren: helpen in huis en er iets voor terugzien.',
    ['Kies een klusje van de lijst', 'Klaar? Zet hem af en verdien sterren', 'Spaar je sterren voor iets leuks'],
    'Elke dag een klein klusje voelt licht; alles op zaterdag voelt zwaar.'),
  '/apps/foundation/kompas.html': G('Het kompas: nadenken over wie je bent en wat je wilt, met een maatje dat meedenkt.',
    ['Doe de denkstukjes op jouw tempo', 'Schrijf op wat je ontdekt', 'Deel alleen wat jij wilt delen'],
    'Er is geen goed of fout antwoord over wie jij bent; nadenken zelf is het punt.'),
  '/apps/foundation/leren.html': G('Leren: overhoren, duellen, samen aan projecten en beter schrijven.',
    ['Kies wat je wilt oefenen', 'Daag een vriend uit voor een duel', 'Laat de schrijfcoach meelezen'],
    'Fouten maken is gewoon oefenen; wie nooit een fout maakt, oefent te makkelijk.'),
  '/apps/foundation/markt.html': G('Koopje: de gezinsmarkt voor tweedehands en delen.',
    ['Zet iets erop dat weg mag', 'Zoek iets dat jullie nodig hebben', 'Ruil of geef door in de buurt'],
    'Wat jij niet meer gebruikt, maakt een ander blij; doorgeven is twee keer winst.'),
  '/apps/foundation/ochtend.html': G('Het ochtendritme: rustig opstaan met een vast lijstje.',
    ['Zet jullie ochtendstappen op volgorde', 'Vink af wat klaar is', 'Zie in één blik of iedereen op schema ligt'],
    'Een vast ritme maakt de ochtend rustig; je hoofd hoeft niet meer na te denken.'),
  '/apps/foundation/oppasinfo.html': G('Belangrijke info: alles wat een oppas of invaller moet weten.',
    ['Zet de belangrijke dingen erin (allergieën, bedtijd, nummers)', 'Deel met de oppas van vanavond', 'Haal de toegang daarna weer weg'],
    'Wat op papier bij de koelkast hing, staat nu veilig hier; en je kunt het weer intrekken.'),
  '/apps/foundation/opvoeden.html': G('Opvoedhulp: steun voor ouders, zonder oordeel.',
    ['Lees per leeftijd wat helpt', 'Bekijk hoe andere ouders het doen', 'Vraag hulp als het zwaar wordt'],
    'Niemand voedt perfect op; goed genoeg is echt goed genoeg.'),
  '/apps/foundation/overhoren.html': G('Overhoren: woordjes en begrippen erin krijgen, op de slimme manier.',
    ['Maak of kies een lijst', 'Laat je overhoren; fouten komen vaker terug', 'Speel een duel met een vriend'],
    'Tien minuten per dag verslaat twee uur op de avond ervoor; je hoofd houdt van herhalen.'),
  '/apps/foundation/pesten.html': G('Sterker dan pesten: wat je kunt doen als jij of een ander gepest wordt.',
    ['Lees wat je kunt zeggen en doen', 'Bewaar bewijs van online pesten', 'Praat met een grote die je vertrouwt'],
    'Pesten is nooit jouw schuld; erover praten is de sterkste zet die er is.'),
  '/apps/foundation/privacy.html': G('Privacy en veiligheid: wat van jou is, blijft van jou.',
    ['Leer wat je beter niet deelt', 'Check je instellingen samen met een grote', 'Meld het als iets niet klopt'],
    'Een foto die weg is, is nooit echt weg; denk drie tellen na voor je deelt.'),
  '/apps/foundation/projecten.html': G('Samen aan een project: met je gezin of vrienden iets moois maken.',
    ['Start een project en nodig uit', 'Verdeel de taken', 'Vier het als het af is'],
    'Een project af maken leert je meer dan tien beginnen; klein beginnen mag.'),
  '/apps/foundation/reis.html': G('Op reis: alles voor een gezinsreis, van paklijst tot spelletjes onderweg.',
    ['Maak samen de paklijst', 'Bekijk tips voor onderweg', 'Speel de reisspelletjes in de auto'],
    'Wie zijn eigen tas inpakt, vergeet minder én sjouwt bewuster.'),
  '/apps/foundation/rust.html': G('Even rust: ademhalen en tot rust komen als het te veel wordt.',
    ['Adem mee met de cirkel', 'Kies een rustmoment dat bij je past', 'Kom terug wanneer je wilt'],
    'Drie keer diep ademen werkt echt; je lijf kalmeert je hoofd.'),
  '/apps/foundation/school.html': G('School: je rooster, huiswerk, cijfers en berichten van school.',
    ['Bekijk je rooster en huiswerk', 'Zie je cijfers zodra ze er zijn', 'Ziekmelden gaat via je ouders hier'],
    'Huiswerk meteen in de app zetten scheelt gedoe; je hoofd mag het dan vergeten.'),
  '/apps/foundation/schrift.html': G('Het schrift: live meeschrijven met de les.',
    ['Doe mee met wat de juf of meester deelt', 'Schrijf je eigen aantekeningen', 'Alles wordt vanzelf bewaard'],
    'In je eigen woorden opschrijven werkt beter dan overtypen; dan snapt je hoofd het echt.'),
  '/apps/foundation/schrijven.html': G('Schrijven: elke dag een leuke schrijfopdracht met een vriendelijke coach.',
    ['Pak de opdracht van vandaag', 'Schrijf; de coach leest mee als je wilt', 'Bewaar je mooiste stukken'],
    'De coach herschrijft nooit jouw tekst; jij blijft de schrijver, altijd.'),
  '/apps/foundation/steun.html': G('Steun voor jou: als het thuis of vanbinnen even zwaar is.',
    ['Lees dat je niet de enige bent', 'Zie wie je kunt bellen, ook anoniem', 'Praat met iemand die je vertrouwt'],
    'Je hoeft het niet alleen te dragen; er zijn mensen die niets liever doen dan luisteren.'),
  '/apps/foundation/studie.html': G('Verder leren: kiezen wat je na school wilt en hoe je daar komt.',
    ['Verken studies en beroepen', 'Kijk wat erbij past en wat het kost', 'Praat erover met je mentor of ouders'],
    'Kies met je nieuwsgierigheid, niet met je angst; je mag altijd nog bijsturen.'),
  '/apps/foundation/toetsen.html': G('De toetsplanner: rustig naar je toetsen toe werken.',
    ['Zet je toetsen erin', 'De planner verdeelt het leren voor je', 'Vink af wat je gedaan hebt'],
    'Beginnen is het moeilijkst; plan het eerste blokje extra klein, dan kom je vanzelf op gang.'),
  '/apps/foundation/veilig.html': G('Veilig thuis: wat te doen als thuis niet veilig voelt.',
    ['Lees wat je kunt doen, stap voor stap', 'Zie de nummers die je altijd mag bellen', 'Dit blijft tussen jou en de hulp'],
    'Bellen mag altijd, ook als je twijfelt of het "erg genoeg" is; dat mag de hulp beoordelen.'),
  '/apps/foundation/verjaardagen.html': G('Verjaardagen en wensen: nooit meer een verjaardag missen.',
    ['Zie wie er binnenkort jarig is', 'Bewaar cadeau-ideeën per persoon', 'Zet een herinnering voor het kaartje'],
    'Een kaartje op tijd is meer waard dan een cadeau te laat.'),
  '/apps/foundation/vrienden.html': G('Contacten: je vrienden, snaps en verhalen, veilig geregeld.',
    ['Stuur snaps en bekijk verhalen', 'Nieuwe vrienden keurt een grote goed', 'Blokkeer of meld wat niet oké is'],
    'Echte vrienden vragen nooit om geheimen voor je ouders; dat is een rood vlaggetje.'),
  '/apps/foundation/werk.html': G('Werk en vacatures: bijbanen en stages die bij jouw leeftijd passen.',
    ['Bekijk vacatures voor jouw leeftijd', 'Solliciteer met je cv uit de CV-maker', 'Volg je sollicitaties live'],
    'Een korte, eerlijke sollicitatie verslaat een lange opgepompte; wees gewoon jezelf.'),
  '/apps/foundation/klas.html': G('De klas-PDA: doe live mee met de les van je juf of meester, op je eigen scherm of de iPad.',
    ['Typ de klascode van het bord en je voornaam', 'Lees de uitleg en beantwoord de vragen zodra ze starten', 'Zie je score en aan het einde het podium'],
    'Snel antwoorden geeft een klein beetje extra punten, maar goed nadenken levert het meest op.'),
  '/apps/foundation/zakgeld.html': G('Zakgeld: jouw eigen potje, sparen en uitgeven leren.',
    ['Houd bij wat erin komt en eruit gaat', 'Zet een spaardoel', 'Kijk hoe ver je bent'],
    'Verdeel je zakgeld in potjes (sparen, uitgeven, geven); dan is kiezen ineens makkelijk.')
};

// de terugvaluitleg: ook een onbekende of nieuwe pagina krijgt nette hulp
const FALLBACK_RTG = G('Een RTG-app: onderdeel van jouw ledenomgeving.',
  ['Kijk rustig rond; alles legt zichzelf uit', 'Vraag Rahul als je iets zoekt', 'Terug naar alle apps kan altijd linksboven'],
  'Elke RTG-app werkt hetzelfde: rustig, veilig en zonder trucjes.');
const FALLBACK_RTF = G('Een RTFoundation-app: gratis hulp voor jullie gezin.',
  ['Kijk rustig rond', 'Vraag een grote mee als iets moeilijk is', 'Terug naar alle hulp kan altijd bovenaan'],
  'Alles in de RTFoundation is gratis en veilig; er zit nooit een addertje onder.');

function gidsVan(pad) {
  const p = String(pad || '').split('?')[0].split('#')[0].slice(0, 120);
  const entry = GIDS[p];
  const wereld = p.startsWith('/apps/foundation/') ? 'rtf' : 'rtg';
  if (entry) return { pad: p, wereld, ...entry };
  if (!/^\/apps\//.test(p)) return null;
  return { pad: p, wereld, algemeen: true, ...(wereld === 'rtf' ? FALLBACK_RTF : FALLBACK_RTG) };
}

module.exports = { gidsVan, GIDS, TOTAAL: Object.keys(GIDS).length };
