/* RTG Boeken (data): de huisbibliotheek -- korte klassiekers in eigen
   navertelling (publiek domein van oorsprong, de tekst is een huisuitgave
   van RTG). Pure data, geen logica. Elke titel is bewust kort: dit is de
   startplank; eigen tekstbestanden uit de kluis komen ernaast. */
module.exports = [
  { id: 'haas', titel: 'De haas en de schildpad', auteur: 'naar Aesopus', jaar: 'huisuitgave',
    over: 'Waarom gestaag winnen kan van snel.',
    tekst: 'Een haas lachte een schildpad uit om haar trage poten. "Loop een wedstrijd met me," zei de schildpad rustig, "dan zien we wie er wint." De haas schoot weg en was al snel zo ver voor dat hij besloot even te gaan liggen in het gras. De zon was warm, de wind was zacht, en de haas viel in slaap.\n\nDe schildpad liep door. Stap voor stap, zonder haast en zonder pauze. Ze passeerde de slapende haas en liep verder, de heuvel over, tot aan de streep.\n\nToen de haas wakker schrok en er alles aan deed om nog te winnen, stond de schildpad al bij de finish. "Snel zijn is mooi," zei ze, "maar doorgaan is beter."\n\nWie gestaag doorgaat, komt verder dan wie hard begint en halverwege stopt.' },
  { id: 'krekel', titel: 'De krekel en de mier', auteur: 'naar Aesopus', jaar: 'huisuitgave',
    over: 'Over vooruitdenken, en over mild zijn.',
    tekst: 'De hele zomer zong de krekel in het hoge gras. De mier sjouwde ondertussen graankorrels naar haar nest, de een na de ander. "Kom toch zingen," riep de krekel. "De zomer is er om van te genieten!" De mier knikte vriendelijk en sjouwde door.\n\nToen de winter kwam, had de krekel niets. Koud en hongerig klopte hij bij de mier aan. "Ik heb gezongen, de hele zomer," zei hij zacht. "Dan heb je vast mooi gezongen," zei de mier -- en ze schoof een deel van haar voorraad naar hem toe. "Volgende zomer sjouw jij een uurtje mee, en zing je daarna voor ons allebei."\n\nVooruitdenken houdt je warm in de winter. En wie kan delen, heeft het meeste voorraad.' },
  { id: 'leeuw', titel: 'De leeuw en de muis', auteur: 'naar Aesopus', jaar: 'huisuitgave',
    over: 'Klein kan groot redden.',
    tekst: 'Een muis rende per ongeluk over de neus van een slapende leeuw. De leeuw sloeg zijn klauw over haar heen. "Laat me gaan," piepte de muis, "en ooit help ik jou." De leeuw moest lachen om zoiets kleins dat zoiets groots beloofde, maar hij liet haar gaan.\n\nNiet lang daarna raakte de leeuw verstrikt in het net van jagers. Hij brulde tot het bos ervan trilde, maar het touw gaf niet mee. Toen kwam de muis. Ze knaagde het net door, draad voor draad, tot de leeuw vrij was.\n\n"Je lachte om mijn belofte," zei de muis. "Nooit meer," zei de leeuw.\n\nNiemand is te klein om groot te zijn voor een ander.' },
  { id: 'wind', titel: 'De wind en de zon', auteur: 'naar Aesopus', jaar: 'huisuitgave',
    over: 'Warmte wint van kracht.',
    tekst: 'De wind en de zon kregen ruzie over wie de sterkste was. "Zie je die reiziger met zijn mantel?" zei de zon. "Wie hem zijn mantel af krijgt, is de sterkste."\n\nDe wind begon te blazen, harder en harder. Maar hoe harder hij blies, hoe steviger de reiziger zijn mantel om zich heen trok. De wind gaf het hijgend op.\n\nToen scheen de zon. Rustig en warm. De reiziger deed zijn kraag los, toen een knoop, en even later legde hij zijn mantel over zijn arm en liep fluitend verder.\n\n"Zo," zei de zon. "Wat kracht niet lukt, lukt warmte vaak wel."' },
  { id: 'sterren', titel: 'Het meisje en de sterren', auteur: 'huisvertelling', jaar: 'huisuitgave',
    over: 'Een avondverhaal over klein beginnen.',
    tekst: 'Er was eens een meisje dat de sterren wilde tellen. "Dat zijn er te veel," zei iedereen. "Begin er niet aan."\n\nMaar het meisje ging elke avond op het dak zitten en telde er tien. Niet meer. Tien sterren, elke avond, en ze schreef ze op in een schriftje: waar ze stonden, hoe fel ze waren, en welke knipoogde.\n\nNa een jaar kende ze de hemel boven haar huis beter dan wie ook in het dorp. Schippers kwamen haar de weg vragen. Geleerden kwamen haar schriftje lezen. "Hoe heb je dat gedaan?" vroegen ze. "Alle sterren!"\n\n"Niet alle," zei het meisje. "Tien per avond. Maar wel elke avond."' },
  { id: 'brug', titel: 'De twee broers en de brug', auteur: 'huisvertelling', jaar: 'huisuitgave',
    over: 'Over ruzie, en wat je er tegenover kunt bouwen.',
    tekst: 'Twee broers hadden ruzie gekregen -- waarover wist eigenlijk niemand meer, zijzelf ook niet. Tussen hun boerderijen liep een beek, en de oudste broer huurde een timmerman in. "Bouw een hek langs die beek," zei hij. "Hoog. Ik wil hem niet meer zien."\n\nDe timmerman werkte een week. Toen de oudste broer kwam kijken, stond er geen hek. Er stond een brug.\n\nOp het midden van de brug stond zijn jongere broer, met zijn hand al uitgestoken. "Dat je dit bouwt," zei hij, "na alles wat ik heb gezegd." En de oudste liep de brug op en pakte de hand.\n\nDe timmerman pakte zijn kist. "Blijf nog," vroegen de broers, "we hebben meer te bouwen." "Dat geloof ik graag," zei de timmerman, "maar er zijn meer bruggen nodig."' }
];
