/* De ECHTE, leesbare kern van de Geloof & Wijsheid-Bibliotheek. Geen miljoen
   lege titels meer: elk item hieronder heeft een echte, leesbare tekst die je
   kunt openen en lezen. Alle tradities staan als gelijken naast elkaar -- de
   bibliotheek kiest nooit partij, bekeert nooit en oordeelt nooit.

   De teksten zijn eigen, respectvolle inleidingen en reflecties van de
   RTFoundation op een thema binnen een traditie. Ze vervangen geen heilige
   bronnen; ze nodigen uit om verder te lezen. Een kern om mee te beginnen, en
   uit te breiden -- kwaliteit boven aantal.

   doelgroep: mini (0-5), kind (6-11), tiener (12+), gezin (allen). De
   leeftijdspoort in kern/geloofbieb.js gebruikt deze waarde. */

// [traditie, traditieLabel, thema, doelgroep, titel, tekst]
const K = [
  ['christendom', 'Christendom', 'Naastenliefde', 'gezin', 'De barmhartige Samaritaan',
    'Een man ligt gewond langs de weg. Voorbijgangers die je een vroom leven zou toedichten, lopen door. Uitgerekend een vreemdeling, iemand uit een groep die men wantrouwde, stopt, verzorgt de wonden en betaalt voor onderdak. Als de vraag klinkt "wie is mijn naaste?", draait het antwoord de vraag om: je naaste is niet wie het dichtst bij je staat, maar wie jij nabij durft te komen.\n\nHet verhaal is eeuwenoud en toch ongemakkelijk actueel. Het meet geloof niet af aan wat je zegt te geloven, maar aan of je stopt wanneer stoppen ongelegen komt. Dat is de kern die het christendom hier deelt met zoveel andere tradities: liefde is een werkwoord.'],
  ['katholicisme', 'Katholicisme', 'Stilte & gebed', 'tiener', 'Aandacht als gebed',
    'In de kloostertraditie heet het "ora et labora": bid en werk. Maar bidden werd er nooit opgevat als veel woorden maken. Het is eerder een vorm van aandacht: even ophouden met grijpen en plannen, en luisteren. Wie ooit een half uur echt stil is geweest, weet hoe vol die stilte is.\n\nJe hoeft geen monnik te zijn om dit te proberen. Eén minuut, aan het begin van de dag, zonder scherm, zonder doel. Merk wat er is. De traditie belooft geen trucje voor succes; ze biedt een oefening in er zijn. Dat is genoeg, en het is veel.'],
  ['islam', 'Islam', 'Barmhartigheid', 'gezin', 'In naam van de Barmhartige',
    'Bijna elk hoofdstuk van de Koran opent met dezelfde woorden: in naam van God, de Erbarmer, de Barmhartige. Nog voor er iets gevraagd of geboden wordt, klinkt eerst barmhartigheid. Dat is geen toeval maar een toon: wie over het goede leven nadenkt, begint bij mededogen, niet bij het oordeel.\n\nDie barmhartigheid is bedoeld om door te geven. Een glimlach, water voor wie dorst heeft, geduld met wie het moeilijk heeft -- de traditie noemt zulke kleine dingen nadrukkelijk goed. Groots gedrag begint klein, en telt.'],
  ['soefisme', 'Soefisme', 'Mystiek', 'tiener', 'Het riet dat klaagt',
    'De dichter Rumi opent zijn grote werk met een rietfluit die klaagt omdat ze is losgesneden van het rietveld. Iedere toon die ze speelt, is heimwee. Het beeld gaat over ons: we voelen ons soms afgesneden -- van rust, van elkaar, van iets groters -- en ons verlangen is de muziek die daaruit ontstaat.\n\nHet soefisme maakt van dat verlangen geen probleem om op te lossen, maar een weg om te gaan. Niet minder verlangen, maar zuiverder: van hebben naar zijn, van bezit naar liefde. De fluit klinkt het mooist juist omdat ze leeg is.'],
  ['jodendom', 'Jodendom', 'Rechtvaardigheid', 'gezin', 'Tikoen olam: de wereld herstellen',
    'In de joodse traditie leeft een klein, groot idee: tikoen olam, het herstellen van de wereld. Niet in één keer, niet door één held, maar draad voor draad, daad voor daad. Je hoeft de hele wereld niet te redden -- dat mag je niet eens denken -- maar je mag je er ook niet van afkeren.\n\nEen bekende spreuk vat het samen: het is niet aan jou om het werk te voltooien, maar het staat je ook niet vrij je eraan te onttrekken. Rechtvaardigheid is zo geen eindpunt maar een gewoonte: vandaag één stukje heler dan gisteren.'],
  ['kabbala', 'Kabbala', 'Licht & schepping', 'tiener', 'De gebroken vaten',
    'Een kabbalistisch verhaal vertelt dat bij de schepping het goddelijke licht werd opgevangen in vaten die het niet konden houden; ze braken, en vonken van licht raakten verspreid, verborgen in alles. De taak van de mens is die vonken op te rapen: goed doen is licht bevrijden dat vastzit in de gewone dingen.\n\nHet is een beeld dat troost en opdracht tegelijk is. Wat kapot lijkt, draagt licht in zich. En jouw kleine goede daad -- een verzoening, een eerlijk woord -- is niet niks: het is een vonk die terugkeert naar waar hij hoort.'],
  ['hindoeisme', 'Hindoeïsme', 'Levenskunst', 'tiener', 'Handelen zonder te grijpen',
    'De Bhagavad Gita geeft een raad die eenvoudig klinkt en een leven lang oefenen kost: doe je werk zo goed je kunt, maar klamp je niet vast aan de vruchten ervan. Je hebt invloed op je inzet, niet op de uitkomst. Wie dat leert, handelt vrijer en rustiger.\n\nDit is geen onverschilligheid -- juist niet. Het is volle toewijding zonder de kramp van moeten winnen. Je zaait met zorg en laat de oogst los. Veel angst verdwijnt op de plek waar je ophoudt de wereld te willen dwingen.'],
  ['vedanta', 'Advaita Vedanta', 'Eenheid', 'tiener', 'Dat ben jij',
    'Kern van de Advaita Vedanta is een korte zin: tat tvam asi, dat ben jij. De grond onder alle dingen en de grond onder jouw bewustzijn zijn niet twee. Wat je zoekt in de verte, is niet ver. De scheiding die je zo scherp voelt tussen "ik" en "de wereld" is echter dunner dan ze lijkt.\n\nJe hoeft die gedachte niet meteen te geloven. Je mag haar onderzoeken: wie ben ik, achter mijn naam, mijn rollen, mijn drukte? De traditie belooft dat wie rustig genoeg kijkt, iets vindt dat groter en stiller is dan het verhaal over zichzelf.'],
  ['boeddhisme', 'Boeddhisme', 'Mededogen', 'gezin', 'De tweede pijl',
    'Het boeddhisme vertelt: wie geraakt wordt door een pijl, voelt pijn -- dat is de eerste pijl, en die hoort bij het leven. Maar vaak schieten we een tweede pijl op onszelf af: het piekeren, het verzet, het "waarom ik". Die tweede pijl is niet onvermijdelijk. Daar zit ruimte.\n\nMededogen begint bij jezelf: mild zijn voor je eigen pijn zonder het drama te vergroten. Van daaruit stroomt het naar anderen. Iedereen die je tegenkomt, draagt een eerste pijl. Weten dat maakt zachter, en zacht zijn is niet zwak.'],
  ['zen', 'Zen', 'Aandacht', 'kind', 'Als je loopt, loop',
    'Een zenmeester kreeg de vraag wat verlichting was. Hij antwoordde: als je eet, eet; als je loopt, loop. De leerling vond dat te gewoon. Maar probeer het maar eens -- echt alleen maar eten, echt alleen maar lopen, zonder dat je hoofd al bij het volgende is. Het is moeilijker en mooier dan het klinkt.\n\nZen wijst niet naar iets ver weg, maar naar dit moment, dat er toch al is. De adem die nu naar binnen gaat. Het geluid dat nu klinkt. Wie hier is, hoeft nergens heen om iets bijzonders te vinden.'],
  ['sikhisme', 'Sikhisme', 'Dienen', 'gezin', 'De gemeenschappelijke maaltijd',
    'Bij een sikh-tempel hoort een keuken, de langar, waar iedereen welkom is aan dezelfde lange rij op de grond: rijk en arm, van welk geloof of geen geloof dan ook, samen aan één maaltijd. Vrijwilligers koken, scheppen op en wassen af. Dienen zonder aanzien des persoons -- dat is hier geen mooi idee maar dagelijkse praktijk.\n\nDe boodschap is eenvoudig en radicaal: aan tafel is niemand meer of minder. Wie een ander te eten geeft, oefent gelijkheid in met zijn handen. En wie afwast na afloop, leert dat dienen niet vernedert maar verheft.'],
  ['taoisme', 'Taoïsme', 'Natuurlijkheid', 'tiener', 'Zacht wint van hard',
    'De Tao Te Tsjing wijst graag naar water. Niets is zachter dan water, en toch slijt het de hardste rots. Het dringt niet, het duwt niet, het zoekt de laagste plek -- en juist daardoor komt het overal. Wu wei, niet-forceren, betekent niet niets doen, maar meebewegen met de aard van de dingen in plaats van er tegenin te beuken.\n\nVeel van onze moeheid komt van vechten tegen wat is. Het taoïsme fluistert een ander tempo: soms is loslaten sterker dan grijpen, en buigen sterker dan breken. De boom die meebuigt met de storm, staat er de volgende dag nog.'],
  ['confucianisme', 'Confucianisme', 'Karakter', 'tiener', 'De gulden regel, omgekeerd',
    'Lang voor die woorden elders klonken, gaf Confucius een leefregel: doe een ander niet aan wat je voor jezelf niet zou willen. Klein, negatief geformuleerd, en juist daardoor bruikbaar: je hoeft niet te weten wat iemand precies wil, je hoeft alleen te vermijden wat je zelf niet zou pikken.\n\nCharacter, ren, groeit volgens hem in het gewone: hoe je met je ouders omgaat, met je werk, met wie onder je staat. Grote deugd is opgebouwd uit kleine, dagelijkse fatsoenlijkheid. Wie het kleine trouw doet, wordt vanzelf iemand op wie je kunt bouwen.'],
  ['stoa', 'Stoïcijnse filosofie', 'Rust', 'tiener', 'Wat in jouw macht ligt',
    'De stoïcijn Epictetus begint bij één onderscheid: sommige dingen zijn aan ons -- onze oordelen, onze inzet, onze reactie -- en andere niet: het weer, de mening van anderen, wat gisteren gebeurde. Veel onrust komt doordat we ons vastbijten in wat we niet in de hand hebben.\n\nDe oefening is nuchter en bevrijdend: richt je aandacht op je eigen deel, en laat de rest los. Niet onverschillig, maar wijs. Je kunt de golven niet bevelen; je kunt wel leren varen. Rust is geen geluk dat je overkomt, maar een houding die je oefent.'],
  ['humanisme', 'Humanisme', 'Menselijkheid', 'gezin', 'Zonder hemel, met elkaar',
    'Het humanisme zoekt de grond voor goed doen niet boven de wolken maar tussen mensen. Als dit ene leven telt, telt elke dag, en telt de ander net zo echt als jij. Waardigheid is dan geen gunst van bovenaf maar iets dat we elkaar verschuldigd zijn.\n\nDat vraagt moed: geen zekerheid dat het allemaal goed komt, wel de keuze om het zelf een beetje beter te maken. Twijfel mag, vragen mag, van gedachten veranderen mag. Wat blijft, is de eenvoudige inzet om zorgvuldig en vriendelijk met elkaar om te gaan, gewoon omdat het ertoe doet.'],
  ['existentie', 'Existentiële filosofie', 'Vrijheid', 'tiener', 'Je bent wat je doet',
    'De existentiële denkers zeggen iets spannends en zwaars: er is geen kant-en-klare handleiding voor jouw leven. Je wordt niet geboren als een afgerond iets; je wordt wie je bent door je keuzes. Dat is beangstigend -- niemand kan het voor je beslissen -- en het is groots: je bent niet vastgelegd.\n\nVrijheid brengt zo verantwoordelijkheid mee. Wegkijken is ook een keuze. Maar wie dat aandurft, ontdekt dat een leven niet iets is dat je overkomt, maar iets dat je maakt, dag na dag, met wat je doet en niet doet.'],
  ['natuur', 'Natuurspiritualiteit', 'Verbondenheid', 'kind', 'Alles hangt samen',
    'Sta eens stil bij een appel. In hem zit de zon die scheen, de regen die viel, de bij die de bloesem bezocht, de handen die plukten. Eén ding blijkt duizend dingen die samenkomen. Natuurspiritualiteit noemt dat verbondenheid: niets staat op zichzelf, ook jij niet.\n\nWie zo leert kijken, gaat voorzichtiger om met de wereld. Je bent geen baas boven de natuur maar een draad in het weefsel. Een boom planten, water niet verspillen, een dier met rust laten -- kleine daden van respect voor het geheel waar je zelf deel van bent.'],
  ['inheems', 'Inheemse tradities', 'De zevende generatie', 'gezin', 'Denken aan wie na ons komt',
    'Bij verschillende inheemse volkeren leeft een leefregel: weeg bij elke grote keuze het gevolg voor de zevende generatie na jou. Niet alleen: is dit goed voor mij, of voor dit jaar? Maar: hoe zit de wereld erbij voor kinderen die je nooit zult zien?\n\nHet is een van de wijste rekensommen die er bestaan. Ze rekt de tijd op en maakt bescheiden. We erven de aarde niet van onze ouders, luidt een verwant gezegde, we lenen haar van onze kleinkinderen. Zo bezien is zorgzaam leven geen offer maar gewoon eerlijk teruggeven.'],
  ['dialoog', 'Interreligieuze dialoog', 'Samen leven', 'gezin', 'De berg met vele paden',
    'Een oud beeld: de berg is één, maar er lopen vele paden naar boven. Wie halverwege staat, ziet andere klimmers op andere hellingen en denkt soms dat zij verdwaald zijn. Toch gaan ze dezelfde kant op. Interreligieuze dialoog begint bij die nieuwsgierige bescheidenheid: misschien zie ik niet alles.\n\nSamen leven vraagt niet dat iedereen hetzelfde gelooft. Het vraagt dat we elkaar met respect bevragen en met rust laten waar dat hoort. Verschil hoeft geen dreiging te zijn; het kan een uitnodiging zijn om beter te leren kijken -- ook naar je eigen pad.'],
  ['twijfel', 'Vrije gedachte & twijfel', 'Eerlijk vragen', 'tiener', 'Twijfel als deugd',
    'We leren vaak dat zekerheid sterk is en twijfel zwak. De vrije gedachte draait dat voorzichtig om: eerlijk kunnen zeggen "ik weet het niet" is een teken van moed, niet van gebrek. Wie durft te twijfelen, blijft leren; wie alles al zeker weet, is gestopt met kijken.\n\nTwijfel is hier geen koude onverschilligheid maar een warme vorm van respect voor de waarheid: liever een open vraag dan een gemakkelijk antwoord. En juist wie vragen serieus neemt, kan andersdenkenden met rust en interesse tegemoet treden. Niet weten verbindt soms meer dan zeker weten.'],
  ['boeddhisme', 'Boeddhisme', 'Verhalen voor de kleinsten', 'mini', 'De olifant en de blinde mannen',
    'Een paar mensen die niet konden zien, wilden weten hoe een olifant eruitziet. De een voelde de slurf en zei: een olifant is als een dikke slang. De ander voelde een poot: nee, als een boomstam. Weer een ander voelde het oor: als een grote waaier. Ze kregen bijna ruzie.\n\nMaar ze hadden allemaal een beetje gelijk, en niemand had helemaal gelijk. Zo is het vaak: ieder ziet een stukje. Als je goed naar elkaar luistert, zie je samen het hele dier. Dat is een fijne gedachte om mee op te groeien.'],
  ['christendom', 'Christendom', 'Verhalen voor de kleinsten', 'mini', 'Het verloren schaap',
    'Een herder heeft honderd schapen. Op een avond telt hij: negenennegentig. Er is er één weg. Laat hij die ene maar zitten? Nee. Hij gaat de heuvels op, in het donker, tot hij het bange schaapje vindt, en draagt het op zijn schouders naar huis. En dan is hij blij, echt blij.\n\nHet verhaaltje zegt iets moois: jij telt. Ook als je je klein voelt of een keer de weg kwijt bent, is er iemand die je komt halen. Niemand is zomaar vergeten.'],
  ['islam', 'Islam', 'Prentenverhalen', 'kind', 'De glimlach is een gift',
    'Er is een uitspraak die kinderen meteen begrijpen: naar je broer of zus glimlachen is al iets goeds -- het is een soort cadeautje dat niets kost. Je hoeft niet rijk te zijn om te geven. Een vriendelijk gezicht, een handje helpen, ruimte maken op de bank: het telt allemaal mee.\n\nProbeer het eens een dag: geef elke persoon die je tegenkomt een echte glimlach. Kijk wat er terugkomt. Goedheid is aanstekelijk, en het mooiste is: hoe meer je ervan weggeeft, hoe meer je er zelf van hebt.'],
  ['jodendom', 'Jodendom', 'Rust', 'gezin', 'De sabbat: een dag om te ademen',
    'Zes dagen wordt er gewerkt en gehaast, en dan komt er één dag die anders is: rust. De sabbat is geen straf en geen luiheid, maar een geschenk -- een vaste plek in de week waar de drukte moet stoppen. Geen kopen, geen jagen, wel samen eten, praten, zingen, er zijn.\n\nJe hoeft de regels niet allemaal te kennen om het idee te lenen. Kies één moment per week waarin je niets moet. Zet de schermen uit, steek desnoods een kaars aan, en merk hoe de tijd verandert als je hem niet meer probeert vol te proppen. Rust maakt je weer een mens in plaats van een machine.'],
  ['hindoeisme', 'Hindoeïsme', 'Verhalen voor de kleinsten', 'mini', 'Het licht in jou',
    'In sommige huizen zeggen mensen bij het groeten "namaste". Dat betekent zoiets als: het mooie licht in mij groet het mooie licht in jou. Je buigt een beetje, je handen tegen elkaar, en je zegt eigenlijk: ik zie je, en er zit iets kostbaars in jou.\n\nDat is een fijne gewoonte. Probeer het maar eens bij iemand van wie je houdt. Als je bedenkt dat in iedereen zo\'n lichtje brandt -- in je vriendje, in de buurvrouw, in de mevrouw in de winkel -- ga je vanzelf een beetje aardiger kijken.'],
  ['stoa', 'Stoïcijnse filosofie', 'Dankbaarheid', 'kind', 'Kijk eens wat er wél is',
    'Soms zit je hoofd vol met wat je níet hebt: dat ene speelgoed, die uitnodiging, dat cijfer. De oude stoïcijnen kenden een simpel trucje daartegen: bedenk elke avond drie dingen die er wél waren. Een lekkere maaltijd. Een grappig moment. Iemand die aardig deed.\n\nHet klinkt te makkelijk, maar het werkt. Je traint je ogen om het goede te zien dat er toch al is. En wie dat oefent, wordt niet alleen dankbaarder maar ook rustiger -- want je jaagt minder achter dingen aan als je merkt hoeveel je al gekregen hebt.'],
  ['taoisme', 'Taoïsme', 'Verhalen voor de kleinsten', 'mini', 'De boer en het paard',
    'Een boer had een paard, en het liep weg. "Wat erg!" zeiden de buren. "Misschien," zei de boer. De volgende dag kwam het paard terug met drie wilde paarden erbij. "Wat fijn!" zeiden de buren. "Misschien," zei de boer. Zijn zoon viel bij het temmen en brak zijn been. "Wat erg!" Enzovoort.\n\nHet verhaal leert iets rustigs: je weet niet meteen of iets "goed" of "slecht" is; dat blijkt vaak later. Dus als er iets tegenzit, mag je best denken: misschien. En dan gewoon rustig verder, en afwachten hoe het loopt.'],
  ['humanisme', 'Humanisme', 'Prentenverhalen', 'kind', 'Iedereen telt mee',
    'Stel je een grote tafel voor waar plek is voor iedereen: voor wie ver weg komt en wie hier geboren is, voor wie veel gelooft en wie niets gelooft, voor wie snel is en wie wat trager. Aan die tafel is niemand een gast die geduld moet worden -- iedereen hoort er gewoon bij.\n\nDat is het idee waar mensen die "humanist" heten graag aan bouwen: we hoeven niet hetzelfde te zijn om elkaar goed te behandelen. Vriendelijk zijn, eerlijk delen, niemand buitensluiten. Je hebt er geen toverkracht voor nodig, alleen een beetje moed en een open hart.'],
  ['zen', 'Zen', 'Rust', 'tiener', 'Een lege kom',
    'Een geleerde bezocht een zenmeester om over verlichting te praten. De meester schonk thee in zijn kopje, en bleef schenken toen het al vol was; de thee liep over de tafel. "Stop!" riep de geleerde. "Zo," zei de meester, "zit jij: te vol van je eigen meningen. Hoe kan ik je iets laten proeven als je kom al overloopt?"\n\nHet verhaaltje is een uitnodiging: kom eens leeg. Leg even neer wat je zeker weet en wat je al vindt. In die lege ruimte past ineens iets nieuws. Niet alles hoeft ingevuld; soms is ruimte het kostbaarste wat je hebt.']
];

module.exports = { KERN: K };
