/* Invisible Arrival: één wens, dezelfde bestaande reservering, plus tijdelijke
   pass en verifieerbare beloften. Geen GPS; alleen vrijwillige statuspulsen. */
'use strict';
const beleid=require('../../../kern/reservering/beleid');
module.exports=kern=>{
  const {app,supplierAuth,managerOnly,accounts,db,crypto,save,schoon,findSupplier,notifySupplier,sseToSupplier,horeca}=kern,{H,nu}=horeca;
  const vandaag=()=>new Date().toISOString().slice(0,10),rid=()=>crypto.randomBytes(7).toString('hex');
  function store(code){const h=H(code);h.arrivals=h.arrivals||{};return h.arrivals}
  function datumUit(q){const iso=q.match(/\b(20\d\d-[01]\d-[0-3]\d)\b/);if(iso)return iso[1];const d=new Date();const dagen=['zondag','maandag','dinsdag','woensdag','donderdag','vrijdag','zaterdag'];const hit=dagen.findIndex(x=>q.includes(x));if(hit>=0){let plus=(hit-d.getDay()+7)%7;if(!plus)plus=7;d.setDate(d.getDate()+plus);return d.toISOString().slice(0,10)}return null}
  function interpreteer(tekst){const q=String(tekst||'').toLowerCase(),tm=q.match(/\b([01]?\d|2[0-3])[:.]([0-5]\d)\b/),p=q.match(/\b(?:met|voor)\s+(\d{1,2})\s*(?:mensen|personen|gasten)?/);return{datum:datumUit(q),tijd:tm?String(tm[1]).padStart(2,'0')+':'+tm[2]:null,personen:p?Math.max(1,Math.min(20,Number(p[1]))):null,toegankelijk:/rolstoel|toegankelijk|slecht ter been/.test(q),allergie:/allerg|noten|gluten|lactose|schaaldier/.test(q),gelegenheid:/verjaardag|jubileum|aanzoek|vier/.test(q)?(q.match(/verjaardag|jubileum|aanzoek/)||['bijzonder moment'])[0]:null,zone:/terras/.test(q)?'terras':/bar/.test(q)?'bar':/priv[eé]/.test(q)?'privé':'zaal'}}
  function capaciteit(s,datum,tijd,personen,wensen){const reserv=(db.data.reserveringen||[]).filter(r=>r.supplierCode===s.code&&r.datum===datum&&['aangevraagd','bevestigd','aangekomen'].includes(r.status));const min=t=>{const a=String(t||'').split(':');return Number(a[0])*60+Number(a[1])},m=min(tijd),overlap=reserv.filter(r=>Math.abs(min(r.tijd)-m)<120),bezet=new Set(overlap.map(r=>r.tafel).filter(Boolean)),opties=(s.tables||[]).filter(t=>Number(t.seats)>=personen&&!bezet.has(t.name)).map(t=>({naam:t.name,plaatsen:t.seats,toegankelijk:t.accessible===true?true:t.accessible===false?false:null,zone:t.zone||null})).filter(t=>!wensen.toegankelijk||t.toegankelijk!==false);const klok=((db.data.klok||{})[s.code]||[]).filter(k=>k.in&&!k.out).length,keuken=Object.values(H(s.code).rekeningen||{}).filter(r=>r.status==='open').reduce((n,r)=>n+(r.regels||[]).filter(x=>x.vrijAt&&x.stand!=='uitgegeven').length,0),score=Math.max(0,100-overlap.reduce((n,r)=>n+(r.personen||0),0)*2-keuken*2-(klok?0:20));return{kan:opties.length>0,score,opties:opties.slice(0,5),voorstel:opties[0]||null,bewijs:{overlappendeReserveringen:overlap.length,verwachteGasten:overlap.reduce((n,r)=>n+(r.personen||0),0),ingekloktNu:klok,openKeukenregels:keuken},uitleg:opties[0]?opties[0].naam+' past bij '+personen+' gasten en heeft in dit tijdvenster geen tafelconflict.':'Geen passende tafel zonder conflict gevonden.'}}
  function publiek(a){return{pass:a.pass,reserveringId:a.reserveringId,zaak:a.zaak,datum:a.datum,tijd:a.tijd,personen:a.personen,status:a.status,tafel:a.tafel||null,pulse:a.pulse,beloften:a.beloften,servicelijn:a.servicelijn,vervaltAt:a.vervaltAt}}
  app.post('/api/arrival/interpret',(req,res)=>res.json({ok:true,plan:interpreteer(schoon(req.body.tekst,500)),let:'Controleer dit plan; er is nog niets aangevraagd.'}));
  app.post('/api/arrival/request',(req,res)=>{const b=req.body||{},s=findSupplier(String(b.supplierCode||''));if(!s)return res.status(404).json({error:'Zaak niet gevonden.'});const datum=schoon(b.datum,10),tijd=schoon(b.tijd,5),personen=Math.max(1,Math.min(20,Number(b.personen)||2));if(!/^20\d\d-[01]\d-[0-3]\d$/.test(datum)||datum<vandaag()||!/^\d\d:\d\d$/.test(tijd))return res.status(400).json({error:'Controleer datum en tijd.'});const wensen={toegankelijk:!!b.toegankelijk,allergie:!!b.allergie,gelegenheid:schoon(b.gelegenheid,50)||null,zone:schoon(b.zone,20)||'zaal'},cap=capaciteit(s,datum,tijd,personen,wensen);if(!cap.kan)return res.status(409).json({error:'De hele operatie kan dit moment nu niet verantwoord dragen.',capacity:cap});const pass=rid(),reserveringId=rid(),r={id:reserveringId,supplierCode:s.code,supplierName:s.name,customerKey:'arrival:'+pass,customerCodename:schoon(b.naam,40)||'Gast',tier:null,datum,tijd,personen,notitie:[wensen.zone,wensen.gelegenheid].filter(Boolean).join(' · ').slice(0,140),status:'aangevraagd',at:nu(),arrivalPass:pass};Object.assign(r,beleid.beginToestand({datum,tijd,aanbetalingCenten:(s.settings&&s.settings.aanbetalingCenten)||0,nu:nu()}));db.data.reserveringen.unshift(r);const beloften=[{id:'tafel',label:'Passende tafel',status:'voorgesteld',bewijs:cap.voorstel.naam},{id:'capaciteit',label:'Operationele capaciteit',status:'berekend',bewijs:'score '+cap.score+' · '+cap.bewijs.verwachteGasten+' gasten in tijdvenster'}];if(wensen.toegankelijk)beloften.push({id:'toegankelijk',label:'Toegankelijke route',status:'wacht-op-mens',bewijs:null});if(wensen.allergie)beloften.push({id:'allergie',label:'Allergiebriefing keuken',status:'wacht-op-mens',bewijs:null});if(wensen.gelegenheid)beloften.push({id:'moment',label:'Bijzonder moment',status:'wacht-op-zaak',bewijs:wensen.gelegenheid});const a={pass,reserveringId,zaak:{code:s.code,naam:s.name},datum,tijd,personen,status:'aangevraagd',tafel:cap.voorstel.naam,pulse:'nog-niet-onderweg',wensen,beloften,capacity:cap,servicelijn:[{stap:'wens',status:'klaar'},{stap:'veilig mogelijk',status:'klaar'},{stap:'zaak bevestigt',status:'actief'},{stap:'voorbereid',status:'wacht'},{stap:'welkom',status:'wacht'}],at:nu(),vervaltAt:new Date(new Date(datum+'T'+tijd+':00').getTime()+12*3600000).toISOString()};store(s.code)[pass]=a;save();notifySupplier(s.code,{icon:'table',title:'Invisible Arrival',body:r.customerCodename+': '+datum+' '+tijd+' · '+personen+'p · beloften vragen controle'});sseToSupplier(s.code,'sync',{scope:'arrival'});res.json({ok:true,pass:publiek(a),capacity:cap})});
  function vind(pass){for(const [code,h]of Object.entries(db.data.horeca||{})){const a=(h.arrivals||{})[pass];if(a)return{code,a}}return null}
  app.post('/api/arrival/pass',(req,res)=>{const v=vind(String(req.body.pass||''));if(!v)return res.status(404).json({error:'Deze Arrival Pass bestaat niet of is verlopen.'});if(Date.parse(v.a.vervaltAt)<Date.now())return res.status(410).json({error:'Deze Arrival Pass is verlopen.'});res.json({ok:true,pass:publiek(v.a)})});
  app.post('/api/arrival/pulse',(req,res)=>{const v=vind(String(req.body.pass||''));if(!v)return res.status(404).json({error:'Arrival Pass niet gevonden.'});const p=String(req.body.pulse||''),toegestaan=['nog-niet-onderweg','onderweg','in-de-buurt','gearriveerd','stop'];if(!toegestaan.includes(p))return res.status(400).json({error:'Onbekende aankomststatus.'});v.a.pulse=p;v.a.pulseAt=nu();if(p==='stop')v.a.pulse='delen-gestopt';
    /* Eén idempotente voorbereidingsmissie zodra de gast nabij is. Alleen een
       operationeel tafelnummer reist mee; bijzondere gegevens blijven in de
       afgeschermde beloftestroom. */
    if((p==='in-de-buurt'||p==='gearriveerd')&&!v.a.prepMission){const open=(((db.data.klok||{})[v.code])||[]).filter(k=>k.in&&!k.out),k=open.map(x=>({k:x,s:accounts.getStaffById(Number(x.staffId))})).sort((a,b)=>/host|bedien|service/i.test(a.s&&a.s.func||'')?-1:/host|bedien|service/i.test(b.s&&b.s.func||'')?1:0)[0];if(k){db.data.horecaMissies=db.data.horecaMissies||{};const lijst=db.data.horecaMissies[v.code]=db.data.horecaMissies[v.code]||[],m={id:rid(),titel:'Invisible Arrival · tafel '+v.a.tafel,detail:'Maak de tafel gereed en open in Host Command alleen de beloften die persoonlijk gecontroleerd moeten worden.',sectie:'Host',prioriteit:p==='gearriveerd'?'hoog':'normaal',minuten:6,status:'nieuw',voorId:k.k.staffId,voorNaam:k.k.name,reden:'Gast deelde vrijwillig: '+p,gemaaktDoor:'Host Autopilot',at:nu()};lijst.unshift(m);v.a.prepMission=m.id}else v.a.hostException='Geen ingeklokte host voor de voorbereiding.'}
    save();sseToSupplier(v.code,'sync',{scope:'arrival'});res.json({ok:true,pass:publiek(v.a),let:'Er is alleen een tijdelijke status gedeeld; geen GPS of route.'})});
  app.post('/api/supplier/horeca/arrivals',supplierAuth,(req,res)=>{const arr=Object.values(store(req.supplier.code)).filter(a=>Date.parse(a.vervaltAt)>Date.now()).sort((a,b)=>(a.datum+a.tijd).localeCompare(b.datum+b.tijd));res.json({ok:true,arrivals:arr.map(a=>Object.assign(publiek(a),{wensen:a.wensen,capacity:a.capacity})),openBeloften:arr.reduce((n,a)=>n+a.beloften.filter(p=>/wacht|voorgesteld/.test(p.status)).length,0)})});
  app.post('/api/supplier/horeca/arrival/promise',supplierAuth,(req,res)=>{const a=store(req.supplier.code)[String(req.body.pass||'')];if(!a)return res.status(404).json({error:'Arrival Pass niet gevonden.'});const p=a.beloften.find(x=>x.id===String(req.body.id||''));if(!p)return res.status(404).json({error:'Belofte niet gevonden.'});p.status=req.body.akkoord===false?'niet-mogelijk':'persoonlijk-bevestigd';p.bewijs=schoon(req.body.bewijs,180)||(p.status==='niet-mogelijk'?'Door zaak afgewezen':'Persoonlijk gecontroleerd door '+req.actor.name);p.door=req.actor.name;p.at=nu();if(a.beloften.every(x=>['persoonlijk-bevestigd','berekend'].includes(x.status))){a.status='bevestigd';a.servicelijn[2].status='klaar';a.servicelijn[3].status='actief';const r=(db.data.reserveringen||[]).find(x=>x.id===a.reserveringId);if(r)r.status='bevestigd'}save();sseToSupplier(req.supplier.code,'sync',{scope:'arrival'});res.json({ok:true,pass:publiek(a)})});
};
