/* Living Venue Twin, veilige servicegolven, overdracht en Guest Recovery. Er
   wordt geen GPS of loopgedrag opgeslagen: zones zijn geaccepteerde werkzones. */
'use strict';
module.exports=kern=>{
  const {app,supplierAuth,managerOnly,accounts,db,crypto,save,schoon,sseToSupplier,horeca}=kern,{H,Hlees,nu}=horeca;
  const safety=require('../../../kern/horeca/safety');
  const live=code=>{const seen=new Set();return (((db.data.klok||{})[code])||[]).filter(k=>k.in&&!k.out&&!seen.has(String(k.staffId))&&seen.add(String(k.staffId))).map(k=>{const s=accounts.getStaffById(Number(k.staffId));return{id:k.staffId,name:k.name,func:s&&s.func||'Service',zone:(((H(code).venue||{}).zones)||{})[k.staffId]||null}})};
  const missies=code=>{db.data.horecaMissies=db.data.horecaMissies||{};return db.data.horecaMissies[code]=db.data.horecaMissies[code]||[]};
  const S=code=>{const h=H(code);h.spatial=h.spatial||{golven:[],overdrachten:[],recovery:[],blokkades:[]};return h.spatial};
  function tafels(req){const h=H(req.supplier.code),reks=Object.values(h.rekeningen||{}).filter(r=>r.status==='open');return (req.supplier.tables||[]).map((t,i)=>{const r=reks.find(x=>String(x.tafel)===String(t.name)),regels=r&&r.regels||[],verzoeken=(h.verzoeken||[]).filter(v=>r&&v.rekeningId===r.id&&/open|opgepakt/.test(v.stand));return{id:t.id,naam:t.name,plaatsen:t.seats,status:t.status,zone:t.zone||('Zone '+(Math.floor(i/6)+1)),x:t.x!=null?t.x:(12+(i%6)*15),y:t.y!=null?t.y:(18+Math.floor(i/6)*24),rekeningId:r&&r.id||null,gasten:r&&r.gasten||0,fase:!r?'vrij':!regels.length?'welkom':regels.every(x=>x.stand==='uitgegeven')?'genieten':regels.some(x=>x.stand==='klaar')?'uitserveren':'bereiding',allergieen:[...new Set(regels.map(x=>x.allergie).filter(Boolean))],verzoeken:verzoeken.length,gereed:regels.filter(x=>x.stand==='klaar').length}})}
  app.post('/api/supplier/horeca/spatial',supplierAuth,(req,res)=>{const t=tafels(req),team=live(req.supplier.code),sp=S(req.supplier.code);res.json({ok:true,tafels:t,team,blokkades:sp.blokkades,recovery:sp.recovery.filter(x=>x.status!=='gesloten'),overdrachten:sp.overdrachten.filter(x=>x.status==='wacht'),samenvatting:{bezet:t.filter(x=>x.rekeningId).length,gasten:t.reduce((n,x)=>n+x.gasten,0),aandacht:t.filter(x=>x.verzoeken||x.allergieen.length||x.gereed).length},privacy:'Werkzones, geen exacte personeelstracking.'})});
  app.post('/api/supplier/horeca/venue/concept',supplierAuth,(req,res)=>{if(!managerOnly(req,res))return;const posities=Array.isArray(req.body.posities)?req.body.posities.slice(0,300):[],bekend=new Set((req.supplier.tables||[]).map(t=>String(t.id)));const schoonPos=posities.filter(p=>bekend.has(String(p.id))).map(p=>({id:String(p.id),x:Math.max(4,Math.min(96,Number(p.x)||50)),y:Math.max(6,Math.min(94,Number(p.y)||50)),zone:schoon(p.zone,30)||'Zaal'}));const h=H(req.supplier.code);h.venueConcept={posities:schoonPos,door:req.actor.name,at:nu()};save();res.json({ok:true,concept:h.venueConcept,let:'Concept opgeslagen; de werkvloer gebruikt nog de gepubliceerde versie.'})});
  /* Eerst KIJKEN of er een concept klaarstaat (Hlees), en pas daarna de doos
     pakken (H). H() zet de horecadoos neer voor een zaak die er nog geen had --
     ook op de weg die hieronder met een 404 eindigt, en dan zeggen de
     statuscode en de opslag iets anders over hetzelfde verzoek. Bestaat de doos
     wel, dan geeft Hlees hem ECHT terug: het concept dat hier gelezen wordt is
     hetzelfde object dat hieronder wordt gepubliceerd en gewist. */
  app.post('/api/supplier/horeca/venue/publiceer',supplierAuth,(req,res)=>{if(!managerOnly(req,res))return;const c=Hlees(req.supplier.code).venueConcept;if(!c)return res.status(404).json({error:'Er staat geen venue-concept klaar.'});const h=H(req.supplier.code);h.venue=h.venue||{versie:0,geschiedenis:[]};h.venue.versie=(h.venue.versie||0)+1;for(const p of c.posities){const t=(req.supplier.tables||[]).find(x=>String(x.id)===String(p.id));if(t){t.x=p.x;t.y=p.y;t.zone=p.zone}}h.venue.geschiedenis=h.venue.geschiedenis||[];h.venue.geschiedenis.unshift({versie:h.venue.versie,posities:c.posities,door:req.actor.name,at:nu()});h.venue.geschiedenis=h.venue.geschiedenis.slice(0,20);h.venue.gepubliceerdAt=nu();h.venue.gepubliceerdDoor=req.actor.name;delete h.venueConcept;save();sseToSupplier(req.supplier.code,'sync',{scope:'venue'});res.json({ok:true,versie:h.venue.versie,tafels:tafels(req)})});
  app.post('/api/supplier/horeca/wave/voorstel',supplierAuth,(req,res)=>{const t=tafels(req),team=live(req.supplier.code),acties=[];t.filter(x=>x.gereed).forEach(x=>acties.push({soort:'service',tafel:x.naam,tekst:'Serveer '+x.gereed+' gereed gerecht(en)',prio:x.allergieen.length?'hoog':'normaal'}));t.filter(x=>x.verzoeken).forEach(x=>acties.push({soort:'service',tafel:x.naam,tekst:'Pak '+x.verzoeken+' gastverzoek(en) op',prio:'hoog'}));const kandidaat=team.slice().sort((a,b)=>(missies(req.supplier.code).filter(m=>m.voorId==a.id&&!/klaar|geannuleerd/.test(m.status)).length)-(missies(req.supplier.code).filter(m=>m.voorId==b.id&&!/klaar|geannuleerd/.test(m.status)).length))[0]||null;const geselecteerd=acties.slice(0,4),oordeel=safety.beoordeel({medewerker:kandidaat,acties:geselecteerd,allergie:t.some(x=>x.allergieen.length&&geselecteerd.some(a=>a.tafel===x.naam)),ingeklokt:!!kandidaat,noodrouteVrij:S(req.supplier.code).blokkades.length===0});res.json({ok:true,voorstel:{id:crypto.randomBytes(4).toString('hex'),acties:geselecteerd,kandidaat,oordeel,duur:Math.max(4,geselecteerd.length*3)},uitleg:!geselecteerd.length?'Geen acties om veilig te bundelen.':oordeel.mag?'Deze handelingen kunnen als één rustige servicegolf.':'Menselijke controle nodig: '+oordeel.bezwaren.join('; ')})});
  app.post('/api/supplier/horeca/wave/activeer',supplierAuth,(req,res)=>{if(!managerOnly(req,res))return;const v=req.body.voorstel||{},team=live(req.supplier.code),med=team.find(x=>String(x.id)===String(v.kandidaat&&v.kandidaat.id));const oordeel=safety.beoordeel({medewerker:med,acties:v.acties,allergie:!!(v.oordeel&&v.oordeel.menselijkeCheck),ingeklokt:!!med,noodrouteVrij:S(req.supplier.code).blokkades.length===0}),harde=oordeel.bezwaren.filter(x=>!x.startsWith('allergie '));if(!med||harde.length||(oordeel.menselijkeCheck&&req.body.allergieAkkoord!==true))return res.status(409).json({error:'Deze golf passeert de veiligheidsgrens niet.',bezwaren:oordeel.bezwaren});const g={id:v.id||crypto.randomBytes(4).toString('hex'),acties:(v.acties||[]).slice(0,8),voorId:med.id,voorNaam:med.name,status:'actief',at:nu(),door:req.actor.name,audit:[{at:nu(),door:req.actor.name,wat:'golf-bevestigd'}]};S(req.supplier.code).golven.unshift(g);missies(req.supplier.code).unshift({id:g.id,titel:'Servicegolf · '+g.acties.length+' momenten',detail:g.acties.map(a=>a.tafel+': '+a.tekst).join(' → '),sectie:'Zaal',prioriteit:g.acties.some(a=>a.prio==='hoog')?'hoog':'normaal',minuten:v.duur||10,status:'nieuw',voorId:med.id,voorNaam:med.name,reden:'Veilig gebundeld door Spatial Command',gemaaktDoor:req.actor.name,at:nu()});save();sseToSupplier(req.supplier.code,'sync',{scope:'spatial'});res.json({ok:true,golf:g})});
  app.post('/api/supplier/horeca/handover/start',supplierAuth,(req,res)=>{if(!req.actor.staffId)return res.status(403).json({error:'Alleen vanaf een persoonlijke PDA.'});const m=missies(req.supplier.code).find(x=>x.id===String(req.body.missieId||'')&&String(x.voorId)===String(req.actor.staffId)&&!/klaar|geannuleerd/.test(x.status));if(!m)return res.status(404).json({error:'Geen overdraagbare missie gevonden.'});const kandidaat=live(req.supplier.code).find(x=>String(x.id)!==String(req.actor.staffId));if(!kandidaat)return res.status(409).json({error:'Geen andere ingeklokte medewerker beschikbaar.'});const o={id:crypto.randomBytes(5).toString('hex'),missieId:m.id,vanId:req.actor.staffId,vanNaam:req.actor.name,naarId:kandidaat.id,naarNaam:kandidaat.name,status:'wacht',at:nu()};S(req.supplier.code).overdrachten.unshift(o);save();sseToSupplier(req.supplier.code,'sync',{scope:'spatial'});res.json({ok:true,overdracht:o})});
  app.post('/api/supplier/horeca/handover/accept',supplierAuth,(req,res)=>{if(!req.actor.staffId)return res.status(403).json({error:'Alleen vanaf een persoonlijke PDA.'});const o=S(req.supplier.code).overdrachten.find(x=>x.id===String(req.body.id||'')&&x.status==='wacht'&&String(x.naarId)===String(req.actor.staffId));if(!o)return res.status(404).json({error:'Deze overdracht wacht niet op u.'});const m=missies(req.supplier.code).find(x=>x.id===o.missieId);if(!m)return res.status(404).json({error:'De missie bestaat niet meer.'});o.status='geaccepteerd';o.akkoordAt=nu();m.voorId=req.actor.staffId;m.voorNaam=req.actor.name;m.overdrachtId=o.id;save();sseToSupplier(req.supplier.code,'sync',{scope:'spatial'});res.json({ok:true,overdracht:o})});
  app.post('/api/supplier/horeca/recovery/open',supplierAuth,(req,res)=>{const t=schoon(req.body.tafel,30),wat=schoon(req.body.wat,500);if(!t||!wat)return res.status(400).json({error:'Kies een tafel en beschrijf wat rechtgezet moet worden.'});const x={id:crypto.randomBytes(5).toString('hex'),tafel:t,wat,actie:schoon(req.body.actie,300)||'Ga persoonlijk naar de gast en erken wat er misging.',status:'open',compensatie:null,door:req.actor.name,at:nu(),audit:[{at:nu(),door:req.actor.name,wat:'recovery-geopend'}]};S(req.supplier.code).recovery.unshift(x);save();res.json({ok:true,recovery:x})});
  app.post('/api/supplier/horeca/recovery/beslis',supplierAuth,(req,res)=>{if(!managerOnly(req,res))return;const x=S(req.supplier.code).recovery.find(r=>r.id===String(req.body.id||''));if(!x)return res.status(404).json({error:'Herstelstroom niet gevonden.'});x.compensatie=schoon(req.body.compensatie,180)||null;x.status=req.body.sluit===true?'gesloten':'opvolgen';x.beslistDoor=req.actor.name;x.beslistAt=nu();x.audit.push({at:nu(),door:req.actor.name,wat:x.status,compensatie:x.compensatie});save();res.json({ok:true,recovery:x,let:'Dit registreert alleen het besluit; het verplaatst geen geld en past geen rekening aan.'})});
};
