'use strict';
const TYPES={klacht:{titel:'Gast voelt zich niet gehoord',effecten:['service','reputatie'],besluiten:['manager luistert persoonlijk','feiten en rekening controleren','rustige herstelplek aanbieden']},publiek:{titel:'Publieke gast trekt onverwachte groep',effecten:['crowd','privacy','noodroute'],besluiten:['gast bepaalt eigen gezelschap','uitgang vrijhouden','discrete vertrekroute coördineren']},kwetsbaar:{titel:'Persoon zoekt beschutting en wil niet vertrekken',effecten:['menswaardigheid','veiligheid','service'],besluiten:['rustig contact en hulpvraag','tweede medewerker betrekken','passende hulpverlening afstemmen']},beschermd:{titel:'Fictief beschermd gezelschap arriveert te vroeg',effecten:['toegang','levering','noodroute'],besluiten:['protocolverantwoordelijke beslist','leveranciersvenster scheiden','alternatieve ruimte gebruiken']},kind:{titel:'Kind en begeleider zijn elkaar kwijt',effecten:['veiligheid','crowd'],besluiten:['kinderprotocol starten','één aanspreekpunt aanwijzen','openbare details minimaliseren']},medisch:{titel:'Gast wordt onwel',effecten:['veiligheid','service'],besluiten:['menselijke eerste hulp','hulpdienst volgens protocol','ruimte en route vrijmaken']}};
const HARD=['Geen diagnose door AI','Geen automatische verwijdering','Geen status boven veiligheidsregels','Geen kamer- of tafellocatie delen','Geen echte beveiligingsdetails','Noodroute blijft vrij'];
function begin(){return{situaties:[],groepen:[],signalen:[],audit:[],lessen:[],invarianten:HARD.slice()}}
function bereken(h){h.groepen=h.situaties.filter(s=>s.status!=='afgerond'&&s.omstanders>2).map(s=>({situatieId:s.id,zone:s.zone,omstanders:s.omstanders,doorgang:Math.max(10,100-s.omstanders*5),escalatie:Math.min(100,s.spanning+Math.round(s.omstanders*1.8))}));h.signalen=[];for(const s of h.situaties.filter(x=>x.status!=='afgerond')){const g=h.groepen.find(x=>x.situatieId===s.id);if(g&&g.doorgang<45)h.signalen.push({niveau:'hoog',situatieId:s.id,zone:s.zone,tekst:'Groepsvorming beperkt de doorgang; houd de noodroute vrij.'});if(s.status==='open'&&s.spanning>=70)h.signalen.push({niveau:'hoog',situatieId:s.id,zone:s.zone,tekst:'Spanning vraagt een bevoegde menselijke gesprekspartner.'});if(s.status==='opvolging'&&(s.spanning>35||(g&&g.doorgang<60)))h.signalen.push({niveau:'aandacht',situatieId:s.id,zone:s.zone,tekst:'Nazorg is nog niet stabiel; controleer rust, doorgang en betrokkenen.'});if(s.type==='kind'||s.type==='medisch')h.signalen.push({niveau:'acuut',situatieId:s.id,zone:s.zone,tekst:'Menselijk veiligheidsprotocol heeft voorrang op service.'})}return h.signalen}
function open(h,type,zone,c){const d=TYPES[type];if(!d)return{status:400,error:'Onbekende menselijke situatie.'};if(type==='beschermd'&&c&&c.echteDetails)return{status:400,error:'Echte beveiligingsdetails horen niet in Universe.'};const s={id:'S-'+String(h.situaties.length+1).padStart(2,'0'),type,titel:d.titel,zone:zone||'lobby',effecten:d.effecten.slice(),besluiten:d.besluiten.slice(),status:'open',fase:'waarnemen',omstanders:Number(c&&c.omstanders)||0,spanning:Number(c&&c.spanning)||35,privacy:/publiek|beschermd/.test(type)?'need-to-know':'minimaal',at:Number(c&&c.tick)||0,historie:[]};h.situaties.push(s);h.audit.push({tick:s.at,wat:'situatie-geopend',type,zone:s.zone});bereken(h);return{status:200,ok:true,situatie:s}}
function ontwikkel(h,id,mensen,spanning){const s=h.situaties.find(x=>x.id===id&&x.status!=='afgerond');if(!s)return{status:404,error:'Situatie niet gevonden.'};s.omstanders=Math.max(0,s.omstanders+Number(mensen||0));s.spanning=Math.max(0,Math.min(100,s.spanning+Number(spanning||0)));s.historie.push({wat:'situatie-ontwikkeld',omstanders:s.omstanders,spanning:s.spanning});bereken(h);return{status:200,ok:true}}
function besluit(h,id,keuze,door){const s=h.situaties.find(x=>x.id===id&&x.status==='open');if(!s)return{status:404,error:'Situatie wacht niet op een besluit.'};if(!s.besluiten.includes(keuze))return{status:400,error:'Geen begrensde herstelroute.'};if(!door||!door.mens)return{status:409,error:'Deze situatie vraagt een menselijke verantwoordelijke.'};s.status='opvolging';s.fase='nazorg';s.keuze=keuze;s.door=String(door.rol||'bevoegde medewerker');s.spanning=Math.max(0,s.spanning-25);s.historie.push({tick:door.tick||0,wat:'menselijk-besluit',keuze,rol:s.door});h.audit.push({tick:door.tick||0,wat:'menselijk-besluit',situatieId:s.id,keuze,rol:s.door});bereken(h);return{status:200,ok:true}}
function afronden(h,id,controle,door){const s=h.situaties.find(x=>x.id===id&&x.status==='opvolging');if(!s)return{status:404,error:'Deze situatie staat niet in nazorg.'};if(!door||!door.mens)return{status:409,error:'Alleen een mens mag nazorg aftekenen.'};const c=controle||{},g=h.groepen.find(x=>x.situatieId===id);const rustig=Boolean(c.betrokkenenGesproken)&&s.spanning<=35&&(!g||g.doorgang>=60);if(!rustig)return{status:409,error:'Nazorg nog niet afgerond: controleer betrokkenen, spanning en vrije doorgang.'};s.status='afgerond';s.fase='geleerd';s.afgerondDoor=String(door.rol||'bevoegde medewerker');const les={type:s.type,zone:s.zone,effecten:s.effecten.slice(),keuze:s.keuze,uitkomst:'stabiel',persoonlijkeDetails:false};h.lessen.push(les);h.audit.push({tick:door.tick||0,wat:'nazorg-afgetekend',situatieId:s.id,rol:s.afgerondDoor});bereken(h);return{status:200,ok:true,les}}
module.exports={TYPES,HARD,begin,open,ontwikkel,besluit,afronden,bereken};
