'use strict';
const VERSIE='hospitality-world/1.0';
const FASES=['discovery','onboarding','planning','arrival','production','service','payment','aftercare'];
const kopie=x=>JSON.parse(JSON.stringify(x)),Human=require('./human-reality');
function locatie(x,i){return{id:x.id||'LOC-'+String(i+1).padStart(2,'0'),naam:String(x.naam||'Locatie '+(i+1)).slice(0,50),stad:String(x.stad||'Onbekend').slice(0,40),type:x.type||'restaurant',capaciteit:Math.max(1,Number(x.capaciteit)||80),terras:Math.max(0,Number(x.terras)||0),medewerkers:Math.max(1,Number(x.medewerkers)||8),verwacht:Math.max(0,Number(x.verwacht)||60),regenKans:Math.max(0,Math.min(1,Number(x.regenKans)||0)),certificaten:(x.certificaten||[]).map(c=>({soort:String(c.soort||'certificaat').slice(0,40),dagen:Math.max(0,Number(c.dagen)||0)})),stations:Object.assign({keuken:100,bar:100,ontbijt:x.naam==='Amsterdam'?68:(Number(x.capaciteit)||100)},x.stations||{})}}
function maak(config){config=config||{};const standaard=[{naam:'Amsterdam',stad:'Amsterdam',capaciteit:90,medewerkers:9,verwacht:84},{naam:'Ibiza',stad:'Ibiza',capaciteit:120,terras:55,medewerkers:12,verwacht:108,regenKans:.63},{naam:'Dubai',stad:'Dubai',capaciteit:140,medewerkers:14,verwacht:92,certificaten:[{soort:'HACCP',dagen:18},{soort:'BHV',dagen:20},{soort:'allergenen',dagen:21}]}];return{modelVersie:VERSIE,id:config.id||'WORLD-1',seed:String(config.seed||'rtg-universe-1'),status:'concept',fase:FASES[0],locaties:(config.locaties||standaard).map(locatie),mensen:kopie(config.mensen||[]),gasten:kopie(config.gasten||[]),leveranciers:kopie(config.leveranciers||[]),reserveringen:[],orders:[],betalingen:[],besluiten:[],gebeurtenissen:[],human:Human.begin(),aannames:kopie(config.aannames||[]),beperkingen:kopie(config.beperkingen||['Geen fysieke bouwkundige keuring','Geen omzetgarantie','Weer en vraag blijven onzeker'])}}
function keur(w){const fouten=[];if(!w||w.modelVersie!==VERSIE)fouten.push('onbekende modelversie');if(!w||!Array.isArray(w.locaties)||!w.locaties.length)fouten.push('geen locaties');const ids=new Set();for(const l of w&&w.locaties||[]){if(ids.has(l.id))fouten.push('dubbele locatie '+l.id);ids.add(l.id);if(l.medewerkers<1)fouten.push(l.id+' zonder medewerkers');if(l.capaciteit<1)fouten.push(l.id+' zonder capaciteit')}return{geldig:!fouten.length,fouten}}
function wijzig(w,v){const n=kopie(w),l=n.locaties.find(x=>x.id===v.locatieId);if(!l)return{error:'Locatie niet gevonden.'};for(const k of ['medewerkers','verwacht','capaciteit','terras','regenKans'])if(v[k]!==undefined)l[k]=Number(v[k]);n.besluiten.push({soort:'counterfactual',locatieId:l.id,verandering:kopie(v)});return{wereld:n}}
module.exports={VERSIE,FASES,maak,keur,wijzig,kopie};
