/* Magnaat Hospitality Universe: een speelbare bedrijfsproef. De wereld gebruikt
   uitsluitend synthetische of vooraf geanonimiseerde tellingen. Een simulatie
   schrijft nooit rechtstreeks terug naar een levende zaak. */
'use strict';
const ROUTES={
  goud:{naam:'Gouden dienst',druk:64,chaos:0,tekst:'Een volledige gastreis met normale druk.'},
  rood:{naam:'Rode afwijking',druk:78,chaos:1,tekst:'Eén operationele fout vraagt zichtbaar herstel.'},
  zwart:{naam:'Zwarte samenloop',druk:96,chaos:3,tekst:'Meerdere verstoringen versterken elkaar.'},
  platina:{naam:'Platina herstel',druk:88,chaos:2,tekst:'Een zware dienst wordt uitzonderlijk goed hersteld.'}
};
const INCIDENTEN=[
  {id:'ziek',titel:'Kok meldt zich ziek',as:'mensen',zwaarte:18,keuzes:['herverdelen','menu verkleinen','extern oproepen']},
  {id:'allergie',titel:'Allergiecontrole op de pas',as:'veiligheid',zwaarte:24,keuzes:['menselijke dubbelcheck','gerecht vervangen','stop uitgifte']},
  {id:'regen',titel:'Terras sluit door regen',as:'capaciteit',zwaarte:20,keuzes:['herplaatsen','tijdsloten spreiden','partnerlocatie']},
  {id:'pin',titel:'Betaalprovider hapert',as:'geld',zwaarte:16,keuzes:['offline wachtrij','alternatieve provider','menselijke registratie']},
  {id:'koeling',titel:'Koeling buiten bandbreedte',as:'veiligheid',zwaarte:26,keuzes:['batch blokkeren','reservevoorraad','service beperken']},
  {id:'dubbel',titel:'Laatste tafel dubbel geclaimd',as:'belofte',zwaarte:19,keuzes:['eerlijk alternatief','wachtbeleving','partnerlocatie']},
  {id:'document',titel:'Onboardingdocument ontbreekt',as:'mensen',zwaarte:14,keuzes:['veilig blokkeren','persoonlijk aanvullen','start uitstellen']},
  {id:'levering',titel:'Leverancier komt te laat',as:'capaciteit',zwaarte:17,keuzes:['reservevoorraad','kaart beperken','partnerleverancier']},
  {id:'noshow',titel:'Reservering verschijnt niet',as:'gast',zwaarte:11,keuzes:['wachtlijst bellen','tafel vrijgeven','persoonlijk navragen']},
  {id:'privacy',titel:'Gast trekt aankomsttoestemming in',as:'veiligheid',zwaarte:12,keuzes:['tracking stoppen','handmatige ontvangst','gegevens minimaliseren']}
];
const FASES=['ontdekken & solliciteren','onboarding & reserveren','planning & levering','aankomst & ontvangst','bestellen & produceren','service & herstel','betalen & vertrek','nazorg & loon'];
const clamp=n=>Math.max(0,Math.min(100,Math.round(n)));
function wereld(bron){const g=Math.max(3,Math.min(24,Number(bron&&bron.gasten)||8)),m=Math.max(2,Math.min(16,Number(bron&&bron.medewerkers)||4));return{
  markt:[{id:'V-01',type:'restaurant',stijl:'rustig',capaciteit:72,toegankelijk:true,allergiebeleid:'menselijk-bevestigd'},{id:'V-02',type:'hotelrestaurant',stijl:'zakelijk',capaciteit:110,toegankelijk:true,allergiebeleid:'menselijk-bevestigd'},{id:'V-03',type:'buurtzaak',stijl:'levendig',capaciteit:44,toegankelijk:false,allergiebeleid:'beperkt'}],
  sollicitanten:[{id:'K-01',rol:'bediening',status:'gevonden',geschikt:'onbeoordeeld'},{id:'K-02',rol:'keuken',status:'gevonden',geschikt:'onbeoordeeld'}],
  medewerkers:Array.from({length:m},(_,i)=>({id:'M-'+String(i+1).padStart(2,'0'),rol:i===0?'manager':i===1?'chef':i%3===0?'keuken':'service',status:'gepland',vaardigheid:i<2?'ervaren':'basis',taken:0})),
  gasten:Array.from({length:g},(_,i)=>({id:'G-'+String(i+1).padStart(2,'0'),reis:i%3===0?'zaken':i%3===1?'gezin':'vrij',status:'zoekt',toestemming:i%5!==0,allergie:i===2?'noten':null,toegankelijk:i===1,keuze:null,matchreden:null,tevreden:82})),
  leveranciers:[{id:'L-01',soort:'vers',status:'bevestigd',betrouwbaarheid:88},{id:'L-02',soort:'drank',status:'bevestigd',betrouwbaarheid:92}],
  reserveringen:[],bestellingen:[],betalingen:[],audit:[]};}
function nieuw(bron){const b=bron||{soort:'synthetisch'};return{status:'gereed',route:null,tick:0,fase:FASES[0],bron:b,scores:{gast:82,mensen:82,veiligheid:100,geld:100,capaciteit:84,belofte:88,herstel:70},wereld:wereld(b),incidenten:[],tijdlijn:[],voorstellen:[],replay:[]}}
function start(h,route){const r=ROUTES[route];if(!r)return{status:400,error:'Onbekende simulatieroute.'};h.status='live';h.route=route;h.tick=0;h.fase=FASES[0];h.wereld=wereld(h.bron);h.incidenten=[];h.voorstellen=[];h.tijdlijn=[{tick:0,soort:'start',tekst:r.naam+' gestart · '+r.tekst}];h.replay=[];h.scores={gast:86,mensen:84,veiligheid:100,geld:100,capaciteit:86,belofte:90,herstel:route==='platina'?88:72};for(let i=0;i<r.chaos;i++)injecteer(h,INCIDENTEN[i]);return{status:200,ok:true}}
function injecteer(h,incident){const x=incident||INCIDENTEN[(h.tick+h.incidenten.length)%INCIDENTEN.length];if(h.incidenten.some(i=>i.id===x.id&&i.status==='open'))return{status:409,error:'Deze verstoring staat al open.'};h.incidenten.push(Object.assign({},x,{status:'open',at:h.tick}));h.scores[x.as]=clamp(h.scores[x.as]-x.zwaarte);h.scores.gast=clamp(h.scores.gast-Math.ceil(x.zwaarte/3));h.tijdlijn.unshift({tick:h.tick,soort:'incident',tekst:x.titel});return{status:200,ok:true,incident:x.id}}
function pasHerstelToe(h,x,keuze){const w=h.wereld;if(x.id==='ziek'){const k=w.medewerkers.find(m=>m.rol==='keuken'&&m.status==='gepland');if(k)k.status='ziek';if(keuze==='herverdelen')w.medewerkers.filter(m=>m.status==='gepland').forEach(m=>m.taken++)}if(x.id==='allergie'){const b=w.bestellingen.find(o=>o.allergie);if(b)b.status=keuze==='menselijke dubbelcheck'?'veilig-bevestigd':'vervangen'}if(x.id==='regen')w.reserveringen.filter(r=>r.zone==='terras').forEach(r=>{r.zone=keuze==='partnerlocatie'?'partner':'zaal';r.status='herplaatst'});if(x.id==='pin')w.betalingen.forEach(b=>b.status=keuze==='offline wachtrij'?'wacht-op-sync':'alternatief');if(x.id==='koeling')w.leveranciers[0].status=keuze==='batch blokkeren'?'batch-geblokkeerd':'hersteld';if(x.id==='dubbel'&&w.reserveringen[0])w.reserveringen[0].status=keuze==='eerlijk alternatief'?'alternatief-aangeboden':'wacht';if(x.id==='document'){const n=w.medewerkers.find(m=>m.id==='M-NIEUW');if(n)n.status=keuze==='persoonlijk aanvullen'?'onboarding-compleet':'start-geblokkeerd'}if(x.id==='levering')w.leveranciers[0].status=keuze;if(x.id==='noshow'&&w.reserveringen[0])w.reserveringen[0].status=keuze;if(x.id==='privacy'){const g=w.gasten.find(g=>g.toestemming);if(g){g.toestemming=false;g.status=keuze==='tracking stoppen'?'delen-gestopt':'ontvangen-zonder-tracking'}}}
function besluit(h,id,keuze){const x=h.incidenten.find(i=>i.id===id&&i.status==='open');if(!x)return{status:404,error:'Deze verstoring wacht niet op een besluit.'};if(!x.keuzes.includes(keuze))return{status:400,error:'Dit herstelplan hoort niet bij deze verstoring.'};x.status='hersteld';x.keuze=keuze;x.hersteldAt=h.tick;pasHerstelToe(h,x,keuze);h.scores[x.as]=clamp(h.scores[x.as]+Math.round(x.zwaarte*.72));h.scores.herstel=clamp(h.scores.herstel+7);h.scores.gast=clamp(h.scores.gast+3);h.wereld.audit.push({tick:h.tick,wat:'menselijk-herstel',incident:x.id,keuze});h.tijdlijn.unshift({tick:h.tick,soort:'herstel',tekst:x.titel+' · '+keuze});h.replay.push({tick:h.tick,incident:x.id,keuze});return{status:200,ok:true}}
function beweeg(h){const w=h.wereld,t=h.tick;if(t===1){w.sollicitanten[0].status='uitgenodigd';w.gasten.forEach(g=>g.status='gevonden');w.audit.push({tick:t,wat:'discover-en-werving'})}if(t===2){w.sollicitanten[0].status='aangenomen';w.sollicitanten[0].geschikt='menselijk-bevestigd';w.medewerkers.push({id:'M-NIEUW',rol:'bediening',status:'onboarding',vaardigheid:'basis',taken:0});w.gasten.forEach((g,i)=>{g.status='gereserveerd';w.reserveringen.push({id:'R-'+g.id,gast:g.id,status:'bevestigd',zone:i%4===0?'terras':'zaal'})});w.audit.push({tick:t,wat:'onboarding-en-reservering'})}if(t===3){w.medewerkers.forEach(m=>{if(m.status==='gepland')m.status='ingeklokt'});w.leveranciers.forEach(l=>l.status='geleverd-gecontroleerd');w.audit.push({tick:t,wat:'planning-en-ontvangst'})}if(t===4){w.gasten.forEach(g=>g.status=g.toestemming?'veilig-aangekomen':'ontvangen-zonder-tracking');w.reserveringen.forEach(r=>{if(r.status==='bevestigd')r.status='gearriveerd'});w.audit.push({tick:t,wat:'arrival'})}if(t===5){w.gasten.forEach((g,i)=>{g.status='in-service';w.bestellingen.push({id:'B-'+g.id,gast:g.id,allergie:g.allergie,status:g.allergie?'wacht-op-mens':'productie'})});w.audit.push({tick:t,wat:'order-en-productie'})}if(t===6){w.bestellingen.forEach(b=>{if(b.status==='productie')b.status='uitgeserveerd'});w.gasten.forEach(g=>g.status='geniet');w.audit.push({tick:t,wat:'service'})}if(t===7){w.gasten.forEach(g=>{w.betalingen.push({id:'P-'+g.id,gast:g.id,status:'betaald'});g.status='vertrokken'});w.audit.push({tick:t,wat:'betaling'})}if(t===8){w.medewerkers.forEach(m=>{if(m.status==='ingeklokt')m.status='uren-ter-controle'});w.gasten.forEach(g=>g.status='nazorg');w.audit.push({tick:t,wat:'nazorg-en-loon'})}}
function stap(h){if(h.status!=='live')return{status:409,error:'Start eerst een Hospitality-simulatie.'};h.tick++;h.fase=FASES[Math.min(h.tick-1,FASES.length-1)];beweeg(h);const r=ROUTES[h.route];if(h.route!=='goud'&&h.tick%2===0&&h.incidenten.filter(x=>x.status==='open').length<2)injecteer(h);const open=h.incidenten.filter(x=>x.status==='open');h.scores.mensen=clamp(h.scores.mensen-(r.druk>85?2:0)-open.length);h.scores.gast=clamp(h.scores.gast-open.length);h.tijdlijn.unshift({tick:h.tick,soort:'keten',tekst:h.fase+' · '+(open.length?open.length+' menselijk besluit(en) open.':'keten beweegt gecontroleerd.')});if(h.tick>=8){h.status='afgerond';h.voorstellen=advies(h)}return{status:200,ok:true,afgerond:h.status==='afgerond'}}
function advies(h){const laag=Object.entries(h.scores).sort((a,b)=>a[1]-b[1])[0];return[{id:'focus-'+laag[0],titel:'Versterk '+laag[0],uitleg:'De simulatie eindigde hier op '+laag[1]+' van 100.',status:'voorstel'},{id:'replay',titel:'Train het zwaarste herstel',uitleg:(h.incidenten.sort((a,b)=>b.zwaarte-a.zwaarte)[0]||{titel:'de piekdienst'}).titel+' wordt een herhaalbare teamtraining.',status:'voorstel'}]}
function beeld(h){return JSON.parse(JSON.stringify(h))}
module.exports={ROUTES,INCIDENTEN,FASES,nieuw,start,injecteer,besluit,stap,advies,beeld};
