#!/usr/bin/env node
/* ============================================================================
   CI STELT EEN NIEUW GEWICHTREGISTER VOOR -- en een mens besluit.

   WAAROM DIT ER IS

   TOETSDUUR.json stuurt de scherfverdeling en staat daarom IN de repo: de
   verdeling hoort deterministisch te zijn, en een register dat onderweg
   verandert zet dezelfde toets morgen op een andere scherf. Daar stond dus
   bewust `Een mens commit hem` boven.

   Alleen: sinds die stap bestaat heeft niemand hem gecommit. Het register bleef
   een lokale meting -- zonder dekking, op een andere machine -- terwijl de keten
   op runners met dekking draait, en de scherven liepen 1348s tegen 526s uit
   elkaar zonder dat er iets rood werd. `Een mens doet het` is geen mechanisme
   als niemand het onder ogen krijgt.

   Dit script verandert dat zonder het principe op te geven: CI meet, CI STELT
   VOOR, een mens merget. Het verschil met automatisch schrijven is precies dat
   de verandering door een pull request gaat en dus in de historie staat, met
   het driftoordeel eronder.

   WAT HET NOOIT DOET

     - naar main schrijven. Alleen naar een eigen tak.
     - de bouw laten zakken. Lukt het voorstel niet, dan zegt het waarom en
       eindigt het met 0: een mislukt voorstel is geen kapotte keten, en een
       rood vinkje hier zou over de verkeerde dingen gaan.
     - een tweede PR openen. Bestaat de tak al, dan wordt hij bijgewerkt.
     - iets voorstellen bij ACTUEEL. Ruis went, en dan wordt ook het echte
       voorstel weggeklikt.

   DRAAIEN (in CI, met GITHUB_TOKEN en schrijfrechten)

     node scripts/gewichtvoorstel.js --oordeel gewichtdrift.json
   ========================================================================== */
'use strict';
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const WORTEL = path.join(__dirname, '..');
const TAK = 'ci/gewichtregister';

const zeg = (...a) => console.log('[gewichtvoorstel]', ...a);

function git(...args) {
  return execFileSync('git', args, { cwd: WORTEL, encoding: 'utf8' }).trim();
}

async function api(pad, methode, lijf) {
  const repo = process.env.GITHUB_REPOSITORY;
  const r = await fetch('https://api.github.com/repos/' + repo + pad, {
    method: methode,
    headers: {
      Authorization: 'Bearer ' + process.env.GITHUB_TOKEN,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json'
    },
    body: lijf ? JSON.stringify(lijf) : undefined
  });
  const tekst = await r.text();
  let json = null;
  try { json = JSON.parse(tekst); } catch (e) { /* geen json */ }
  return { ok: r.ok, status: r.status, json, tekst };
}

/* De tekst van het voorstel. Hij opent met wat er is GEMETEN en niet met wat
   iemand moet doen: wie dit over een maand terugleest wil eerst weten waarom
   het register niet meer klopte. */
function lijf(rijen) {
  const r = [];
  r.push('CI heeft de toetsduren opnieuw gemeten en het gecommitte gewichtregister');
  r.push('wijkt daar materieel van af. Dit voorstel vervangt `TOETSDUUR.json` door de');
  r.push('meting van deze ronde.');
  r.push('');
  r.push('| modus | bron van het register | totale kosten | max bestand | projectiefout | status |');
  r.push('|---|---|---|---|---|---|');
  for (const x of rijen) {
    const pct = (v) => (v === null || v === undefined ? '-' : (v >= 0 ? '+' : '') + (v * 100).toFixed(0) + '%');
    r.push('| `' + x.modus + '` | ' + ((x.stempel && x.stempel.waar) || 'ontbreekt') +
      ' | ' + pct(x.totaleKosten) + ' | ' + pct(x.maxBestand) +
      (x.maxNaam ? ' (`' + x.maxNaam + '`)' : '') +
      ' | ' + (x.fout === null ? '-' : (x.fout * 100).toFixed(0) + '%') +
      ' | **' + x.status + '** |');
  }
  r.push('');
  r.push('De **projectiefout** is de maat die telt: verdeel met de oude gewichten, weeg');
  r.push('met de nieuwe, en kijk hoeveel de traagste scherf boven het ideaal uitkomt.');
  r.push('Dat is wat een runner werkelijk doet zolang dit register niet is bijgewerkt.');
  r.push('');
  r.push('Wat hier NIET in staat: een oordeel over de toetsen zelf. Een toets die trager');
  r.push('wordt is hier geen fout maar een ander gewicht -- daarvoor is `NORM.json`.');
  r.push('');
  r.push('Gemeten in run ' + (process.env.GITHUB_RUN_ID || '?') + ' op commit ' +
    String(process.env.GITHUB_SHA || '').slice(0, 8) + '.');
  r.push('');
  r.push('---');
  r.push('_Generated by [Claude Code](https://claude.ai/code)_');
  return r.join('\n');
}

async function main() {
  const i = process.argv.indexOf('--oordeel');
  const oordeelPad = i > 0 ? process.argv[i + 1] : 'gewichtdrift.json';

  let rijen = null;
  try { rijen = JSON.parse(fs.readFileSync(path.resolve(WORTEL, oordeelPad), 'utf8')); }
  catch (e) { zeg('geen driftoordeel gelezen (' + oordeelPad + '):', e.message); return 0; }

  const raak = rijen.filter((r) => r.status === 'VEROUDERD' || r.status === 'ONGELDIG');
  if (!raak.length) { zeg('alles ACTUEEL -- geen voorstel, en dat is de bedoeling.'); return 0; }

  if (!process.env.GITHUB_TOKEN || !process.env.GITHUB_REPOSITORY) {
    zeg('geen token of repository in de omgeving; het oordeel staat hierboven,',
      'het voorstel wordt niet gedaan.');
    return 0;
  }

  /* Verandert het bestand niets, dan is er ook niets voor te stellen. Dat kan:
     het oordeel gaat over een MODUS die de verdeler niet gebruikt. */
  if (!git('status', '--porcelain', 'TOETSDUUR.json')) {
    zeg('TOETSDUUR.json is niet veranderd -- niets voor te stellen.');
    return 0;
  }

  const basis = process.env.GITHUB_REF_NAME || 'main';
  try {
    git('config', 'user.name', 'rtg-ci');
    git('config', 'user.email', 'ci@rahultravelgroup.invalid');
    git('checkout', '-B', TAK);
    git('add', 'TOETSDUUR.json');
    git('commit', '-m',
      'Het gewichtregister opnieuw gemeten in CI\n\n' +
      raak.map((r) => '  modus ' + r.modus + ': ' + r.status +
        (r.fout === null ? '' : ', projectiefout ' + (r.fout * 100).toFixed(0) + '%')).join('\n') +
      '\n\nVoorgesteld door scripts/gewichtvoorstel.js uit run ' +
      (process.env.GITHUB_RUN_ID || '?') + '. Een mens merget.');
    /* Een expliciete URL, zodat er geen credential in .git/config achterblijft
       -- dezelfde reden waarom elke checkout hier persist-credentials: false
       draagt. */
    const url = 'https://x-access-token:' + process.env.GITHUB_TOKEN +
      '@github.com/' + process.env.GITHUB_REPOSITORY + '.git';
    git('push', '--force-with-lease', url, TAK + ':' + TAK);
  } catch (e) {
    zeg('de tak kon niet worden weggeschreven:', e.message);
    return 0;
  }

  const bestaand = await api('/pulls?head=' +
    encodeURIComponent(process.env.GITHUB_REPOSITORY.split('/')[0] + ':' + TAK) + '&state=open', 'GET');
  if (bestaand.ok && Array.isArray(bestaand.json) && bestaand.json.length) {
    zeg('bestaande PR bijgewerkt: #' + bestaand.json[0].number);
    await api('/issues/' + bestaand.json[0].number + '/comments', 'POST',
      { body: lijf(raak) });
    return 0;
  }

  const pr = await api('/pulls', 'POST', {
    title: 'Het gewichtregister van de toetsketen opnieuw gemeten',
    head: TAK, base: basis, body: lijf(raak)
  });
  if (pr.ok && pr.json) { zeg('voorstel geopend: #' + pr.json.number); return 0; }

  zeg('de PR kon niet worden geopend (' + pr.status + '):', pr.tekst.slice(0, 300));
  /* DE TAK STAAT ER WEL, EN DAT IS DE HELFT DIE TELT. Gebeurd op 1 september
     2026: 403 "GitHub Actions is not permitted to create or approve pull
     requests" -- een instelling van de organisatie, niet iets wat dit script
     kan oplossen. Zonder deze regel leest een mens alleen een foutmelding en
     denkt hij dat de meting weg is; hij staat gewoon klaar op een tak. */
  zeg('de tak ' + TAK + ' staat WEL klaar met het nieuwe register.');
  if (pr.status === 403) {
    zeg('403 betekent hier meestal: Settings -> Actions -> General ->',
      '"Allow GitHub Actions to create and approve pull requests" staat uit.',
      'Zet die aan, of open de PR met de hand vanaf die tak.');
  }
  return 0;
}

if (require.main === module) main().then((c) => process.exit(c), (e) => { zeg('onverwacht:', e); process.exit(0); });
module.exports = { lijf, TAK };
