/* Geloof & Wijsheid: de kern-teksten, deel 2. De uitleg over WAT dit is en
   welke regels eraan hangen staat in ../geloofbieb-kern.js; dit bestand is
   alleen de inhoud. Vorm per item:
   [traditie, traditieLabel, thema, doelgroep, titel, tekst] */
module.exports = [
  ['humanisme', 'Humanisme', 'Menselijkheid', 'gezin', 'Zonder hemel, met elkaar',
    'Het humanisme zoekt de grond voor goed doen niet boven de wolken maar tussen mensen. Als dit ene leven telt, telt elke dag, en telt de ander net zo echt als jij. Waardigheid is dan geen gunst van bovenaf maar iets dat we elkaar verschuldigd zijn.\n\nDat vraagt moed: geen zekerheid dat het allemaal goed komt, wel de keuze om het zelf een beetje beter te maken. Twijfel mag, vragen mag, van gedachten veranderen mag. Wat blijft, is de eenvoudige inzet om zorgvuldig en vriendelijk met elkaar om te gaan, gewoon omdat het ertoe doet.'],
  ['existentie', 'Existentiële filosofie', 'Vrijheid', 'tiener', 'Je bent wat je doet',
    'De existentiële denkers zeggen iets spannends en zwaars: er is geen kant-en-klare handleiding voor jouw leven. Je wordt niet geboren als een afgerond iets; je wordt wie je bent door je keuzes. Dat is beangstigend -- niemand kan het voor je beslissen -- en het is groots: je bent niet vastgelegd.\n\nVrijheid brengt zo verantwoordelijkheid mee. Wegkijken is ook een keuze. Maar wie dat aandurft, ontdekt dat een leven niet iets is dat je overkomt, maar iets dat je maakt, dag na dag, met wat je doet en niet doet.'],
  ['natuur', 'Natuurspiritualiteit', 'Verbondenheid', 'kind', 'Alles hangt samen',
    'Sta eens stil bij een appel. In hem zit de zon die scheen, de regen die viel, de bij die de bloesem bezocht, de handen die plukten. Eén ding blijkt duizend dingen die samenkomen. Natuurspiritualiteit noemt dat verbondenheid: niets staat op zichzelf, ook jij niet.\n\nWie zo leert kijken, gaat voorzichtiger om met de wereld. Je bent geen baas boven de natuur maar een draad in het weefsel. Een boom planten, water niet verspillen, een dier met rust laten -- kleine daden van respect voor het geheel waar je zelf deel van bent.'],
  ['inheems', 'Inheemse tradities', 'De zevende generatie', 'gezin', 'Denken aan wie na ons komt',
    'Bij verschillende inheemse volkeren leeft een leefregel: weeg bij elke grote keuze het gevolg voor de zevende generatie na jou. Niet alleen: is dit goed voor mij, of voor dit jaar? Maar: hoe zit de wereld erbij voor kinderen die je nooit zult zien?\n\nHet is een van de wijste rekensommen die er bestaan. Ze rekt de tijd op en maakt bescheiden. We erven de aarde niet van onze ouders, luidt een verwant gezegde, we lenen haar van onze kleinkinderen. Zo bezien is zorgzaam leven geen offer maar gewoon eerlijk teruggeven.'],
  ['dialoog', 'Interreligieuze dialoog', 'Samen leven', 'gezin', 'De berg met vele paden',
    'Een oud beeld: de berg is één, maar er lopen vele paden naar boven. Wie halverwege staat, ziet andere klimmers op andere hellingen en denkt soms dat zij verdwaald zijn. Toch gaan ze dezelfde kant op. Interreligieuze dialoog begint bij die nieuwsgierige bescheidenheid: misschien zie ik niet alles.\n\nSamen leven vraagt niet dat iedereen hetzelfde gelooft. Het vraagt dat we elkaar met respect bevragen en met rust laten waar dat hoort. Verschil hoeft geen dreiging te zijn; het kan een uitnodiging zijn om beter te leren kijken -- ook naar je eigen pad.'],
  ['twijfel', 'Vrije gedachte & twijfel', 'Eerlijk vragen', 'tiener', 'Twijfel als deugd',
    'We leren vaak dat zekerheid sterk is en twijfel zwak. De vrije gedachte draait dat voorzichtig om: eerlijk kunnen zeggen "ik weet het niet" is een teken van moed, niet van gebrek. Wie durft te twijfelen, blijft leren; wie alles al zeker weet, is gestopt met kijken.\n\nTwijfel is hier geen koude onverschilligheid maar een warme vorm van respect voor de waarheid: liever een open vraag dan een gemakkelijk antwoord. En juist wie vragen serieus neemt, kan andersdenkenden met rust en interesse tegemoet treden. Niet weten verbindt soms meer dan zeker weten.'],
  ['boeddhisme', 'Boeddhisme', 'Verhalen voor de kleinsten', 'mini', 'De olifant en de blinde mannen',
    'Een paar mensen die niet konden zien, wilden weten hoe een olifant eruitziet. De een voelde de slurf en zei: een olifant is als een dikke slang. De ander voelde een poot: nee, als een boomstam. Weer een ander voelde het oor: als een grote waaier. Ze kregen bijna ruzie.\n\nMaar ze hadden allemaal een beetje gelijk, en niemand had helemaal gelijk. Zo is het vaak: ieder ziet een stukje. Als je goed naar elkaar luistert, zie je samen het hele dier. Dat is een fijne gedachte om mee op te groeien.'],
  ['christendom', 'Christendom', 'Verhalen voor de kleinsten', 'mini', 'Het verloren schaap',
    'Een herder heeft honderd schapen. Op een avond telt hij: negenennegentig. Er is er één weg. Laat hij die ene maar zitten? Nee. Hij gaat de heuvels op, in het donker, tot hij het bange schaapje vindt, en draagt het op zijn schouders naar huis. En dan is hij blij, echt blij.\n\nHet verhaaltje zegt iets moois: jij telt. Ook als je je klein voelt of een keer de weg kwijt bent, is er iemand die je komt halen. Niemand is zomaar vergeten.'],
  ['islam', 'Islam', 'Prentenverhalen', 'kind', 'De glimlach is een gift',
    'Er is een uitspraak die kinderen meteen begrijpen: naar je broer of zus glimlachen is al iets goeds -- het is een soort cadeautje dat niets kost. Je hoeft niet rijk te zijn om te geven. Een vriendelijk gezicht, een handje helpen, ruimte maken op de bank: het telt allemaal mee.\n\nProbeer het eens een dag: geef elke persoon die je tegenkomt een echte glimlach. Kijk wat er terugkomt. Goedheid is aanstekelijk, en het mooiste is: hoe meer je ervan weggeeft, hoe meer je er zelf van hebt.'],
  ['jodendom', 'Jodendom', 'Rust', 'gezin', 'De sabbat: een dag om te ademen',
    'Zes dagen wordt er gewerkt en gehaast, en dan komt er één dag die anders is: rust. De sabbat is geen straf en geen luiheid, maar een geschenk -- een vaste plek in de week waar de drukte moet stoppen. Geen kopen, geen jagen, wel samen eten, praten, zingen, er zijn.\n\nJe hoeft de regels niet allemaal te kennen om het idee te lenen. Kies één moment per week waarin je niets moet. Zet de schermen uit, steek desnoods een kaars aan, en merk hoe de tijd verandert als je hem niet meer probeert vol te proppen. Rust maakt je weer een mens in plaats van een machine.'],
  ['hindoeisme', 'Hindoeïsme', 'Verhalen voor de kleinsten', 'mini', 'Het licht in jou',
    'In sommige huizen zeggen mensen bij het groeten "namaste". Dat betekent zoiets als: het mooie licht in mij groet het mooie licht in jou. Je buigt een beetje, je handen tegen elkaar, en je zegt eigenlijk: ik zie je, en er zit iets kostbaars in jou.\n\nDat is een fijne gewoonte. Probeer het maar eens bij iemand van wie je houdt. Als je bedenkt dat in iedereen zo\'n lichtje brandt -- in je vriendje, in de buurvrouw, in de mevrouw in de winkel -- ga je vanzelf een beetje aardiger kijken.'],
  ['stoa', 'Stoïcijnse filosofie', 'Dankbaarheid', 'kind', 'Kijk eens wat er wél is',
    'Soms zit je hoofd vol met wat je níet hebt: dat ene speelgoed, die uitnodiging, dat cijfer. De oude stoïcijnen kenden een simpel trucje daartegen: bedenk elke avond drie dingen die er wél waren. Een lekkere maaltijd. Een grappig moment. Iemand die aardig deed.\n\nHet klinkt te makkelijk, maar het werkt. Je traint je ogen om het goede te zien dat er toch al is. En wie dat oefent, wordt niet alleen dankbaarder maar ook rustiger -- want je jaagt minder achter dingen aan als je merkt hoeveel je al gekregen hebt.'],
  ['taoisme', 'Taoïsme', 'Verhalen voor de kleinsten', 'mini', 'De boer en het paard',
    'Een boer had een paard, en het liep weg. "Wat erg!" zeiden de buren. "Misschien," zei de boer. De volgende dag kwam het paard terug met drie wilde paarden erbij. "Wat fijn!" zeiden de buren. "Misschien," zei de boer. Zijn zoon viel bij het temmen en brak zijn been. "Wat erg!" Enzovoort.\n\nHet verhaal leert iets rustigs: je weet niet meteen of iets "goed" of "slecht" is; dat blijkt vaak later. Dus als er iets tegenzit, mag je best denken: misschien. En dan gewoon rustig verder, en afwachten hoe het loopt.'],
  ['humanisme', 'Humanisme', 'Prentenverhalen', 'kind', 'Iedereen telt mee',
    'Stel je een grote tafel voor waar plek is voor iedereen: voor wie ver weg komt en wie hier geboren is, voor wie veel gelooft en wie niets gelooft, voor wie snel is en wie wat trager. Aan die tafel is niemand een gast die geduld moet worden -- iedereen hoort er gewoon bij.\n\nDat is het idee waar mensen die "humanist" heten graag aan bouwen: we hoeven niet hetzelfde te zijn om elkaar goed te behandelen. Vriendelijk zijn, eerlijk delen, niemand buitensluiten. Je hebt er geen toverkracht voor nodig, alleen een beetje moed en een open hart.'],
  ['zen', 'Zen', 'Rust', 'tiener', 'Een lege kom',
    'Een geleerde bezocht een zenmeester om over verlichting te praten. De meester schonk thee in zijn kopje, en bleef schenken toen het al vol was; de thee liep over de tafel. "Stop!" riep de geleerde. "Zo," zei de meester, "zit jij: te vol van je eigen meningen. Hoe kan ik je iets laten proeven als je kom al overloopt?"\n\nHet verhaaltje is een uitnodiging: kom eens leeg. Leg even neer wat je zeker weet en wat je al vindt. In die lege ruimte past ineens iets nieuws. Niet alles hoeft ingevuld; soms is ruimte het kostbaarste wat je hebt.']
];
