/* Geloof & Wijsheid: de kern-teksten, deel 1. De uitleg over WAT dit is en
   welke regels eraan hangen staat in ../geloofbieb-kern.js; dit bestand is
   alleen de inhoud. Vorm per item:
   [traditie, traditieLabel, thema, doelgroep, titel, tekst] */
module.exports = [

  ['christendom', 'Christendom', 'Naastenliefde', 'gezin', 'De barmhartige Samaritaan',
    'Een man ligt gewond langs de weg. Voorbijgangers die je een vroom leven zou toedichten, lopen door. Uitgerekend een vreemdeling, iemand uit een groep die men wantrouwde, stopt, verzorgt de wonden en betaalt voor onderdak. Als de vraag klinkt "wie is mijn naaste?", draait het antwoord de vraag om: je naaste is niet wie het dichtst bij je staat, maar wie jij nabij durft te komen.\n\nHet verhaal is eeuwenoud en toch ongemakkelijk actueel. Het meet geloof niet af aan wat je zegt te geloven, maar aan of je stopt wanneer stoppen ongelegen komt. Dat is de kern die het christendom hier deelt met zoveel andere tradities: liefde is een werkwoord.'],
  ['katholicisme', 'Katholicisme', 'Stilte & gebed', 'tiener', 'Aandacht als gebed',
    'In de kloostertraditie heet het "ora et labora": bid en werk. Maar bidden werd er nooit opgevat als veel woorden maken. Het is eerder een vorm van aandacht: even ophouden met grijpen en plannen, en luisteren. Wie ooit een half uur echt stil is geweest, weet hoe vol die stilte is.\n\nJe hoeft geen monnik te zijn om dit te proberen. Eén minuut, aan het begin van de dag, zonder scherm, zonder doel. Merk wat er is. De traditie belooft geen trucje voor succes; ze biedt een oefening in er zijn. Dat is genoeg, en het is veel.'],
  ['islam', 'Islam', 'Barmhartigheid', 'gezin', 'In naam van de Barmhartige',
    'Bijna elk hoofdstuk van de Koran opent met dezelfde woorden: in naam van God, de Erbarmer, de Barmhartige. Nog voor er iets gevraagd of geboden wordt, klinkt eerst barmhartigheid. Dat is geen toeval maar een toon: wie over het goede leven nadenkt, begint bij mededogen, niet bij het oordeel.\n\nDie barmhartigheid is bedoeld om door te geven. Een glimlach, water voor wie dorst heeft, geduld met wie het moeilijk heeft -- de traditie noemt zulke kleine dingen nadrukkelijk goed. Groots gedrag begint klein, en telt.'],
  ['soefisme', 'Soefisme', 'Mystiek', 'tiener', 'Het riet dat klaagt',
    'De dichter Rumi opent zijn grote werk met een rietfluit die klaagt omdat ze is losgesneden van het rietveld. Iedere toon die ze speelt, is heimwee. Het beeld gaat over ons: we voelen ons soms afgesneden -- van rust, van elkaar, van iets groters -- en ons verlangen is de muziek die daaruit ontstaat.\n\nHet soefisme maakt van dat verlangen geen probleem om op te lossen, maar een weg om te gaan. Niet minder verlangen, maar zuiverder: van hebben naar zijn, van bezit naar liefde. De fluit klinkt het mooist juist omdat ze leeg is.'],
  ['jodendom', 'Jodendom', 'Rechtvaardigheid', 'gezin', 'Tikoen olam: de wereld herstellen',
    'In de joodse traditie leeft een klein, groot idee: tikoen olam, het herstellen van de wereld. Niet in één keer, niet door één held, maar draad voor draad, daad voor daad. Je hoeft de hele wereld niet te redden -- dat mag je niet eens denken -- maar je mag je er ook niet van afkeren.\n\nEen bekende spreuk vat het samen: het is niet aan jou om het werk te voltooien, maar het staat je ook niet vrij je eraan te onttrekken. Rechtvaardigheid is zo geen eindpunt maar een gewoonte: vandaag één stukje heler dan gisteren.'],
  ['kabbala', 'Kabbala', 'Licht & schepping', 'tiener', 'De gebroken vaten',
    'Een kabbalistisch verhaal vertelt dat bij de schepping het goddelijke licht werd opgevangen in vaten die het niet konden houden; ze braken, en vonken van licht raakten verspreid, verborgen in alles. De taak van de mens is die vonken op te rapen: goed doen is licht bevrijden dat vastzit in de gewone dingen.\n\nHet is een beeld dat troost en opdracht tegelijk is. Wat kapot lijkt, draagt licht in zich. En jouw kleine goede daad -- een verzoening, een eerlijk woord -- is niet niks: het is een vonk die terugkeert naar waar hij hoort.'],
  ['hindoeisme', 'Hindoeïsme', 'Levenskunst', 'tiener', 'Handelen zonder te grijpen',
    'De Bhagavad Gita geeft een raad die eenvoudig klinkt en een leven lang oefenen kost: doe je werk zo goed je kunt, maar klamp je niet vast aan de vruchten ervan. Je hebt invloed op je inzet, niet op de uitkomst. Wie dat leert, handelt vrijer en rustiger.\n\nDit is geen onverschilligheid -- juist niet. Het is volle toewijding zonder de kramp van moeten winnen. Je zaait met zorg en laat de oogst los. Veel angst verdwijnt op de plek waar je ophoudt de wereld te willen dwingen.'],
  ['vedanta', 'Advaita Vedanta', 'Eenheid', 'tiener', 'Dat ben jij',
    'Kern van de Advaita Vedanta is een korte zin: tat tvam asi, dat ben jij. De grond onder alle dingen en de grond onder jouw bewustzijn zijn niet twee. Wat je zoekt in de verte, is niet ver. De scheiding die je zo scherp voelt tussen "ik" en "de wereld" is echter dunner dan ze lijkt.\n\nJe hoeft die gedachte niet meteen te geloven. Je mag haar onderzoeken: wie ben ik, achter mijn naam, mijn rollen, mijn drukte? De traditie belooft dat wie rustig genoeg kijkt, iets vindt dat groter en stiller is dan het verhaal over zichzelf.'],
  ['boeddhisme', 'Boeddhisme', 'Mededogen', 'gezin', 'De tweede pijl',
    'Het boeddhisme vertelt: wie geraakt wordt door een pijl, voelt pijn -- dat is de eerste pijl, en die hoort bij het leven. Maar vaak schieten we een tweede pijl op onszelf af: het piekeren, het verzet, het "waarom ik". Die tweede pijl is niet onvermijdelijk. Daar zit ruimte.\n\nMededogen begint bij jezelf: mild zijn voor je eigen pijn zonder het drama te vergroten. Van daaruit stroomt het naar anderen. Iedereen die je tegenkomt, draagt een eerste pijl. Weten dat maakt zachter, en zacht zijn is niet zwak.'],
  ['zen', 'Zen', 'Aandacht', 'kind', 'Als je loopt, loop',
    'Een zenmeester kreeg de vraag wat verlichting was. Hij antwoordde: als je eet, eet; als je loopt, loop. De leerling vond dat te gewoon. Maar probeer het maar eens -- echt alleen maar eten, echt alleen maar lopen, zonder dat je hoofd al bij het volgende is. Het is moeilijker en mooier dan het klinkt.\n\nZen wijst niet naar iets ver weg, maar naar dit moment, dat er toch al is. De adem die nu naar binnen gaat. Het geluid dat nu klinkt. Wie hier is, hoeft nergens heen om iets bijzonders te vinden.'],
  ['sikhisme', 'Sikhisme', 'Dienen', 'gezin', 'De gemeenschappelijke maaltijd',
    'Bij een sikh-tempel hoort een keuken, de langar, waar iedereen welkom is aan dezelfde lange rij op de grond: rijk en arm, van welk geloof of geen geloof dan ook, samen aan één maaltijd. Vrijwilligers koken, scheppen op en wassen af. Dienen zonder aanzien des persoons -- dat is hier geen mooi idee maar dagelijkse praktijk.\n\nDe boodschap is eenvoudig en radicaal: aan tafel is niemand meer of minder. Wie een ander te eten geeft, oefent gelijkheid in met zijn handen. En wie afwast na afloop, leert dat dienen niet vernedert maar verheft.'],
  ['taoisme', 'Taoïsme', 'Natuurlijkheid', 'tiener', 'Zacht wint van hard',
    'De Tao Te Tsjing wijst graag naar water. Niets is zachter dan water, en toch slijt het de hardste rots. Het dringt niet, het duwt niet, het zoekt de laagste plek -- en juist daardoor komt het overal. Wu wei, niet-forceren, betekent niet niets doen, maar meebewegen met de aard van de dingen in plaats van er tegenin te beuken.\n\nVeel van onze moeheid komt van vechten tegen wat is. Het taoïsme fluistert een ander tempo: soms is loslaten sterker dan grijpen, en buigen sterker dan breken. De boom die meebuigt met de storm, staat er de volgende dag nog.'],
  ['confucianisme', 'Confucianisme', 'Karakter', 'tiener', 'De gulden regel, omgekeerd',
    'Lang voor die woorden elders klonken, gaf Confucius een leefregel: doe een ander niet aan wat je voor jezelf niet zou willen. Klein, negatief geformuleerd, en juist daardoor bruikbaar: je hoeft niet te weten wat iemand precies wil, je hoeft alleen te vermijden wat je zelf niet zou pikken.\n\nCharacter, ren, groeit volgens hem in het gewone: hoe je met je ouders omgaat, met je werk, met wie onder je staat. Grote deugd is opgebouwd uit kleine, dagelijkse fatsoenlijkheid. Wie het kleine trouw doet, wordt vanzelf iemand op wie je kunt bouwen.'],
  ['stoa', 'Stoïcijnse filosofie', 'Rust', 'tiener', 'Wat in jouw macht ligt',
    'De stoïcijn Epictetus begint bij één onderscheid: sommige dingen zijn aan ons -- onze oordelen, onze inzet, onze reactie -- en andere niet: het weer, de mening van anderen, wat gisteren gebeurde. Veel onrust komt doordat we ons vastbijten in wat we niet in de hand hebben.\n\nDe oefening is nuchter en bevrijdend: richt je aandacht op je eigen deel, en laat de rest los. Niet onverschillig, maar wijs. Je kunt de golven niet bevelen; je kunt wel leren varen. Rust is geen geluk dat je overkomt, maar een houding die je oefent.'],
];
