'use strict';
const escape = value => String(value ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(report) {
  const e=escape, graph=report.graph, screens=graph.nodes.filter(n=>n.route);
  const proofIds=j=>[...j.proofs.map(p=>p.id),...(j.proofRefs||[])];
  const journeyState=j=>!graph.valid?'CONTRACT_INVALID':proofIds(j).every(id=>report.proofs.some(p=>p.id===id&&p.state==='PROVEN'))?'PROVEN_IN_SCOPE':'INCOMPLETE';
  const proof=report.proofs.map(p=>`<tr data-status="${e(p.state)}" data-journeys="${e(graph.journeys.filter(j=>proofIds(j).includes(p.id)).map(j=>j.id).join(' '))}"><td>${e(p.id)}</td><td>${e(p.layer)}</td><td><strong>${e(p.state)}</strong></td><td>${e(p.scope)}<details><summary>Herkomst en bewijs</summary><p>Test: ${e(p.test)}</p><p>Gemeten: ${e(p.at||'Niet gemeten')}</p><p>Werkboom gewijzigd tijdens vastleggen: ${p.worktreeDirty?'ja':'nee'}</p><p>Bron: ${e(p.sourceHash||'Geen')}</p>${p.log?`<a href="${e(p.log)}">Testlog openen</a>`:''}</details></td></tr>`).join('');
  const journeys=graph.journeys.map(j=>`<article id="journey-${e(j.id)}"><h2>${e(j.humanIntent)}</h2><p>Automatisch bewijs voor deze reis: <strong>${e(journeyState(j))}</strong></p><p>Verantwoordelijk: ${e(j.owner)} · Object: ${e(j.domainObject)}</p><ol>${j.steps.map(s=>`<li><strong>${e(s.capability)}</strong> · ${e(s.world)}<p>${e(s.screen)} → ${e(s.destination)}</p><details><summary>Resultaat, bevoegdheid en herstel</summary><p>${e(s.result)}</p><p>${e(s.authority)}</p><p>Terug: ${e(s.recovery)}</p></details></li>`).join('')}</ol><p>Menselijke beoordeling: <strong>${e(j.humanReview.status)}</strong></p><p>Inspanningsbudget (doel, nog geen meting): ${e(JSON.stringify(j.effortBudget))}</p></article>`).join('');
  return `<!doctype html><html lang="nl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RTG Experience Observatory</title><style>
:root{color-scheme:light}*{box-sizing:border-box}body{margin:0;background:#faf8f3;color:#202722;font:16px/1.6 system-ui,sans-serif}main{overflow-wrap:anywhere;max-width:1160px;margin:auto;padding:32px 24px}header{border-bottom:1px solid #c6b99d;margin-bottom:28px}h1{font:44px/1.15 Georgia,serif;margin:14px 0}h2{font:28px/1.3 Georgia,serif}small{letter-spacing:.15em}article,section{padding:24px;background:#fffdf9;border:1px solid #ddd5c7;margin:20px 0}a{color:#66512e}table{min-width:760px;width:100%;border-collapse:collapse}td,th{text-align:left;vertical-align:top;padding:14px 10px;border-bottom:1px solid #ddd5c7;overflow-wrap:anywhere}td:first-child{min-width:130px}summary{cursor:pointer;color:#66512e}li{margin:16px 0}input,select{font:inherit;padding:8px;max-width:100%}.scroll{overflow:auto}.warning{color:#87341e}code{overflow-wrap:anywhere}#screens p{border-bottom:1px solid #ddd5c7;padding:8px} [hidden]{display:none!important}@media(max-width:600px){main{padding:20px 12px}article,section{padding:16px}h1{font-size:32px}}
</style><main><header><small>RTG / INTERN / EXPERIENCE</small><h1>Van bedoeling naar bewijs.</h1><p>Vier werelden. ${screens.length} app-ingangen uit de bron. ${graph.journeys.length} gemodelleerde reizen.</p><p>Contract: <strong>${graph.valid?'GELDIG':'AFGEKEURD'}</strong> · Automatische bewijslaag: <strong>${e(report.status)}</strong></p><p>Geldig contract betekent niet dat de ervaring bewezen of voor productie goedgekeurd is.</p></header>
<section><h2>Wat aandacht vraagt</h2><p>${report.proofs.filter(p=>p.state!=='PROVEN').length} bewijsstukken niet actueel bewezen. ${screens.filter(s=>s.coverage==='NOT_MODELED').length} app-ingangen zonder Experience DNA.</p><p>Begrijpelijkheid, fysieke iPhone, tekstvergroting, inspanningsmeting en volledige accountdekking: nog niet bewezen. Dit overzicht bevat geen gebruikersgegevens.</p>${graph.errors.map(x=>`<p class="warning">${e(x.code)}: ${e(x.subject)}</p>`).join('')}</section>
<section><h2>Operationeel · Ervaring · Weerbaarheid</h2><label>Gebruikersreis <select id="journey"><option value="">Alle reizen</option>${graph.journeys.map(j=>`<option value="${e(j.id)}">${e(j.humanIntent)}</option>`).join('')}</select></label> <label>Toon bewijs <select id="status"><option value="">Alles</option>${['PROVEN','FAILED','NOT_TESTED','STALE','BLOCKED'].map(s=>`<option>${s}</option>`).join('')}</select></label><div class="scroll"><table><thead><tr><th>Proef</th><th>Laag</th><th>Status</th><th>Geteste scope</th></tr></thead><tbody>${proof}</tbody></table></div></section>
${journeys}<section><h2>Schermen en dekking</h2><label>Zoek scherm <input type="search" id="search" placeholder="Bijvoorbeeld agenda"></label><div id="screens">${screens.map(s=>`<p>${e(s.route)} · ${e(s.world)} · ${e(s.coverage)}</p>`).join('')}</div></section><footer><p>Snapshot: ${e(report.at)} · Commit: ${e(report.commit)}</p><p>Bewijs geldt maximaal 24 uur en vervalt bij gewijzigde broninhoud. Opnieuw genereren: npm run experience:report.</p><a href="report.json">Machineleesbare graaf en bewijs</a></footer></main><script>
function filterProof(){const status=document.querySelector('#status').value,journey=document.querySelector('#journey').value;document.querySelectorAll('tr[data-status]').forEach(r=>r.hidden=(!!status&&r.dataset.status!==status)||(!!journey&&!r.dataset.journeys.split(' ').includes(journey)));}
document.querySelector('#status').addEventListener('change',filterProof);
document.querySelector('#journey').addEventListener('change',filterProof);
document.querySelector('#search').addEventListener('input',function(){const q=this.value.toLowerCase();document.querySelectorAll('#screens p').forEach(p=>p.hidden=!p.textContent.toLowerCase().includes(q))});
</script></html>`;
}
module.exports={render};
