/* De ECHTE, leesbare kern van de Reis-Bibliotheek. Geen miljoen lege titels
   meer: elke gids hieronder heeft een echte, leesbare tekst die je kunt openen
   en lezen. Eigen RTG-redactie: sfeer en hoogtepunten, eten, en een praktisch
   woord. Eerlijk en zonder opsmuk; geen boekingslinks, geen reclame. Een kern
   om mee te beginnen en uit te breiden; kwaliteit boven aantal.

   [slug, bestemming, regio, titel, tekst]; alinea's gescheiden door \n\n. */

const G = [
  ['amsterdam', 'Amsterdam', 'Europa', 'Amsterdam: de stad op mensenmaat',
    'Amsterdam is klein genoeg om te lopen en rijk genoeg om nooit uitgekeken te raken. De grachtengordel is werelderfgoed, maar het echte geheim zit in de zijstraten: de Negen Straatjes voor winkels met karakter, de Jordaan voor bruine cafés en hofjes waar het ineens stil is. Het Rijksmuseum en het Van Gogh Museum liggen op loopafstand van elkaar; reserveer online en ga vroeg.\n\nEet als de stad zelf: haring van een kraam, Indonesische rijsttafel (de koloniale geschiedenis proef je hier eerlijker dan waar ook), en appeltaart bij een café aan het water. In de Pijp vind je de Albert Cuypmarkt en de betere kleine keukens.\n\nPraktisch: huur een fiets alleen als je vlot mee kunt in het verkeer, de tram en je benen zijn anders sneller en veiliger. Kijk uit met foto momenten op fietspaden; dat is de enige plek waar de stad haar geduld verliest.'],
  ['londen', 'Londen', 'Europa', 'Londen: dorpen aan elkaar geregen',
    'Londen is geen stad maar een verzameling dorpen, elk met een eigen toon. De grote namen (Westminster, de Tower, het British Museum) verdienen hun roem, maar plan per buurt: een ochtend South Kensington voor de musea, een middag langs de South Bank van de Tate Modern naar Borough Market, een avond Soho of Shoreditch.\n\nDe Britse keuken is allang geen grap meer: van de curry op Brick Lane tot de zondagse roast in een pub met open haard. Borough Market is de smaakversneller; kom hongerig. En de afternoon tea blijft, mits een keer, een klein feest van beschaving.\n\nPraktisch: de metro is duur per los kaartje; check gewoon in met je betaalpas, dan rekent het systeem zelf het dagplafond. Musea zijn er gratis; dat maakt Londen op regenachtige dagen verrassend betaalbaar.'],
  ['parijs', 'Parijs', 'Europa', 'Parijs: leren flaneren',
    'Parijs beloont wie langzaam gaat. De Eiffeltoren en het Louvre horen erbij, maar de stad zelf is het museum: de kades van de Seine, de passages met glazen daken, de stoelen in de Jardin du Luxembourg die je naar de zon draait. Kies per dag een arrondissement en loop; het Marais voor galeries en joodse bakkers, Montmartre in de vroege ochtend voordat de bussen komen.\n\nEten is hier een dagtaak: een croissant die kraakt, een lange lunch met een karaf wijn, een fromagerie waar je advies vraagt in plaats van kiest. Reserveer voor het avondeten; de goede adressen zijn klein.\n\nPraktisch: de metro brengt je overal, maar veel ritten zijn te voet mooier. Leer twee woorden ("bonjour" en "merci") en de stad wordt merkbaar vriendelijker.'],
  ['rome', 'Rome', 'Europa', 'Rome: alle eeuwen tegelijk',
    'In Rome ligt de geschiedenis niet achter glas maar op straat. Het Colosseum en het Forum Romanum vragen een ochtend en goede schoenen; het Pantheon is gratis en misschien wel het volmaaktste gebouw van Europa. Gooi je muntje in de Trevi vroeg in de ochtend, als het plein nog van de stad is.\n\nEet Romeins: cacio e pepe, carbonara zonder room (vraag er nooit om), artisjokken in het voorjaar, en ijs bij een gelateria waar de pistache grijsgroen is in plaats van felgroen; dat is het echte werk. In Trastevere eet je het best in de straten waar geen foto menu hangt.\n\nPraktisch: reserveer het Vaticaan en het Colosseum vooraf, altijd. Draag bedekte schouders in kerken. En neem de middag zoals de Romeinen: rustig aan; de stad is er morgen ook nog.'],
  ['lissabon', 'Lissabon', 'Europa', 'Lissabon: licht, heuvels en heimwee',
    'Lissabon heeft het mooiste licht van Europa; de stad ligt op heuvels aan een rivier die op zee lijkt. Verdwaal in de Alfama, waar de was tussen de huizen hangt en fado uit open ramen komt. Neem tram 28 een keer voor het verhaal, en loop hem daarna terug voor de foto momenten. Belém verdient een halve dag: het klooster, de toren en de pastéis de nata uit de oven.\n\nDe keuken is eerlijk en van zee: gegrilde sardines in de zomer, bacalhau in honderd gedaanten, en een glas vinho verde op een miradouro bij zonsondergang.\n\nPraktisch: draag schoenen met grip; de tegels zijn glad als het regent. De stad is heuvelachtig, dus plan per wijk en neem af en toe de lift of de funicular; die horen bij het openbaar vervoer.'],
  ['ibiza', 'Ibiza', 'Europa', 'Ibiza: het stille eiland achter de mythe',
    'Ibiza is twee eilanden in een: de clubkalender van juni tot september, en daaronder een kalkstenen eiland met dennen, kliffen en baaien waar het water doorzichtig is. Dalt Vila, de ommuurde bovenstad, is werelderfgoed; loop hem bij avondlicht. Huur een auto en zoek de kleine cala die je zelf ontdekt; dat is de herinnering die blijft.\n\nEet vis aan het water: een bullit de peix in een baai in het noorden, of gewoon gegrilde gamba met ijskoude witte wijn. De zonsondergang aan de westkust is een dagelijks ritueel; kies een rustige rots boven een druk terras.\n\nPraktisch: mei, juni en september zijn de mooiste maanden; warm, licht en zonder de drukte van augustus. Reserveer restaurants aan zee ruim vooraf en neem contant geld mee voor de kleinste strandtenten.'],
  ['istanbul', 'Istanbul', 'Midden-Oosten & Noord-Afrika', 'Istanbul: de stad op twee continenten',
    'Istanbul ligt op de naad van Europa en Azië, en dat voel je overal. De Hagia Sophia en de Blauwe Moskee staan tegenover elkaar als twee hoofdstukken van dezelfde geschiedenis; het Topkapi paleis vraagt een halve dag. Maar het echte Istanbul is de veerboot over de Bosporus: thee in een tulpglas, meeuwen naast de reling, en de stad die aan beide kanten oprijst.\n\nEet je door de dag heen: simit bij het ontbijt, een balik ekmek (visbroodje) aan de kade, meze in een meyhane in Beyoglu. De Grote Bazaar is theater; de kruidenbazaar ruikt beter.\n\nPraktisch: koop een openbaar vervoer kaart voor tram en veerboot. Kleed je bedekt in moskeeën; sjaals liggen bij de ingang. En neem de tijd voor thee als een winkelier hem aanbiedt; dat is gastvrijheid, geen verkooptruc.'],
  ['marrakech', 'Marrakech', 'Midden-Oosten & Noord-Afrika', 'Marrakech: het rode labyrint',
    'Marrakech overweldigt, en dat is precies de bedoeling. Het Djemaa el-Fna plein verandert elk uur van gedaante: sinaasappelsap in de ochtend, verhalenvertellers in de middag, rooksliert van honderd grills in de avond. De soeks erachter zijn een doolhof; verdwalen hoort erbij, en elke uitgang komt ergens goed uit. Zoek de rust van de Jardin Majorelle en het Bahia paleis als de medina te veel wordt.\n\nEet tajine waar de lokale werklui eten, drink muntthee op een dakterras, en waag je aan de nachtelijke eetkramen; kies de kraam met de langste rij Marokkanen.\n\nPraktisch: onderhandel met een glimlach en zonder haast; het is een spel, geen strijd. Sla een aanbod nooit bot af. En logeer in een riad in de medina; de stilte achter die dikke muren is de helft van de ervaring.'],
  ['cairo', 'Caïro', 'Midden-Oosten & Noord-Afrika', 'Caïro en de piramides: vijfduizend jaar in een dag',
    'De piramides van Gizeh staan niet in de woestijn maar aan de rand van de stad, en juist dat contrast maakt ze onwerkelijk: de laatste van de zeven wereldwonderen, met een miljoenenstad aan haar voeten. Ga bij opening, huur een gids die je zelf kiest, en neem de tijd voor de sfinx. Het nieuwe Grote Egyptische Museum bij Gizeh bundelt de schatten, met Toetanchamon als hart.\n\nCaïro zelf is luid, warm en gul. De Khan el-Khalili bazaar, koffie met kardemom, koshari (het nationale gerecht van pasta, rijst en linzen) voor een paar euro.\n\nPraktisch: het verkeer is een belevenis; neem voor afstanden een taxi via een app. Vrouwen reizen er comfortabeler met bedekte schouders. En koop water in flessen, overal verkrijgbaar.'],
  ['jeruzalem', 'Jeruzalem', 'Midden-Oosten & Noord-Afrika', 'Jeruzalem: de stad die iedereen heilig is',
    'Weinig plekken dragen zoveel betekenis op zo weinig vierkante meters. Binnen de muren van de oude stad liggen de Klaagmuur, de Heilig Grafkerk en de Rotskoepel op loopafstand van elkaar; drie werelden, een plattegrond. Loop de vier kwartieren (joods, christelijk, islamitisch, Armeens) met open ogen en zachte stem; dit is voor miljarden mensen geen bezienswaardigheid maar een gebed.\n\nDe markt van Machane Yehuda is de tegenpool: luid, jong en vol smaak, van hummus tot moderne keukens.\n\nPraktisch: kleed je bescheiden bij heilige plaatsen en vraag voordat je mensen fotografeert. De politieke situatie is er dagelijkse werkelijkheid; volg het reisadvies, luister meer dan je oordeelt, en laat de stad je eerder stiller dan stelliger maken.'],
  ['dubai', 'Dubai', 'Midden-Oosten & Noord-Afrika', 'Dubai: de stad die zichzelf tekende',
    'Dubai is een stad die in een generatie uit het zand is getekend, en die dat trots laat zien. De Burj Khalifa bij zonsondergang, de souks aan de kreek waar goud en saffraan naast elkaar liggen, en een abra (houten veerbootje) voor een paar cent over het water: het oude en het gloednieuwe liggen een vaart van elkaar.\n\nEet breed: de stad is voor negentig procent migrant, dus de beste maaltijden zijn Indiaas, Libanees, Iraans of Filipijns, vaak in eenvoudige zaken in Deira. De woestijn begint een half uur verderop; een avond tussen de duinen relativeert de skyline.\n\nPraktisch: van november tot maart is het buitenweer volmaakt; in de zomer leef je binnen. Kleed je licht maar niet bloot in winkelcentra, en respecteer de regels rond ramadan als je dan reist.'],
  ['kaapstad', 'Kaapstad', 'Afrika', 'Kaapstad: berg, oceaan en geschiedenis',
    'Weinig steden hebben zo\'n decor: de Tafelberg valt recht de oceaan in en elke straat kijkt ergens tegenaan. Neem de kabelbaan (of loop via Platteklip Gorge) op een heldere ochtend; de wolk die "het tafelkleed" heet, komt vaak in de middag. Rij de kustweg Chapman\'s Peak naar Kaap de Goede Hoop en zie de pinguïns bij Boulders Beach.\n\nRobbeneiland, de gevangenis van Mandela, is geen uitje maar een les; boek vooraf en luister naar de gidsen, vaak oud-gevangenen. Eet in de V&A Waterfront voor het gemak, maar beter in de buurten: Kaaps-Maleise curry in Bo-Kaap, wijn en lange lunches in Constantia.\n\nPraktisch: de wijnlanden (Stellenbosch, Franschhoek) liggen op een uur; neem een chauffeur. Wees, zoals overal, verstandig met waardevolle spullen en reis na zonsondergang per auto.'],
  ['zanzibar', 'Zanzibar', 'Afrika', 'Zanzibar: specerijen en getijden',
    'Zanzibar ruikt naar kruidnagel; het eiland leefde eeuwen van specerijen en die geschiedenis loop je na in Stone Town, een doolhof van gebeeldhouwde deuren, binnenplaatsen en de zware erfenis van de slavenmarkt, die je bezoeken moet. In de avond vult de Forodhani tuin zich met grills en lantaarns.\n\nDe stranden in het oosten (Paje, Jambiani) hebben een groot getijverschil: bij eb loop je honderden meters door lagunes, bij vloed is het water turkoois en diep. In het noorden (Nungwi) kun je altijd zwemmen. Vaar een keer mee op een dhow bij zonsondergang.\n\nPraktisch: het eiland is overwegend islamitisch; bedek schouders en knieën buiten het strand. Juni tot oktober is droog en zacht; de regens vallen vooral in april en mei.'],
  ['tokio', 'Tokio', 'Azië', 'Tokio: de stilste metropool ter wereld',
    'Tokio is de grootste stad op aarde en tegelijk de best geordende: treinen op de seconde, stille wijken op vijf minuten van neonkruispunten. Sta een keer in de mensenzee van Shibuya, maar besteed je dagen aan de buurten: Yanaka voor het oude Tokio, Shimokitazawa voor vintage en koffie, Asakusa voor de Senso-ji tempel in de vroege ochtend.\n\nEten is hier de nationale kunstvorm: een kom ramen aan een bar, sushi bij een zaak met tien stoelen, een izakaya avond met kleine gerechten en veel gelach. Ook het eten van de supermarkt en de stationsbento is goed; slecht eten vergt in Tokio moeite.\n\nPraktisch: koop een oplaadbare vervoerskaart (Suica of Pasmo) en houd links op de roltrap. Praat zacht in de trein en bel er niet; die rust is een gezamenlijke keuze en de stad geeft haar je terug.'],
  ['kioto', 'Kioto', 'Azië', 'Kioto: duizend tempels, een stille ochtend',
    'Kioto was duizend jaar de keizerlijke hoofdstad en draagt dat kalm. De gouden Kinkaku-ji, de rode poorten van Fushimi Inari en het bamboebos van Arashiyama zijn beroemd en dus druk; het geheim is het uur: bij Fushimi Inari om zeven uur in de ochtend loop je vrijwel alleen tussen de poorten omhoog.\n\nNeem daarnaast een tempel zonder naam op je route en blijf er zitten; de tuinen zijn gemaakt om lang naar te kijken, niet om af te vinken. In Gion zie je in de schemer soms een geiko of maiko op weg naar een afspraak; kijk met respect en fotografeer niet in haar gezicht.\n\nEet kaiseki als het budget het toelaat, of de eenvoudige tegenhanger: een kom udon, tofu in een tempelrestaurant, matcha met een zoetigheid aan de Kamo rivier. Praktisch: huur een fiets; de stad is er vlak en volmaakt voor.'],
  ['bangkok', 'Bangkok', 'Azië', 'Bangkok: de stad die op straat kookt',
    'Bangkok leeft op straat en op het water. Het Grote Paleis en de liggende Boeddha van Wat Pho zijn overweldigend goud; ga vroeg en drink daarna kokoswater in de schaduw. Neem de rivierboot als openbaar vervoer, en een longtail door de klongs (grachten) van Thonburi, waar de stad ineens dorp wordt.\n\nHet eten van Bangkok is het beste straateten ter wereld: een kom noedelsoep op een plastic kruk, pad thai van een kar, mango met kleefrijst als toetje. Kies kramen waar de omzet hoog is en de wok heet.\n\nPraktisch: onderhandel bij tuktuks vooraf of neem de meter taxi en de skytrain. Kleed je bedekt in tempels en raak nooit iemands hoofd aan; de wai (buiging met samengevouwen handen) terugkrijgen doe je met dezelfde groet.'],
  ['bali', 'Bali', 'Azië', 'Bali: rijstterrassen en tempelbloemen',
    'Bali is een hindoeïstisch eiland in de grootste moslimarchipel ter wereld, en die eigenheid zie je overal: dagelijkse offermandjes op de stoep, tempelfeesten met gamelan, wierook in de ochtendlucht. Ubud is het culturele hart, met de rijstterrassen van Tegalalang en rustiger, mooier, die van Jatiluwih. De zonsopgang vanaf de Batur vulkaan is de vroege opstaan waard.\n\nDe kust is voor iedereen wat: surfen in Canggu, kalme baaien in Amed in het oosten, de kliftempel Uluwatu bij zonsondergang met de kecak dans.\n\nEet nasi campur bij een warung, betaal er een paar euro en eet beter dan in menig resort. Praktisch: huur een scooter alleen met ervaring en helm; het verkeer is de grootste valkuil van het eiland. Draag een sarong in tempels; die liggen bij de ingang.'],
  ['singapore', 'Singapore', 'Azië', 'Singapore: drie keukens, een stad',
    'Singapore is de gemakkelijkste stap in Azië: geordend, groen en veilig, met drie grote culturen (Chinees, Maleis, Indiaas) die elkaar al eeuwen aanvullen. De Gardens by the Bay met hun supertrees zijn futuristisch theater; de buurten Chinatown, Kampong Glam en Little India zijn de ziel.\n\nHet hart van de stad klopt in de hawker centres: overdekte hallen vol kraampjes, waar een michelinwaardige kip met rijst een paar euro kost. Eet laksa, satay, roti prata en chili crab; sta in de langste rij, die heeft altijd gelijk.\n\nPraktisch: de metro is vlekkeloos en aircokoud; neem een vestje mee. De regels zijn er echt (geen kauwgom, niet eten in de metro, forse boetes) en juist daardoor werkt alles. Drie tot vier dagen is genoeg; combineer met de buurlanden.'],
  ['delhi-agra', 'Delhi & Agra', 'Azië', 'Delhi en de Taj Mahal: overgave aan India',
    'Delhi is twee steden: het brede, koloniale New Delhi en het kolkende Old Delhi, waar de Jama Masjid boven een zee van steegjes uitrijst. Neem een fietsriksja door Chandni Chowk, eet parathas in de steeg die ernaar genoemd is, en zoek daarna de stilte van het graf van Humayun, de voorstudie van de Taj.\n\nDe Taj Mahal in Agra, twee tot drie uur sporen verderop, is het enige monument ter wereld dat mooier is dan zijn foto. Ga bij zonsopgang: het marmer kleurt van roze naar wit, en een uur lang is het stil genoeg om te begrijpen dat dit een graf uit liefde is.\n\nPraktisch: reis met de vroege sneltrein, boek treinen en toegang vooraf, en drink alleen flessenwater. India vraagt overgave; wie de chaos accepteert in plaats van bestrijdt, krijgt er het meest voor terug.'],
  ['new-york', 'New York', 'Amerika\'s', 'New York: de stad die je al kent',
    'New York voelt bij aankomst al bekend; de stad is het decor van honderd films. Juist daarom werkt het om de iconen slim te doen: de Staten Island veerboot is gratis en vaart vlak langs het Vrijheidsbeeld; de Brooklyn Bridge loop je bij zonsopgang; Central Park is op zijn mooist op een doordeweekse ochtend. De High Line, een park op een oud spoorviaduct, is de beste wandeling van Manhattan.\n\nEet zoals de stad: een bagel met lox in de ochtend, een dollar pizzapunt onderweg, dumplings in Flushing, en een lange avond in een klein restaurant in de West Village of Brooklyn.\n\nPraktisch: de metro rijdt altijd en je betaalpas is je kaartje. Loop veel; de stad is een raster en verdwalen is er bijna onmogelijk. Reken op fooien van rond de twintig procent; dat is er loon, geen extraatje.'],
  ['mexico-stad', 'Mexico-Stad', 'Amerika\'s', 'Mexico-Stad: de onderschatte reus',
    'Mexico-Stad is een van de grootste steden ter wereld en een van de meest onderschatte: gebouwd op een drooggelegd meer, boven op de Azteekse hoofdstad Tenochtitlan. Op het reusachtige Zócalo plein zie je de lagen letterlijk: de kathedraal, het paleis met de muurschilderingen van Diego Rivera, en de opgegraven Templo Mayor ertussen. De piramides van Teotihuacan liggen op een uur; ga vroeg.\n\nDe wijken Roma en Condesa zijn groen en ontspannen, vol koffie, boekwinkels en de beste restaurants van Latijns-Amerika. Maar eet ook op straat: tacos al pastor van de draaiende spies, tamales in de ochtend, churros bij El Moro om middernacht.\n\nPraktisch: de stad ligt op 2.240 meter; doe de eerste dag rustig aan. Neem taxi\'s via een app en drink flessenwater. Het weekendbezoek aan de drijvende tuinen van Xochimilco is luid, gekleurd en volkomen Mexicaans.'],
  ['cusco', 'Cusco & Machu Picchu', 'Amerika\'s', 'Cusco en Machu Picchu: de navel van de wereld',
    'Cusco was de hoofdstad van het Inca rijk (de naam betekent "navel van de wereld") en de Spanjaarden bouwden hun kerken letterlijk op de Inca muren; in de Qorikancha zonnetempel zie je beide lagen in een gebouw. Neem twee dagen om te wennen aan de hoogte van 3.400 meter: coca thee, langzaam lopen, licht eten.\n\nDe Heilige Vallei (Pisac, Ollantaytambo) is meer dan een tussenstop; de terrassen en markten verdienen een eigen dag. Machu Picchu zelf bereik je per trein of via de Inca Trail; boek beide maanden vooraf. Sta bij de zonnepoort als de mist optrekt en de stad onder je opdoemt; geen foto bereidt je erop voor.\n\nPraktisch: koopjes en tickets zijn er gereguleerd; koop alleen via de officiële kanalen. Het droge seizoen loopt van mei tot september; de ochtenden zijn koud, de middagzon fel.'],
  ['rio', 'Rio de Janeiro', 'Amerika\'s', 'Rio de Janeiro: de wonderbaarlijke stad',
    'Rio noemt zichzelf de Cidade Maravilhosa en maakt dat waar: bergen van glad graniet rijzen recht uit zee en stad op. Ga met de trein door het regenwoud omhoog naar de Christus de Verlosser en neem de kabelbaan naar de Suikerbroodberg bij zonsondergang; de baai kleurt dan goud. De stranden zijn de huiskamer van de stad: Ipanema bij post 9 om te kijken en gezien te worden, Copacabana voor de ochtendwandeling.\n\nEet en drink Braziliaans: een caipirinha bij een strandkiosk, feijoada op zaterdagmiddag, açai uit een beker. In Lapa wordt in het weekend op straat samba gedanst; ga met weinig op zak en veel zin.\n\nPraktisch: laat sieraden en horloge in het hotel, neem het strand serieus (sterke stroming) en gebruik taxi apps in de avond. De stad beloont nuchtere voorzichtigheid met de grootste levensvreugde van het halfrond.'],
  ['sydney', 'Sydney', 'Oceanië', 'Sydney: leven om een haven heen',
    'Sydney is gebouwd rond de mooiste natuurlijke haven ter wereld en de stad gebruikt haar ook: veerboten zijn er openbaar vervoer en het mooiste uitje tegelijk. Vaar naar Manly voor het strand en de wandeling langs de kust, kijk vanaf het water naar het Opera House en loop over de Harbour Bridge terug.\n\nDe kustwandeling van Bondi naar Coogee is twee uur zeeklif, baaien en oceaanzwembaden; neem zwemgoed mee en zwem tussen de vlaggen. In de wijken Surry Hills en Newtown vind je de koffiecultuur waar Australië terecht verwaand over is.\n\nPraktisch: het zonlicht is er scherper dan thuis; smeer je elke twee uur in, ook bij bewolking. Betaal het openbaar vervoer gewoon met je bankpas. December tot februari is hoogzomer; maart en november zijn zachter en rustiger.'],
  ['queenstown', 'Queenstown & Fiordland', 'Oceanië', 'Queenstown en Fiordland: het einde van de wereld',
    'Het zuiden van Nieuw-Zeeland is landschap in overtreffende trap: bergen die recht uit meren oprijzen, en fjorden waar watervallen uit de wolken vallen. Queenstown is de basis; wie durft springt er aan een elastiek (de bungee is er uitgevonden), wie liever kijkt neemt de gondel en de wandelpaden.\n\nMilford Sound is de beroemdste dagtocht: de weg erheen is al de helft van het wonder. Vaar de fjord in de regen zonder teleurstelling; juist dan zijn er duizend watervallen. Wandel een dagdeel van een van de Great Walks (Routeburn, Kepler) om te begrijpen waarom dit land wandelen als nationale sport heeft.\n\nPraktisch: het weer draait er per uur; draag lagen en een regenjas, altijd. Boek Milford en de hutten van de Great Walks ver vooruit. En rij zelf: de wegen zijn leeg, de uitzichten niet.']
];

module.exports = { GIDSEN: G };
