/* ============================================================================
   DE LIJST -- negenenvijftig poorten, elk gelezen.

   De uitleg staat in ./index.js: waarom deze lijst bestaat, waarom de sleutel de
   NAAM is (en niet bestand:naam, wat de eerste poging was), en waarom een
   genre-eis hier geen CAPABILITY_GATED heet. Hier alleen wat elke poort DOET --
   dat is de tekst die je erbij pakt als je een route indeelt, en die hoort niet
   weggestopt onder drie pagina's uitleg.

   naam -> { toegang, veld?, versmalt?, genre?, soort?, wat }
   ========================================================================== */
'use strict';

const POORTEN = {
  /* ---- OBJECT_SCOPED: een code of token uit het lichaam wijst het object aan ---- */

  'familieVan': { toegang: 'OBJECT_SCOPED', veld: 'code',
    wat: 'gezinssessie (code + token) en daarbinnen geen gast: dit hoort bij de privezaken van het gezin' },
  'sessieVan': { toegang: 'OBJECT_SCOPED', veld: 'code',
    wat: 'gezinssessie: gezinVan(req.body.code) plus profielVan(token)' },
  'gezinVan': { toegang: 'OBJECT_SCOPED', veld: 'code',
    wat: 'zoekt het gezin bij req.body.code; 404 als het niet bestaat' },
  'gezinSessie': { toegang: 'OBJECT_SCOPED', veld: 'code',
    wat: 'gezin + profiel, met de vraag of dit een beheerder of ouder is' },
  'klasVan': { toegang: 'OBJECT_SCOPED', veld: 'klasCode',
    wat: 'klas bij req.body.klasCode, met leraar-, personeel- of beheertoken' },
  'personeelVan': { toegang: 'OBJECT_SCOPED', veld: 'schoolCode',
    wat: 'school bij schoolCode plus een personeelToken dat daarin bestaat' },
  'schoolVan': { toegang: 'OBJECT_SCOPED', veld: 'schoolCode',
    wat: 'school bij schoolCode plus het beheerToken van die school' },
  'poort': { toegang: 'OBJECT_SCOPED', veld: 'schoolCode',
    wat: 'school plus beheer- of personeelToken, en daarna een recht binnen die school' },
  'mijn': { toegang: 'OBJECT_SCOPED', veld: 'schoolCode',
    wat: 'personeelVan() plus het eigen mailadres binnen die school' },
  'lesVan': { toegang: 'OBJECT_SCOPED', veld: 'code',
    wat: 'de les bij req.body.code; 404 op een onbekende lescode' },
  'rtfSociaal': { toegang: 'OBJECT_SCOPED', veld: 'code',
    wat: 'gezinsprofiel (code + token) en geen gast' },
  'profiel': { toegang: 'OBJECT_SCOPED', veld: 'code',
    wat: 'gezinsprofiel via rtf.verifieerProfiel(code, token)' },
  'profiel': { toegang: 'OBJECT_SCOPED', veld: 'code',
    wat: 'gezinsprofiel via rtf.verifieerProfiel(code, token)' },
  'profiel': { toegang: 'OBJECT_SCOPED', veld: 'code',
    wat: 'gezinsprofiel via rtf.verifieerProfiel(code, token)' },
  'samenSess': { toegang: 'OBJECT_SCOPED', veld: 'code',
    wat: 'gezinsprofiel en geen gast: Samen is voor het gezin en vrienden' },
  'rtfSpeler': { toegang: 'OBJECT_SCOPED', veld: 'code',
    wat: 'gezinsprofiel en geen gast' },
  'werkPoort': { toegang: 'OBJECT_SCOPED', veld: 'werkruimte',
    wat: 'beheerToken of lidToken binnen een werkruimte, plus een recht' },
  'lidVan': { toegang: 'OBJECT_SCOPED', veld: 'werkruimte',
    wat: 'lidToken binnen een werkruimte -- NIET kern/agenda-pro.js:lidVan, die knipt een prefix' },
  'beheerVan': { toegang: 'OBJECT_SCOPED', veld: 'werkruimte',
    wat: 'beheerToken van een werkruimte -- NIET kern/office/samen.js:beheerVan, die normaliseert velden' },
  'viaBeheerOfDirectie': { toegang: 'OBJECT_SCOPED', veld: 'werkruimte',
    wat: 'beheerToken van de werkruimte, of de directie erboven' },
  'rekVan': { toegang: 'OBJECT_SCOPED', veld: 'rekeningId',
    wat: 'de rekening bij rekeningId, binnen de eigen zaak' },
  'rekeningVan': { toegang: 'OBJECT_SCOPED', veld: 'rekeningId',
    wat: 'de order bij rekeningId, binnen de eigen zaak' },
  'eventVan': { toegang: 'OBJECT_SCOPED', veld: 'eventId',
    wat: 'het event bij eventId, binnen de eigen zaak' },
  'eigenRekening': { toegang: 'OBJECT_SCOPED', veld: 'zaak',
    wat: 'de zaak uit het lichaam, en daarbinnen de eigen rekening' },
  'zaakVan': { toegang: 'OBJECT_SCOPED', veld: 'zaak',
    wat: 'de zaak uit het lichaam; 404 op een onbekende code' },
  'zaakVan': { toegang: 'OBJECT_SCOPED', veld: 'zaak',
    wat: 'de zaak uit het lichaam; 404 op een onbekende code' },
  'mijnCharter': { toegang: 'OBJECT_SCOPED', veld: 'ref',
    wat: 'de charterboeking bij ref, en die moet van deze sessie zijn' },
  'mijnHuur': { toegang: 'OBJECT_SCOPED', veld: 'ref',
    wat: 'de huurboeking bij ref, en die moet van deze sessie zijn' },
  'ritVanZaak': { toegang: 'OBJECT_SCOPED', veld: 'ref',
    wat: 'de opdracht bij ref, en de vervoerder moet de eigen zaak zijn' },
  'werktDaar': { toegang: 'OBJECT_SCOPED', veld: 'werkgever',
    wat: 'de werkgever uit het lichaam, en dit lid moet daar werken' },
  'lijnVan': { toegang: 'OBJECT_SCOPED', veld: 'key',
    wat: 'het gesprek uit de sleutel in het lichaam, en dat moet van de eigen zaak zijn' },
  'dmCollega': { toegang: 'OBJECT_SCOPED', veld: 'staffId',
    wat: 'een collega bij staffId, binnen dezelfde zaak en niet jezelf' },
  'eigenPostvak': { toegang: 'OBJECT_SCOPED', veld: 'adres',
    wat: 'het postvak uit het lichaam moet bij de persoonlijke inlog horen' },

  /* ---- AUTHENTICATED: de identiteit staat al vast, deze poort versmalt hem ---- */

  'geenGast': { toegang: 'AUTHENTICATED', versmalt: 'geen anonieme demo-gast',
    wat: 'een echt account mag, ook de gratis laag; alleen een anonieme gast niet' },
  'eisAccount': { toegang: 'AUTHENTICATED', versmalt: 'een eigen RTG-account',
    wat: 'req.session.account moet bestaan' },
  'managerOnly': { toegang: 'AUTHENTICATED', versmalt: 'manager',
    wat: 'req.actor.manager, gezet door supplierAuth' },
  'managerOf': { toegang: 'AUTHENTICATED', versmalt: 'manager',
    wat: 'req.actor.manager, gezet door supplierAuth' },
  'actor': { toegang: 'AUTHENTICATED', versmalt: 'een zaak in de sessie',
    wat: 'wie.vanZaak(req); 401 zonder zaak' },
  'alleenPersoneel': { toegang: 'AUTHENTICATED', versmalt: 'personeelslogin',
    wat: 'req.actor.staffId moet bestaan voor het personeelsstuur' },
  'alleenBaas': { toegang: 'AUTHENTICATED', versmalt: 'de eigenaar',
    wat: 'isBaas(req) -- alleen de eigenaar komt bij het papierwerk' },
  'eigenaarAlleen': { toegang: 'AUTHENTICATED', versmalt: 'de eigenaar',
    wat: 'eigenaar.isEigenaar(accounts, req.session.account) -- alleen de eigenaar beheert de platform-onboarding' },
  'lid': { toegang: 'AUTHENTICATED', versmalt: 'geen gast',
    wat: 'req.session.tier !== guest' },
  'gast': { toegang: 'AUTHENTICATED', versmalt: 'geen gast',
    wat: 'RTG Bank is voor leden' },
  'gate': { toegang: 'AUTHENTICATED', versmalt: 'geen gast, en de bank moet live zijn',
    wat: 'gast() plus dicht(): een schakelaar en een identiteit in een poort' },
  'geenEchtAccount': { toegang: 'AUTHENTICATED', versmalt: 'een echt account',
    wat: 'een anonieme gast kan niet met RTG Pay betalen' },
  'geenEchtAccount': { toegang: 'AUTHENTICATED', versmalt: 'een echt account',
    wat: 'een anonieme gast kan niet met RTG Pay betalen' },
  'echtAccount': { toegang: 'AUTHENTICATED', versmalt: 'een echt account',
    wat: 'de algemene pin hoort bij een echt RTG-account' },
  'echtAccount': { toegang: 'AUTHENTICATED', versmalt: 'een echt account',
    wat: 'de rollenkoppeling hoort bij een echt RTG-account' },
  'eigenSleutel': { toegang: 'AUTHENTICATED', versmalt: 'een echt account',
    wat: 'een vakbewijs hoort bij een echt RTG-account' },
  'echtLid': { toegang: 'AUTHENTICATED', versmalt: 'een echt account',
    wat: 'meedoen aan het Lab-fonds vraagt een gratis RTG-account' },
  'ontmoetKey': { toegang: 'AUTHENTICATED', versmalt: 'een echt account',
    wat: 'eisAccount() en dan de eigen sessiesleutel' },
  'lidOk': { toegang: 'AUTHENTICATED', versmalt: 'Business Pass',
    wat: 'borden zijn onderdeel van de Business Pass' },
  'eis': { toegang: 'AUTHENTICATED', versmalt: 'Lifestyle of Business Pass',
    wat: 'deze app is onderdeel van de Lifestyle Pass' },
  'eis': { toegang: 'AUTHENTICATED', versmalt: 'Lifestyle of Business Pass',
    wat: 'Rendez-vous is voor Signature-members' },
  'kyc': { toegang: 'AUTHENTICATED', versmalt: 'kyc afgerond',
    wat: 'onboarding.payGate(req.session)' },

  /* ---- genre-cap: WAT VOOR SOORT ZAAK is dit. Geen capability -- zie de kop ---- */

  'eisRetail': { toegang: 'AUTHENTICATED', genre: 'retail',
    wat: "db.capsVan(req.supplier).includes('retail')" },
  'eisVracht': { toegang: 'AUTHENTICATED', genre: 'vracht',
    wat: "db.capsVan(req.supplier).includes('vracht')" },
  'eisVak': { toegang: 'AUTHENTICATED', genre: 'vak',
    wat: 'vak().isVak(req.supplier) -- alleen voor dienstverlenende zaken' },
  'eisDorp': { toegang: 'AUTHENTICATED', genre: 'verblijf-afdelingen',
    wat: 'dorpKan(req.supplier) -- heeft deze zaak een afdelingenbord' },
  'eisBeveiliging': { toegang: 'AUTHENTICATED', genre: 'beveiliging',
    wat: 'bevIsBeveiliging(req.supplier)' },
  'eisGroothandel': { toegang: 'AUTHENTICATED', genre: 'groothandel',
    wat: 'de zaak moet een groothandel zijn' },
  'ovZaakOnly': { toegang: 'AUTHENTICATED', genre: 'ov',
    wat: "req.supplier.type !== 'ov'" },
  'ovZaakOnly': { toegang: 'AUTHENTICATED', genre: 'ov',
    wat: "req.supplier.type !== 'ov'" },
  'eisSalonProfiel': { toegang: 'AUTHENTICATED', genre: 'salon',
    wat: 'de zaak moet een salonprofiel hebben' },
  'eisSalonProfiel': { toegang: 'AUTHENTICATED', genre: 'salon',
    wat: 'de zaak moet een salonprofiel hebben' },

  /* ---- geen deur: wel een rem, geen identiteit ---- */

  'geremd': { toegang: null, soort: 'geen-deur',
    wat: 'uitsluitend een snelheidsrem per IP; stelt geen identiteit vast' },
  'doosSleutelOk': { toegang: null, soort: 'geen-deur',
    wat: 'telt afketsers per IP voordat de sleutel wordt gecontroleerd; de rem, niet de deur' }
};

module.exports = { POORTEN };
