/* Reis-Bibliotheek: de gidsen van Amerika's.

   Eigen RTG-redactie: sfeer en hoogtepunten, eten, en een praktisch woord.
   Eerlijk en zonder opsmuk; geen boekingslinks, geen reclame. Kwaliteit boven
   aantal, dus deze lijst groeit langzaam en met opzet.

   Vorm per gids: [id, plaats, werelddeel, titel, tekst]. */
module.exports = [
  ['new-york', 'New York', 'Amerika\'s', 'New York: de stad die je al kent',
    'New York voelt bij aankomst al bekend; de stad is het decor van honderd films. Juist daarom werkt het om de iconen slim te doen: de Staten Island veerboot is gratis en vaart vlak langs het Vrijheidsbeeld; de Brooklyn Bridge loop je bij zonsopgang; Central Park is op zijn mooist op een doordeweekse ochtend. De High Line, een park op een oud spoorviaduct, is de beste wandeling van Manhattan.\n\nEet zoals de stad: een bagel met lox in de ochtend, een dollar pizzapunt onderweg, dumplings in Flushing, en een lange avond in een klein restaurant in de West Village of Brooklyn.\n\nPraktisch: de metro rijdt altijd en je betaalpas is je kaartje. Loop veel; de stad is een raster en verdwalen is er bijna onmogelijk. Reken op fooien van rond de twintig procent; dat is er loon, geen extraatje.'],
  ['mexico-stad', 'Mexico-Stad', 'Amerika\'s', 'Mexico-Stad: de onderschatte reus',
    'Mexico-Stad is een van de grootste steden ter wereld en een van de meest onderschatte: gebouwd op een drooggelegd meer, boven op de Azteekse hoofdstad Tenochtitlan. Op het reusachtige Zócalo plein zie je de lagen letterlijk: de kathedraal, het paleis met de muurschilderingen van Diego Rivera, en de opgegraven Templo Mayor ertussen. De piramides van Teotihuacan liggen op een uur; ga vroeg.\n\nDe wijken Roma en Condesa zijn groen en ontspannen, vol koffie, boekwinkels en de beste restaurants van Latijns-Amerika. Maar eet ook op straat: tacos al pastor van de draaiende spies, tamales in de ochtend, churros bij El Moro om middernacht.\n\nPraktisch: de stad ligt op 2.240 meter; doe de eerste dag rustig aan. Neem taxi\'s via een app en drink flessenwater. Het weekendbezoek aan de drijvende tuinen van Xochimilco is luid, gekleurd en volkomen Mexicaans.'],
  ['cusco', 'Cusco & Machu Picchu', 'Amerika\'s', 'Cusco en Machu Picchu: de navel van de wereld',
    'Cusco was de hoofdstad van het Inca rijk (de naam betekent "navel van de wereld") en de Spanjaarden bouwden hun kerken letterlijk op de Inca muren; in de Qorikancha zonnetempel zie je beide lagen in een gebouw. Neem twee dagen om te wennen aan de hoogte van 3.400 meter: coca thee, langzaam lopen, licht eten.\n\nDe Heilige Vallei (Pisac, Ollantaytambo) is meer dan een tussenstop; de terrassen en markten verdienen een eigen dag. Machu Picchu zelf bereik je per trein of via de Inca Trail; boek beide maanden vooraf. Sta bij de zonnepoort als de mist optrekt en de stad onder je opdoemt; geen foto bereidt je erop voor.\n\nPraktisch: koopjes en tickets zijn er gereguleerd; koop alleen via de officiële kanalen. Het droge seizoen loopt van mei tot september; de ochtenden zijn koud, de middagzon fel.'],
  ['rio', 'Rio de Janeiro', 'Amerika\'s', 'Rio de Janeiro: de wonderbaarlijke stad',
    'Rio noemt zichzelf de Cidade Maravilhosa en maakt dat waar: bergen van glad graniet rijzen recht uit zee en stad op. Ga met de trein door het regenwoud omhoog naar de Christus de Verlosser en neem de kabelbaan naar de Suikerbroodberg bij zonsondergang; de baai kleurt dan goud. De stranden zijn de huiskamer van de stad: Ipanema bij post 9 om te kijken en gezien te worden, Copacabana voor de ochtendwandeling.\n\nEet en drink Braziliaans: een caipirinha bij een strandkiosk, feijoada op zaterdagmiddag, açai uit een beker. In Lapa wordt in het weekend op straat samba gedanst; ga met weinig op zak en veel zin.\n\nPraktisch: laat sieraden en horloge in het hotel, neem het strand serieus (sterke stroming) en gebruik taxi apps in de avond. De stad beloont nuchtere voorzichtigheid met de grootste levensvreugde van het halfrond.']
];
