/* Reis-Bibliotheek: de gidsen van Azië.

   Eigen RTG-redactie: sfeer en hoogtepunten, eten, en een praktisch woord.
   Eerlijk en zonder opsmuk; geen boekingslinks, geen reclame. Kwaliteit boven
   aantal, dus deze lijst groeit langzaam en met opzet.

   Vorm per gids: [id, plaats, werelddeel, titel, tekst]. */
module.exports = [
  ['tokio', 'Tokio', 'Azië', 'Tokio: de stilste metropool ter wereld',
    'Tokio is de grootste stad op aarde en tegelijk de best geordende: treinen op de seconde, stille wijken op vijf minuten van neonkruispunten. Sta een keer in de mensenzee van Shibuya, maar besteed je dagen aan de buurten: Yanaka voor het oude Tokio, Shimokitazawa voor vintage en koffie, Asakusa voor de Senso-ji tempel in de vroege ochtend.\n\nEten is hier de nationale kunstvorm: een kom ramen aan een bar, sushi bij een zaak met tien stoelen, een izakaya avond met kleine gerechten en veel gelach. Ook het eten van de supermarkt en de stationsbento is goed; slecht eten vergt in Tokio moeite.\n\nPraktisch: koop een oplaadbare vervoerskaart (Suica of Pasmo) en houd links op de roltrap. Praat zacht in de trein en bel er niet; die rust is een gezamenlijke keuze en de stad geeft haar je terug.'],
  ['kioto', 'Kioto', 'Azië', 'Kioto: duizend tempels, een stille ochtend',
    'Kioto was duizend jaar de keizerlijke hoofdstad en draagt dat kalm. De gouden Kinkaku-ji, de rode poorten van Fushimi Inari en het bamboebos van Arashiyama zijn beroemd en dus druk; het geheim is het uur: bij Fushimi Inari om zeven uur in de ochtend loop je vrijwel alleen tussen de poorten omhoog.\n\nNeem daarnaast een tempel zonder naam op je route en blijf er zitten; de tuinen zijn gemaakt om lang naar te kijken, niet om af te vinken. In Gion zie je in de schemer soms een geiko of maiko op weg naar een afspraak; kijk met respect en fotografeer niet in haar gezicht.\n\nEet kaiseki als het budget het toelaat, of de eenvoudige tegenhanger: een kom udon, tofu in een tempelrestaurant, matcha met een zoetigheid aan de Kamo rivier. Praktisch: huur een fiets; de stad is er vlak en volmaakt voor.'],
  ['bangkok', 'Bangkok', 'Azië', 'Bangkok: de stad die op straat kookt',
    'Bangkok leeft op straat en op het water. Het Grote Paleis en de liggende Boeddha van Wat Pho zijn overweldigend goud; ga vroeg en drink daarna kokoswater in de schaduw. Neem de rivierboot als openbaar vervoer, en een longtail door de klongs (grachten) van Thonburi, waar de stad ineens dorp wordt.\n\nHet eten van Bangkok is het beste straateten ter wereld: een kom noedelsoep op een plastic kruk, pad thai van een kar, mango met kleefrijst als toetje. Kies kramen waar de omzet hoog is en de wok heet.\n\nPraktisch: onderhandel bij tuktuks vooraf of neem de meter taxi en de skytrain. Kleed je bedekt in tempels en raak nooit iemands hoofd aan; de wai (buiging met samengevouwen handen) terugkrijgen doe je met dezelfde groet.'],
  ['bali', 'Bali', 'Azië', 'Bali: rijstterrassen en tempelbloemen',
    'Bali is een hindoeïstisch eiland in de grootste moslimarchipel ter wereld, en die eigenheid zie je overal: dagelijkse offermandjes op de stoep, tempelfeesten met gamelan, wierook in de ochtendlucht. Ubud is het culturele hart, met de rijstterrassen van Tegalalang en rustiger, mooier, die van Jatiluwih. De zonsopgang vanaf de Batur vulkaan is de vroege opstaan waard.\n\nDe kust is voor iedereen wat: surfen in Canggu, kalme baaien in Amed in het oosten, de kliftempel Uluwatu bij zonsondergang met de kecak dans.\n\nEet nasi campur bij een warung, betaal er een paar euro en eet beter dan in menig resort. Praktisch: huur een scooter alleen met ervaring en helm; het verkeer is de grootste valkuil van het eiland. Draag een sarong in tempels; die liggen bij de ingang.'],
  ['singapore', 'Singapore', 'Azië', 'Singapore: drie keukens, een stad',
    'Singapore is de gemakkelijkste stap in Azië: geordend, groen en veilig, met drie grote culturen (Chinees, Maleis, Indiaas) die elkaar al eeuwen aanvullen. De Gardens by the Bay met hun supertrees zijn futuristisch theater; de buurten Chinatown, Kampong Glam en Little India zijn de ziel.\n\nHet hart van de stad klopt in de hawker centres: overdekte hallen vol kraampjes, waar een michelinwaardige kip met rijst een paar euro kost. Eet laksa, satay, roti prata en chili crab; sta in de langste rij, die heeft altijd gelijk.\n\nPraktisch: de metro is vlekkeloos en aircokoud; neem een vestje mee. De regels zijn er echt (geen kauwgom, niet eten in de metro, forse boetes) en juist daardoor werkt alles. Drie tot vier dagen is genoeg; combineer met de buurlanden.'],
  ['delhi-agra', 'Delhi & Agra', 'Azië', 'Delhi en de Taj Mahal: overgave aan India',
    'Delhi is twee steden: het brede, koloniale New Delhi en het kolkende Old Delhi, waar de Jama Masjid boven een zee van steegjes uitrijst. Neem een fietsriksja door Chandni Chowk, eet parathas in de steeg die ernaar genoemd is, en zoek daarna de stilte van het graf van Humayun, de voorstudie van de Taj.\n\nDe Taj Mahal in Agra, twee tot drie uur sporen verderop, is het enige monument ter wereld dat mooier is dan zijn foto. Ga bij zonsopgang: het marmer kleurt van roze naar wit, en een uur lang is het stil genoeg om te begrijpen dat dit een graf uit liefde is.\n\nPraktisch: reis met de vroege sneltrein, boek treinen en toegang vooraf, en drink alleen flessenwater. India vraagt overgave; wie de chaos accepteert in plaats van bestrijdt, krijgt er het meest voor terug.']
];
