/* Reis-Bibliotheek: de gidsen van Europa.

   Eigen RTG-redactie: sfeer en hoogtepunten, eten, en een praktisch woord.
   Eerlijk en zonder opsmuk; geen boekingslinks, geen reclame. Kwaliteit boven
   aantal, dus deze lijst groeit langzaam en met opzet.

   Vorm per gids: [id, plaats, werelddeel, titel, tekst]. */
module.exports = [
  ['amsterdam', 'Amsterdam', 'Europa', 'Amsterdam: de stad op mensenmaat',
    'Amsterdam is klein genoeg om te lopen en rijk genoeg om nooit uitgekeken te raken. De grachtengordel is werelderfgoed, maar het echte geheim zit in de zijstraten: de Negen Straatjes voor winkels met karakter, de Jordaan voor bruine cafés en hofjes waar het ineens stil is. Het Rijksmuseum en het Van Gogh Museum liggen op loopafstand van elkaar; reserveer online en ga vroeg.\n\nEet als de stad zelf: haring van een kraam, Indonesische rijsttafel (de koloniale geschiedenis proef je hier eerlijker dan waar ook), en appeltaart bij een café aan het water. In de Pijp vind je de Albert Cuypmarkt en de betere kleine keukens.\n\nPraktisch: huur een fiets alleen als je vlot mee kunt in het verkeer, de tram en je benen zijn anders sneller en veiliger. Kijk uit met foto momenten op fietspaden; dat is de enige plek waar de stad haar geduld verliest.'],
  ['londen', 'Londen', 'Europa', 'Londen: dorpen aan elkaar geregen',
    'Londen is geen stad maar een verzameling dorpen, elk met een eigen toon. De grote namen (Westminster, de Tower, het British Museum) verdienen hun roem, maar plan per buurt: een ochtend South Kensington voor de musea, een middag langs de South Bank van de Tate Modern naar Borough Market, een avond Soho of Shoreditch.\n\nDe Britse keuken is allang geen grap meer: van de curry op Brick Lane tot de zondagse roast in een pub met open haard. Borough Market is de smaakversneller; kom hongerig. En de afternoon tea blijft, mits een keer, een klein feest van beschaving.\n\nPraktisch: de metro is duur per los kaartje; check gewoon in met je betaalpas, dan rekent het systeem zelf het dagplafond. Musea zijn er gratis; dat maakt Londen op regenachtige dagen verrassend betaalbaar.'],
  ['parijs', 'Parijs', 'Europa', 'Parijs: leren flaneren',
    'Parijs beloont wie langzaam gaat. De Eiffeltoren en het Louvre horen erbij, maar de stad zelf is het museum: de kades van de Seine, de passages met glazen daken, de stoelen in de Jardin du Luxembourg die je naar de zon draait. Kies per dag een arrondissement en loop; het Marais voor galeries en joodse bakkers, Montmartre in de vroege ochtend voordat de bussen komen.\n\nEten is hier een dagtaak: een croissant die kraakt, een lange lunch met een karaf wijn, een fromagerie waar je advies vraagt in plaats van kiest. Reserveer voor het avondeten; de goede adressen zijn klein.\n\nPraktisch: de metro brengt je overal, maar veel ritten zijn te voet mooier. Leer twee woorden ("bonjour" en "merci") en de stad wordt merkbaar vriendelijker.'],
  ['rome', 'Rome', 'Europa', 'Rome: alle eeuwen tegelijk',
    'In Rome ligt de geschiedenis niet achter glas maar op straat. Het Colosseum en het Forum Romanum vragen een ochtend en goede schoenen; het Pantheon is gratis en misschien wel het volmaaktste gebouw van Europa. Gooi je muntje in de Trevi vroeg in de ochtend, als het plein nog van de stad is.\n\nEet Romeins: cacio e pepe, carbonara zonder room (vraag er nooit om), artisjokken in het voorjaar, en ijs bij een gelateria waar de pistache grijsgroen is in plaats van felgroen; dat is het echte werk. In Trastevere eet je het best in de straten waar geen foto menu hangt.\n\nPraktisch: reserveer het Vaticaan en het Colosseum vooraf, altijd. Draag bedekte schouders in kerken. En neem de middag zoals de Romeinen: rustig aan; de stad is er morgen ook nog.'],
  ['lissabon', 'Lissabon', 'Europa', 'Lissabon: licht, heuvels en heimwee',
    'Lissabon heeft het mooiste licht van Europa; de stad ligt op heuvels aan een rivier die op zee lijkt. Verdwaal in de Alfama, waar de was tussen de huizen hangt en fado uit open ramen komt. Neem tram 28 een keer voor het verhaal, en loop hem daarna terug voor de foto momenten. Belém verdient een halve dag: het klooster, de toren en de pastéis de nata uit de oven.\n\nDe keuken is eerlijk en van zee: gegrilde sardines in de zomer, bacalhau in honderd gedaanten, en een glas vinho verde op een miradouro bij zonsondergang.\n\nPraktisch: draag schoenen met grip; de tegels zijn glad als het regent. De stad is heuvelachtig, dus plan per wijk en neem af en toe de lift of de funicular; die horen bij het openbaar vervoer.'],
  ['ibiza', 'Ibiza', 'Europa', 'Ibiza: het stille eiland achter de mythe',
    'Ibiza is twee eilanden in een: de clubkalender van juni tot september, en daaronder een kalkstenen eiland met dennen, kliffen en baaien waar het water doorzichtig is. Dalt Vila, de ommuurde bovenstad, is werelderfgoed; loop hem bij avondlicht. Huur een auto en zoek de kleine cala die je zelf ontdekt; dat is de herinnering die blijft.\n\nEet vis aan het water: een bullit de peix in een baai in het noorden, of gewoon gegrilde gamba met ijskoude witte wijn. De zonsondergang aan de westkust is een dagelijks ritueel; kies een rustige rots boven een druk terras.\n\nPraktisch: mei, juni en september zijn de mooiste maanden; warm, licht en zonder de drukte van augustus. Reserveer restaurants aan zee ruim vooraf en neem contant geld mee voor de kleinste strandtenten.']
];
